### ISSUE TITLE
When will there be a stable subset?

### ISSUE THREAD

**Issue by timthelion** [ziglang/zig#1028]
I realize that the language is still under construction, but I'm wondering when there will be a stable subset of the language that I can start using for serious projects. I recently went shopping for languages, I wanted to choose Nim, which has been developed for years, but there still was no stable subset of the language that I could rely on to not change. I'm terrified of bitrot and had a bad experience trying to write things in early Elm. So I chose Go, which I don't like, but at least supports the libraries that I need. I don't need a full feature complete language, Golang certainly isn't! I just need enough to be not as limited as go.

It seems to me that most languages fall into this pit of endless development, where they are never ready to be used in production. But as you can see with golang, you don't really need compile time call graph analysis or any other goodies. It's enough to suck but be stable.

I don't think you even need to put a 1.0 by the name. I would be convinced if you did as much as publish a "stable subset" test suit and claimed that no release would ever break a test in that suit.

**Comment by andrewrk** [comment]
1.0.0 will be the first stability guarantee. I know it seems like a long road to get there, but I predict 2 years from now.

Related: #350 ability to roll zig major version without causing problems for downstream users

**Comment by russmack** [comment]
Would be interested to hear the latest thoughts.

**Comment by nektro** [comment]
1.0.0 is still likely multiple years away. Progress can be tracked on the milestones (https://github.com/ziglang/zig/milestones) and further discussion is best had in communities (https://github.com/ziglang/zig/wiki/Community) rather than here on the issue tracker. If stability is one's goal, using the tagged releases in the interim in between now and 1.0 is the best way to go but changes will certainly come between them. Do note the release notes offer quite detailed upgrade instructions if upgrades are a worry.
