### ISSUE TITLE
C translator failure with void typedef

### ISSUE THREAD

**Issue by presentfactory** [ziglang/zig#10356]
### Zig Version

0.9.0-dev.1695+c6b4fe006

### Steps to Reproduce

Add the following to two files:
**main.zig**:
```zig
const c = @cImport({
    @cInclude("test.h");
});

pub fn main() !void {
    c.foo(null);
}
```

**test.h**:
```c
typedef void V;

V foo(V *) {}
```
Attempt to compile with `zig build` (just used the `init-exe` build script with link libc linked and a include directory set to get it to find the .h file).

### Expected Behavior

The program should compile.

### Actual Behavior

A compilation failure occurs with the error:
```
error: Opaque return type 'c_void' not allowed
pub extern fn foo(?*V) V;
                       ^
./main.zig:6:6: note: referenced here
    c.foo(null);
```

This is likely due to the fact that in C the singular typedef is being used for what was split into 2 things in Zig (`void` and `c_void`) so it cannot possibly compile correctly in this case if it uses the alias `V` directly. Note some code does actually do this, like [this](https://codeberg.org/ngn/k/src/branch/master/k.h) project for whatever reason.

**Comment by ehaas** [comment]
Just to double check - did you rebuild after pulling? `zig build test-run-translated-c test-translate-c` won't actually rebuild the compiler, so it's possible you ran the new test with an old build. I just did a clean build and don't get that error. Otherwise, maybe a problem with the Zig cache? Next step might be to delete that and re-run the tests.

**Comment by Juhlinus** [comment]
> Just to double check - did you rebuild after pulling? `zig build test-run-translated-c test-translate-c` won't actually rebuild the compiler, so it's possible you ran the new test with an old build. I just did a clean build and don't get that error. Otherwise, maybe a problem with the Zig cache? Next step might be to delete that and re-run the tests.

This was a fresh clone of the repo today. So it shouldn’t have anything to do with cache or the compiler as far as I’m aware.

**Comment by ehaas** [comment]
What system are you building it on (OS, CPU, etc)?

**Comment by Juhlinus** [comment]
OSX, M1. The Air model if that’s relevant.

**Comment by ehaas** [comment]
Ok, unfortunately I don't have access to an M1 mac. The only other thing I can think of is that if Zig was previously installed in some other way, an old version might be in your path and it's using that instead of the freshly built one. If that's not the case I think we'd have to find someone with an M1 mac to see if it happens for them. I can't imagine why it would only happen there though.

**Comment by Juhlinus** [comment]
I’ll double check this and get back to you.

**Comment by andrewrk** [comment]
I just ran `zig build test-translate-c test-run-translated-c` on an M1 and it passed. Also the CI system does that, and master branch is passing the CI.

**Comment by Juhlinus** [comment]
Yeah, sorry that’s my bad, my paths were messed up. Runs fine for me now.
