### ISSUE TITLE
Unexpected result on saturated arithmetic on two comptime_int's

### ISSUE THREAD

**Issue by cryptocode** [ziglang/zig#10365]
### Zig Version

0.9.0-dev.2006+ef0566df7

### Steps to Reproduce

`try std.testing.expectEqual(@as(u32, 2), 1 +| 1);`

It doesn't matter if the comptime_int's are literals or constants.

### Expected Behavior

Expected either the test to pass, or a compilation error as saturated addition of two comptime_int's is indicative of a bug. 

### Actual Behavior

Test fails, as arithmetic on two comptime_int's is always zero.

**Comment by matu3ba** [comment]
You can generalize the problem to this code snippet:
```zig
const std = @import("std");
test {
    try std.testing.expectEqual(0, 1 +| 1);
    try std.testing.expectEqual(0, 1 -| 2);
}
```

Question 1: What is the type of 0 and what is the type of 1?
Question 2: How is `1 + 1 == 0` intuitive in any way or `1 - 2 == 0`?

Creating a type either on the lhs or rhs of the operation creates the expected result.

**Comment by riverbl** [comment]
Currently the compiler is inconsistent. At ir.cpp:10050:
```
if (op1_scalar_type->id == ZigTypeIdComptimeInt) {
    // comptime_int has no finite bit width
    casted_op2 = op2;

    if (op_id == IrBinOpShlSat) {
        ir_add_error_node(ira, bin_op_instruction->base.source_node,
            buf_sprintf("saturating shift on a comptime_int which has unlimited bits"));
        return ira->codegen->invalid_inst_gen;
    }
```
Saturating left shift is disallowed on type comptime_int as it will never saturate. However, at ir.cpp:10466:
```
// Comptime integers have no fixed size
if (scalar_type->id == ZigTypeIdComptimeInt) {
    if (op_id == IrBinOpAddWrap) {
        op_id = IrBinOpAdd;
    } else if (op_id == IrBinOpSubWrap) {
        op_id = IrBinOpSub;
    } else if (op_id == IrBinOpMultWrap) {
        op_id = IrBinOpMult;
    }
}
```
Wrapping arithmetic operations are mapped to their non wrapping equivalents so that they work on type comptime_int.

I think both wrapping and saturating arithmetic should be disallowed on type comptime_int, as it doesn't make sense to ask for wrapping or saturation on a type that will never wrap or saturate.

**Comment by nektro** [comment]
likely fixed by https://github.com/ziglang/zig/commit/924eb08b613e3333419512f4de02b167aba9336d

merge closed pr instead of marking as merged
