### ISSUE TITLE
can zig import a directory like golang?

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1037]
Golang can import a directory and use all the public top level variables and functions from another package(file). 
This make spilt a big file into serval small files very easily.

For example(use case):
I write a small package that I will use from another package called kmgFile.
I will add kmgFile.ReadFile , kmgFile.WriteFile .. into that package, and i put them into a file called kmgFile.go in kmgFile directory.
After I write about 20 functions about os file operation. I found that the kmgFile.go have 500 lines. It become difficult for me to find a function to view it implement and interface. 
Then I want to split them into serval small files like read.go, write.go, stat.go. 
read.go may include kmgFile.ReadFile, kmgFile.ReadSymlink, ...
write.go may include kmgFile.WriteFile,kmgFile.WriteFileWithMkdir , ...
stat.go may include kmgFile.GetAllLevelFullPathFromDir , ...
I can just cut and paste the file content and edit the file import part(I hate the import part of golang,but this part do not need a lot of work, and ide can auto solve this problem right now).
The caller package (from another package) do not need any modification and I do not need to edit something like index.zig(ziglang) or index.h(c) to include the public top level functions to tell the compiler that I need export them.

Please tell me wrong if there is something like import a directory stuff in zig.

**Comment by andrewrk** [comment]
Thanks for describing the use case.

In Zig `@import` only works directly with a file. Even in the case where we doing `@import("std")` this is just a mapping of a package name to a file path. E.g. in the command line `--pkg-begin std path/to/std/index.zig --pkg-end`

The recommended way to handle this use case is to create a directory, and have a main entry file, e.g. `index.zig`. Here you make public all the symbols that should be visible. In each file in the directory, you import the index file and use that to access the namespace.

Here's an example: https://github.com/ziglang/zig/blob/e514454c0e092794171d4a62260971cc8de6f200/std/index.zig

This gives us the property that when you look at any identifier, you can find where it comes from by a direct lookup. You will never be faced with a situation where you see something and you have to look at every file in a directory (perhaps with grep) in order to know where it is defined.

Caveat, you can cause this situation by use of `pub use`. For example in your `index.zig` file you could do:

```zig
pub use @import("a.zig");
pub use @import("b.zig");
pub use @import("c.zig");
```

And now `index.zig` makes public everything public from a.zig, b.zig, c.zig. This is generally discouraged as it gives more work for the compiler as well as the human trying to read your code, however it does accomplish what you asked for.

**Comment by bronze1man** [comment]
Thanks. 
I can not find the document of `pub use`. Maybe I do not read the document carefully or there is something wrong with the document.

But I do not think the `pub use` solve my problem. I have to edit two files when I add one file into my `package`
So I can write a program that auto generate the index.zig at compile time if I insist on my habit of import a directory.
Does this file generate process work only use zig compile-time feature?

**Comment by andrewrk** [comment]
> I can not find the document of pub use. Maybe I do not read the document carefully or there is something wrong with the document.

The documentation is unfinished - see #367 

> I have to edit two files when I add one file into my package

That is correct. Zig philosophy is willing to pay the cost of extra effort when writing code for the benefit of less effort when reading code.

**Comment by bronze1man** [comment]
> I'm sorry, I do not understand your question.

It is another big use case. I will file another issue to describe.

**Comment by bronze1man** [comment]
@andrewrk 
I think the effort of reading code, writing code, changing code can be saved at the same time with the ability of generating code by another code.

May be the index.zig can be generated by the zig compiler? It may looks like:
`
const ReadFile = @import("read.zig").ReadFile;
const WriteFile = @import("write.zig").WriteFile;
...
`
 
The shortcomings of the generating code by another code:
   * You should not edit the generated code manually. Or you change will lost after next generated.
   * Your git repo may conflict in the generated code. You need to generated code again.

**Comment by monouser7dig** [comment]
> Caveat, you can cause this situation by use of pub use. For example in your index.zig file you could do: `pub use @import("a.zig");`

maybe running zig-fmt could turn/ explode such a `use` statement into all those `@import` statements @andrewrk, just thinking about this cause I read the fmt commits/ discussion a bit like formatting array literals, in this specific case it would be a syntactic change but it would still preserve the same semantics as far as I can see at first glance so maybe this could still be in scope for zig-fmt.

The only issue is, if new functions are added to `a.zig`, they are not added/ exported into the index.zig automatically anymore, but this could be done by simply writing `pub use @import("a.zig");` yet again and running zig-fmt as I think this does only happen incrementally in real world use.

**Comment by bronze1man** [comment]
> The only issue is, if new functions are added to a.zig, they are not added/ exported into the index.zig automatically anymore, but this could be done by simply writing pub use @import("a.zig"); yet again and running zig-fmt as I think this does only happen incrementally in real world use.

I hate format any old code/all the code in project. It just create a lot of git conflicts.
I hate start generated code by another code manually. It should start whenever I build my code. 
The `index.zig` should generated whenever the code of that directory changed. It should not be a problem of add/delete function in another `a.zig`.

**Comment by monouser7dig** [comment]
> I hate format any old code/all the code in project. It just create a lot of git conflicts.

the point of formatting is quite the contrary, you format each time and thus reduce git conflicts, make machine generated and especially edited source code possible. There is thus no old code getting formatted because code is formatted immediately after its creation.

> I hate start generated code by another code manually. It should start whenever I build my code.

Fmt should ideally be run automatically during build or save.

> It should not be a problem of add/delete function in another a.zig.

if that is a big priority, my suggestions would not work for you, your initial use case mentioned though:
> After I write about 20 functions about os file operation. I found that the kmgFile.go have 500 lines. It become difficult for me to find a function to view it implement and interface.
Then I want to split them into serval small files like read.go, write.go, stat.go.

this would be solved and maybe this is the more common case because changing exported functions all of the time might not be the common case (if functions are exported they are probably hard to change anyway)
