### ISSUE TITLE
Can't cast pointer to opaque type?

### ISSUE THREAD

**Issue by TwoClocks** [ziglang/zig#10453]
### Zig Version

0.9.0

### Steps to Reproduce

I don't know if this is a bug or an incorrect expectation. The docs for Translation failures says

> ... Thus, non-translatable types can still be used as pointers ...

But this won't compile:
```zig
const Unknwon = opaque{}; // some C struct w/ bitfields
const Away = extern struct{
    some:u32,
    other:Unknwon,
};
const Local = struct {
    some:u32,
    other:u32,
};
pub fn main() anyerror!void {
    var works = Local{ .some=10, .other=20, };
    _ = @ptrCast(*Away,&works); // compiler error 
}

```

I can't create a pointer to a type that contains a non-translatable type, it seems. Or I'm doing it wrong.

I got into this trying to call some C code that has bitfields. I made a zig struct by hand, but I can't cast it to the type of the C struct because of this error, so I can't call the function. Unless I alter the signature of the function to take a `*c_void`, and cast to that.

### Expected Behavior

Allow pointers to non-translatable types, and to types that contain non-translatable types.

### Actual Behavior

```
./src/main.zig:30:5: error: opaque types have unknown size and therefore cannot be directly embedded in structs
    other:Unknwon,
    ^
./src/main.zig:38:9: note: referenced here
    _ = @ptrCast(*Away,&works);
        ^
```

**Comment by hazeycode** [comment]
The problem is not that you can't create the pointer, the problem is you are trying to define a type with an unknown size, `Away`, as the error message describes:
"error: opaque types have unknown size and therefore cannot be directly embedded in structs"

This is the expected behavior.

Not sure exactly what you are trying to do so I'm not sure what the best thing to suggest is but I think you want to try and solve your problem without defining `Away` and instead make use of `anyopaque`.
In the case where you want to do something other than just pass the opaque C types along, you will need to define a Zig type with the same size and layout as the C type to cast to and from.

**Comment by TwoClocks** [comment]
The `Away` type is what comes out of `translate-c` for any C structs that contain a struct that has a bitfield. The signature of of the translated C functions look like `pub extern fn some_c_func( [*C]Away );`
I was doing exactly what you suggested. I made a zig struct w/ the correct layout. `Local` in this example. But I need to cast to `Away` to call the C function. Or alter the C function signature as well as make a zig struct.

This makes C interop fairly labor-intensive.

I thought this would work because the docs say pointers to non-translatable types can exist. But it seems like they can't. So are the docs incorrect? What is an example of a pointer to a non-translatable type working?

**Comment by hazeycode** [comment]
> The Away type is what comes out of translate-c for any C structs that contain a struct that has a bitfield.
How is this bit field defined on the C side? That's a bug with translate-c if it is generating structs containing opaque types! A bitfield is usually just represented by an interger type in C which should work just fine.

The docs are correct. You can take a pointer to `Unknwon` for example - but the issue here is that translate-c is generating a struct containing an `Unknwon`, which is illegal and you will indeed not be able to take a pointer to it.

The solution then here I think is to ignore `Away` completely, and instead use `@ptrCast(*anyopaque, &works)` to pass your local struct to a C API.

**Comment by TwoClocks** [comment]
The docs seem to imply that anything w/ a bitfield is converted to an opaque. This matches my experance. This simple C struct
```c
struct one {
    int first:1;
    int second:4;
    short reserved; // reserved
};
struct second {
    int first;
    struct one second;
};
```
results in the following zig
```zig
pub const struct_one = opaque {};
pub const struct_second = extern struct {
    first: c_int,
    second: struct_one,
}; // test.h:18:11: warning: struct demoted to opaque type - has bitfield
```

The generated comment seems to confirm bitfield = opaque.

Casting to `*anyopaque` does not help, if the C function is expecting a pointer to an opaque type. The result is the same error. It would be helpful if `translate-c` didn't reference opaque types in function parameters. Just expect a `*anyopaque`,  Or better yet, support bitfields, which I believe is a known open issue. W/o bitfield support, C interop is quite hard.

**Comment by hazeycode** [comment]
Yes, you're right, in this scenario it is also necessary to change the sig of `simple_c_func` from
`pub extern fn simple_c_func(param: [*c]struct_second) c_short;`
to
`pub extern fn simple_c_func(param: *anyopaque) c_short;`

It is not enough to ignore the illegal types generated by translate-c in user's Zig code, but to modify the code generated by translate-c such that no functions reference the illegal types.

with that done, this code works
```
pub extern fn simple_c_func(param: *anyopaque) c_short;

pub const ZigStruct = struct {
    first: u32,
    second: u64,
};

test "opaque ptr" {
    var foo = ZigStruct{ .first = 12, .second = 34 };
    _ = simple_c_func(@ptrCast(*anyopaque, &foo));
}
```

IMO, this is a bug in translate-c, which could and should instead generate function signatures with demoted arg types e.g. `arg: *anyopaque` if the arg types or fields of that type contain an opaque

**Comment by TwoClocks** [comment]
Should I open a new ticket just about the function signature `translate-c` outputs? or just leave this one?
