### ISSUE TITLE
Turn anything into std.zig.Ast

### ISSUE THREAD

**Issue by locriacyber** [ziglang/zig#10467]
Currently, there is no way to turn a type into a file. `std.builtin.TypeInfo` does not contain AST of its source code, so there is no way to turn a type that only exists in compile-time or run-time back to source code.

For example, I have the following file:
```zig
fn factory(comptime T: type) {
    return struct {
        t: T,
    };
}
```

I want to "preprocess" `factory(i32)` and turn it into a file.

This feature will be useful for "baking" generated code programmatically. This can be used for generating zig code from protobuf definitions, or programmatically output Zig wrapper files of C libraries.

It will also make debugging generated `struct` easier, since you can now see the generated struct.

**Comment by locriacyber** [comment]
Currently, typeinfo does not contain AST of its source code, so there is no way to turn a type that only exists in compile time back to source code.

**Comment by enkore** [comment]
You probably know this but the reason why TypeInfo doesn't reference the AST / code is because types are inherently abstract; a `TypeInfo.Fn` is a function type (aka signature) _not_ a particular function and its definition (code). That's also why arguments in `TypeInfo.Fn` are anonymous; argument names are actually part of the function definition and not the function's signature (just like C).

So semantically a conversion from TypeInfo to Ast and then to Zig source only makes sense for some very limited cases e.g. POD structs .

**Comment by locriacyber** [comment]
I'm thinking of a way to turn things like functions and variables back into AST. This is only possible with static analysis, and easier with internal support from the compiler.

For example, the struct `factory(i32)` is equivalent to:
```zig
blk: {
    const T = i32
    break :blk struct {
        t: T,
    };
}
```
