### ISSUE TITLE
Zig build fails if the user folder contains cyrillic characters

### ISSUE THREAD

**Issue by KatPurpy** [ziglang/zig#10506]
### Zig Version

0.10.0-dev.139+850b053ea

### Steps to Reproduce

The error seems to occur on windows due to Zig toolchain using UTF-8 when Windows uses UTF-16 for paths
1. Have a user folder which name is written in cyrillic characters
2. Run `zig init-exe`
3. Run `zig build`
4. Witness the error

### Expected Behavior

No errors

### Actual Behavior

Just in case: [REDACTED] is a name written in cyrillic characters such as `Василий`. Edited for privacy reasons.

```
error(mingw): clang exited with code 1 and stderr: error: unable to open output file 'C:\Users\[REDACTED]\AppData\Local\zig\o\f6eeb75a2cedb4cc58f95d9ea70a607d\kernel32.def': 'Символ Юникода не имеет сопоставления в конечной многобайтовой кодовой странице.'
1 error generated.

error(mingw): clang exited with code 1 and stderr: error: unable to open output file 'C:\Users\[REDACTED]\AppData\Local\zig\o\c6379a4de5888bcd947790c71c974c8e\ntdll.def': 'Символ Юникода не имеет сопоставления в конечной многобайтовой кодовой странице.'
1 error generated.

error(mingw): clang exited with code 1 and stderr: error: unable to open output file 'C:\Users\[REDACTED]\AppData\Local\zig\o\6d7ede8e82a0e42ab5d39e4d7fda3f42\advapi32.def': 'Символ Юникода не имеет сопоставления в конечной многобайтовой кодовой странице.'
1 error generated.

error: unable to generate DLL import .lib file: ClangPreprocessorFailed
```

**Comment by squeek502** [comment]
I've tried looking into this a bit and from what I can tell the issue lies with the `pub fn main(argc: c_int, argv: [*][*:0]u8) callconv(.C) c_int` entrypoint in `stage1.zig`, as it can't successfully receive non-ASCII characters.

This is reproducible by setting the `ZIG_GLOBAL_CACHE_DIR` env variable to a path that includes non-ASCII characters, e.g.:

```
set ZIG_GLOBAL_CACHE_DIR=C:\Users\Ryan\Programming\Zig\tmp\cache\Кириллица
```

In `mingw.zig`, `def_final_path` here:

https://github.com/ziglang/zig/blob/b316c25cc6f5b1703d7912da16c5c987f4406451/src/mingw.zig#L331-L333

is UTF-8 that looks like this when printed with `std.zig.fmtEscapes`:

```
"C:\\Users\\Ryan\\Programming\\Zig\\tmp\\cache\\\xd0\x9a\xd0\xb8\xd1\x80\xd0\xb8\xd0\xbb\xd0\xbb\xd0\xb8\xd1\x86\xd0\xb0\\o\\ae484bf4ddcd5e1d90fab86e1a85305e\\kernel32.def"
```

And then when it's received by `main` in `stage1.zig` after `mingw.zig` calls its `zig clang ...` incantation via `ChildProcess` (which correctly converts to UTF-16 before passing to `CreateProcessW`), it looks like this:

```
"C:\\Users\\Ryan\\Programming\\Zig\\tmp\\cache\\?????????\\o\\ae484bf4ddcd5e1d90fab86e1a85305e\\kernel32.def"
```

Note: If the non-ASCII characters are within the Windows-1252 range, it causes a different error as the `stage1.zig` main receives it as Windows-1252 encoded:

```zig
// before ChildProcess.init in mingw.zig (correct UTF-8 for á)
"L\xc3\xa1tin-1"
// what gets received by stage1.zig's main (Latin-1/Windows-1252 encoded value for á)
"L\xe1tin-1"
```

And the error looks like this:

```
error: unable to open output file 'C:\Users\Ryan\Programming\Zig\tmp\cache\L<E1>tin-1\o\b5df4c03d7232331db68bf600c63397a\ntdll.def': 'unspecified system_category error'
```
