### ISSUE TITLE
Remove `std.os.argv`

### ISSUE THREAD

**Issue by ominitay** [ziglang/zig#10746]
## Rationale
`std.os.argv` is UNIX-specific, and `std.process.args` should be used instead in all cases of which I can conceive. Following Zig's Zen, which states: `Only one obvious way to do things.`, and to maximize portability of code written in Zig, I believe that it should be removed.

related: #6600 #10734 
cc: @enkore @InKryption

**Comment by InKryption** [comment]
Note: it could maybe still be made available under the Linux namespace, now that I think of it?

**Comment by ominitay** [comment]
That's also a possibility. Good to have an issue to discuss this.

**Comment by enkore** [comment]
Prior discussion [started here](https://github.com/ziglang/zig/issues/6600#issuecomment-1000398193), [summary here](https://github.com/ziglang/zig/issues/6600#issuecomment-1026079893)

**Comment by ominitay** [comment]
> Note: it could maybe still be made available under the Linux namespace, now that I think of it?
> 
> Edit: Because the main issue is that it's under `std.os`, which people may instinctively go to for the likes of `argv`, and thus creates an incorrect incentive to use it, even on platforms that don't support it; such a change would be in line with the sentiment of "A hate letter to std.os".

Well, we can't put it under `std.os.linux`, since it is a UNIX thing. It's in the right place to be in `std.os`. I think making it obscure or inaccessible is the right way to go.

**Comment by InKryption** [comment]
> Well, we can't put it under `std.os.linux`, since it is a UNIX thing. It's in the right place to be in `std.os`. I think making it obscure or inaccessible, or removing it, is the right way to go.

Hmm, that's true. Almost makes me think we should have a `std.os.unix` namespace for general unix-compliant abstractions, but that seems pretty out of scope. 

If I had a vote, I'd argue it'd be best to make it obscure; there are still probably valid use cases for making it available, we just need to make it harder to use it incorrectly.

As for where, it would make sense to me for it to be in `std.start`, as suggested by @enkore, since that is where it is actually initialized, and anybody implementing the entry point logic themselves should probably do something similar (put it in the entry point file by example, so to speak).
From there, it could be further considered whether to make it a compiler error to use it on platforms with no `argv`. 

Sort of a roundabout way of coming back to the original idea; just now with the added clause that it's moved to `std.start`.

**Comment by ominitay** [comment]
> Hmm, that's true. Almost makes me think we should have a std.os.unix namespace for general unix-compliant abstractions, but that seems pretty out of scope.

That's basically just #6600 ;)

> If I had a vote, I'd argue it'd be best to make it obscure; there are still probably valid use cases for making it available, we just need to make it harder to use it incorrectly.

We don't need an `argv`. `std.process.ArgIteratorPosix` can directly use `std.start.argc_argv_ptr` instead.

**Comment by ominitay** [comment]
Although that may break `std.start.mainWithoutEnv`, so should probably look further into this.

**Comment by InKryption** [comment]
> We don't need an argv. std.process.ArgIteratorPosix can directly use std.start.argc_argv_ptr instead.

Can't say I have an qualms with that. If nobody else says anything, I'd definitely say just go ahead and make the PR to make that change (maybe you change #10734 instead of creating another PR?).

**Comment by ifreund** [comment]
My project, river, does not target non-posix systems and does not care for needless abstraction. I am strongly against removing convenient access to `argv`.

**Comment by ominitay** [comment]
> just go ahead and make the PR to make that change
@InKryption 

I expected a fair amount of discussion would need to take place regarding this, so I'm leaving that for until we settle on a method which works for everyone.

> I am strongly against removing convenient access to `argv`.
@ifreund 

Thanks for informing me of your take on this. After thinking further about this, and with your point in mind, I think that perhaps the best course of action could be not to remove `argv`, but to nudge users away from using it by default (i.e. sending it down a namespace which emphasizes its UNIX-dependence), such that the single obvious way to do things is the 'correct', platform-independent way.

That may have to wait until #6600 is implemented, but I believe it's worth looking at whether we can do so sooner. I think definitely though that #10734 is a sensible change in the meantime and prevents bugs without causing unnecessary breakage.

**Comment by ifreund** [comment]
I think moving it to `std.os.posix` or similar as per #6600 is necessary and covered by that issue. This goes for many other things in `std.os` as well though, some of which are even less portable than argv.

The only thing that makes the current `std.os.argv` more of a footgun than the other non-portable stuff in `std.os` is the lack of a compile error when targeting a platform which doesn't support it, but that is addressed by #10734.

Since I feel like we've reached consensus that removing argv entirely from the standard libraries public API as per this proposal is not the path to take, I think this issue can be closed.

**Comment by ominitay** [comment]
Yep, I agree. Thanks :)
