### ISSUE TITLE
Be able to set `--main-pkg-path` through an environment variable

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#10754]
### Zig Version

0.10.0-dev.490+dd7309bde

### Steps to Reproduce

I have a handful of Zig scripts that I keep in a `tools/` directory. However, they share a few source files between each other and the main app code.

As opposed to having to pass `--main-pkg-path .` at every `zig run` callsite, it would be nice if there was a way to be able to set the path globally for the runtime of the script given that the functionality is spread across many scripts that independently call each other.

### Expected Behavior

`ZIG_MAIN_PKG_PATH`

### Actual Behavior

status quo is passing `--main-pkg-path` at every invocation. the scripts are in `tools/` so that's what it defaults to rather than the cwd.

**Comment by nektro** [comment]
oops meant for this to have the proposal label

**Comment by mitchellh** [comment]
One pattern I've liked on other projects I've done is support all CLI flags using `PROGRAM_CLI_<FLAG>`, so as you introduce CLI flags, you can set it using `PROGRAM_CLI_MAIN_PKG_PATH` or whatever. You just write some relatively simple conversion code from hyphens to upcase underscores. Then you just come up with some precedence rules.

As a maintainer, I've found that this avoids making what feel like arbitrary decisions of what is supported by env vars and what is not. 

For special flags, you can introduce non `_CLI_`-prefixed env vars. This might be one of those cases, but just wanted to mention this as well...

Yes, there are a ton of flags that are probably dumb to set using env vars but... I've always been surprised at use cases users find. 😆

**Comment by marler8997** [comment]
In my experience I tend to avoid environment variables to configure processes in most cases.  On the one hand, environment variables are very powerful because by default they are automatically propagated to all child processes without any effort from the processes themselves.  This can be a good thing and a bad thing.  On the other hand, they introduce hidden state that are almost never visible in logs that show all the inputs passed to each subprocess.  You could modify the logging to include all environment variables but then your logs are filled with mostly useless noise.  To improve this you could try to only print the environment variables you know are important, but if you put in the effort to do that then it would have been just as much work to forward them as command-line arguments, and, in many cases it's impossible to know all the environment variables that matter because different platforms/tools can end up using any environment variable.  For example maybe my machine has a custom version of libc that uses `LIBC_GO_FAST` to choose a different implementation that introduces a bug.

This being said sometimes you MUST use environment variables because you may not have much choice.  For example, if you make a library that's deep within the dependency tree that the top-level application may not know about, environment variables are just about your only choice.  For example, If you have a GUI application that uses SDL, SDL might in turn use the x11 client library, which the top-level application may not be aware of.  Rather than add configuration for all possible SDL backends, libraries can short circuit the need for this by querying environment variables.  However, this does have the disadvantage that all the possible options are non-discoverable and makes it difficult to know which environment variables could be affecting the overall program behavior.

These observations come from some painful triage I had to do.  In fact, I had problems with this with the D programming language years ago because it took configuration from 2 config files, an environment variable with extra command-line switches and then the normal command-line arguments.  Also note that with these extra ways to configure you need to come up with a pecking order.  You would think that the command-line arguments would have the highest priority, but it turned out that D chose to make the environment variable higher-priority than the command-line switches.  That turned into quite a headache but it was too late to undo that poor decision.

In any case I don't way to declare that Zig should never use an environment variable, but I wanted to point out some of the complexities/headaches it can introduce.  It might seem annoying to have to add extra command-line arguments, but punting to an environment variable instead will bring in another bag of worms that should be considered against what I consider to be a minor inconvenience.

**Comment by andrewrk** [comment]
On one hand I like the uniformity of having a bijection between environment variables and CLI flags. However, I agree with @marler8997 that in general, avoiding use of environment variables makes for a more reproducible tool, especially in collaboration with others.

My personal feeling is that every supported environment variable is an uncomfortable compromise, and I'd rather minimize the amount of occurrences of it, even at the cost of inconsistency and arbitrariness between what is available via CLI and what is available via environment variables.
