### ISSUE TITLE
use of undefined only compiler error if `const`, not `var`

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#10752]
### Zig Version

0.10.0-dev.500+66cf011aa

### Steps to Reproduce

1. Save the following code as `bug.zig`
2. `zig run bug.zig` -- passes
3. Change `var` to `const`
4. `zig run bug.zig` -- compiler error

```zig
const std = @import("std");

pub fn main() !void {
    var x: bool = undefined;
    if (!x) {
        std.log.info("YES", .{});
    }
}
```

### Expected Behavior

Compiler error regardless of var vs const usage, since either way you're comptime-provably using an undefined value.

### Actual Behavior

Compiler error only if `const`.

**Comment by andrewrk** [comment]
This is actually working as designed because Zig is not able to prove that `x` is `undefined` in the `var` case.

This case looks easy to prove, and indeed it is, but we could construct an arbitrarily difficult problem for which solving it would be the halting problem. Currently Zig's analysis stops at `var`. So, on the line with the `if` expression, the `!x` is an undefined value, and then `if (undefined)` is unchecked undefined *behavior* due to branching on an undefined value.

The issue for adding a safety check for this kind of undefined behavior is #63.

I don't think we have a proposal issue open for advanced control flow analysis which would attempt to prove that an undefined value gets branched on, such as in this case. If you'd like to open that issue, or transform this issue into that one, feel free to do so.

**Comment by mitchellh** [comment]
Ah #63 was what I was looking for. Yeah sorry I figured the comptime angle wasn’t exhaustively solvable but was unsure about the simple case. Runtime made a lot more sense. Thanks!
