### ISSUE TITLE
`addArtifactArg` always returns the default `zig-out` directory, ignoring the value set via `setOuptutDir`.

### ISSUE THREAD

**Issue by dmbfm** [ziglang/zig#10811]
### Zig Version

0.10.0-dev.378+40b3c9a5

### Steps to Reproduce

Create a new exe via `zig init-exe` and replace the default `build.zig` file for this:

```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("exe", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);
    exe.setOutputDir("./out/");
    exe.install();

    const cmd = b.addSystemCommand(&[_][]const u8{"echo"});
    cmd.addArtifactArg(exe);

    b.getInstallStep().dependOn(&cmd.step);
}
```

Then run `zig build`.

### Expected Behavior

The `echo` command should output something like: `projectdir/out/bin/exe` 

### Actual Behavior

It outputs: `projectdir/zig-out/bin/exe`.

**Comment by dmbfm** [comment]
I'm not sure if this is a bug or somehow the intender behavior since the build system is not really documented.

**Comment by MasterQ32** [comment]
> I'm not sure if this is a bug or the intended behavior since the build system is not really documented.

This is the intended behaviour. `setOutputDir` is used for setting the temporary build directory in `build.zig`. If you want to change the install directory (which is what happens when you "output"), call `.install()` and then fetch the install step, modify that.

Imho the behaviour is okay, but there's a doc comment missing that `setOutputDir` doesn't do what one might expect.

**Comment by dmbfm** [comment]
@matu3ba I just wanted to copy the output file. 

@MasterQ32 Gotcha! Yeah, I though it was the intended behavior but I just weren't sure.

Thanks, guys!
