### ISSUE TITLE
Remove the ability to use a labelled block as a while loop expression.

### ISSUE THREAD

**Issue by bdoner** [ziglang/zig#10889]
### Zig Version

0.10.0-dev.625+e42b5e76b

### Steps to Reproduce

Run the following progrram.

```c++
const std = @import("std");

pub fn main() !void {
    std.log.warn("write something! Press 'q' to quit.", .{});
    while (true) loop: {
        var inp = try std.io.getStdIn().reader().readByte();
        switch (inp) {
            'q' => break :loop,
            else => {
                std.log.warn("{c}", .{inp});
            },
        }
    }
}
```

### Expected Behavior

That pressing 'q' will end the while loop, thus exiting the program.

### Actual Behavior

Pressing 'q' breaks the block, but not the loop. Leaving you unable to exit the loop. 

While loops should not allow their blocks to be labeled as there's nowhere to return a value from the block to anyway.

**Comment by InKryption** [comment]
@nektro That isn't the point of this issue. The point is that being able to write `while (true) blk: {...}` is a huge footgun, and shouldn't be allowed.

**Comment by ominitay** [comment]
> putting the label on the left side of `while` or removing the label entirely will provide the behavior you desire

@nektro It's clearly a footgun though; you're missing the point.

**Comment by sigod** [comment]
To me, this behaves exactly as expected.

**Comment by nektro** [comment]
I would call this "unexpected to a new user" behavior but I would not go so far as to call it a footgun.

`while (true) blk: {...}` behaves exactly as expected if used in an assignment expression such as `const x = while (true) blk: {...};` and the compiler does not complain about `_ =` because the result type is `void`

I think the way to solve this footgun is not to remove `while (true) blk: {...}` but to remove `break :loop` and require `break :loop {}` instead

**Comment by andrewrk** [comment]
Decision: don't special case while loop blocks. It's a normal block, just like every block.
