### ISSUE TITLE
Proposal: implicitly dereference most function arguments

### ISSUE THREAD

**Issue by ArborealAnole** [ziglang/zig#10905]
If a function takes a `T` as a parameter, implicitly dereference a `*T` or `*const T` when given as a function argument.

This is for consistency with the behavior of struct methods, and for const correctness in function signatures while being compatible with generic uses. It can add ability to use a value that may either be a `T`, `*T`, etc. directly as a `T`.

The only exception is if you have a parameter that is `*T`, `**T`, etc. - implicit dereference is not performed on an argument being a chain of single-pointers (regardless of `const`). That seems riskier.

**Comment by InKryption** [comment]
Automatically dereferencing, or taking the address of, a container, when using dot call syntax, is reasonable by itself, for the purposes of making the usage of contiainer-namespaced functions ergonomic (e.g., not having to write `std.ArrayList(u8).append(&array_list, value)`), and encouraging good namespacing of functions.

In that respect, I think this proposition adds comparatively little value, being that it would, at most, save one keystroke (`func(&value)` vs `func(value)`), and I would even go so far as to say that it actually adds negative value, since this would lead to a situation wherein the reader of code would very likely have less context on as to the meaning of function calls.

E.g., when interacting with C APIs, which often use output parameters:
```
var exit_code: u8 = undefined;
_ = cFunction(&exit_code);
```
the above code becomes
```
var exit_code: u8 = undefined;
_ = cFunction(exit_code);
```

While simple, it is now ambiguous as to what the semantics are on first glance, without first looking at the signature/definition of `cFunction`.

In brief, I think this proposal makes zig less readable, in exchange for a tiny increase in writing ergonomics, and maybe removes a few checks, and a couple calls to `std.meta.Child`.

**Comment by andrewrk** [comment]
![image](https://user-images.githubusercontent.com/106511/154352172-dd0053c3-9388-45d8-93c9-e763a5efca2c.png)
