### ISSUE TITLE
Support switching on known length []const u8

### ISSUE THREAD

**Issue by frmdstryr** [ziglang/zig#10984]
Is there any "easy" way to switch on a `[]const u8`?

I can currently bitcast to an int and switch but it is incredibly ugly.

Eg I can do this

```zig
const COPY = @bitCast(u32, [4]u8{ 'C', 'O', 'P', 'Y' });
const MOVE = @bitCast(u32, [4]u8{ 'M', 'O', 'V', 'E' });
var value: u32 = @bitCast(buf[0..4].*);
switch (value) {
   COPY => ...,
   MOVE => ...,
   else => ...,
}
```

but I can't do this with 

```zig
var value: u32 = @bitCast(buf[0..4].*);
switch (value) {
   "COPY" => ...,
   "MOVE" => ...,
   else => ...,
}
```

The use case is looking up an error code from a list of about 300... all equal length. I don't want a giant if else tree with mem.eql if possible...

**Comment by ominitay** [comment]
Ask questions regarding this in a Zig community, as the issue template told you to do. And this is pretty much definitely not going to happen btw.

**Comment by InKryption** [comment]
Firstly, no, because switches don't support switching on things that would require memcmps; and secondly, that isn't a `[]const u8`, that's an array, aka `[N]T`; thirdly, don't open issues to ask questions. Consider joining the community discord or some other forum to ask questions, where we would gladly accommodate you.

**Comment by frmdstryr** [comment]
Nevermind I'll just generate an enum
