### ISSUE TITLE
translated code of Python.h fails to build

### ISSUE THREAD

**Issue by ali5h** [ziglang/zig#11040]
### Zig Version

0.9.1

### Steps to Reproduce

On Ubuntu 20.04 with python 3.8 installed
```
$ zig translate-c /usr/include/python3.8/Python.h -I/usr/include/python3.8 -I /usr/include -I /usr/include/x86_64-linux-gnu/ > python3.8.zig
$ zig build-lib python3.8.zig
```

this is also tested on `0.10.0-dev.1091+7fc8dd664`. 

`@cImport` works with no issues. (check here https://github.com/ali5h/zig-py-sample)

### Expected Behavior

translated code should compile

### Actual Behavior

```
$ zig build-lib python3.8.zig
python3.8.zig:9061:124: error: redefinition of label 'blk'
        break :blk if (@import("std").zig.c_translation.cast([*c]PyASCIIObject, op).*.wstr) PyUnicode_WSTR_LENGTH(op) else blk: {
                                                                                                                           ^
python3.8.zig:9059:12: note: previous definition here
    return blk: {
           ^
python3.8.zig:9516:30: error: use of undeclared identifier 'sched_priority'
pub const __sched_priority = sched_priority;
```

**Comment by ehaas** [comment]
Minimal repro:
```c
#define FOO (1, (1,  1))
```

**Comment by ali5h** [comment]
I still see this issue
```
./python3.8.zig:9482:30: error: use of undeclared identifier 'sched_priority'
pub const __sched_priority = sched_priority;
```

**Comment by ali5h** [comment]
@ehaas @Vexu

**Comment by ali5h** [comment]
how can i have zig find `sched_priority` in libc?

**Comment by ehaas** [comment]
Oops, missed that second error. It looks like it's caused by a construct like this:
```c
#define sched_priority    sched_priority
#define __sched_priority  sched_priority
```

that produces the following code:
```zig
pub const __sched_priority = sched_priority;
```

Are you able to edit the generated code? As a workaround you could delete the generated line for `__sched_priority`. 
The other option is to pass `-D__sched_priority` to `zig translate-c` so that `__sched_priority` gets omitted from the output as well, but that could be a problem if any of the source happens to use the `__sched_priority` spelling.
