### ISSUE TITLE
doc/langref: replace `package-level` with `container level`

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#11091]
The documentation uses the term `container level variable` in https://ziglang.org/documentation/master/#Container-Level-Variables, and in the grammar.

However in https://ziglang.org/documentation/master/#Top-Level-Doc-Comments, it uses the term `package-level comment`.

**Comment by Vexu** [comment]
Feel free to make a pull request for a trivial change like this, the langref is generated from https://github.com/ziglang/zig/blob/master/doc/langref.html.in using the command `zig build docs`.

**Comment by perillo** [comment]
@Vexu Thanks.
I have tried to read the CONTRIBUTING.md file but it was not very useful.  There is no information about the conventions to use for a PR, like the format of the commit header (the first line) or if the commit message should include the associated issue number.

I have experience in contributing to the Go project but I have never used the Github Flow.

**Comment by Vexu** [comment]
> I have tried to read the CONTRIBUTING.md file but it was not very useful. There is no information about the conventions to use for a PR, like the format of the commit header (the first line) or if the commit message should include the associated issue number.

We're not too pedantic about details like that but generally the convention is that small changes do not require an issue beforehand, commit messages don't need to follow a format but more detailed is better, and if the PR addresses an issue link it using a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

I'll try to document this in CONTRIBUTING.md to make it more clear in the future.

**Comment by dxps** [comment]
I'm a newbie in Zig, but pretty excited about it and very keen on contributing. :blush: 

Related to `langref.html.in` file, I have a first question about formatting. Let me present my case.

Since this has an HTML format, I am tempted to use it accordingly:

1. Inform VSCode (my editor of choice, by default) about it.
   - Instead of "Plain Text", selecting "HTML" I get a nice syntax highlighting.
   - I would also be able to use a proper formatting.
   - I'm using the default formatter
     ```json
     "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
     },
     ```
     but, of course, if I'd do that pretty much the whole file gets reformatted.

2. Keep treating it as "Plain Text" is doable (not preferred, ofc), but I won't be able to collapse some sections.
   - For example, the `<style` section gets partially collapsed since there is a wrong indentation at line 55 (and everything below within the section).

So the question is: do we have a formatting rule on this file that all of us would use :question: 

Meanwhile, I'll "take my chance" and propose a PR, at least for this minimal indentation fix and the small correction presented in this issue.

**Comment by yujiri8** [comment]
Looks like the PR for this got merged, but the issue didn't get auto-closed because the commit title wasn't formatted correctly. @dxps for future reference I believe you have to put '#' before the issue number to get it to auto-close.
