### ISSUE TITLE
std.dwarf: Incorrect Compile Unit CWD

### ISSUE THREAD

**Issue by ominitay** [ziglang/zig#11106]
### Zig Version

0.10.0-dev.1211+0f0d27ce2

### Steps to Reproduce

Compile the reproduction case below.
https://gist.github.com/ominitay/3dc2886a1bfd3608cad13c78b2f5bdf7
Run the executable, passing the path to an executable built with debug info. The outputted path should be the path to the root source file's parent directory. Now, run the executable with an object file built with debug info. The path outputted will be a seemingly-random string from the file's debug info.

### Expected Behavior

The example program should output the correct path for the object file. 

cc: @N00byEdge @kubkon

**Comment by kubkon** [comment]
Looking at this now, and so far, your gist works fine for me (with a minor tweak to update it for the latest `std.dwarf` changes https://gist.github.com/kubkon/fb65f740fea47c33908836b450398b8f/revisions):

Here's what I tried so far:

```
$ zig build-exe get_cwd.zig
$ cat test.zig
pub fn main() void {
    unreachable;
}

$ zig build-exe test.zig
$ ./get_cwd test
compile unit cwd: .

$ dwarfdump test | grep DW_AT_comp_dir
                                DW_AT_comp_dir              .
```

My setup:

```
Linux kurosaki 5.10.99 #1-NixOS SMP Tue Feb 8 17:30:41 UTC 2022 x86_64 GNU/Linux
```

**Comment by kubkon** [comment]
Posting it here from my explanation on Discord:

For relocatables, since the compiler doesn't know how many translation units there might be, offsets into `.debug_str` (from `.debug_info`) are not relocated. The linker will relocate each entry upon linking and fixup the offsets; thus, if you look into a reloc section, in this case,`.rela.debug_info`, you'll find that the value pointing at a string corresponding to `DW_AT_comp_dir` needs a fixup. Our `std.dwarf` module could do it but it would need to detect that it's a relocatable, which kinda seems forced to me. Perhaps it's best left to the implementor to actually do the relocs themselves?

**Comment by kubkon** [comment]
Again, cross-posting from Discord:

Here's a tweak to the program in the gist that handles relocatable object files https://gist.github.com/kubkon/fb65f740fea47c33908836b450398b8f/revisions. The general rule of thumb here is to first relocate the `.debug_info` section before parsing it using `std.dwarf` functionality. For standalone relocatables, this amounts to simply writing the addends read from the reloc structures into their target offsets in the target section.

**Comment by ominitay** [comment]
Superceded by #11281
