### ISSUE TITLE
doc/langref: use the term `rune literal` instead of `Unicode code point literal`

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#11110]
The term `Unicode code point literal` is simply too long.
This term is used in https://ziglang.org/documentation/master/#String-Literals-and-Unicode-Code-Point-Literals, but as a counter example, in the grammar at https://ziglang.org/documentation/master/#Grammar, the associated token is named `CHAR_LITERAL`.

The use of `char` may be confusing, as documented in https://ziglang.org/documentation/master/#String-Literals-and-Unicode-Code-Point-Literals.

I propose to introduce the term `rune`, and rename the token to `RUNE_LITERAL`.
Unlike Go, `rune` in Zig is not a type, but just an alias for Unicode point literal to improve the documentation.

**Comment by matu3ba** [comment]
The correct terminology for utf8 ist grapheme, glyph, codepoints and code units.
https://stackoverflow.com/questions/27331819/whats-the-difference-between-a-character-a-code-point-a-glyph-and-a-grapheme/27331885#27331885

There are 7 occurences and the terminology is correct, so to me introductin this additional indirection is not worth it.
Further more, there is already the deviation to use "literals" as to have hex characters instead of control characters in source code.
Adding more indirection makes things even more complex.

Used in the grammar are
```txt
CHAR_LITERAL <- "'" char_char "'" skip
char_char
    <- mb_utf8_literal
     / char_escape
     / ascii_char_not_nl_slash_squote
```
and the phrasing in the grammar could be improved to be more accurete to `code unit literal` or something related.

**Comment by perillo** [comment]
@matu3ba It doesn't have to be `rune`, what's important is consistency.
As an example, in the `std` lib there are several occurrence of the term `character`.

Also note that `grapheme`, `glyph` and `code unit` are not equivalent to `code point`, and `utf-8` is just an encoding.
So to be consistent we should use `code point` or `Unicode code point`.  `rune` is just an alias for convenience.
