### ISSUE TITLE
Setting derefed pointer to packed struct member generates invalid llvm

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#1121]
I'm not on current master, but I'm pretty sure this hasn't been fixed.
Zig version: 0.2.0.b11c5d8f

```
const S = packed struct {
    a: u2,
    b: u2,
};

test "" {
    var s = S{.a = 2, .b = 0};
    var b_ptr = &s.b;
    b_ptr.* = 2;
}
```

```
Stored value type does not match pointer operand type!
  store i8* %2, i2** %b_ptr, align 8, !dbg !642
 i2*LLVM ERROR: Broken module found, compilation aborted!
```

**Comment by andrewrk** [comment]
I think I need to rework the bit field pointer metadata.

Right now the type of `b_ptr` is `*align(1:2:4) u2`:
 * The pointer address points to the containing integer, which in this case zig has selected a `u8` to contain the `u2` fields.
 * First number (`1`) is byte alignment of the pointer address.
 * Second number (`2`) is the bit offset in the containing integer. The problem is that we don't know the size of the containing integer from the pointer metadata so we cannot use this information.
 * Third number (`4`) is the end bit offset in the containing integer. This information is redundant with the child element type (`u2`).

So I think to fix this we will have to change it to: `*align(1:2:1) u2`. This will be the same as before, except the third number is replaced with the byte count of the containing integer that can be found at the pointer's address. So then when zig dereferences this pointer, it knows to load a 1 byte integer, then shift right to offset by 2, and then mask to get only 2 bits.

**Comment by andrewrk** [comment]
I implemented the above described change, and now the issue is fixed. In the unlikely scenario that you have explicitly `align(x:y:z)` in your code, the meaning of `z` is changed as described above.
