### ISSUE TITLE
Incorrect bounds check on ptrCast-ed const value

### ISSUE THREAD

**Issue by tgschultz** [ziglang/zig#1150]
```zig
const std = @import("std");
const minInt = std.math.minInt;

test "aoeu" {
    const is_value = ~@intCast(isize, minInt(isize));
    const is_bytes = @ptrCast([*]const u8, &is_value)[0..@sizeOf(isize)];
}
```
Produces:
```
error: out of bounds slice
```
The compiler seems to think the bounds are `[0..1]`. Changing `is_value` to var makes the code compile correctly.

**Comment by isaachier** [comment]
Is this even valid? I had a similar case where I wanted to cast a number to a slice and ended up using a `@bitCast` like so:

```
const x : usize = 10;
const arr = []usize{ x };
const bytes = @sliceToBytes(usize, arr[0..]);
```

**Comment by tgschultz** [comment]
After discussing some things with @alexnask, this is not really a bug due to how the compiler treats values at comptime. Leaving the issue open as I think it would be helpful if this difference was communicated by the compiler in instances like this, though I'm not sure if that can be done with an error message since there might be valid cases for doing something like this anyway.

**Comment by isaachier** [comment]
Care to share the gist of that conversation?

**Comment by tgschultz** [comment]
Right, the gist of it seems to be that all integer types are bigints under the hood at comptime, even if you explicitly type them like so `const some_int: i32 = 10;`. From the behavior, I can guess that this means they are treated as having a size of 1.

**Comment by alexnask** [comment]
@isaachier  @tgschultz 

This particular behavior is not caused because of the underlying bigint representation.  

What is happening is that the casted pointer still points to the correct spot in memory but the information on the underlying byte count is lost.  
That means that the compiler thinks this is a pointer to a single byte.  
Consider the following:  
```zig
test "Comptime byte slices" {
    comptime {
        var a: struct { a: usize, b: u64 } = undefined;
        var b = @ptrCast([*]u8, &a)[0..2]; // <- This fails just like if a: <integer type>
    }
}
```

The only context where @ptrCast'ing is useful in comptime, as far as I can tell, is to erase the type of some pointer but you always have to cast back to the original type to get expected behavior.

**Comment by andrewrk** [comment]
It's a bug - or rather at least it's an unimplemented feature with an incorrect compile error. I believe this is the same as #1292, that is, zig's compile-time pointer reinterpretation code has to be improved to fix this. Since it's rather involved and potentially could surface new bugs, I'll postpone it for after the 0.3.0 release.

**Comment by marler8997** [comment]
Looks like a user on reddit ran into this error: https://www.reddit.com/r/Zig/comments/ju0tqw/out_of_bounds_error_when_taking_a_slice_of_a/

Here is the simplified example I came up with:
```zig
test "" {
    const val : u32 = 0;
    const val_ptr = @ptrCast([*]const u8, &val);
    _ = val_ptr[1];
}
```
```
./test.zig:4:16: error: index 1 outside pointer of size 1
    _ = val_ptr[1];
```



This example has a better error message that confirms what @alexnask said:
> What is happening is that the casted pointer still points to the correct spot in memory but the information on the underlying byte count is lost. That means that the compiler thinks this is a pointer to a single byte.

**Comment by SamTebbs33** [comment]
Thanks for the help @marler8997 . I can confirm that using `var` instead is a workaround.
