### ISSUE TITLE
How to parse json with fields contains whitespaces ?

### ISSUE THREAD

**Issue by thechampagne** [ziglang/zig#11508]

**Comment by Vexu** [comment]
This issue tracker is reserved for issues with the language, questions should be asked in one of the [communities](https://github.com/ziglang/zig/wiki/Community).

But since we're already here, assuming you're talking about parsing into a type, the answer is to use the [`@""` syntax](https://ziglang.org/documentation/master/#Identifiers) for identifiers:
```zig
test {
    const T = struct {
        @"field with whitespace": u32,
    };
    const r = try std.json.parse(T, &std.json.TokenStream.init(
        \\{
        \\  "field with whitespace": 420
        \\}
    ), .{});
    defer std.json.parseFree(T, r, .{});
    try std.testing.expectEqual(@as(i64, 420), r.@"field with whitespace");
}
```
