### ISSUE TITLE
Debug WASM build overwrites unrelated memory

### ISSUE THREAD

**Issue by samrat** [ziglang/zig#11517]
### Zig Version

0.10.0-dev.1863+f8d2b87fa

### Steps to Reproduce

I've detailed the steps to reproduce the issue here: https://gist.github.com/samrat/596bcc50b19773839d514d85d99179a6

### Expected Behavior

When a struct is created with a `null` field, in `Debug` mode another field is also getting set to `null`. This does not happen in `ReleaseSafe` mode.

I expected that the `Debug` mode output(which is also shown in the Gist linked above) when the `js` file invokes the WASM file, to be the same as the output for `ReleaseSafe`.

### Actual Behavior

WASM compiled in `Debug` mode seems to overwrite unrelated memory when a struct is initialized with a `null` field.

**Comment by Luukdegram** [comment]
You're returning a pointer to a stack variable at line 39. 
The reason why in debug mode you have a different value, is because it will overwrite the value at said stack position. What you probably want to do, is return a pointer of the memory you allocated, which can be done with `ptr.ptr`. (I'd suggest a different variable name for that reason). This also means you'll have to update the function signature of your `alloc` function.

**Comment by samrat** [comment]
Ah, thanks. That makes perfect sense.

**Comment by nektro** [comment]
next time please include test code in the issue instead of a gist
