### ISSUE TITLE
Unable to put array of "type < 1 byte" inside packed struct

### ISSUE THREAD

**Issue by locriacyber** [ziglang/zig#11540]
### Zig Version

0.10.0-dev.1919+5da0e0355

### Steps to Reproduce

Run the following code
```
const std = @import("std");

const Foo = packed struct {
    bar: i32,
    baz: [4]u4,
};

pub fn main() anyerror!void {
    var foo: Foo = undefined;
    std.debug.print("{d}\n", .{foo.baz});
}
```

### Expected Behavior

At least some way to use data like `[4]u4` in `packed struct`.

Another example: if a type takes up 12 bits, and I want the following memory layout.

```
01234567 bits/bytes
aaaaaaaa  0x00
aaaabbbb  0x01
bbbbbbbb  0x02
```

One example of this is in old game consoles or fantasy consoles, where there exists array of 2-bit or 4-bit flags.

### Actual Behavior

```
./test.zig:5:5: error: array of 'u4' not allowed in packed struct due to padding bits (must be padded from 16 to 32 bits)
    baz: [4]u4,
    ^
```

**Comment by SpexGuy** [comment]
This is not currently planned.  The primary reason is because the language has no way to represent the type of the result of `&foo.baz[i]`, where `i` is a runtime value.  According to type info (struct containing array), this operation should be valid.  Metaprogramming can expect that this operation will not be a compile error.  But we do not have a way to represent a bitfield pointer with a runtime bit offset.  Adding that would be a large amount of complexity, so we do not plan to support arrays in packed structs.

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
