### ISSUE TITLE
index out of range in std.crypto.ecc.Edwards25519.mulDoubleBasePublic

### ISSUE THREAD

**Issue by OfekShochat** [ziglang/zig#11563]
### Zig Version

0.9.1

### Steps to Reproduce

```
const std = @import("std");
const mem = std.mem;
const crypto = std.crypto;
const Ed25519 = crypto.sign.Ed25519;
const Edwards25519 = crypto.ecc.Edwards25519;
const Ristretto = crypto.ecc.Ristretto255;
const Fe = Edwards25519.Fe;
const g = Ristretto{ .p = .{
    .x = .{ .limbs = .{ 1738742601995546, 1146398526822698, 2070867633025821, 562264141797630, 587772402128613 } },
    .y = .{ .limbs = .{ 1801439850948184, 1351079888211148, 450359962737049, 900719925474099, 1801439850948198 } },
    .z = Fe.one,
    .t = .{ .limbs = .{ 1841354044333475, 16398895984059, 755974180946558, 900171276175154, 1821297809914039 } },
    .is_base = false, // maybe when its true it uses a table
} }; // Ristretto.basePoint somehow isnt correct???
const scalar = crypto.ecc.Curve25519.scalar;
const Scalar = scalar.Scalar;
const sha = crypto.hash.sha3;
const Sha3_512 = sha.Sha3_512;
const Sha3_256 = sha.Sha3_256;
const BigInt = std.math.big.int.Mutable;
const Sfc64 = std.rand.Sfc64;
const mulDoubleBasePublic = crypto.ecc.Edwards25519.mulDoubleBasePublic;

pub fn main() !void {
    var rng = Sfc64.init(10000000);
    // 100000 somehow makes this crash.
    var vrf_secret = randomScalar(&rng);
    var proof = try prove("hoola", vrf_secret, &rng);
    var is_valid = try verify("hoola", try g.mul(vrf_secret.toBytes()), proof);
    std.log.info("{}", .{is_valid});
}

fn RistrettoFromInput(input: []const u8, hasher: anytype) Ristretto {
    if (hasher.digest_length != 64) {
        @compileError("The hasher's output has to be 512 bits");
    }

    var out = mem.zeroes([64]u8);
    hasher.hash(input, &out, .{});

    return Ristretto.fromUniform(out);
}

pub const VrfProof = struct {
    beta: [32]u8, // output
    gamma: Ristretto,
    c: [32]u8,
    s: Scalar,
};

fn randomScalar(rng: anytype) Scalar {
    var s = mem.zeroes([32]u8);
    rng.fill(&s);
    return Scalar.fromBytes(s);
}

fn prove(input: []const u8, secret: Scalar, rng: anytype) !VrfProof {
    const h = RistrettoFromInput(input, Sha3_512);
    const gamma = try h.p.mul(secret.toBytes());

    _ = rng;

    const k = Scalar.fromBytes(.{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }); // randomScalar(rng);
    var hasher = Sha3_256.init(.{});
    hasher.update(&g.toBytes());
    hasher.update(&h.toBytes());
    const gm = try g.mul(secret.toBytes());
    hasher.update(&gm.toBytes());
    const hm = try h.p.mul(secret.toBytes());
    hasher.update(&hm.toBytes());
    var out = mem.zeroes([32]u8);
    hasher.final(&out);
    std.log.info("aa {any}", .{out}); // when printing here it crashes (if I remove this it doesnt crash) also the output isnt correct from here (this included).
    const gmk = try g.mul(k.toBytes());
    hasher.update(&gmk.toBytes());
    const hmk = try h.p.mul(k.toBytes());
    hasher.update(&hmk.toBytes());

    var c = mem.zeroes([32]u8);
    hasher.final(&c);

    const s = scalar.sub(k.toBytes(), secret.mul(Scalar.fromBytes(c)).toBytes());

    var beta = mem.zeroes([32]u8);
    Sha3_256.hash(&gamma.toBytes(), &beta, Sha3_256.Options{});

    return VrfProof{
        .beta = beta,
        .gamma = Ristretto{ .p = gamma },
        .c = c,
        .s = Scalar.fromBytes(s),
    };
}

fn verify(input: []const u8, public: Ristretto, proof: VrfProof) !bool {
    const u = try mulDoubleBasePublic(public.p, proof.c, g.p, proof.s.toBytes()); // proof.c
    const h = RistrettoFromInput(input, Sha3_512);
    const v = try mulDoubleBasePublic(proof.gamma.p, proof.c, h.p, proof.s.toBytes());

    var hasher = Sha3_256.init(.{});
    hasher.update(&g.toBytes());
    hasher.update(&h.toBytes());
    hasher.update(&public.p.toBytes());
    hasher.update(&proof.gamma.toBytes());
    hasher.update(&u.toBytes());
    hasher.update(&v.toBytes());

    var c = mem.zeroes([32]u8);
    hasher.final(&c);

    var gamma_hash = mem.zeroes([32]u8);
    Sha3_256.hash(&proof.gamma.toBytes(), &gamma_hash, .{});

    return gamma_hash[0..32] == proof.beta[0..32] and c[0..32] == proof.c[0..32];
}
```

### Expected Behavior

works and doesnt output wrong stuff. all my notes are crossed checked with a rust version https://github.com/dalek-cryptography/curve25519-dalek

### Actual Behavior
also basepoint is somehow wrong?? (or is it? it isnt endianness because then the whole number would be different, so what is it?)
when the seed is 100000, [this](https://github.com/ziglang/zig/blob/0.9.x/lib/std/crypto/25519/edwards25519.zig#L165) somehow isnt true. the last element is 10 and thus crashes on https://github.com/ziglang/zig/blob/0.9.x/lib/std/crypto/25519/edwards25519.zig#L275. 
also, for some reason when I print the hash after I multiply g and k (before that it wont crash), it crashes in the same place even without that seed.
~~Edit looked at the source and the final method had side effects. So nvm~~ that should not output a wrong value though

note: I cant work rn on the minimal example. will do it later

**Comment by OfekShochat** [comment]
@jedisct1 made it, which is weird. Afaik they made libsodium...

**Comment by jedisct1** [comment]
Hi!

Public scalars are expected to always be in the `]0..l[` range.

The `randomScalar()` function should either sample from a bigger range and perform a reduction, or do rejection sampling. This avoid biases.

With the P256 curve, we have a `P256.scalar.random()` function. Your example shows that having this for curve25519/edwards25519/ristretto255 would also be a useful addition. Noted :)

An implicit reduction was supposed to be made in order to safe guard against inputs that are out of range, but the check was reversed.

This is now fixed, thanks!

**Comment by jedisct1** [comment]
In libsodium, double base multiplication doesn't support non-canonical scalars either, but misuse is impossible since it is only an internal function, that doesn't exist in the public API.

**Comment by OfekShochat** [comment]
Thank you so so much! It hasn't even struck my mind tbh (not that I'm nearly an expert)... Man, I love this community, I expected to wait for weeks. Yea, I considered using libsodium and it worked there..
You mean this is fixed in newer versions (aka do I close the issue or you want to mention it on a pr)?
Thank you so much!

**Comment by jedisct1** [comment]
It's fixed in a PR that will be merged after CI passes :)

libsodium doesn't have APIs for multiplying group elements with public scalars. When using the public API, a reduction is always done even if unnecessary. All the `crypto_scalar_*` functions also silently perform an unconditional reduction.

These functions are never used internally. Internally, we use equivalents of `mulDoubleBasePublic` and `mulPublic` since they are faster, but they would fail in a really bad way with invalid inputs.

In Zig, `mulDoubleBasePublic` and `mulPublic` are available as faster alternatives to a secret multiplication, but this is a sharp razor blade. As a balance between not exposing them and exposing something that can be misused, I added an artificial reduction in case the top bit is set (which is usually not the case with reduced scalars). But the check was reversed. Something that was unnoticed since it doesn't make a difference with valid scalars. But thanks to your bug report, this should now work as expected with invalid scalars as well.

Thanks!
