### ISSUE TITLE
error: invalid argument '-std=c++11' not allowed with 'C'

### ISSUE THREAD

**Issue by leleliu008** [ziglang/zig#11757]
### Zig Version
```
0.10.0-dev.2377+71e2a56e3
```

### Steps to Reproduce
```
zig c++ -std=c++11 test.c
```
### Expected Behavior

same as gcc or clang.

gcc output no warning.

clang output a warning:
```
clang-13: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
```

I found this when I build gcc from source code.

### Actual Behavior

```
error: invalid argument '-std=c++11' not allowed with 'C'
```

**Comment by nektro** [comment]
zig error is more clear

**Comment by leleliu008** [comment]
I understand. Accoding to https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html, it claimed that `zig cc` is a drop-in replacement for gcc and clang. if the behavior is not same as gcc and clang. user can not treat it as a drop-in replacement.

**Comment by andrewrk** [comment]
If zig cc had purely identical behavior to clang then there would be no purpose of using zig cc instead of clang. It is useful precisely because the behavior is different in some key ways. The word "drop in" is a clue of how zig cc is intended to be used rather than a specification.

This is working as designed and has helpfully provided some feedback to your project to clean up your CLI arguments, regardless of whether you are using GCC, clang, or zig cc.
