### ISSUE TITLE
`std.build`: `-L` flags are added after `-l` flags

### ISSUE THREAD

**Issue by yyny** [ziglang/zig#11801]
### Zig Version

0.10.0-dev.2489+33826a6a2

### Steps to Reproduce

Create a `zig build` script, add a `addLibPath("foo")` and a `linkSystemLibrary("bar")`

### Expected Behavior

The `-Lfoo` argument comes before the `-lbar` argument. The bar library is found and linked against.

### Actual Behavior

The `-Lfoo` argument comes after the `-lbar` argument. The bar library is not found.

**Comment by mikdusan** [comment]
On linux, latest zig master, I tried these things to reproduce and could not. They all linked successfully.

1. zig driver with .so
```sh
$ zig build-lib -dynamic foo.c
$ zig build-exe hello.zig -lfoo -L. --verbose-link
LLD Link... ld.lld --error-limit=0 -O0 -z stack-size=16777216 --gc-sections -znow -m elf_x86_64 -o hello -rpath . -L . -L /usr/local/lib64 -L /usr/local/lib -L /usr/lib/x86_64-linux-gnu -L /lib64 -L /lib -L /usr/lib64 -L /usr/lib -L /lib/x86_64-linux-gnu hello.o /home/mike/project/zig/work/main/zig-cache/o/ddf237abdacd2757f27f24078f24008e/libc.a --as-needed -lfoo /home/mike/project/zig/work/main/zig-cache/o/939a2ffbc6512a945a1d4c6a1756bdee/libcompiler_rt.a
# ok
```

2. redo LLD link line, moving `-L .` to last arg
```sh
zig ld.lld --error-limit=0 -O0 -z stack-size=16777216 --gc-sections -znow -m elf_x86_64 -o hello -rpath . -L /usr/local/lib64 -L /usr/local/lib -L /usr/lib/x86_64-linux-gnu -L /lib64 -L /lib -L /usr/lib64 -L /usr/lib -L /lib/x86_64-linux-gnu hello.o /home/mike/project/zig/work/main/zig-cache/o/ddf237abdacd2757f27f24078f24008e/libc.a --as-needed -lfoo /home/mike/project/zig/work/main/zig-cache/o/939a2ffbc6512a945a1d4c6a1756bdee/libcompiler_rt.a -L .
# ok
```

3. similar but using system gcc compiler, and using `collect2` to re-do link with forced last-arg `-L .`; linked fine

This, so far, indicates it *shouldn't* matter if a `-L` is before or after a related `-l` option. It's also possible that zig has improved since opening this issue.

Are you able to reproduce with newest zig, and if so, please provide details like which os, and if using `zig build-exe` or `zig cc`. Thanks.

**Comment by yyny** [comment]
The argument order _does_ matter for `ldd-link.exe`. It seems that this issue was already fixed at some point though, because `-LIBPATH:` options always come first. That seemed to have been the underlying problem.
