### ISSUE TITLE
figure out why stage3 and stage4 are not byte-for-byte identical

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#12183]
According to Zig's [build modes documentation](https://ziglang.org/documentation/master/#Build-Mode):
 * `-ODebug` is not required to be reproducible (building the same zig source may output a different, semantically equivalent, binary)
 * `-OReleaseSafe`, `-OReleaseSmall` and `-OReleaseFast` are all required to be reproducible (building the same zig source outputs a deterministic binary)

Terminology:

 * **stage1** is the compiler implementation in `src/stage1/*`, compiled with system toolchain
 * **stage2** is the compiler implementation in `src/*`, compiled with stage1.
 * **stage3** is the compiler implementation in `src/*`, compiled with stage2.
 * **stage4** is the compiler implementation in `src/*`, compiled with stage3.

In theory, stage3 and stage4 should be byte-for-byte identical when compiled in release mode. In practice, this is not true:

```
$ ls -l stage{3,4}-release/bin/zig
-rwxr-xr-x 1 andy users 240065464 Jul 20 17:22 stage3-release/bin/zig
-rwxr-xr-x 1 andy users 240065552 Jul 20 19:45 stage4-release/bin/zig
```

These binaries are not even the same number of bytes, let alone have the same contents.

This likely indicates a miscompilation in the `src/*` compiler implementation.

Some ideas to look into:
 * Try with a debug build even though it's not guaranteed to be reproducible; there may be some clues there
 * Try comparing LLVM IR pre-optimization
 * Try looking at each linker input independently

**Comment by pjz** [comment]
One initial reason: despite the ZIR (via ast-check) being the same, the AIR (output via --verbose-air) is different.  Specifically, the `Function Air` blocks have been reordered.  This of course also changes the names of anon decls since they're based on that decl's index. In fact, it turns out that the AIR output when building stage3 is not at all reproducible, whether built by stage2 or stage3.  So at least part of the problem is in Sema.zig ;  I may try an narrow it down some, but I figured passing on clues I've found might help someone who knows the compiler internals get there faster.
