### ISSUE TITLE
Root set to test runner instead of main file when running tests

### ISSUE THREAD

**Issue by Sirius902** [ziglang/zig#12201]
### Zig Version

0.10.0-dev.3071+8e75ba653

### Steps to Reproduce

Create a project with `zig init-exe` and modify `main.zig` to contain the following code.
```zig
const a = @import("a.zig");

comptime {
    _ = a;
}

pub const message = "hi";

pub fn main() void {
    a.logMessage();
}
```

Then, add `a.zig` with the following source.
```zig
const std = @import("std");
const message = @import("root").message;

pub fn logMessage() void {
    std.log.info(message, .{});
}

test "foo" {
    try std.testing.expectEqualStrings("hi", message);
}
```

### Expected Behavior

I expect `root` to be `main.zig` both when executing `zig build run` and `zig build test`, causing both to compile successfully.

### Actual Behavior

The program runs properly when run with `zig build run`, outputting `info: hi`,  but when tests are run with `zig build test` it fails with the following compiler error.
```
.\src\a.zig:2:32: error: container '(root)' has no member called 'message'
const message = @import("root").message;
                               ^
error: test...
```

I believe this is due to `root` being `main.zig` when building the executable, but it is `lib/test_runner.zig` when running tests.

**Comment by dweiller** [comment]
There might be an issue with resolving the `"root"` package in situations where the test runner and tested code both want to be the root package (i.e. setting public decls that libraries/std look at).

As a note for if/when someone tries to change the current behaviour: probably need to look at what is happening in `src/Compilation.zig` and the interplay between `main_pkg` and `root_pkg` in `create()`. Is it fine to just do `main_pkg.add(gpa, "root", main_pkg);` rather than adding `root_pkg`?

**Comment by matklad** [comment]
I wonder if this should be reconsidered, given that Zig now has packages?

I'd expect the `test_runner.zig` code, and my own `unit_tests.zig` code to be two different zig packages, with independent `@import("root")`s, such that the `test_runner` package imports my unit-test package and runs its functions.
