### ISSUE TITLE
libcurl example doesn't seem to work

### ISSUE THREAD

**Issue by lkadalski** [ziglang/zig#12255]
Hello there, I'm trying to use curl from simple zig program but it doesn't behave as mentioned in resolved ticket originally posted by @lithdew in https://github.com/ziglang/zig/issues/988#issuecomment-660037488

Using zig 0.9.1(and I belive newer) current output is:
```
./src/bin/curl_c_lib.zig:16:39: error: expected type 'c_uint', found '@Type(.EnumLiteral)'
    try wrap(c.curl_easy_setopt(curl, .CURLOPT_URL, "www.example.org"));
                                      ^
  ```                          
I'm using macos Monterey 12.5

**Comment by Luukdegram** [comment]
Since the release of Zig 0.9.0 we no longer support C-style enums, and translate-c now converts them into constants instead. You can read more about these changes in the release-notes found here: https://ziglang.org/download/0.9.0/release-notes.html#C-Translation.
We have a more up-to-date CURL example on the website of Zig which can be found here: https://ziglang.org/learn/samples/#using-curl-from-zig

The issue tracker is meant for bugs found in the Zig toolchain, so I'm closing this issue. If you have any further questions, I'd suggest joining one of the friendly communities found at https://github.com/ziglang/zig/wiki/Community.

**Comment by lkadalski** [comment]
Thanks, this is what I was looking for! 👍
