### ISSUE TITLE
std.math.rotl/rotr fail to compile for "non-native" (e.g. u12) types

### ISSUE THREAD

**Issue by daneelsan** [ziglang/zig#12315]
### Zig Version

0.10.0-dev.2887+3f11d1d56

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() anyerror!void {
    const x: u12 = 0o7777;
    std.debug.print("res: 0o{o:0>4}\n", .{std.math.rotl(u12, x, 1)});
}
```

### Expected Behavior

It should compile, as the number of rotations, `1`, is less than the size of the type, `12`.

### Actual Behavior

Fails to compile:
```bash
error: RHS of shift is too large for LHS type
        return x << ar | x >> 1 +% ~ar;
                           ^
./test3.zig:5:56: note: called from here
    std.debug.print("res: 0o{o:0>4}\n", .{std.math.rotl(u12, x, 1)});
                                                       ^
./test3.zig:3:29: note: called from here
pub fn main() anyerror!void {
                            ^
/opt/homebrew/Cellar/zig/HEAD-3f11d1d_1/lib/zig/std/math.zig:623:26: note: type u12 has only 12 bits
        return x << ar | x >> 1 +% ~ar;
```

This is used to compile in zig 0.9.

This issue was introduced in https://github.com/ziglang/zig/pull/11432.
@paoda gives a good explanation about why this fails in the comments.

**Comment by iury** [comment]
we seem to have a regression. this same example fails the same way on version `0.12.0-dev.3161+377ecc6af`

**Comment by paoda** [comment]
When `T == u12`, Zig seems to behave as if `isPowerofTwo(12) == true`?  
https://github.com/ziglang/zig/blob/f3227598ebe9ac7e330fea0259d4290ee31e96b9/lib/std/math.zig#L737-L739

My embarrassing mistake when I wrote this was assuming that `isPowerofTwo` would be executed at `comptime`. It is not.

Ensuring that `isPowerOfTwo` is run at `comptime` fixes the regression, but that should be more than enough to demonstrate that there's some more severe bug here, since I didn't change any of the logic. 

I'll submit my PR that adds the `comptime` keyword, but I'd assume that either an already issue should link to here or another issue should be created that investigates what's going on here. 

From what I understand.
- The problem has to do with `if (isPowerOfTwo(@typeInfo(T).Int.bits)) {} else {}`  as it is used in `std.math.rotl` and `std.math.rotr` specifically
- `isPowerOfTwo` is executed at runtime
- In the case that `T == u12` when calling `std.math.rotl` or `std.math.rotr` the "`true` block" is run even though 12 is not a power of two. 
-  If the statement becomes `if (comptime isPowerOfTwo(@typeInfo(T).Int.bits)) {} else {}`, when `T == 12` the "`false` block" is run as expected
- There is nothing in the implementation of `isPowerOfTwo` to suggest that behaviour should differ between runtime and `comptime`

**Comment by Vexu** [comment]
> * In the case that `T == u12` when calling `std.math.rotl` or `std.math.rotr` the "`true` block" is run even though 12 is not a power of two.

Both branches of the if statement are analyzed because the condition was not comptime known.

**Comment by paoda** [comment]
Alright thanks. I wasn't aware this was the case.
