### ISSUE TITLE
missing search results

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#12334]
https://ziglang.org/documentation/0.9.1/std/#?readUntil shows results

https://ziglang.org/documentation/master/std/#?readUntil shows no results

however the data exists: https://ziglang.org/documentation/master/std/#root;io.Reader.readUntilDelimiterArrayList

We should be able to say with confidence that every declaration will be present in the search results, even if not much is known about its type information.

**Comment by kristoff-it** [comment]
For context: those decls were missing because they were part of a generic type (ie the type returned by a comptime function) that was not indexed correctly. 

Instances of `Reader`s are still not present because autodoc is unable to resolve the result of the comptime function call. This could be improved without recurring to semantic analysis, but at the moment it's not done yet.
