### ISSUE TITLE
doc: please document that local const variable cannot be assess before define in source file.

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1244]
### top-level const variable can be assess before define in source file.
```
const std = @import("std");

pub fn main() !void {
    var stdout_file = try std.io.getStdOut();
    std.debug.warn("{}\n",a );
}
const a = "2";
```

### local const variable cannot be assess before define in source file.
```
const std = @import("std");

pub fn main() !void {
    var stdout_file = try std.io.getStdOut();
    std.debug.warn("{}\n",a );
    const a = "1";
}
```
will get:
```
h.zig:6:27: error: use of undeclared identifier 'a'
    std.debug.warn("{}\n",a );
```

**Comment by nodefish** [comment]
This is called hoisting. It would make more sense to document the case when hoisting happens (a simple mention that top-level declarations are hoisted is sufficient), rather than having to explain what the undeclared identifier error means (way too fundamental a concept which even brand new programmers understand on their first day).
