### ISSUE TITLE
Getting location of vector component for non-power-of-two type is broken on stage2

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#12812]
### Zig Version

0.10.0-dev.3978+4fd4c733d

### Steps to Reproduce

```zig
const std = @import("std");
pub fn main() !void {
    var x: std.meta.Vector(2, u15) = .{ 1, 4 };
    std.debug.print("{} {}\n", .{ (&x[0]).*, (&x[1]).* });
}
```

### Expected Behavior

Output of `1 4`

### Actual Behavior

Output of `1 2`, as the second integer is shifted down by 1 bit.

**Comment by kkHAIKE** [comment]
I spent two days trying to fix this bug and found that the problem is not easy..

solution from stage1 is that if 'airLoad' get a ptr to elem of vector, then add llvm-ir `load(vec_ptr) + ExtractElement(vec_ptr, idx)`, but I don't think it works in all cases.

another solution is to modify the following places:
1. 'fn Sema.elemPtrType' when if 'ptr_ty == vector' and 'bits mod 8 != 0'(eg: u15):
    1. if  'offset != null', then calc 'host_size' and 'bit_offset' corrently.
    2. if 'offset == null', means the index is runtime-known, then return a ?:
        1. new pointer type vector_elem_ptr
        2. or current pointer type add new field maybe 'unkown_offset: bool'
        3. must ensure that this pointer type cannot be convert/cast to other type !!!!.
  3. 'fn Sema.analyzeLoad' when if get the new pointer type, try to find vector_ptr, and add air 'load(vec_ptr) + array_elem_val(vec_ptr, index)
