### ISSUE TITLE
Wrong ioctl() return value type (Linux)

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#12961]
Prototype for ioctl() in C  is `int ioctl(int fd, unsigned long request, ...);`
So we typically write

```c
int r = ioctl(fd, SOMEIOCCMD, somearg);
if (-1 == r) { /* handle error */}
```

But in `/opt/zig/lib/std/os/linux.zig` the wrapper for ioctl syscall is defined as

```zig
pub fn ioctl(fd: fd_t, request: u32, arg: usize) usize {
    return syscall3(.ioctl, @bitCast(usize, @as(isize, fd)), request, arg);
}
```
* this function does not return any error
* return value type is unsigned

How do I check for an error then?..
* cast to i32?
* use `/opt/zig/lib/std/c.zig:pub extern "c" fn ioctl(fd: c.fd_t, request: c_int, ...) c_int` instead?

**Comment by squeek502** [comment]
An example usage can be found here:

https://github.com/ziglang/zig/blob/6d7b0690a0e49819ffd92e330f0fd48a7abc0d16/lib/std/os.zig#L6690

`errono` is `system.getErrno` which is implemented here for Linux:

https://github.com/ziglang/zig/blob/6d7b0690a0e49819ffd92e330f0fd48a7abc0d16/lib/std/os/linux.zig#L203-L208

**Comment by dee0xeed** [comment]
> An example usage can be found here:

Yes, I saw this, it is just a **special** case for SIOCGIFINDEX 'command'.

> EDIT: By the way, this type of question is better directed at one of the [community spaces]

I know that (sorry for bothering), but I was not asking for help actually,
the question is why, for example, the read() syscall wrapper (`pub fn read(fd: fd_t, buf: []u8) ReadError!usize {`)
can return an error in **general** case, but ioctl() wrapper (in general case) does not return an error.

**Comment by squeek502** [comment]
> `pub fn read(fd: fd_t, buf: []u8) ReadError!usize {`

This is the `std.os.read` fn definition, not the syscall wrapper. The `read` syscall wrapper is similar to the `ioctl` syscall wrapper:

https://github.com/ziglang/zig/blob/6d7b0690a0e49819ffd92e330f0fd48a7abc0d16/lib/std/os/linux.zig#L462

You can also see that the implementation of `std.os.read` uses the same `errno` function call (actually `system.getErrno`) to convert the `usize` returned from the syscall wrapper into an error enum:

https://github.com/ziglang/zig/blob/6d7b0690a0e49819ffd92e330f0fd48a7abc0d16/lib/std/os.zig#L642-L643

If you wanted a generic `ioctl` wrapper similar to `std.os.read` you could do something like:

```zig
pub const IoCtlError = error{
    FileSystem,
    InterfaceNotFound,
} || UnexpectedError;

pub fn ioctl(fd: std.os.system.fd_t, request: u32, arg: usize) IoCtlError!void {
    while (true) {
        switch (std.os.system.getErrno(std.os.system.ioctl(fd, request, arg))) {
            .SUCCESS => return,
            .INVAL => unreachable, // Bad parameters.
            .NOTTY => unreachable,
            .NXIO => unreachable,
            .BADF => unreachable, // Always a race condition.
            .FAULT => unreachable, // Bad pointer parameter.
            .INTR => continue,
            .IO => return error.FileSystem,
            .NODEV => return error.InterfaceNotFound,
            else => |err| return std.os.unexpectedErrno(err),
        }
    }
}
```

(you'd have to vet that the errors are handled/translated correctly, I just copied the switch from `std.os.ioctl_SIOCGIFINDEX`)

As for why `std.os.ioctl` doesn't exist but `std.os.ioctl_SIOCGIFINDEX` does, it's likely just because Zig internally had a use for `ioctl_SIOCGIFINDEX` but not for a more generic `std.os.ioctl`.

**Comment by dee0xeed** [comment]
I got it, thank you @squeek502!
