### ISSUE TITLE
look into using Ryu instead of Errol3 for floating point printing

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1299]
Bold claim:

> simpler and approximately three times faster than the previously fastest implementation.

paper: https://dl.acm.org/citation.cfm?id=3192369
C implementation: https://github.com/ulfjack/ryu

things to measure:
 * performance
 * code size
 * if it's possible to work without ever using floating point registers

**Comment by andrewrk** [comment]
Note if porting the reference C implementation: we should port the `-DRYU_OPTIMIZE_SIZE`  stuff by checking `builtin.Mode.ReleaseSmall`.

**Comment by tiehuis** [comment]
Will be committing here for the moment. https://github.com/tiehuis/zig-ryu

Also, it would be nice to implement proper `f16` printing support and `f128` (#1181) alongside so I'll keep these in mind.

**Comment by tiehuis** [comment]
Quick update:
 - Preliminary support was added upstream for f128 and f80 values. I've got a local port nearly done.
 - f16 as well I've pretty much done as we can reuse f32 formatting.

This leaves the formatted printing of values remaining before I'd be happy to make a PR. There is an upstream issue for that as well: https://github.com/ulfjack/ryu/issues/27.

**Comment by tiehuis** [comment]
`f16` and `f128` printing support is now present using the 128-bit conversion backend. We should also have proper `c_longdouble` (80-bit float) printing as well when #1188 is done.

**Comment by andrewrk** [comment]
@tiehuis were you blocking on #1188 for this? I can prioritize that if you like.

**Comment by tiehuis** [comment]
Not really. Main requirement here is to put the time and effort in getting the formatted float output modes modes done for alignment/precision, scientific/decimal modes etc. It'll probably tie in with #1358 since they both touch a lot of the formatting code.

**Comment by tiehuis** [comment]
This is a response to https://github.com/ziglang/zig/issues/1290#issuecomment-474109293. Related moreso to this issue so bringing the discussion here.

Here are some actual numbers in regards to the size savings. First, we can construct two simple examples:

### format-std.zig

	const std = @import("std");

	var buf: [32]u8 = undefined;

	export fn print(value: f32) [*]const u8 {
	    const slice = std.fmt.bufPrint(buf[0..], "{}", value) catch unreachable;
	    return slice.ptr;
	}


### format-ryu.zig

	const ryu = @import("index.zig");

	var buf: [32]u8 = undefined;

	export fn print(value: f32) [*]const u8 {
	    const slice = ryu.floatToBuffer(value, buf[0..]);
	    return slice.ptr;
	}


Compiling both of these under `--release-small` with `build-obj` we get two object files. The output of `readelf -s` is as follows (omitting irrelevant noise).

### format-std.o

Total size is **29163 bytes** (excluding `buf` symbol).

	Symbol table '.symtab' contains 483 entries:
	   Num:    Value          Size Type    Bind   Vis      Ndx Name
	     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
	     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS format-std

	   ...

	   460: 0000000000000000    32 OBJECT  LOCAL  DEFAULT    6 buf
	   461: 0000000000004668   200 OBJECT  LOCAL  DEFAULT    7 c_digits_lut
	   462: 0000000000000000  3456 OBJECT  LOCAL  DEFAULT    7 enum3
	   463: 0000000000000000 10368 OBJECT  LOCAL  DEFAULT    8 enum3_data
	   464: 00000000000020e8  9600 OBJECT  LOCAL  DEFAULT    7 lookup_table
	   465: 00000000000011f0  1788 FUNC    LOCAL  DEFAULT    2 std.fmt.errol.u64toa
	   466: 00000000000018f0   168 FUNC    LOCAL  DEFAULT    2 std.math.frexp.frexp64

	   ...

	   479: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __fixunsdfti
	   480: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __udivti3
	   481: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __umodti3
	   482: 0000000000000000  4583 FUNC    GLOBAL DEFAULT    2 print

### format-ryu.o

Total size is **3007 bytes**. Note also that ryu only requires integer operations while errol operates on floats directly.

	Symbol table '.symtab' contains 19 entries:
	   Num:    Value          Size Type    Bind   Vis      Ndx Name
	     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
	     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS format-ryu
	     2: 0000000000000000   200 OBJECT  LOCAL  DEFAULT    5 DIGIT_TABLE

	    ...

	     5: 0000000000000000    32 OBJECT  LOCAL  DEFAULT    4 buf
	     6: 00000000000000c8   248 OBJECT  LOCAL  DEFAULT    5 float_pow5_inv_split
	     7: 00000000000001c0   376 OBJECT  LOCAL  DEFAULT    5 float_pow5_split
     
            ...

	    18: 0000000000000000  2183 FUNC    GLOBAL DEFAULT    2 print

An important thing to note is that internally our errol implementation only works on f64 values. Even when printing an f32 we cast up to an f32 and back down once down. Likewise for f128, in which we lose precision during printing. The current ryu implementation has a 32, 64 and 128 bit backend for each of the float types which any narrower type can use without loss of precision.

That being said, the above example is slightly apples to oranges, since we are comparing a 32-bit printing backend to a 64-bit. Modifying our original examples we get the following:

### format-std.o

Same size as previously. Slightly smaller by a few bytes since casting between f32 to f64 is now not done.

### format-ryu.o

Total size is **4176 bytes**. Slightly larger that the f32 but not a huge amount. The increase in size is not linear as the types increase since the precomputed values are different between the engines. Storing lots of tables is only required for increasing runtime performance. We can precompute smaller amounts and compute based on these instead of doing them all to keep the table sizes reasonable. This is done as per the original implementation.

	Symbol table '.symtab' contains 50 entries:
	   Num:    Value          Size Type    Bind   Vis      Ndx Name
	     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
	     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS format-ryu
	     2: 0000000000000000   200 OBJECT  LOCAL  DEFAULT    5 DIGIT_TABLE

	    ...

	    31: 0000000000000000    32 OBJECT  LOCAL  DEFAULT    4 buf
	    32: 0000000000000000   208 OBJECT  LOCAL  DEFAULT    7 double_pow5_inv_split2
	    33: 00000000000000d0   208 OBJECT  LOCAL  DEFAULT    7 double_pow5_split2
	    34: 00000000000000c8   208 OBJECT  LOCAL  DEFAULT    5 double_pow5_table
	    35: 0000000000000198    80 OBJECT  LOCAL  DEFAULT    5 pow5_inv_offsets
	    36: 00000000000001e8    52 OBJECT  LOCAL  DEFAULT    5 pow5_offsets

	    ...

	    49: 0000000000000000  3220 FUNC    GLOBAL DEFAULT    2 print

### Summary

 - 5-10 times smaller table sizes
 - Accurate floating point printing
 - No floating point operations required (valuable for soft-float architectures)
 - 2-3 times fast the errol
 - Supports f16, f32 and f128 without messy casts to f64

**Comment by andrewrk** [comment]
Wow, huge improvements!

**Comment by tiehuis** [comment]
An additional note but there is some preliminary support now upstream for formatting to a specific precision with ryu. This is done for the f64 backend. This is a separate implementation distinct from the existing (which is focused on shortest representable unique output). I haven't yet looked at it in depth but this was the main remaining issue on the "backend" side of things.

**Comment by shawnl** [comment]
`parse_float.zig` **`Is not round-trip accurate for all values`**

So does that need to be re-written to, to work specifically with ryu's output, so we can be round-trip accurate for all values (including subnormals)?

**Comment by daurnimator** [comment]
@tiehuis is there something ready to merge?

**Comment by tiehuis** [comment]
No. I haven't done anything on this since my last message here so it is still in the same state. You could technically merge right now (updating the code for latest zig), but you would only have the default format provided by ryu and would the precision and different notation options.

**Comment by marler8997** [comment]
I ported the 32-bit version to D if anyone wants to see it for reference.  It's all in one file in D (tests as well): https://github.com/dragon-lang/mar/blob/master/src/mar/ryu.d

**Comment by data-man** [comment]
> updating the code for latest zig

https://github.com/tiehuis/zig-ryu/pull/3

**Comment by tiehuis** [comment]
I've implemented the fixed precision modes for scientific/fixed in a new branch: https://github.com/tiehuis/zig-ryu/tree/dev

I'll likely make a PR soon once I finish up some comparisons and do some testing. Do note that we need more tables to handle this formatting so I'll need to benchmark the increase compared to just preferring shortest unique.

**Comment by data-man** [comment]
Just for info: [dragonbox](https://github.com/jk-jeon/dragonbox) was [merged](https://github.com/fmtlib/fmt/pull/1882) to fmtlib.

**Comment by frmdstryr** [comment]
@tiehuis Thanks for sharing your port.  

I moved everything into a single folder ( https://github.com/tiehuis/zig-ryu/compare/master...frmdstryr:zig-ryu:single-folder ) updated the tests and used it to format a f32 on a cortex-m4f (@192mhz).

With ryu:
```zig
const t = mcu.system.time(.s);
var buf: [20]u8 = undefined;
const result = ryu(f32).printFixed(&buf, t, 1);
try lcd.writeLine(3, result);
```

Size is ~116k (a lot larger) but it only takes about 9us to format!
```
   text    data     bss     dec     hex filename
 115828      20     152  116000   1c520 firmware.elf
```

With zig's current fmt
```zig
const t = mcu.system.time(.s);
var buf: [20]u8 = undefined;
const result = std.fmt.bufPrint(&buf, "{d:.1}", .{t}) catch unreachable;
try lcd.writeLine(3, result);
```

Size is ~46k (a lot smaller) but it takes about ~120us to format the time. (Oddly for small numbers it is almost 500us while ryu seems to be faster in that case).
```
   text    data     bss     dec     hex filename
  46124      20     152   46296    b4d8 firmware.elf
```

Both output the correct value and are compiled with release small.  

It is unfortunate that the tables are so large... as that makes it unusable for a lot of mcus with smaller flash sizes... for PC's the size is negligible.

**Comment by andrewrk** [comment]
I wonder if table values could be generated lazily for -OReleaseSmall builds 🤔

**Comment by tiehuis** [comment]
The tables for the fixed printing variant are pretty large. Something to note as well is the fixed print for f32 up-casts internally to f64 so uses larger tables than is strictly required. There isn't an upstream f32 fixed print however so I didn't implement one in my original code.

As for smaller tables or lazy computation, I do know that the computation of accurate values for these tables uses BigInteger's and needs higher precision than native values so the performance hit could be significant. I am unsure however if you could compute partial tables and get a better trade-off.

On your edit, Ryu doesn't use floating point values internally to compute the string so this matches my expectation.

**Comment by jk-jeon** [comment]
It is in fact possible to do fixed-precision formatting with a much smaller table: https://jk-jeon.github.io/posts/2022/12/fixed-precision-formatting/

For small enough precisions I think it will be faster than Ryu-printf. Actually, the algorithm operates in different ways for small precisions and large precisions, and the portion for the small precisions is recently adapted into fmtlib (https://github.com/fmtlib/fmt/pull/3269). That portion reuses the table used for the shortest roundtrip formatting (which for the case of Dragonbox is of size 9\~10KB, or 500\~600 bytes with a bit of runtime performance cost).

Large precisions case (which should be very rare in practice) still can be done with an additional table of size 580 bytes with 2x-3x slower performance than Ryu-printf, or with a table of size 3\~4 KB with similar performance to Ryu-printf, or something in between those two, according to the benchmark I've done.
