### ISSUE TITLE
std.testing.expectEqual does not work for top-level struct and comptime struct/tuple

### ISSUE THREAD

**Issue by Pyrolistical** [ziglang/zig#13307]
### Zig Version

0.10.0-dev.4563+55c5da1b2

### Steps to Reproduce

Given `repo.zig`
```zig
const expectEqual = @import("std").testing.expectEqual;

const Foo = @This();

bar: u8,

pub fn init() Foo {
    return .{
        .bar = 42,
    };
}

test "std.testing.expectEqual" {
    const foo = Foo.init();

    // expected to fail but does not
    try expectEqual(.{
        .bar = 1,
    }, foo);

    // expected to fail but does not
    try expectEqual(.{ .bar = 1 }, .{ .baz = 42 });

    // expected to fail but does not
    try expectEqual(.{1}, .{42});

    // this properly fails
    // try expectEqual([_]u8{1}, [_]u8{42});

    // this properly fails
    // try expectEqual(1, 42);
}
```

Run `zig test repo.zig`

### Expected Behavior

Expect test to fail

### Actual Behavior

Test passes

**Comment by rohlem** [comment]
Notes from a quick scan:
I think this issue is primarily related to tuple handling, although depending on how compiler fixes in this area develop, we may want to modify `std.testing.expectEqual` to provide additional safety (and/or safety to hotfix this in the mean time).

The current signature is `pub fn expectEqual(expected: anytype, actual: @TypeOf(expected)) !void`. Note that the second argument type is deduced from the first.
In all instances, this shared argument is a tuple, internally translating to something like `struct{ comptime bar: comptime_int = 1 }` (with field name `baz` and `@"1"` for the unnamed tuple later).

In the first instance it seems stage2 is missing a safety check when coercing structs to tuples.
In the second and third instances it seems the incompatible tuple types are also coerced between without error; by the time `expectEqual` would iterate over the fields, their values (as defined by comptime fields' default value) already changed.
I couldn't find any issues about tuple coercion in stage2 directly.

I also thought there was an issue about assigning to a comptime field (like a tuple's field is) in stage2, although I can't find currently find that either. IIRC it was in a bug report with code using a loop over `@typeInfo` data.
The stage1 behaviour in this case was to assert the assigned value was equal to the comptime field's value, although iirc there's been discussion to change this. The only issue I can find right now is proposal #5675 .

**Comment by Vexu** [comment]
The bug is that stage2 doesn't do any type coercion for zero bit generic args:
```zig
fn bar(a: anytype, _: @TypeOf(a)) void {}
test {
    bar(@as(u0, 0), "fooo");
}
```
