### ISSUE TITLE
untangle `std.fs.path.resolve` from the current working directory

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#13613]
`std.fs.path.resolve` is trying to do too much at once, and it results in a leaky abstraction. It can be a nice substitute for `realpath` when trying to avoid this syscall, however, it suffers from not taking symlinks into account, as well as asking the OS for the cwd unnecessarily.

I propose to change it to be purely a string manipulation function and lose the ability to call cwd().

Any callsites that break from this change should be audited for potential pre-existing bugs.

**Comment by kubkon** [comment]
Not putting an enormous amount of thought into that, I agree. Unless I am misunderstanding the proposal, it would also make for a safer API since without asking the OS for CWD, there is nothing to escape from with `../../` or similar. I also take it, the new function would also *not* resolve symlinks as it requires inquiring the OS, correct?

**Comment by andrewrk** [comment]
The status quo function also does not resolve symlinks. The only syscall status quo does is getcwd(). This proposal would reduce it from that one syscall to none.

**Comment by kubkon** [comment]
> The status quo function also does not resolve symlinks. The only syscall status quo does is getcwd(). This proposal would reduce it from that one syscall to none.

So I understood correctly, and I am in favour FWIW.

**Comment by matu3ba** [comment]
Could be extra mentioned:
- 1.  `resolvePosix called on windows can't use getCwd` is resolved for WSL.
- 2. wasi paths work
