### ISSUE TITLE
"unable to resolve comptime value"  error when trying to get a pointer to a global defined on another file

### ISSUE THREAD

**Issue by dmbfm** [ziglang/zig#13634]
### Zig Version

0.11.0-dev.251+7c527c6df

### Steps to Reproduce and Observed Behavior

main.zig:

```zig
const std = @import("std");
const s = @import("global.zig").s;
const S = @import("global.zig").S;

pub fn inc(ss: *S) void {
    ss.*.x += 1;
}

pub fn main() !void {
    inc(&s);
    std.log.info("s.x = {}", .{s.x});
}
```

global.zig:
```zig
pub const S = struct {
    x: i32,
};

pub var s = S{ .x = 10 };
```

When compiling this program, I get the following error message:
```
/Users/daniel/Dump/zbug/src/main.zig:2:32: error: unable to resolve comptime value
const s = @import("global.zig").s;
          ~~~~~~~~~~~~~~~~~~~~~^~
/Users/daniel/Dump/zbug/src/main.zig:2:32: note: global variable initializer must be comptime-known
referenced by:
    main: /Users/daniel/Dump/zbug/src/main.zig:10:10
    comptime_0: /Users/daniel/Sources/zig-macos-aarch64-0.11.0-dev.251+7c527c6df/lib/std/start.zig:59:50
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

```

If I change the contents of main.zig to this instead:
```zig
const std = @import("std");
const g = @import("global.zig");

pub fn inc(ss: *g.S) void {
    ss.*.x += 1;
}

pub fn main() !void {
    inc(&g.s);
    std.log.info("s.x = {}", .{g.s.x});
}
```

Then the program compiles and runs correctly.

### Expected Behavior

The program should compile and run.

**Comment by InKryption** [comment]
I expect that this is intended behavior. Zig doesn't have semantic references, all that happens when you do `const s = @import("global.zig").s;` is that you try to copy the value held by `s` into another variable, which as a `var` isn't known at comptime, and thus can't be used to initialize another variable at container scope. The only way to "import a reference" to a global variable would be to take a pointer to it, e.g. `const s = &@import("global.zig").s;` (note: doesn't work with `threadlocal` variables, as their addresses also aren't known at `comptime`).

**Comment by dmbfm** [comment]
Got it. It is a little subtle but it makes sense now that I think about it. Closing this for now.

Thanks!
