### ISSUE TITLE
spurious std lib test failure on Windows: Thread.Condition signal wakes one

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#13660]
When running the standard library tests on the Windows CI for an unrelated task, [it failed](https://github.com/ziglang/zig/actions/runs/3555311638/jobs/5971931353) with:
```
2022-11-26T21:40:19.5412274Z 469/1557 test.Condition - signal wakes one... expected 2, found 1
```

cc @ianic
cc @kprotty

**Comment by kprotty** [comment]
That test seems inherently flaky as it 1) relies somewhat on a 10ms timeout to accurately fire and 2) relies on signal() to only wake one thread. It may surface on Windows easier due to Condition wait timeouts being implemented by spuriously waking up everyone else internally.

**Comment by ianic** [comment]
Yes, the test is fragile on both timeout and spurious waking on architectures that don't use FutexIml.

I used that test, with a high number of [runs](https://github.com/ziglang/zig/blob/d5e41bf15b3f6c7d66beee1ddf7b825b204c23d9/lib/std/Thread/Condition.zig#L619), while tweaking FutexIml. I was thinking about whether to commit it or not and seemed to me that it had some value.
FutexIml counts number of signals and should always wake up only one. But still depends on timeout and I can imagine that it fails because of that in some environments.

I suggest that we delete that test altogether. It is FutexImpl only and still timeout dependent.
