### ISSUE TITLE
wasm: integer constant gets wrong value for build-lib

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#13709]
### Zig Version

0.11.0-dev.368+1829b6eab

### Steps to Reproduce and Observed Behavior

```zig
// Note: const/var makes no difference here.
export const A: u32 = 42;
```

```sh
$ zig build-lib -dynamic -target wasm32-freestanding test.zig 
$ wasm2wat test.wasm
(module
  (memory (;0;) 17)
  (global $__stack_pointer (mut i32) (i32.const 1048576))
  (global (;1;) i32 (i32.const 1048576))
  (export "memory" (memory 0))
  (export "A" (global 1))
  (data $.rodata (i32.const 1048576) "*\00\00\00"))
```

Specifically: notice that `export "A"` points to `global 1` which itself is a constant "1048576". In the rodata section I can see that "1048576" seems to be the offset for data that does indeed have "42" (`*`) in it, but what JS sees is just the constant "1048576" since that is the value of the global...

I'm not super familiar with wasm so I'm not sure if this is supposed to work but regardless of it is or isn't this behavior seems busted.

### Expected Behavior

A global is exported with value "42".

**Comment by Luukdegram** [comment]
This is intended behavior. It's a common mistake to think that what is called a global in Wasm is the same thing as in other languages. Any export is done using the same ABI as C, the type system of languages such as C, Rust, and Zig is much more versatile than what Wasm has. Due to this, we cannot represent any of those types using a Wasm global. For instance, granted you have the following code, how would that possibly be represented using a single Wasm global?

```zig
const X = extern struct{
    x: u32,
    y: f64,
    z: u128,
};

export const foo: X = .{.x = 0, .y = 0, .z = 0};
```

Here, `foo` is 224 bits large. The largest a Wasm global can represent is 64 bits. You'd need multiple of those globals to represent `foo`. But you can only call a single global the name `foo`, so how would you know which other globals to use without looking into the binary? For this reason, *all* languages such as C, Rust, and Zig put the declaration's value into the linear memory segment and have the global represent a pointer into that memory segment. This is actually the same on other architectures than Wasm also, which is what most languages model the implementation after.

Perhaps future Wasm proposals will allow us to improve this situation, but for now, this is it. I promise you it's not busted behavior once you understand the reasoning behind this design. :)
