### ISSUE TITLE
error: parameter of opaque type 'cimport.struct_JSContext' not allowed

### ISSUE THREAD

**Issue by yisar** [ziglang/zig#13752]
To be honest, I don't know what to do, When I try to bind to quickjs, I receive this error. It seems that it is the contradiction of zig itself. Is there any way to make it work successfully without modifying the c file？

quickjs.c
https://github.com/bellard/quickjs/blob/master/quickjs.h#L50

to zig

```zig
pub fn set_int(context:qjs.JSContext ) qjs.JSValue{
    const str = "console.log(123)";

    var jsval: qjs.JSValue = qjs.JS_Eval(context, str, str.len, "", 0);
    return jsval;
}
```

The github repo is here: https://github.com/yisar/fre-embed

**Comment by rohlem** [comment]
At Line 50 of the header file you linked, the struct `JSContext` is only declared, not defined.
Therefore we don't know its size, and it cannot be passed by value, which leads to the given error message.

However, all the functions declared in the file take a **pointer** to `JSContext` as a parameter, not an object.
For your code to do the same, change the function signature from
```zig
pub fn set_int(context:  qjs.JSContext) qjs.JSValue
```
to
```zig
pub fn set_int(context: *qjs.JSContext) qjs.JSValue
```

---

Unrelated, but `str` is of type `*const [16:0]u8` here: a pointer to a constant array of 16 bytes (u8) with 0 as a terminator.
Values of this type don't have a `.len` field.

To make your code work, you can explicitly coerce it to a slice-of-const by specifying the type:
```zig
const str: []const u8 = "console.log(123)";
```
You'll also need to pass `str.ptr` instead of `str` as the second argument to match qjs.JS_Eval's argument type.
```zig
var jsval = qjs.JS_Eval(context, str.ptr, str.len, "", 0);
```

**Comment by yisar** [comment]
@rohlem 
You are right, but I have encountered a new problem, which is still a type error. I beg you to run this project and help me put forward suggestions for modification. Thank you!!!
https://github.com/yisar/fre-embed

**Comment by yisar** [comment]
They look the same, but the error still exists. I'm confused.

error: expected type '*const fn(?*cimport.struct_JSContext, cimport.struct_JSValue, c_int, [*c]cimport.struct_JSValue) callconv(.C) cimport.struct_JSValue', found '*const fn(*cimport.struct_JSContext, cimport.struct_JSValue, c_int, [*c]cimport.struct_JSValue) callconv(.C) cimport.struct_JSValue'

**Comment by rohlem** [comment]
In that new error message, the type of the first parameter is different:
`?*cimport.struct_JSContext` is an optional pointer - so a pointer that may be null,
`*cimport.struct_JSContext` is a non-optional pointer.
It seems like the commit you pushed just now might have fixed the issue?
Generally, the GitHub issues here are meant for bugs and language discussion, not for back-and-forth debugging. See https://github.com/ziglang/zig/wiki/Community for a list of alternative communities with more immediate feedback.

**Comment by yisar** [comment]
You know, Zig's community is not prosperous. When I search for similar questions, I often can't find them.

Unfortunately, I have solved this problem now, but there are still new problems. I will close this issue and reopen a new one.
