### ISSUE TITLE
CBE: Extern struct definitions aren't present if fields aren't used

### ISSUE THREAD

**Issue by kcbanner** [ziglang/zig#13835]
### Zig Version

225ed65ed2cc88fce54660250feaeb44e45943fa

### Steps to Reproduce and Observed Behavior

As part of https://github.com/ziglang/zig/issues/13574 I'm working on MSVC compat in the CBE, and I noticed this quirk: Full extern struct definitions aren't present if the fields aren't referenced. This happens in the test case for https://github.com/ziglang/zig/issues/529

```
..\build-stage3-debug\bin\zig.exe test ..\test\behavior.zig -I..\test -ofmt=c -femit-bin=test_529.c --test-filter "issue 529"
cl -I../lib test_529.c
```

The generated code has:
```
typedef struct zig_S_behavior_bugs_529_other_file_A__7325 zig_S_behavior_bugs_529_other_file_A__7325;
typedef struct zig_S_behavior_bugs_529_A__7326 zig_S_behavior_bugs_529_A__7326;
```

This causes this warning under MSVC:
```
test_529.c(3595): warning C4133: 'function': incompatible types - from 'zig_S_behavior_bugs_529_other_file_A__7325 *' to 'zig_S_behavior_bugs_529_other_file_2_A__7320 *const '
test_529.c(3598): warning C4133: 'function': incompatible types - from 'zig_S_behavior_bugs_529_A__7326 *' to 'zig_S_behavior_bugs_529_other_file_2_A__7320 *const '
```

However, if you add this to the test case:
```
    var a = A{
        .field = 3
    };
    _ = a;
```

The generated code now contains:
```
typedef struct zig_S_behavior_bugs_529_other_file_A__7326 zig_S_behavior_bugs_529_other_file_A__7326;
typedef struct zig_S_behavior_bugs_529_A__7321 zig_S_behavior_bugs_529_A__7321;
struct zig_S_behavior_bugs_529_A__7321 {
 zig_c_int field;
};
```

However, this doesn't actually solve the MVSC warning as the structs are still incompatible (as they are in the same source file).

### Expected Behavior

The generated code should have struct definitions for extern structs with all fields present.

**Comment by jacobly0** [comment]
Hi, could you elaborate on this a bit so that I can make sure that a future PR gets this correct.  I understand that there are some cases in the C backend where types do not match correctly, and that should be fixed by using proper types and/or casts.  However, I fail to see why it is necessary in this case to have a complete definition of the struct (for MSVC or otherwise).  Note that `struct S; struct S *s;` is perfectly valid in C.

**Comment by kcbanner** [comment]
I think I thought it was odd that the definition was missing when it did have one in zig, since it was an extern struct. However, since nothing reads that field or needs its address, maybe this is the intended behavior?

**Comment by jacobly0** [comment]
Yes, this is the expected behavior.  It is similar to how unreferenced decls aren't even analyzed in zig, let alone show up in the output.  However, the reason we do this specifically in the C backend is because we need to output forward and complete struct definitions in a very specific order to make the C compiler happy, so when one is not needed we don't bother trying to keep track of that and output them unnecessarily.

**Comment by kcbanner** [comment]
Makes sense, thanks for the clarification!
