### ISSUE TITLE
@boolToInt doesn't return 0 or 1 for struct field reads inside array

### ISSUE THREAD

**Issue by svmhdvn** [ziglang/zig#13940]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

Observed behaviour:
@boolToInt(...) returns a value >=2 in certain cases of struct field reads when the structs are inside arrays. See the following test output:

```sh
$ zig test test.zig
Test [3/4] test.@boolToInt array struct... FAIL (TestUnexpectedResult)
[...]
./test.zig:33:5: 0x211d12 in test.@boolToInt array struct (test)
    try std.testing.expect(total <= 13);
    ^
Test [4/4] test.@boolToInt array packed... FAIL (TestUnexpectedResult)
[...]
./test.zig:42:5: 0x211f59 in test.@boolToInt array packed (test)
    try std.testing.expect(total <= 13);
    ^
2 passed; 0 skipped; 2 failed.
```

Minimal repro:

```zig
const std = @import("std");

const Repro = struct {
    a: u4,
    b: bool,
};

const PackedRepro = packed struct {
    a: u4,
    b: bool,
};

test "@boolToInt single struct" {
    var f_repro = Repro{ .a = 10, .b = false };
    var t_repro = Repro{ .a = 10, .b = true };
    try std.testing.expectEqual(@as(usize, 0), @boolToInt(f_repro.b));
    try std.testing.expectEqual(@as(usize, 1), @boolToInt(t_repro.b));
}

test "@boolToInt single packed" {
    var fp_repro = PackedRepro{ .a = 10, .b = false };
    var tp_repro = PackedRepro{ .a = 10, .b = true };
    try std.testing.expectEqual(@as(usize, 0), @boolToInt(fp_repro.b));
    try std.testing.expectEqual(@as(usize, 1), @boolToInt(tp_repro.b));
}

test "@boolToInt array struct" {
    var buf1: [13]Repro = undefined;
    var total: usize = 0;
    for (buf1) |s| {
        total += @boolToInt(s.b);
    }
    try std.testing.expect(total <= 13);
}

test "@boolToInt array packed" {
    var buf2: [13]PackedRepro = undefined;
    var total: usize = 0;
    for (buf2) |s| {
        total += @boolToInt(s.b);
    }
    try std.testing.expect(total <= 13);
}
```

### Expected Behavior

I expect all the above tests to pass. From zig's documentation in 0.10.0 https://ziglang.org/documentation/0.10.0/#boolToInt:

> Converts true to `@as(u1, 1)` and false to `@as(u1, 0)`

I would expect that in all cases, the only possible return values are 0 and 1. However in the above tests, you can see that somehow, `total` is greater than the expected value.

Please correct me if I'm wrong about my assumptions, but intuitively this is strange behaviour.

**Comment by pfgithub** [comment]
`repro` is initialized to undefined, and undefined values are infectious. almost anything you do with them causes that output to become undefined.

- `repro` is undefined
- that means that `repro.b` is undefined
- so `@boolToInt(s.b)` is undefined
- that value is added to `total`, so now `total` is undefined

In debug builds, undefined values are initialized to `0xAAAA` and that's why boolToInt(s.b) is returning `0xAA` instead of an expected u1 value. Printing it works fine because the printer only prints one bit from the "u1", but adding to total the u1 is used as a u8

I think this is expected behaviour - it can be fixed by initializing `repro`

```zig
    var buf1: [13]Repro = undefined;
    for(buf1) |*repro| repro.* = .{.a = 24, .b = true};
```

**Comment by svmhdvn** [comment]
Agreed, but at the very least then, 

> Converts true to @as(u1, 1) and false to @as(u1, 0)

should be reworded in the docs to reflect this right? When I rerun the test as the following:

```zig
var total: usize = 0;
    for (buf2) |s| {
        if (s.b) total += 1;
    }
    try std.testing.expect(total <= 13);
```

then it works just fine. So shouldn't `@boolToInt` simply read the single bit from whatever register holds that data, regardless of its size or what the register is initialized to? Based on the wording of the docs, I would at least expect the value to be either 0 or 1 definitively.

**Comment by pfgithub** [comment]
```zig
var total: usize = 0;
for (buf2) |s| {
    if (s.b) total += 1;
}
try std.testing.expect(total <= 13);
```

This is branching on undefined, which is undefined behaviour. The if statement is allowed to do anything it wants here according to the language spec, meaning the compiler is allowed to optimize this to `total += s.b` if it feels like it and that would cause the same behaviour. I don't think it makes sense to reword the docs to say that boolToInt can return any u8 value because in cases with undefined it does that sometimes.

**Comment by nektro** [comment]
if that was the case, the docs would have to mention in every single section that `undefined` mangles the data. they're written (other than the sections describing the illegal behavior itself) with the assumption that you're not using illegal or undefined behavior. `std.mem.zeroes([13]Repro)` is the proper initialization btw if you're not doing an otherwise proper initialization loop yourself

**Comment by svmhdvn** [comment]
Thanks for the explanation, all of this cleared it up! Closing as "not a bug".
