### ISSUE TITLE
a zig build mode intended to be used when packaging an application or library for a system distribution

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14281]
This proposal is accepted; please see these comments for the criteria for closing the issue:
 * https://github.com/ziglang/zig/issues/14281#issuecomment-1624220653
 * https://github.com/ziglang/zig/issues/14281#issuecomment-1644900436

-----

Extracted from #14265.

The use case is as follows:

Someone wants to take an upstream application, and package it for a Linux distribution, or another kind of distribution such as Homebrew or Nix.

The application knows exactly what versions of each dependency it wants to build against, but distributions only provide a limited set of versions. Furthermore, the system distribution wants to be in charge of providing all dependencies, building the application from source without access to any files outside of those provided by the system itself, via its own dependency management system.

For this use case, instead of fetching dependencies from the URLs provided by zig build.zig.zon files, instead there should be some kind of override that makes the dependencies fetched from the system package manager.

Related: [Stay Together For The Kids: Why System Package Managers and Language Package Managers Struggle to Cooperate](https://www.youtube.com/watch?v=stChOsejLEQ)

**Comment by daurnimator** [comment]
> For this use case, instead of fetching dependencies from the URLs provided by zig build.zig.toml files, instead there should be some kind of override that makes the dependencies fetched from the system package manager. Perhaps Zig can provide tooling that makes an application support being built in both contexts.

As long as zig can be pointed at a local directory for each dependency instead of ever fetching itself, then the external packaging systems (and/or the tooling around it) can be made to work.

**Comment by andrewrk** [comment]
I suspect that, in this mode, it will be necessary for zig to shell out to the system C/C++ compiler toolchain instead of relying on its own embedded clang library code. This is a very large can of worms, but, if we accept the foundational premise that zig build is intended to be truly used as a competitor to other build systems, this point is non-negotiable.

**Comment by motiejus** [comment]
On IRC I asked whether we should store decompressed archives in the global cache, so we can use more efficient means to decompress the file (I mentioned `copy_file_range`).

Turns out more efficient ways to decompress the file are not that more efficient. GNU tar wins (unsurprisingly, it is well optimized), followed by Andrew's stdlib implementation which uses pread/pwrite. sendfile and copy_file_range are a bit slower, definitely not worth the added complexity.

```
$ hyperfine --export-markdown table.md -r 5 -w 1 -p 'rm -fr ffmpeg' 'tar -xf ffmpeg.tar' 'tar -xf ffmpeg.tar.gz' './std-tar ffmpeg.tar' './std-tar ffmpeg.tar.gz' './maybe-faster sendfile ffmpeg.tar' './maybe-faster copy_file_range ffmpeg.tar'
Benchmark 1: tar -xf ffmpeg.tar
  Time (mean ± σ):     840.9 ms ±  34.8 ms    [User: 14.4 ms, System: 813.4 ms]
  Range (min … max):   800.5 ms … 890.5 ms    5 runs
 
Benchmark 2: tar -xf ffmpeg.tar.gz
  Time (mean ± σ):     900.8 ms ±  17.9 ms    [User: 294.7 ms, System: 858.3 ms]
  Range (min … max):   882.3 ms … 921.4 ms    5 runs
 
Benchmark 3: ./std-tar ffmpeg.tar
  Time (mean ± σ):     863.5 ms ±  19.1 ms    [User: 5.7 ms, System: 844.4 ms]
  Range (min … max):   838.1 ms … 886.8 ms    5 runs
 
Benchmark 4: ./std-tar ffmpeg.tar.gz
  Time (mean ± σ):      1.391 s ±  0.122 s    [User: 0.404 s, System: 0.974 s]
  Range (min … max):    1.179 s …  1.486 s    5 runs
 
Benchmark 5: ./maybe-faster sendfile ffmpeg.tar
  Time (mean ± σ):      1.089 s ±  0.049 s    [User: 0.005 s, System: 1.072 s]
  Range (min … max):    1.048 s …  1.143 s    5 runs
 
Benchmark 6: ./maybe-faster copy_file_range ffmpeg.tar
  Time (mean ± σ):      1.162 s ±  0.044 s    [User: 0.006 s, System: 1.092 s]
  Range (min … max):    1.121 s …  1.235 s    5 runs
 
Summary
  'tar -xf ffmpeg.tar' ran
    1.03 ± 0.05 times faster than './std-tar ffmpeg.tar'
    1.07 ± 0.05 times faster than 'tar -xf ffmpeg.tar.gz'
    1.29 ± 0.08 times faster than './maybe-faster sendfile ffmpeg.tar'
    1.38 ± 0.08 times faster than './maybe-faster copy_file_range ffmpeg.tar'
    1.65 ± 0.16 times faster than './std-tar ffmpeg.tar.gz'
```


| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `tar -xf ffmpeg.tar` | 840.9 ± 34.8 | 800.5 | 890.5 | 1.00 |
| `tar -xf ffmpeg.tar.gz` | 900.8 ± 17.9 | 882.3 | 921.4 | 1.07 ± 0.05 |
| `./std-tar ffmpeg.tar` | 863.5 ± 19.1 | 838.1 | 886.8 | 1.03 ± 0.05 |
| `./std-tar ffmpeg.tar.gz` | 1390.6 ± 122.5 | 1178.6 | 1486.2 | 1.65 ± 0.16 |
| `./maybe-faster sendfile ffmpeg.tar` | 1088.6 ± 48.7 | 1047.6 | 1142.7 | 1.29 ± 0.08 |
| `./maybe-faster copy_file_range ffmpeg.tar` | 1161.7 ± 43.8 | 1121.2 | 1235.0 | 1.38 ± 0.08 |


Files:
[std-tar.txt](https://github.com/ziglang/zig/files/10431286/std-tar.txt)
[maybe-faster.txt](https://github.com/ziglang/zig/files/10431287/maybe-faster.txt)

Built with:

```
for f in maybe-faster.zig std-tar.zig; do zig build-exe -lc -OReleaseFast $f; done
```

**Comment by nektro** [comment]
i think something akin to `CMAKE_PREFIX_PATH` could help a lot here. in a system package manager environment, it could be populated by them, and if its empty zig could fill the value itself

**Comment by andrewrk** [comment]
The equivalent parameter in zig build is --search-prefix

**Comment by nektro** [comment]
yes but i mean a variable different but similar for finding zig packages instead of cmake packages

**Comment by andrewrk** [comment]
Note what's happening over at https://github.com/NixOS/nixpkgs/pull/241741.

They are creating common logic for packaging Zig applications on NixOS and have this line:

```
zig build -Drelease-safe -Dcpu=baseline $zigBuildFlags
```

This is a bit of a problem because `-Drelease-safe`, while commonly exposed,

 * Is not always exposed because the build script might build multiple things and a single choice like this might not make sense
 * The upstream author might expose only `-Drelease` because they want to choose the safety/size tradeoff.

Furthermore, `-Dcpu` is also not necessarily exposed, for similar reasons. There might be different things being built, with different CPUs. Anything could happen.

What we need is a way for nix and other systems to be able to specify their *true intent*, which is this:

 * Make a release build, not a debug build.
 * Any binary artifacts that otherwise would be compiled for the native host, compile them for this target/cpu instead.

We should make both of these things easy to specify, regardless of what is in the upstream application's build.zig script.

Here is my concrete proposal:

 * Add a `--release` flag to `zig build`. So they can change `-Drelease-safe` to `--release`. In build.zig, upstream authors can observe this boolean, and pick a release mode, or, if they don't pick, an error will be emitted, something like, "upstream package supports fast, safe, and small. Please choose: --prefer-fast, --prefer-safe, or --prefer-small." Those options are also options that `zig build` will unconditionally support. So, probably Nix will have this: `zig build --release --prefer-safe`.
 * Add `--override-host-target <target>` and `--override-host-cpu <cpu>` flags to `zig build`. These are always supported, and do what they say on the tin: any time the host target or cpu would be used, the provided one is used instead.

Finally, we need to also tackle one more problem, which is that zig packages need to know when they are being built in a mode that means they should try to depend on system libraries rather than fetching dependencies via the zig build system. For this I think we will need one or more flags, but I haven't quite thought through all the ramifications and how exactly this will be integrated into systems like Debian or Nix, but that concern should not block the implementation of these other flags, which would help Nix right now.

**Comment by andrewrk** [comment]
Accepting the proposal now. When closing the issue, there should be 2 follow-up issues opened:

* ability to provide package dependencies by system package manager rather than downloaded by the zig build system
* ability to build C/C++ source files by the system toolchain rather than by zig's C compiler.

**Comment by andrewrk** [comment]
In addition to those two flags specified in https://github.com/ziglang/zig/issues/14281#issuecomment-1624220653, this proposal also introduces a `--system <zig-package-dir>` flag that does the following:
* makes `zig build` entirely skip fetching dependency packages to the global zig cache.
* the build runner exposes system mode to build scripts
* build scripts observe system mode and, where appropriate, avoid calling `dependency()`, instead linking directly to system libraries.
  * note that this provides an opportunity for build scripts to re-use logic for doing this for individual components via standard build options, e.g. `-Duse-system-ffmpeg`.
    * example: https://github.com/MasonRemaley/2Pew/blob/a912fcf64b04ffdcb0935f31b87fe3ae2be4ff09/build.zig#L34 - here we simply add a `b.isSystemMode() or ...` clause.
* for dependencies on zig modules, `dependency()` is called like normal, and those packages are found in `<zig-package-dir>`. Note that only these dependencies, and not the previous bullet point, need to be populated inside `<zig-package-dir>`. It is the responsibility of the system package manager to ensure this directory is populated with the necessary packages before invoking `zig build` in system mode.

As for reconciliation of dependency versions, it will be the responsibility of build scripts to probe the system and decide if it is acceptable to proceed. Zig build system API will be provided for common tasks to aid this endeavor, such as checking the major version of a shared library.

As for ability to build C/C++ source files by the system toolchain rather than by zig's toolchain, the decision to do this can be done automatically when in system mode, and the logic for being a system toolchain driver can go directly into the zig build system.

**Comment by ifreund** [comment]
Overall the proposed `--system` flag and proposed behavior sounds like a straightforward and effective way of solving this that is relatively easy to use and understand for zig developers and distro packagers alike.

>     * build scripts observe system mode and, where appropriate, avoid calling `dependency()`, instead linking directly to system libraries.

My only concern with this proposal is that the default and path of least resistance here for zig projects seems to be calling dependency and doing nothing further to handle the possibility of that dependency being provided by the system. I see this resulting in distro maintainers needing to patch the build.zig files of many projects to fix this.

Perhaps it would be possible to handle the simple case of this automatically by adding more declarative metadata to zig packages providing system libraries (e.g. the ffmpeg zig package could declare that it is equivalent to linkSystemLibrary("ffmpeg") in some way). I'm not clear on the details here though and such an approach may not be worth the complexity.

> As for reconciliation of dependency versions, it will be the responsibility of build scripts to probe the system and decide if it is acceptable to proceed. Zig build system API will be provided for common tasks to aid this endeavor, such as checking the major version of a shared library.

A build.zig API for requiring a specific shared library soversion would be very much appreciated.

> As for ability to build C/C++ source files by the system toolchain rather than by zig's toolchain, the decision to do this can be done automatically when in system mode, and the logic for being a system toolchain driver can go directly into the zig build system.

I assume this also covers linking the system libc version instead of the zig provided one?

**Comment by BratishkaErik** [comment]
> build scripts observe system mode and, where appropriate, avoid calling dependency(), instead linking directly to system libraries.

Perhaps related https://github.com/ziglang/zig/issues/3671 . There can be additional field like `zig_artifact` which will point to artifact of some dependency, and this field can be used with other fields from that proposal, like this:

```zig
const mach_glfw_dep = b.dependency("mach_glfw", .{});

exe.linkSomeLibrary(.{
    .system_artifact = .{
        .so_name = "glfw",
        .pkgconf_name = "glfw3",
        .vcpkg_name = "glfw3",
    },
    .zig_artifact = mach_glfw_dep.artifact("glfw"),
});
```

Then it uses either system_artifact or zig_artifact, depending on current mode.

**Comment by mitchellh** [comment]
The ability for a library link to specify a dynamic counterpart (if any) to source from the system would be very welcome indeed. 

As a bullet point, the way Ghostty does this today is with a flag `-Dstatic=false` (default true). This defaults to true so that for a new dev cloning out the project, all they need to build Ghostty is `zig` and `git`. But that's not a healthy way to build a release so we provide `-Dstatic=false` which will link most dependencies dynamically. 

This is done very manually with a giant `if` in `build.zig`. I'd be super happy with the proposals above to standardize this on the library itself as well as stanardize modes and CPU targets and so on.

Looking forward to it.
