### ISSUE TITLE
add support for v1 and v2 SSL certificates

### ISSUE THREAD

**Issue by BanchouBoo** [ziglang/zig#14304]
### Zig Version

0.11.0-dev.1300+7cb2f9222

### Steps to Reproduce and Observed Output

In any project, running anything that includes `zig build`.

### Expected Output

Any amount of information about what's happening. What certificate is causing the issue? Is it something I can fix? If not, is there a way I can ignore this error and build my projects anyway? As it stands, all I'm getting is the error and nothing else and I can't build anything with `zig build` so I can't work on anything.

**Comment by andrewrk** [comment]
As a hint for whoever wants to work on this in the future (perhaps myself in a week or so), the problem is this line:

 https://github.com/ziglang/zig/blob/d813cef42af43b499fc5dc465e34f873008aaad0/lib/std/crypto/Certificate.zig#L303

I didn't really understand how the DER format worked with respect to this field, so I supported only V3. But I understand the DER format better now. After refreshing my memory I could fix it or explain it to a contributor.
