### ISSUE TITLE
support fetching dependencies bundled with `.tar.xz` extension

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14300]
Extracted from #14265.
Depends on #2851.

`zig build` should support fetching via an URL like this:

```zig
    .url = "https://example.com/foo.tar.xz",
```

https://github.com/ziglang/zig/blob/7cb2f9222da38d687e8708dd5d94d3175cc77995/src/Package.zig#L357-L376

Related:
 * #14299

**Comment by nikicoon** [comment]
with package manager hat on (pkgsrc), I have a question: will you consider people pre-fetching URLs out-of-band with an override for this and similar settings, since most system package managers do not have online enabled environments (for reproducibility and other reasons)? (in pkgsrc we wrap build-systems and repeated steps)

**Comment by nektro** [comment]
yes thats handled in https://github.com/ziglang/zig/issues/14281

**Comment by andrewrk** [comment]
> pre-fetching URLs out-of-band

The system is designed to avoid network access when unnecessary. Combined with #14283, it would be trivial to ensure no network access by providing the directory pre-populated with the necessary dependencies.

And yes the mode hinted at in #14281 would likely make attempted network access by the build system into a compilation error.
