### ISSUE TITLE
Proposal: Make `x[a..b]` yield array instead of slice / array pointer

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#14359]
Sorry for making a proposal.
This has bugged me for over 2 years, but I only spotted the underlying irregularity *just now*.

In short, slicing `x[a..b]` auto-references (yields a slice, which is a pointer),
while accessing an element `x[i]` doesn't.
I think we should unify this so that slicing also yields (array) values:
- `x[a..b]` only gives you an array, and becomes an error if `(b-a)` is not comptime-known.
- To construct a slice, use `&x[a..b]` (which remains valid for runtime-known `(b-a)`).

---

I think this would make the language more regular, thereby less surprising.
As values aren't susceptible to aliasing and lifetime issues, imho they are the saner default.
This would make `&` the only builtin operator that constructs pointers.
(Which could make it easier to spot when looking for potential lifetime issues.)

---

Pro: Explicitness, increased regularity imo => peace of mind.
Con: *Slightly* more typing when dealing with slices (which is probably much more common than dealing with arrays).
Oh, and we'd probably need a `zig fmt` fixup, like back in the good old days.

**Comment by nektro** [comment]
returning a pointer-to-array for `x[a..b]` when `a` and `b` are comptime known makes `x[a..b]` always coercible to a slice

you can get the array by doing `x[a..b].*`

**Comment by mlugg** [comment]
This idea only works if the bounds are comptime-known, since arrays have a fixed size encoded in their type (that's not a Zig limitation, it's just necessary to give any memory layout for the types). If you were to implement the proposal like that (leaving runtime-known bounds to the current behaviour), slicing semantics would be totally different to the programmer depending on whether bounds are comptime-known or not (`foo[1..]` gives an array, `foo[runtime..]` gives a slice), which is incredibly confusing and just makes the consistency problem worse. It's clearly not reasonable to ban runtime slices, so I don't see a way this can work.

**Comment by mlugg** [comment]
(sorry if you saw my original comment here, I misread something)

I appreciate the goal, but to me these new semantics are more confusing because they special-case a particular shape of expression in the type checker. For other things you can take a reference to, we use the idea of an lvalue to justify it, like in C, which is a nice unified system without special cases. This proposal gives us a case where `&e` might be valid (semantic analysis-wise) while `e` is not, which I don't like. Moreover, suddenly `&` has a whole second job: in its current incarnation it strictly takes a single pointer to an lvalue (i.e. `&x: *@TypeOf(X)`), but this would make it also able to directly create a slice. To me, these changes are far more confusing than the current slicing semantics, which are less of an exception to a rule and more of just there not being a rule in the first place.

**Comment by rohlem** [comment]
<details> <summary>@mlugg Your assessment is correct.</summary>

(Small nitpick, I think all symbols in `&x[a..b]` would become an atomic expression - separate in AIR from the new non-ref-slicing `x[a..b]`.
 It wouldn't further be divided, so no *type-checking* in particular of the subexpression `x[a..b]`, only of operands `x`, `a`, `b`.)
</details>

To solve that new irregularity we would need a separate proposal:
Introduce a new builtin type equivalent to std.BoundedArray, tentative syntax `[<N]T` for capacity `N`.
They would be a generalization of arrays, with runtime length but comptime capacity:
- `[<usize_max]T` can be written as `[]T`. A pointer to this type, `*[]T`, is the slice type `[]T` of current Zig.
- `[<N]T` coerces to an array `[N]T` if its length is comptime-known to be equal to its capacity `N`.

However, I'm still brainstorming on this.
> 98% of use cases would still only use current slices = new syntax `*[]T`,
so I'm not sure if the expressive benefits are worth the additional complexity (hence no issue yet).

If we decide that a compile error when reaching this "type hole" is acceptable, this first issue would not technically depend on this new type class.

**Comment by mlugg** [comment]
To me, that suggestion feels pretty complex, which is something Zig strives to *not* be. Like you say, the *vast* majority of use cases don't require such a type, so adding it as an actual language feature is pointless (since any benefit it provides in and of itself is already encompassed by `std.BoundedArray`). For that reason I'm just not a fan of this proposal as a whole - I'm open to being proven wrong, but it feels like any attempt to make it work either leads to unnecessary language complexity (as with the `[<n]T` idea) or weird inconsistencies in type checking.

**Comment by kuon** [comment]
I think having explicit `BoundedArray` where you need them is enough. Also, for me, doing `foo[a..b]` is "slicing" which yields a slice. As @mlugg said, giving `&` the power to slice would be more confusing than helping. I do some embedded programming when I often convert pointer address to int and having `&` generate a slice would not be intuitive.

**Comment by ekipan** [comment]
An option (though not one I'm particularly fond of):

Separate the syntax of comptime-known subarray from runtime-known slice, say `arr[i..j]` gives an array with comptime-known i and j, an error otherwise, and introducing the syntax `arr&[n..m]` for a slice.
