### ISSUE TITLE
Crash when indexing @typeInfo(Struct).Struct.fields with runtime value

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#1435]
This test crashes the compiler (no error message so I think it's not an assert):
```
const Struct = struct{
  a: u32,
  b: u32,
  c: u32,
  d: u32,
};

// use function to force index to be a runtime value
fn getIndex() usize {
  return 2;
}

test "" {
  const index = getIndex();
  const field = @typeInfo(Struct).Struct.fields[index];
}
```

Currently I'm getting around this problem in my project (oxid) by doing an inline loop over the struct fields and waiting until `i == index`. It's causing duplicate code though (conditions checked in the loop body).

https://gitlab.com/dbandstra/oxid/blob/88236210911c0a3a9abf4e4fabb37b4f4f9b3704/src/gbe_system.zig#L97

**Comment by dbandstra** [comment]
Is it supposed to be possible to do this? (use comptime stuff at runtime)

**Comment by andrewrk** [comment]
> Is it supposed to be possible to do this? (use comptime stuff at runtime)

Sorry for not seeing your question earlier.

`StructField` is defined like this:

```zig
    pub const StructField = struct {
        name: []const u8,
        offset: ?usize,
        field_type: type,
    };
```

Because this has a field of type `type`, that makes the `StructField` type itself a "comptime type". This means that all values that are of type `StructField` must be comptime known. In your code example, I think what should happen is that indexing a `[]T` where `T` is a comptime type makes the index expression implicitly comptime. So your code example would give "error: unable to evaluate constant expression" pointing at `index` (and you could fix it with `comptime getIndex()`).
