### ISSUE TITLE
zig does not build with RELRO and PIE on NetBSD

### ISSUE THREAD

**Issue by nikicoon** [ziglang/zig#14420]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

While building zig for pkgsrc (lang/zig), I had to turn off the PIE and RELRO checks, as the resulting binary had neither of these on NetBSD. This is different compared to the last version which did build (0.9x? 0.10x?) on NetBSD with pkgsrc.

Do we have to pass additional options to the build process of zig to enable these?

Additionally: projects written in zig seem to not be able to build with RELRO either (but PIE works when enabled in the project)

### Expected Behavior

zig itself builds with RELRO and PIE, zig projects can be build with RELRO.

**Comment by mikdusan** [comment]
using the netbsd system toolchain, can you show how to produce a hello-world executable that is:
- not pie
- is pie

and how to check (hopefully using netbsd system tools)
- if exe is pie or not
- if exe passes or fails relro checks

I can pass `-fPIE` to create a zig prog `zig build-exe -fPIE z0.zig` and `file z0` shows it is pie, and yet using `gcc -o main -fPIE main.c` and `file main` does not show as pie . Maybe `file` is an outdated way to check.

**Comment by mikdusan** [comment]
- check for relro:
```sh
$ readelf -a main | grep GNU_RELRO
  GNU_RELRO      0x0000000000000e28 0x0000000000200e28 0x0000000000200e28
```

- check for pie:
```sh
# NOT PIE
$ readelf -a main | grep Type
Type:                              EXEC (Executable file)

# PIE
$ readelf -a main | grep Type
Type:                              DYN (Shared object file)
```

**Comment by nikicoon** [comment]
sorry for the long silence.
https://www.netbsd.org/docs/pkgsrc/hardening.html#hardening.audit.relropartial relro and partial relro checks:
```
$ objdump -p /path/to/bin/ary

/path/to/bin/ary:     file format elf64-x86-64

Program Header:
[...]
   RELRO off    0x0000000000000d78 vaddr 0x0000000000600d78 paddr 0x0000000000600d78 align 2**0
```

```
$ objdump -x /path/to/bin/ary

/path/to/bin/ary:     file format elf64-x86-64

Dynamic Section:
[...]
  BIND_NOW             0x0000000000000000
```

**Comment by mikdusan** [comment]
### default case
- with system toolchain, a simple executable is *not* PIE and *not* RELRO
- the default behaviour for zig is the same

I don't see a compelling reason to change zig's default.

### how to match netbsd's pkgsrc specs
- with system toolchain, `gcc -pie -o main1 main.c -Wl,-z,relro` does the trick
- with zig, `zig build-exe -fPIE ...` produces a PIE executable
- with zig, `zig build-exe -fPIE -z relro ...` is not effective because we have an workaround in place for an older issue which forces `-z norelro`

### blocker PART-1
https://github.com/ziglang/zig/blob/fd6200eda6d4fe19c34a59430a88a9ce38d6d7a4/src/link/Elf.zig#L1639-L1646

That's a fairly dated issue+solve, and it's possible `ld.lld` has improved but it bears more investigation. From the patch it looks like `-z relro` is problematic wrt #9109 . 

### blocker PART-2
Find a way to augment zig's build procedure to let a pkgsrc maintainer enable PIE + RELRO .
PIE looks to be already exposed, via `CMAKE_POSITION_INDEPENDENT_CODE`.

**Comment by mikdusan** [comment]
@nikicoon, could you try out PR #15511 in your pkgsrc and:

1. re-enable PIE check
2. re-enable RELRO check
3. add `-DZIG_PIE` to the cmake command

**Comment by nikicoon** [comment]
thanks! I did apply the patches on latest git (via pkgsrc-wip/zig-git package) and this makes the pie + relro tests pass (I presume this also means this satisfies the conditions for the zig binary being actually pie + relro built).

**Comment by nikicoon** [comment]
any chance this will make it into the next release?
