### ISSUE TITLE
Proposal: A way to add custom information to stack- and error traces

### ISSUE THREAD

**Issue by tecanec** [ziglang/zig#14446]
Currently, the stack traces printed when a safety check fails will only show the locations of the failure and of all calls in the current call stack. This is useful, but sometimes more information is needed to make it clear what went wrong.

For example, when iterating over a list of items, it may be useful to know which item caused the crash, and maybe even where that item was generated. And to give a real example, I'd like to see stack traces of where failing callbacks were set.

Of course, there's no way for Zig to handle every case like this, as many of them are too situational; There's no way for the compiler to know that the origin of this function pointer is somehow significant. I therefore propose adding some way to manually add such information to the stack trace.

I propose the following:
- Add a new builtin named something like `@addToTrace`.
- Modify `builtin.StackTrace` to hold messages in addition to the current instruction addresses.

`@addToTrace` will be used to add messages to the current stack trace. These messages are added once the builtin is called and are removed when leaving the current scope. For example:
```zig
{
    @addToTrace("a");
    {
        @addToTrace("b");
        {
            @addToTrace("c");
        }
        @addToTrace("d");
        assert(false);
        @addToTrace("e");
    }
}
```
In the above code, "a", "b", and "d" will be in the stack trace, but not "c" (because its scope has been left) or "e" (because it has not been added yet).

When error- and stack traces are disabled, `@addToTrace` is a no-op, and dead-code elimination will be able to remove the overhead of obtaining the message in simple cases. Otherwise, compile-time if statements can be used to manually removing said overhead, such as replacing unneeded struct fields with void. `@addToTrace` can therefore be used without ever affecting the performance of release builds that require no stack trace. And since `@addToTrace` is unlikely to be observable unless the stack trace gets shown, there is little reason not to place them wherever one expects them to be useful. Leaving behind some `@addToTrace` statements in advance may turn out to be a good habit, much like with assertions.

Further considerations:
- How should the messages be stored by `builtin.StackTrace` relative to the instruction addresses?
- Should the messages be stored as strings or as data to be formatted later when needed? If it is the latter, how should it work?
- How should these appear in the printed stack trace? Should they be left bare or come with a small label? Or should even the location of the `@addToTrace` be included?

**Comment by rohlem** [comment]
My first impression is that a builtin would be relatively heavy-handed.
I would appreciate a detailed comparison to what is already possible in userspace, since afaik we can already supply a custom function to be called at `@panic`.

- When would you use userspace-only additional information added to custom traces, and when would you use the builtin?
- Could maybe another layer of standard library logic / customization provide a simple enough integration that provides the same benefits?
   (say, `const id = std.debug.addToTrace("asdf");` + `defer std.debug.removeFromTrace(id);` - could be toggled by a `root` declaration that configures/enhances the standard stack trace printing provided for `@panic`)
   If this is not possible, why? / What is missing from current customization points?

**Comment by tecanec** [comment]
I admit, I hadn't thought of using a custom panic handler. I think it's a cool idea.

However, panics aren't the only things that use the stack trace. For example, the general-purpose memory allocator saves the stack traces of allocations and deallocations for debugging memory leaks and double frees.

Such cases would have to support the custom messages as well. So at the very least, this would need to be supported by stdlib to get the most out of it. I think the simplest solution to that would be to modify `builtin.StackTrace`.

Since custom stack trace messages would then be directly modifying something internal to Zig, I thought it'd be natural to use a builtin. I could be wrong, though.

It may also be possible to define a wrapper around `builtin.StackTrace` in the stdlib and make that the "proper" way of dealing with stack traces. This may be the most flexible option, as it doesn't involve changing the compiler. It would also allow for a prettier interface.

**Comment by rohlem** [comment]
Something I just realized:
If this is a builtin, compile errors executing code in `comptime` would be able to put this into their traces as well.
(In fact, I can't really imagine a library-only solution that shows up in compile error traces - you would have to artificially introduce stack frames, by wrapping part of your function, that can then show up.)

But then again, I would _really_ prefer if all traces included comptime arguments in addition to the function names.
While that's not as flexible and powerful as this proposal, it would probably already cover my personal current needs for tracing comptime code.
(Though it would surely need to be configurable, because many use cases would not want the size bloat resulting from that.)
