### ISSUE TITLE
std.http.Client ignores uri.query

### ISSUE THREAD

**Issue by billzez** [ziglang/zig#14512]
### Zig Version

0.11.0-dev.1507

### Steps to Reproduce and Observed Behavior

`uri.query` is not part of the http header.

### Expected Behavior

`uri.query` is part of the http header.

**Comment by billzez** [comment]
This kinda feels like a foot-gun.  `path` usually includes the query string.  It might make sense to make this more inline with the WHATWG spec:

https://nodejs.org/api/url.html#url-strings-and-url-objects

I propose that `std.Uri`:
* the `path` field includes the query string (but not the fragment/hash)
* adds `pathname()` and `query()` methods.

@MasterQ32

**Comment by MasterQ32** [comment]
I strongly disagree, as `path` and `query` fields are semantically so different that's a footgun to merge them. Especially as `std.Uri` supports a lot of different styles of uri. Would you expect to be `doi:1234?foobar` the path to be `1234?foobar` instead of `1234`?

Imho we should not replicate nodejs, but stick closely to the RFC terms that have well defined `path` and `query` properties. Using `std.Uri` for HTTP is only one use case of many

**Comment by billzez** [comment]
Understood, looks like Go and Rust follow the RFC (and not WHATWG) as well.

Looking at Go's net/url, it also has `requestURI()` that combines path+query.

**Comment by 20kano** [comment]
Why is the `request()` function argument a URI and not a URL?
Because the URL is just not implemented?

**Comment by seiflotfy** [comment]
Is this regarding the `http/Client.zig` `Request.Headers` struct ?

**Comment by truemedian** [comment]
This was fixed in #14762.
