### ISSUE TITLE
Autodoc: regression, impossible to select "Internal Doc Mode"

### ISSUE THREAD

**Issue by KaneRoot** [ziglang/zig#14563]
I encountered a bug: the button "Internal Doc Mode" ignores clicks. The button is never selected, impossible to read the documentation. Also, the doc seems incomplete: I can't find my code even within the search mode.

I worked with an old version of Zig `zig-linux-x86_64-0.11.0-dev.866+f24c77fc4` then I tried to generate docs from the latest version and it doesn't work anymore. The bug may not be recent (my old version of Zig is more than a month old).

**Comment by kristoff-it** [comment]
We are going to remove internal doc mode from autodoc. It was a potentially nice feature to have under the assumption that we would have to analyze everything regardless, but this turned out to not be true. We are working towards omitting private decl information from the json payload (making it smaller) and even skipping the analysis when not necessary in the backend.

Ultimately internal doc mode was a way of putting to use data that we had to collect anyway. Once we're not going to collect it anymore, the feature seems not worth its cost, especially considering that if you're working on the codebase, you want to be familiar with the source code directly.
