### ISSUE TITLE
doc building c lib (linking c against zig, not the other way round)

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#1475]
the builder has no docs but especially no examples for building a c lib and link it against zig.

building a zig lib and linking against c has some examples

I would like to build https://github.com/munificent/wren and just follow the basic setup 
http://wren.io/embedding/

something basic like this (which is probably not 100% correct yet but still)
```c
pub fn main() u8 {
    var config: c.WrenConfiguration = undefined;

    c.wrenInitConfiguration(@ptrCast(?[*]c.WrenConfiguration, &config));
    var vm = c.wrenNewVM(@ptrCast(?[*]c.WrenConfiguration, &config));

    var result: c.WrenInterpretResult = c.wrenInterpret(vm, c"main", c"System.print(\"I am running in a VM!\")");
    
    c.wrenFreeVM(vm);
    return 0;
}
```

Main issue is, I can not figure out how to build wren using zig.

I also had issues with @cImport where I have to give absolut paths (tried trivial c example and got it working), otherwise zig would not find the c file. I tried `--library-path .` and some other things like absolute path but nothing worked 😞

**Comment by andrewrk** [comment]
`-isystem` is for `@cImport` include paths. `--library-path` is for finding .a, .lib, .so files.

Have a look at https://tiehuis.github.io/blog/zig1.html

I'm a bit confused because you say "linking c against zig, not the other way round" but your example is zig code linking against C code.

Docs for exporting a C library: https://ziglang.org/documentation/master/#Exporting-a-C-Library
Example of importing and using C libraries: https://github.com/andrewrk/tetris

**Comment by monouser7dig** [comment]
> I'm a bit confused because you say "linking c against zig, not the other way round"

> Have a look at https://tiehuis.github.io/blog/zig1.html

Saw that and generally think this sort of post is helpful but this time its the wrong way as far as I see because he basically does export a c lib 

maybe my wording was not good, I'll try to clarify 

> Example of importing and using C libraries: https://github.com/andrewrk/tetris

that is roughly what I want, but I do not just import an existing lib from my system but want zig to compile some c source files from wren.

The idea (for fun) in the end would be to have zig+wren using zigs libc all in one as a custom extensible scripting language. And experiment with both a bit because you can set allocators of wren, bind functions etc...

I'll probably just wait for the documentation of the build process and maybe this described use case can serve as a goal that should ultimately be possible easily.

**Comment by tiehuis** [comment]
Check out this repo which is pretty much what you want to do but with lua instead.

https://github.com/tiehuis/zig-lua

**Comment by monouser7dig** [comment]
> Check out this repo which is pretty much what you want to do but with lua instead.

fools never differ 😃  ... and I thought my idea was anything interesting 😃 
thanks !

Don't know if I should keep this issue open? I think it's probably resolved for me but probably not for zig, Andrew may decide.

**Comment by monouser7dig** [comment]
@tiehuis so I have one issue I can't figure out, I can basically copy your config but wren does not have all files in one dir.

My directories are set up like
- src
  - src/main.zig
- build.zig
- wren
  - wren/vm/foo
  - wren/src/include/wren.h

So it has wren/src/include/wren.h which gets included in wren/src/vm/foo, where foo are the files which are in your lua/src dir.

**The invoked c compiler does not get wren/src/include passed as an include dir though so it aborts.**
`/wren/src/vm/wren_compiler.h:4:10: fatal error: wren.h: No such file or directory`

I used 
```c
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    const mode = b.standardReleaseOptions();
    const exe = b.addExecutable("wren_example", "src/main.zig");
    exe.setBuildMode(mode);

    exe.linkSystemLibrary("c");
    b.addCIncludePath("./wren/src/include/");
    b.addCIncludePath("./wren/src/vm/");


    const wren_c_files = [][]const u8 {
        "wren_compiler.c",
        "wren_core.c",
        "wren_core.wren",
        "wren_core.wren.inc",
        "wren_debug.c",
        "wren_primitive.c",
        "wren_utils.c",
        "wren_value.c",
        "wren_vm.c",
    };


    inline for (wren_c_files) |c_file| {
        const c_obj = b.addCObject(c_file, "wren/src/vm/" ++ c_file);
        exe.addObject(c_obj);
    }

    exe.setOutputPath("./wren_example");

    b.default_step.dependOn(&exe.step);
    b.installArtifact(exe);
}

```
maybe some stupid copy paste bug I'm not seeing or ..

**Comment by tiehuis** [comment]
Looks like the C files are in different directories and need specific include paths when building them. Try the following loop:

```
    inline for (wren_c_files) |c_file| {
        const c_obj = b.addCObject(c_file, "wren/src/vm/" ++ c_file);
        c_obj.include_dirs.append("wren/src/include") catch unreachable;
        exe.addObject(c_obj);
    }
```

Adjust the include if that isn't the correct path.

**Comment by monouser7dig** [comment]
ok I had to add all of this
```c
   inline for (wren_c_files) |c_file| {
        const c_obj = b.addCObject(c_file, "wren/src/vm/" ++ c_file);
        c_obj.include_dirs.append("wren/src/include") catch unreachable;
        c_obj.include_dirs.append("wren/src/optional") catch unreachable;
        c_obj.include_dirs.append("wren/src/vm") catch unreachable;
        exe.addObject(c_obj);
    }
```
now it compiles but then fails linking and complains about `Cannot open ...zig-cache/wren_compiler.c.o: bad relocation (Invalid pointer diff) in section __TEXT/__eh_frame (r1_address=1b78, r1_type=5, r1_extern=1, r1_length=3, r1_pcrel=0, r1_symbolnum=253), (r2_address=1b78, r2_type=0, r2_extern=1, r2_length=3, r2_pcrel=0, r2_symbolnum=259)warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version`

and in turn the build-exe fails
`zig build-exe .../src/main.zig --object .../zig-cache/wren_compiler.c.o --object .../zig-cache/wren_core.c.o --object .../zig-cache/wren_core.wren.o --object .../zig-cache/wren_core.wren.inc.o --object .../zig-cache/wren_debug.c.o --object .../zig-cache/wren_primitive.c.o --object .../zig-cache/wren_utils.c.o --object .../zig-cache/wren_value.c.o --object .../zig-cache/wren_vm.c.o --cache-dir .../zig-cache --output .../wren_example --name wren_example --library c --library c -isystem .../zig-cache -isystem .../zig-cache -isystem .../zig-cache -isystem .../zig-cache -isystem .../zig-cache -isystem .../zig-cache -isystem .../zig-cache -isystem .../zig-cache -isystem .../zig-cache -isystem .../wren/src/include -isystem .../wren/src/vm `

**note: I do not expect you to troubleshoot this with me**, if I just can't figure it out or zig needs some time thats fine as well. On the other hand if we could get it working that would be kind of fun as well 😃

**Comment by andrewrk** [comment]
Unfortunately I think this is the mach-o LLD code not being well maintained. The linker code needs to be improved to support this .o file. Since nobody in LLVM seems interested in improving it, it seems it will fall on the Zig project to dedicate some resources to improving the mach-o linker.

**Comment by monouser7dig** [comment]
okay well that's a bit unfortunate 😀 

I'm always for improving the current state rather than [redoing/ reinventing](https://en.wikipedia.org/wiki/Not_invented_here) it. At least if there is no blatant flaw and I think its reasonable to say that the LLVM people know a thing or two about what they do... 👍 
_(their 11k vs 24k issue stat is btw. not much different from current zig opened vs closed issues, because your tweet seemed to imply their issue management/ quality might be low, at least that is how I read that)_

---

@tiehuis 
> get zligc far enough along to avoid needing to pull in the libc dependency.

> The idea (for fun) in the end would be to have zig+wren using zigs libc all in one as a custom extensible scripting language. And experiment with both a bit because you can set allocators of wren, bind functions etc...

👍 👍
