### ISSUE TITLE
profiler support (state of the art)

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#1501]
I want to make a point for thinking about profiling support early on.

It's very important that a new language should come with easy profiling support because thats just what is prayed everywhere, measure -> optimize.

Go is one example where you can get calligraphs/ flame graph really easily and use that to make guided decisions about how to optimize a program.

Another example (apart from go) I want to bring up is this https://www.youtube.com/watch?v=59lKAlb6cRg#t=52m where its demoed how you get a htop like live view into the current program execution which is pretty amazing.

Both of these examples (and probably others) should be the aim for zig as well 👍 😃

**Comment by binary132** [comment]
I will second that if powerful profiling (and debugging) is not in a language's featureset, I will never consider it a real alternative to C/C++ since those requirements can hit very hard in "serious" projects.

**Comment by andrewrk** [comment]
Here's something you can do right now:

 1. Build with `--no-rosegment` to work around a valgrind bug (see #896)
 2. Run your code with `valgrind --tool=callgrind` or `valgrind --tool=cachegrind`
 3. Analyze the results with `kcachegrind`.

You get something like this:

![](https://edinburghhacklab.com/wp-content/uploads/2012/04/kcachegrind.png)

**Comment by andrewrk** [comment]
Also, `perf` works with zig programs and does the thing in the video above.

**Comment by monouser7dig** [comment]
Well 1st I don’t see how perf does the same as shown in the video, e.g. the Memory usage Graph. 

2nd valagrind and perf are Linux only afaik

3rd zig has its own build system to avoid external tooling dependencies so I think the same should go for profiling (now you would need Linux and perf and valgrind and cachegrind or on windows/ Mac maybe Xcode and VS would work to some extend but then again those are several Gigabyte of dependencies) whereas in Go you just run one command and the graphs pop up into your browser, I think this gives a better incentive to do the right thing (profile).

**Comment by andrewrk** [comment]
I agree with all this

**Comment by monouser7dig** [comment]
just as a summary of whats currently possible see 
https://www.youtube.com/watch?v=keydVd-Zn80&list=WL&index=5&#t=19m45s 

actually this example makes a point where profiled go code gets as fast as rust/ cpp (in that case anyway) so I'd argue that without having a profiler, we'll not be able to push zig to its real potential (all the time)/ its speed can be beaten by go.

(zigs goal is not performance but also accuracy so lets not picture go as a real alternative I just want to make an additional argument for a good profiling tool)

**Comment by Sahnvour** [comment]
Another useful type of profiler is what I believe is now called _Flamegraph_. That's basically a temporal trace of the program execution, recording the timings of annotated functions. You can then display the data as some kind of "callstack" over the whole run, and it allows to both have a nice overview of its flow and inspect very precisesely what functions take time. (this can easily be googled)

For example, virtually every game engine provides this as a tool for optimisation, wether the data is collected and/or displayed by an in-house library, or an external tool.

Typical usage in C++ is having a macro `TIME_SCOPE("name", "additional info")` that creates a small object making use of RAII to time the execution of the current scope.

In Zig, this would translate as a function call + a `defer` expression, and it is entirely feasible in library.

However, compiler support may be useful to offer more possibilities and better integration.
For example, this kind of debug/profiling macros typically also record the source file, line number and function name which, to my knowledge, are not queryable at compile time in Zig at the moment.

So we can think of at least two ways of going for this:
1. adding `@functionName()`, `@sourceFilePath()` and `@lineNumber()` and having the rest of the implementation in library code (in the standard lib or not)
2. adding the feature directly in the compiler, for example as `@setScopeTimed()` (similarly to `@setCold()`)

With solution 1, we have all the building blocks to do good flamegraph data collection, but the usability is not so good compared to C++ macros. Inside every function (or scope) that we want to profile, we would have to write boilerplate along the lines of
```zig
const scopeTimer = timeNewScope(@functionName(), @sourceFilePath(), @lineNumber(), "name", "additional info"); // returns a pointer
defer scopeTimer.duration = now() - scopeTimer.start;
```

On the other hand, solution 2 would be dead simple to use: just drop a `@setScopeTimed()` and the compiler takes care of inserting the instrumentation code. The caveat is that the implementation is then heavier on Zig's side.
In Jonathan Blow's video linked before, it seems that he is going for a standard library that makes use (showed screen graph) of compiler-inserted timings. I assume this would not do for Zig, since its intended use cases are broader, and users' needs vary _a lot_ (not even taking into account the not-invented-here syndrom).
The most neutral option would perhaps having a way to hook user's code with the compiler-generated one so that the latter passes data directly to the former to handle. You don't record these things the same way in a single-threaded and a multi-threaded program for example.
Note: timing of functions could be off by default with opt-in, or on by default with opt-out plus some heuristics to evict small uninteresting functions.

I'm kind of dumping my thoughts on this as I write, but I find this subject very interesting especially with the interaction of user code, standard library and compiler.

**Comment by andrewrk** [comment]
Closing because there is nothing specific enough to act on.
