### ISSUE TITLE
Autodoc: keep #Mixing-Object-Files in sync

### ISSUE THREAD

**Issue by wenq1** [ziglang/zig#15082]
Reference issue: #2905

Please keep docs in sync, and please take a look at the following sections:

https://ziglang.org/documentation/master/#Mixing-Object-Files        
https://ziglang.org/documentation/0.10.1/#Mixing-Object-Files

Clearly on the so-called "master", the following piece of code is out of date. The second argument has to be nil.

``` zig
const exe = b.addExecutable(.{
        .name = "test",
});
```

I know lots of hard work has been put into a language like zig, and I refrain from complaining. But when I tried the basic example [here](https://tiehu.is/blog/zig1), I got lovely results:

``` zig
pub fn build (b: &Builder) => no longer works in master
const   source_files = [][]const u8 { => no longer works in master
const   exe       = b.addCExecutable ("main"); => no longer works in master
exe.addCompileFlags ([][]const u8 {  => no longer works in master
exe.addSourceFile (source); => no longer works in master
exe.setOutputPath ("./main"); -=> no longer works in master
b.default_step.dependOn (&exe.step); => no longer works in master

```

Sorry for being bluntly sarcastic. How lovely is it to find EVERY SINGLE LINE no longer works! Did I just waste my whole afternoon going through zig's documentation and only to find myself a fool unworthy of programming?

**Comment by wenq1** [comment]
I have solved the issue. I'll close once anyone replies, so that someone gets attention.

**Comment by squeek502** [comment]
It's not clear to me exactly what the problem is. The docs for the master version use code that only works on the latest master version (which has breaking changes all the time; the code you use today might not work tomorrow). The docs for 0.10.1 use code that works with 0.10.1 but may not work with the latest master version.

For future reference, this type of question/inquiry would be better directed to [one of the community spaces](https://github.com/ziglang/zig/wiki/Community) first.

**Comment by mlugg** [comment]
What squeek said is totally correct, but just a few points:
- This issue is unrelated to Autodoc. Autodoc is a (beta) system used to automatically generate documentation webpages from Zig source code. It is not used for the documentation pages linked.
- The first code snippet is absolutely *not* outdated for `master`; it's specifically *updated* to work on it. `master` refers to the Zig compiler in the `master` branch of the repo - essentially, the nightly builds. You can download binaries from https://ziglang.org/download/. Passing `null` as a second argument to `addExecutable` is not valid in `master` and will not compile.
- The blog post you linked is almost 6 years old. Zig is a pre-1.0 language, so evolves very rapidly. That blog post was made less than 2 years after Zig was created: you can't expect it to be even remotely up-to-date.

In general: if you aren't prepared to deal with semi-frequent breaking changes, a v0 language is *not* for you.
