### ISSUE TITLE
`zig test` will fail if `test` is an existing directory

### ISSUE THREAD

**Issue by cgag** [ziglang/zig#1508]
I have my tests in a directory called `test` and `zig test` now gives me an ldd error: `lld: error: cannot open output file test: Is a directory`. If test is a file it'll just overwrite it. 

Seems like it should be moved back into the zig-cache dir?  

just working around with `zig --cache on test [...]` for now

**Comment by andrewrk** [comment]
Here's another workaround: `zig test --output test2 foo.zig`

Possible solutions to this problem:
 * default to creating `zig-cache/test` rather than `test`. This matches previous behavior. What about `build-exe` though? That outputs to the current directory. Should `test` be different? This solution mainly operates on the fact that `zig-cache` is a better globally unique name than `test`.
 * default to `--cache on`. Rely on cache eviction.
 * avoid overwriting a `test` directory by renaming, appending numbers. For example it would create `test1`. But would it overwrite files?
 * write to a global temp folder, and delete upon successful test completion. Then we need some kind of deletion strategy for old temp files. And probably we would want an option to not delete even on success.
 * leave as is and require users to use the `--output` (or `--cache on`) workaround if this situation occurs.

**Comment by kristate** [comment]
I think that it should default to `zig-cache/test` and then try to `mv` `test` to the current directory. If that fails, let the programmer know that the file was outputted to `zig-cache/test` but it could not be moved.
