### ISSUE TITLE
inline switch in comptime context erroneously reports runtime error

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#15157]
### Zig Version

0.11.0-dev.2266+49e33a2f2

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test "comptime inline switch" {
    const U = union(enum) { a: type, b: type };
    const value = comptime blk: {
        var u: U = .{ .a = u32 };
        break :blk switch (u) {
            inline .a, .b => |v| v,
        };
    };

    try std.testing.expectEqual(u32, value);
}
```

Error:
```
test.zig:12:38: error: unable to resolve comptime value
    try std.testing.expectEqual(u32, value);
                                     ^~~~~
test.zig:12:38: note: argument to parameter with comptime-only type must be comptime-known
```

### Expected Behavior

Test should pass.

If you manually unroll `inline .a, .b` to separate `.a`, `.b` cases with identical logic, it works.

**Comment by rohlem** [comment]
> If you manually unroll inline .a, .b to separate .a, .b cases with identical logic, it works.

Another important detail: If you **remove inline**, and **demote** it to a regular switch case, **it works**!
Whereas **separate cases** that are **still marked `inline` lead to the same error**.
(For me, on outdated `0.11.0-dev.1302+d813cef42`, but the initial report is still the same.)
Which makes sense in the regard that we're already at a `comptime` scope, so the compiler obviously knows the value already, even in non-`inline` switch cases.

To me this seems like there's specific code for inline `switch` cases with unions,
because usually (in a runtime scope) the tag becomes `comptime`-known via unrolling but the payload doesn't.
This breaks at `comptime` because it forces some "must-be-runtime" dummy value into the payload - which is the wrong behavior in a `comptime` scope, where all values must be known.
