### ISSUE TITLE
getopt.h is missing in macOS

### ISSUE THREAD

**Issue by jiacai2050** [ziglang/zig#15212]
### Zig Version

0.11.0-dev.2455+48f98494f

### Steps to Reproduce and Observed Behavior

issue.c
```c
#include <getopt.h>

void main() {}
```
build.zig
```
const std = @import("std");

pub fn build(b: *std.Build) void {
    const exe = b.addExecutable(.{
        .name = "demo",
        .target = .{},
        .optimize = .Debug,
    });

    exe.linkLibC();
    exe.addCSourceFile("issue.c", &[_][]const u8{});
    exe.install();
}
```
Then execute
```
zig build
```
Following error will be thrown
```
zig build-exe demo Debug native: error: error(compilation): clang failed with stderr: /Users/jiacai/tt/demo/issue.c:1:10: fatal error: 'getopt.h' file not found
```

### Expected Behavior

No error

**Comment by andrewrk** [comment]
Thanks for filing the issue - we can have this in by 0.11.0 for sure. Are there any other missing headers after this one for your use case?

**Comment by jiacai2050** [comment]
Noop, currently only this one.

**Comment by kubkon** [comment]
Incoming in #15260

**Comment by plajjan** [comment]
@kubkon I had a missing header file just like this, which you fixed rapidly enough, but I am still curious about the idea here, like what is the criteria for header files to be added on macos? isn't there a way to determine all the relevant libc / base platform libraries and just add them once rather than doing this one-by-one approach? (given that you guys usually know what you're doing, I actually assume there is a good reason, but I want to know why :))

**Comment by kubkon** [comment]
Initially we were very careful not to add headers that are unused by folks as every new header increases the size of Zig distribution. Seeing as there are more and more used, I think it warrants me going over the list we have and adding missing headers so that we can avoid this type of issues in the future.

**Comment by kubkon** [comment]
> I'm also curious why some headers are still missing, is https://github.com/ziglang/fetch-them-macos-headers this tool cannot found all headers for specific macOS version?

I now have a concrete answer to this. Programmatically finding correct set of include headers is non-trivial as not all header include paths under system's `<sysroot>/usr/include` are to be included explicitly by the user's code. For example, including `#include <sys/_types/...>` should never be done, and instead the user should only include `<sys/types.h>`. Some Apple specific headers such as `<AppleArchive/...>` error out stating you should only include `<AppleArchive.h>`, and so it is safer to do add missing headers on a case-by-case basis. Having said that, now that I have a better grasp of the problem space, I might try and figure out a better alternative to the process.
