### ISSUE TITLE
Support for Windows __uuidof

### ISSUE THREAD

**Issue by jcalabro** [ziglang/zig#15365]
Hey there! I was wondering if there is any way to use Windows C++'s [__uuidof](https://learn.microsoft.com/en-us/cpp/cpp/uuidof-operator?view=msvc-170) in Zig natively? If not, is it possible to add it?

I'm writing some code against the [Desktop Duplication API](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api) which requires calling the COM mechanism [QueryInterface](https://learn.microsoft.com/en-us/cpp/atl/queryinterface?view=msvc-170), which in turn takes the result of `__uuidof`.

Thanks!

**Comment by squeek502** [comment]
`__uuidof` is a MSVC++ only extension. Instead of that, you'd need to find the actual GUID value and use that in Zig ([see here](https://stackoverflow.com/questions/8868784/alternative-to-uuidof-in-c)). For example, `IID_ID3D11Texture2D` is defined in `d3d11.h` as:

```c
DEFINE_GUID(IID_ID3D11Texture2D,0x6f15aaf2,0xd208,0x4e89,0x9a,0xb4,0x48,0x95,0x35,0xd3,0x4f,0x9c);
```

In Zig, I believe this would be translated to:

```zig
std.os.windows.GUID{
    .Data1 = 0x6f15aaf2,
    .Data2 = 0xd208,
    .Data3 = 0x4e89,
    .Data4 = .{ 0x9a, 0xb4, 0x48, 0x95, 0x35, 0xd3, 0x4f, 0x9c },
}
```

If you have the string version of the GUID, then it's even easier:

```zig
// this is not ID3D11Texture2D, this is just an example (it happens to be IShellIconOverlayIdentifier)
windows.GUID.parse("{0c6c4200-c589-11d0-999a-00c04fd655e1}");
```

If you'd like to look at a more complete example of using COM from Zig, you can check out https://github.com/squeek502/watchedoverlay

---

For future reference, this type of question is better directed at [one of the community spaces](https://github.com/ziglang/zig/wiki/Community).

**Comment by jcalabro** [comment]
Aha, thank you! Apologies for posting in the wrong spot.

There's no chance that we would want to port the `__uuidof` msvc extension over to Zig to make it easier to use COM objects? Closing assuming the answer is no, but if yes feel free to reopen.

Thanks again for the detailed answer!

**Comment by jcalabro** [comment]
[This file](https://github.com/ziglang/zig/blob/31b6d14bf76fa6b78013a6a32d3066e882d64043/lib/std/os/windows.zig#L2890) is also a great resource when working with Windows GUIDs.
