### ISSUE TITLE
Build error on snap install of 0.11.0 - internal cause?

### ISSUE THREAD

**Issue by Henrik9000** [ziglang/zig#15360]
### Zig Version

0.11.0-dev.2652+8ba937c78

### Steps to Reproduce and Observed Behavior

Can't build zig code from https://github.com/sigidagi/cgotest/tree/main/bindings/zig - seems like an internal error?

```
@:~/git/cgotest/bindings/zig$ snap install zig --classic --edge
zig (edge) 0.11.0-dev.2652+8ba937c78 from Jay Petacat (jayschwa) installed
@:~/git/cgotest/bindings/zig$ zig env
{
 "zig_exe": "/snap/zig/7172/zig",
 "lib_dir": "/snap/zig/7172/lib",
 "std_dir": "/snap/zig/7172/lib/std",
 "global_cache_dir": "/home/heso/.cache/zig",
 "version": "0.11.0-dev.2652+8ba937c78",
 "target": "x86_64-linux.5.15...5.15-gnu.2.35"
}
@:~/git/cgotest/bindings/zig$ zig build
/snap/zig/7172/lib/std/Build/CompileStep.zig:554:21: error: deprecated; use std.Build.installArtifact
pub const install = @compileError("deprecated; use std.Build.installArtifact");
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    build: /home/heso/git/cgotest/bindings/zig/build.zig:18:8
    runBuild__anon_7401: /snap/zig/7172/lib/std/Build.zig:1545:27
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

Clean build.

**Comment by mlugg** [comment]
The issue is exactly what the error message says: the `build.zig` for that project is using a function which is deprecated and has been removed. This deprecation was very recent, so presumably the author just hasn't gotten around to fixing this yet. You should be able to resolve it by changing the line `exe.install()` in the `build.zig` to `b.installArtifact(exe)`.
