### ISSUE TITLE
zig cc can't build trivial file for glibc 2.15 and earlier - undefined symbol: aligned_alloc

### ISSUE THREAD

**Issue by ekliptik** [ziglang/zig#15486]
```
emil@blahaj /t/aaa> export VER=17 && zig c++ -c a.cpp -target native-linux-gnu.2.$VER && zig c++ a.o -target native-linux-gnu.2.$VER
emil@blahaj /t/aaa> export VER=16 && zig c++ -c a.cpp -target native-linux-gnu.2.$VER && zig c++ a.o -target native-linux-gnu.2.$VER
emil@blahaj /t/aaa> export VER=15 && zig c++ -c a.cpp -target native-linux-gnu.2.$VER && zig c++ a.o -target native-linux-gnu.2.$VER
LLD Link... ld.lld: error: undefined symbol: aligned_alloc
>>> referenced by stdlib_new_delete.cpp
>>>               /home/emil/.cache/zig/o/ac5f3332801238b14e3dd389fbc44890/stdlib_new_delete.o:(operator new(unsigned long, std::align_val_t)) in archive /home/emil/.cache/zig/o/c5197ee19e47a3291e58db8f0c510750/libc++abi.a
>>> referenced by fallback_malloc.cpp
>>>               /home/emil/.cache/zig/o/5b362b01356b41831dc4c0689b14a1b1/fallback_malloc.o:(__cxxabiv1::__aligned_malloc_with_fallback(unsigned long)) in archive /home/emil/.cache/zig/o/c5197ee19e47a3291e58db8f0c510750/libc++abi.a

emil@blahaj /t/aaa> cat a.cpp
int main() {return 0;}
emil@blahaj /t/aaa> zig version
0.11.0-dev.2834+13101295b
```
This isn't the case with 0.10.1, at least

**Comment by ekliptik** [comment]
Prior to reproducing this, I have removed `ld.lld` from my system to prevent contamination

**Comment by ekliptik** [comment]
Related is #3783 which says GLIBC has aligned_alloc since 2.16. I suspect some wrapper which replaces aligned_alloc with generic code is what's failing here

**Comment by ekliptik** [comment]
It seems like `_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION` should be defined by something but isn't

**Comment by agostonrobert** [comment]
I guess the root cause of this issue is that the first glibc version known by Zig is 2.16.
See the list of known glibc versions by the [glibc-abi-tool ](https://github.com/ziglang/glibc-abi-tool/blob/main/README.md) at https://github.com/ziglang/glibc-abi-tool/tree/main/glibc
The README.md [mention](https://github.com/ziglang/glibc-abi-tool/blob/main/README.md#strategy) that in some cases the abilist file from the latest libc is not enough to generate the symbol db, hence they store the abilist for the handled glibc versions.
Also, [consolidate.zig](https://github.com/ziglang/glibc-abi-tool/blob/main/consolidate.zig) handles different versions of abilist structures, but I am not sure if it has any constrain to generate abilist files for glibc versions prior 2.16.

**Comment by rootbeer** [comment]
Zig's glibc-abi-tool parses and include all versions of glibc back to 2.0.0.  There is a v2.16 restriction if you're using the Zig runtime (as it references symbols that only exist in that and later versions).  But if you're building something standalone, or using the c/c++ compilers, the full range of glibcs should be available, I think.  See the most recent discussion in #17769.

That said, the Zig glibc header files have had problems with individual symbols being made visible correctly in the header files, so there can still be problems with some symbols.

Back to this problem, with a recent Zig build, I am able to compile and run the no-op example from the original bug just fine against very old glibc versions (back to 2.2.5):

```
$ zig  version
0.12.0-dev.2241+20ebfef92
$ cat > retzero.cpp
int main() {return 0;}
$ zig c++ retzero.cpp -target native-native-gnu.2.10 -o retzero-2.10 -lc
$ ./retzero-2.10
$  nm -uD retzero-2.10
                 w __gmon_start__
                 U __libc_start_main@GLIBC_2.2.5
```

If you go back real far (glibc v2.2 era), there is a more fundamental problem with `__libc_start_main`:
```
$   zig c++ retzero.cpp -target native-native-gnu.2.2.4 -o retzero-2.2.4 -lc
LLD Link... ld.lld: error: undefined symbol: __libc_start_main
>>> referenced by start-2.33.S:120 (/home/pat/projects/ziglang/zig/lib/libc/glibc/sysdeps/x86_64/start-2.33.S:120)
>>>               /home/pat/.cache/zig/o/a3769da7602da072119ac76d600048dd/Scrt1.o:(_start)

```

However, if I have a terrible C++ program that uses new/delete, that seems to pull in a dependency on `aligned_alloc` via libcxx:
```
$ cat > cppalloc.cpp
int main(void)
{
        char* ptr = new char[10];
        delete[] ptr;
        return 0;
}
$ zig  c++ cppalloc.cpp -target native-native-gnu.2.15 -o cppalloc-2.15 -lc
LLD Link... ld.lld: error: undefined symbol: aligned_alloc
>>> referenced by aligned_alloc.h:44 (/home/pat/projects/ziglang/zig/lib/libcxx/include/__memory/aligned_alloc.h:44)
>>>               /home/pat/.cache/zig/o/a04f07ede75d989e6adc0cb297376051/stdlib_new_delete.o:(operator new(unsigned long, std::align_val_t)) in archive /home/pat/.cache/zig/o/eec4e8f855262fc996159990deee2d9f/libc++abi.a
>>> referenced by aligned_alloc.h:44 (/home/pat/projects/ziglang/zig/lib/libcxx/include/__memory/aligned_alloc.h:44)
>>>               /home/pat/.cache/zig/o/8e1cab93b822985ee0db734a29321316/fallback_malloc.o:(__cxxabiv1::__aligned_malloc_with_fallback(unsigned long)) in archive /home/pat/.cache/zig/o/eec4e8f855262fc996159990deee2d9f/libc++abi.a
```

(It compiles just fine against glibc v2.16.)

The libcxx source reference is clearer now in the backtrace: zig/lib/libcxx/include/__memory/aligned_alloc.h: https://github.com/ziglang/zig/blob/master/lib/libcxx/include/__memory/aligned_alloc.h

And this is just what @ekliptik was pointing out about needing to define `_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION` when compiling libcxx (at least when compiling against older glibcs).    I'll poke at how Zig builds its libcxx, but I'm new here and can't promise anything ...

**Comment by ekliptik** [comment]
I see, thanks and good luck. It's surprising is that the empty main C++ file doesn't pull in libcxx anymore, but it *used to* do that. Something changed between 0.11.0 and 0.12.0-dev.2261+c4a1b54eb

**Comment by rootbeer** [comment]
Zig's libcxx build configuration is defined in [src/libcxx.zig](https://github.com/ziglang/zig/blob/master/src/libcxx.zig), and the `buildLibCXX` and `buildLibCXXABI` functions in there define the compiler command lines.  (I'm not entirely sure what the difference between the two targets is).  Adding

```
        if (target.isGnuLibC()) {
            // glibc 2.16 introduced aligned_alloc
            if (target.os.version_range.linux.glibc.order(.{ .major = 2, .minor = 16, .patch = 0 }) == .lt) {
                try cflags.append("-D_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION");
            }
        }
```

to both build functions, makes it so `zig c++` can build the cppalloc.cpp example above against a glibc v2.6.0 target and v2.17.0 target.

I'm not sure what libcxx defines are meant as external toggles, and which ones are internal.  The real libcxx [__config](https://github.com/llvm/llvm-project/blob/47d59670230fe6940fafd3844c219c4c4636ea76/libcxx/include/__config#L897-L911) only sets this define for certain C runtimes, so there may be other settings that in practice change with it, or maybe there is some more abstract flag in the libcxx configuration that should be set instead.

There are also [`-faligned-allocation` and `fno-aligned-allocation` flags](https://github.com/ziglang/zig/blob/master/src/libcxx.zig#L241-L245) that are passed to the compiler when building this library.  Not sure if that needs to be consistent with this flag or not.  I left that unchanged.

While my trivial example builds and runs, I'm not sure if there are subtle things around actually-aligned allocations or whatnot that may be introduced by this.  So if you have a more interesting C++ project you can test this on, I'm curious to see if this introduces other problems ...

One development note: because (? I think?) the `libcxx.zig` file is in the src/ directory, Zig itself (at least the "stage 4" part) has to be re-built for changes to libcxx.zig to be visible.  (Unlike `lib/` changes, which Zig seems to pick up from the source tree directly.)

**Comment by poolshrk** [comment]
This issue is back on zig 0.15.1, I was able to reproduce with a simple hello world program:

```
user@debian:~/hello$ cat hello.cpp 
#include <iostream>

int main() {
    std::cout << "Hello World!" << std::endl;
    return 0;
}
user@debian:~/hello$ /opt/zig-x86_64-linux-0.15.1/zig c++ -target x86_64-linux-gnu.2.10.0 -o hello hello.cpp
ld.lld: error: undefined symbol: aligned_alloc
>>> referenced by aligned_alloc.h:42 (/opt/zig-x86_64-linux-0.15.1/lib/libcxx/include/__memory/aligned_alloc.h:42)
>>>               /home/user/.cache/zig/o/8da8cc1f99238718042d800a2fb793be/stdlib_new_delete.o:(operator new(unsigned long, std::align_val_t)) in archive /home/user/.cache/zig/o/7b285ac5c92dbb09fc4153ba2471c9de/libc++abi.a
>>> referenced by aligned_alloc.h:42 (/opt/zig-x86_64-linux-0.15.1/lib/libcxx/include/__memory/aligned_alloc.h:42)
>>>               /home/user/.cache/zig/o/b0e4c195a966962779febce08047a976/fallback_malloc.o:(__cxxabiv1::__aligned_malloc_with_fallback(unsigned long)) in archive /home/user/.cache/zig/o/7b285ac5c92dbb09fc4153ba2471c9de/libc++abi.a
```

I'm unsure if this should be a new bug report or this one should be reopened?

**Comment by alexrp** [comment]
New bug report please. It looks like something changed on the libc++ side that wasn't caught in the LLVM 20 upgrade.
