### ISSUE TITLE
additional float modes

### ISSUE THREAD

**Issue by numsim1415** [ziglang/zig#1562]
As [Fabian Giesen](https://twitter.com/rygorous/status/1032074614619267073) points out,  different floating point behaviour on a per-scope basis is useful.
Note, however, that `-ffast-math` can be too much. Instead, using  `-freciprocal-math -fno-signed-zeros -fno-trapping-math -fassociative-math` is often reasonable, in my opinion. 
Are there plans to enable the use of such settings?

_Originally posted by @numsim1415 in https://github.com/ziglang/zig/issues/1227#issuecomment-422795920_

Edit: These four settings are useful because they are the minimal ones required to enable reciprocal and associative simplifications: 
> `-fassociative-math` [...] requires that both `-fno-signed-zeros` and `-fno-trapping-math` be in effect.

see [gcc/Optimize-Options](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html)

**Comment by andrewrk** [comment]
from https://ziglang.org/documentation/master/#setFloatMode:

 Optimized - Floating point operations may do all of the following:

   * Assume the arguments and result are not NaN. Optimizations are required to retain defined behavior over NaNs, but the value of the result is undefined.
   *  Assume the arguments and result are not +/-Inf. Optimizations are required to retain defined behavior over +/-Inf, but the value of the result is undefined.
   *   Treat the sign of a zero argument or result as insignificant.
   *   Use the reciprocal of an argument rather than perform division.
   *   Perform floating-point contraction (e.g. fusing a multiply followed by an addition into a fused multiply-and-add).
   *   Perform algebraically equivalent transformations that may change results in floating point (e.g. reassociate).

Which of these would you want to disable in this new proposed FloatMode?

**Comment by numsim1415** [comment]
- One point is that I might not want to assume all results and arguments to be finite (`ninf`) and non-nan (`nnan`). Since the value of a result from using NaNs/Infs is undefined when `nnan` or `ninf ` are set, respectively, this would produce undefined behaviour.
- Similarly, one point is to make sure that calls to [`isnan`](https://github.com/ziglang/zig/blob/master/std/math/isnan.zig) and [`isinf`](https://github.com/ziglang/zig/blob/master/std/math/isinf.zig) do not get optimized away (or cause undefined behaviour similar to undefined variables). As far as I understand, LLVM could optimize it away if it realizes the bitcast represents a NaN. Thinking of it, of course, users could switch to Strict before calling these functions. Anyhow, should a warning/error be emitted by `isnan` and `isinf` at comptime when they are called with `Optimized`/`nnan`/`ninf` set to on? 

- Another thing is being able to switch off the use-approximate-functions `afn` feature which inserts approximate versions for the intrinsics `llvm.{sqrt,sin,cos,pow,exp,exp2,log,log10,log2,fma}.*`. According to zig's documentation, however, zig does not use/expose this feature anyway. 

[llvm's flags](https://www.llvm.org/docs/LangRef.html#fast-math-flags)
[llvm's instrinsics affected by afn flag](https://www.llvm.org/docs/LangRef.html#llvm-sqrt-intrinsic)

Please excuse me, if I misunderstood the documentations.

**Comment by andrewrk** [comment]
No but I made this other plan instead =>  #6634
