### ISSUE TITLE
Proposal: zig init-module for zig based libraries

### ISSUE THREAD

**Issue by DraagrenKirneh** [ziglang/zig#15653]
#Proposal
A new command `init-module` for initializing a new `zig build` project for zig based libraries

There are currently two commands for initializing the current cwd with a zig specific build and template code; init-exe and init-lib.
Neither of these supports initializing of a build and template for starting a new project aimed to be a direct zig module aimed to be consumed by other zig projects without the need to build it as a shared/static library.

**Comment by andrewrk** [comment]
I changed my mind. Instead of adding `zig init-mod`, the already existing `zig init-lib` should be modified to create and expose both a zig module, as well as exporting a C API wrapper around the zig API. This is a gentle nudge to encourage people to consider making their zig modules reusable by C (and therefore other languages too). However, the template should make it obvious how to delete this extra layer on top of the zig module.
