### ISSUE TITLE
Program compiled on AMD machine crashes on Intel Celeron machine with 'illegal instruction' exception

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#15895]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

A program can be any. I took this simple after observing the behavior with a complex one:

```zig
const std = @import("std");
pub fn main() void {
    std.debug.print("Hello!\n", .{});
}
```

It was compiled on a machine with `AMD E2-9000e RADEON R2, 4 COMPUTE CORES 2C+2G` CPU (Linux Mint 19.1)
and then run on a machine with `Intel(R) Celeron(R) N4020` CPU (also Linux Mint 19.1). The result was abnormal termination (illegal instruction). 

### Expected Behavior

No crash, should run susccessfully.

**Comment by nullptrdevs** [comment]
Try `-Dcpu=baseline`.

**Comment by dee0xeed** [comment]
Did not help, `illegal instruction` again

**Comment by nullptrdevs** [comment]
Hmm, I wonder what would be a common ground.. try `zig build-exe zb.zig -mcpu=` for a list of available CPU architectures and look for a one that might fit both.

**Comment by dee0xeed** [comment]
`-mcpu=x86_64` is ok.

**Comment by nullptrdevs** [comment]
By default Zig tailors the app to the host cpu, but obviously a newer/better cpu has more instructions/extensions and trying to run the app on an earlier/not as capable cpu would cause the aforementioned crash.

**Comment by dee0xeed** [comment]
I do not think `AMD E2-9000e RADEON R2` (it's a quite old HP laptop) is newer/better than `Intel(R) Celeron(R) N4020` (though it's also not a brand new). Tbh, I just do not know which one is newer or "better".

**Comment by dee0xeed** [comment]
Google tells me that
* AMD E2-9000e RADEON R2 - 2016
* Intel(R) Celeron(R) N4020 - 2019

**Comment by nektro** [comment]
`-Dtarget=x86_64-native-native`

**Comment by andrewrk** [comment]
This is working as designed. Here are some additional ways things can go wrong if you blithely copy build artifacts from one machine to another:
 * An executable compiled for Windows will not run on Linux (PE vs ELF)
 * An executable compiled for aarch64 linux will not run on x86_64 linux
 * An executable compiled for dynamically linked glibc will not run on a system that uses musl libc (e.g. alpine)
 * An executable compiled for dynamically linked glibc will not run on a system with a different dynamic linker path (e.g. nixos)

As you can see, CPU features are the least of your concerns.

If you want to target a different computer than the host, you must pass the `-target` flag to the compiler. Note that `-D` creates a preprocessor macro definition, and does not have the ability to change the target. People in this thread who suggested it were likely getting confused with `zig build`, which uses `-D` for user-specified options, which may or may not expose a target option.

```
zig build-exe --help
...
  -D[macro]=[value]         Define C [macro] to [value] (1 if [value] omitted)
...
```

**Comment by dee0xeed** [comment]
Hey, wait! It was not a question, I'm not that dumb. An executable (statically linked!) produced by zig compiler for x86_64, should work on any x86_64 (as zig compiler itself!!!) with the same OS (Linux Mint in my case) , shouldn't it? And your 4 examples are not to the point at all. Both AMD and Celeron above are x86_64, right? Both runs one and the same OS. So why a prorgam when compiled on the 1-st machine, gets `SIGILL` being run on the second, but when compiled on the second, runs normally on the 1-st?

**Comment by mlugg** [comment]
> An executable (statically linked!) produced by zig compiler for x86_64, should work on any x86_64 (as zig compiler itself!!!) with the same OS (Linux Mint in my case) , shouldn't it?

No, it should not. x86 and x86_64 have a large amount of extra CPU features which were introduced in later versions as extensions to the architecture, like SSE and AVX. When you compile a binary for the "native" target (which is the default), the compiler will assume it's allowed to use all features of the CPU you're compiling on; for instance, if your CPU supports SSE4, it'll use SSE4 instructions where it makes sense. If you then try to copy that binary to a machine running the same OS and general architecture, but a different CPU which does not support SSE4, you'll get `SIGILL`. The `-mcpu` option you passed (you can also use `-target`) is telling the compiler "actually, target a common subset of x86_64 processors; i.e. only use features they're guaranteed to support". This gives you a cross-CPU binary, at the expense of some performance (since you lose access to e.g. SSE4 instructions, which would result in faster code).

Any language with a sufficiently optimizing compiler will have the same issue as this. You can observe it in C code too; Clang also accepts the `-mcpu=x86-64` parameter for instance.

**Comment by andrewrk** [comment]
Nobody is being accused of being dumb here, don't worry. In fact this is a common mistake for zig beginners because people are used to the ridiculous defaults of other toolchains. Other projects may give in and copy the legacy defaults, however, it is a hill that I am prepared to die on. In order to cross compile using Zig, one must inform the compiler of such intent.

**Comment by dee0xeed** [comment]
@mlugg and @andrewrk , I do understand everything you are telling to me.
Just answer then one simple question - what compiler options (target) should I use
to build a public binary release (say, Linux x86_64) that will work without suprises
on any linux-x86_64, just like zig itself does.

**Comment by mlugg** [comment]
You just have to manually specify your target using (for instance) `-target x86_64-linux-musl` (which generates a binary for Linux, using musl libc, targetting a generic x86_64 processor). (The `-mcpu` option you passed also works, and is equivalent, but when you're targeting a generic CPU like this, specifying the target is more clear.) When you don't specify the target, it's implied to be `native-native`, which is what leads to your host CPU features being used.

**Comment by dee0xeed** [comment]
@mlugg, thank you very much, now everything is clear.
If I want to share an executable, I should use generic target.
If someone want to have an executable for a CPU with some specific instructions
(say, for the purpose of performance) - let he/she take source code and compile
it on whatever host he/she likes.
