### ISSUE TITLE
add docs for usingnamespace

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1589]
```zig
usingnamespace @import("foo.zig");
```

 * [x] might plan to rename the keyword?
 * [ ] ~might plan to get rid of it?~
 * [ ] ~try not to use this feature until it becomes stable.~
 * [ ] however it makes sense to use the feature to combine imports and re-export them, like [this](https://github.com/andrewrk/tetris/blob/29f50a199d299fa95db5d923f2ac4891b7fa4c5a/src/c.zig#L1)

**Comment by UniqueID1** [comment]
When I look at Zig projects on the internet I have to say that I'm impressed by how little people use the 'use' keyword, I'm the exact opposite and I just can't seem to stop using it.

Is it better to prepend every SDL_* function with 'c.' or 'sdl.'? Does that make it clearer where it comes from? The way I have things setup, I can press 't' to instantly go to a symbol. And thanks to zig I can grep for "pub fn NameOfFunction" to find it instantly. Why do I need a path to each symbol spelled out for me? Everyone knows vk, gl, SDL symbols are going to be coming from a single file or a few files someplace. For me, those symbols are clear enough without an explicit path.

I take compilation time very seriously. If the lack of 'use' speeds of compilation time, then I may see the point. However, because of namespace per file, it wouldn't surprise me if people write more methods than they would have otherwise so it's easier to (sort of) escape the namespace mechanism:
const Struct = @import("file.zig").Struct;

No one's going to be pulling out individual functions (when there's a lot of them), so writing methods is easier. But the act of doing this reduces the compile time penalty from using 'use' and makes it much easier to guess where symbols come from. So it would seem that struct methods are already providing both the ability to reduce compile time and see where symbols come from, making the namespace per file unnecessary in my opinion. Why have a namespace for a file that contains just a single struct?

I think I'm in a very small minority here.

**Comment by tiehuis** [comment]
@UniqueID1 see also #1047.

**Comment by BarabasGitHub** [comment]
I had no idea 'use' existed and also have no clue what it actually does and
why it would be related to compile speeds.

So that's the main reason I'm not using it and that probably goes for
others as well.

Op do 27 sep. 2018 05:24 schreef Andrew Kelley <notifications@github.com>:

**Comment by dbandstra** [comment]
This issue should be renamed to "add docs for usingnamespace"
