### ISSUE TITLE
Improve Error Messages when equality comparison with a constant fails (would this be considered an `error-hint`?)

### ISSUE THREAD

**Issue by haleemur** [ziglang/zig#16073]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Output

**Steps to Reproduce**

1. make a directory and run `zig init-exe`.

2. add the following lines to the generated file `src/main.zig`.

    ```
    const expect @import("std").testing.expect;

    ...
    test "while with continue expression" {
        var sum: u8 = 0;
        var i: u8 = 1;
        while (i <= 10) : (i += 1) {
            sum += i;
        }
       try expect(sum == 10);
    }
    ```
3. run `zig build test`

This results in the following output:

```
Test [1/1] test.while with continue expression... FAIL (TestUnexpectedResult)
/opt/homebrew/Cellar/zig/0.10.1/lib/zig/std/testing.zig:347:14: 0x104dcc6f3 in expect (test)
    if (!ok) return error.TestUnexpectedResult;
             ^
/Users/hal/zig-hello-world/src/main.zig:23:5: 0x104dcc9cb in test.while with continue expression (test)
    try expect(sum == 10);
    ^
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
/Users/hal/zig-hello-world/zig-cache/o/dd2360d564acd54512a670dfa33b00a3/test
error: test...
error: The following command exited with error code 1:
/opt/homebrew/Cellar/zig/0.10.1/bin/zig test /Users/hal/zig-hello-world/src/main.zig --cache-dir /Users/hal/zig-hello-world/zig-cache --global-cache-dir /Users/hal/.cache/zig --name test --enable-cache 
error: the following build command failed with exit code 1:
/Users/hal/zig-hello-world/zig-cache/o/7b81da46e7e82f6a5397963128a4a2c2/build /opt/homebrew/Cellar/zig/0.10.1/bin/zig /Users/hal/zig-hello-world /Users/hal/zig-hello-world/zig-cache /Users/hal/.cache/zig test
```

**Comment on Observed Output**

While the compiler tells me what expression did not evaluate to true, it does not tell me what value sum had at that time. It would be great to have this information supplied by the compiler when it makes sense to do so.

### Expected Output

I'm proposing that an error message give more information on why the test failed on the simple cases. For the above case, I believe it would be an improvement to see this in the error output.

```
Couldn't match expected value `10: u8` to actual value `55: u8`
```

**expected error output**

```
Test [1/1] test.while with continue expression... FAIL (TestUnexpectedResult)
/opt/homebrew/Cellar/zig/0.10.1/lib/zig/std/testing.zig:347:14: 0x104dcc6f3 in expect (test)
    if (!ok) return error.TestUnexpectedResult;
             ^
/Users/hal/zig-hello-world/src/main.zig:23:5: 0x104dcc9cb in test.while with continue expression (test)
    try expect(sum == 10);
    ^
    Couldn't match expected value `10: u8` to actual value `55: u8`
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
/Users/hal/zig-hello-world/zig-cache/o/dd2360d564acd54512a670dfa33b00a3/test
error: test...
error: The following command exited with error code 1:
/opt/homebrew/Cellar/zig/0.10.1/bin/zig test /Users/hal/zig-hello-world/src/main.zig --cache-dir /Users/hal/zig-hello-world/zig-cache --global-cache-dir /Users/hal/.cache/zig --name test --enable-cache 
error: the following build command failed with exit code 1:
/Users/hal/zig-hello-world/zig-cache/o/7b81da46e7e82f6a5397963128a4a2c2/build /opt/homebrew/Cellar/zig/0.10.1/bin/zig /Users/hal/zig-hello-world /Users/hal/zig-hello-world/zig-cache /Users/hal/.cache/zig test
```

**other considerations**

when the error message gets unweildly, the compiler should say something like below. The compiler may have trouble printing complex types that for which the string representation is not possible or implemented yet.

```
Unable not print error hint [because resulting error message is too big | because X is not implemented on Y | some other reason ]
```

**Comment by mlugg** [comment]
This issue makes the false assumption that `std.testing.expect` is anything to do with the compiler.

`expect` is a completely normal Zig function in the standard library (unlike some other languages, there's virtually no special compiler integration with Zig's standard libarary code). Its implementation is very simple:
```zig
/// This function is intended to be used only in tests.
/// When `ok` is false, returns a test failure error.
pub fn expect(ok: bool) !void {
    if (!ok) return error.TestUnexpectedResult;
}
```

So when you say this (emphasis my own):
> While **the compiler** tells me what expression did not evaluate to true...

...you're making a false assumption about how it works. This might seem pedantic, but the difference is really important, because it means that what you're asking for isn't possible. The *only* thing the `expect` function receives as input is a `bool`; if it's `false`, it has no way of knowing why that is.

However, there *is* an alternative function which gives the output you want! It's called `expectEqual`:
```zig
var x: u32 = 5;
try expectEqual(@as(u32, 5), x);
```
(note that the argument order is `expected, actual`, which is a little unintuitive (#4437); it doesn't really matter if you get it wrong, but the error message will be confusingly worded.)
If the check fails - say, `x` was `6` - you'll get an error like this:
```
Test [1/1] test_0... expected 5, found 6
Test [1/1] test_0... FAIL (TestExpectedEqual)
/home/mlugg/.opt/zig/lib/std/testing.zig:78:17: 0x20ee09 in expectEqual__anon_1085 (test)
                return error.TestExpectedEqual;
                ^
/home/mlugg/test/thing.zig:4:5: 0x20eff2 in test_0 (test)
    try expectEqual(@as(u32, 5), x);
    ^
0 passed; 0 skipped; 1 failed.
```
Again, this is all implemented in completely standard Zig in the standard library, with no compiler integration. The `std.testing` namespace has a whole bunch of related functions, such as `expectEqualSlices` (for checking the *contents* of slices are equal), `expectEqualStrings`, `expectError`, etc.

You can find these functions by reading `std`'s source code (if you understand Zig it's genuinely not hard - unlike the standard libraries of languages like C++, the code is readable and not too far abstracted). If you prefer, you can try using the generated docs at https://ziglang.org/documentation/master/std - but bear in mind you'll likely encounter Autodoc bugs here and there.
