### ISSUE TITLE
Miscompilation on ReleaseFast when using std.rand.Random.uintLessThan backed by rdrand.

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [ziglang/zig#16084]
### Zig Version

0.11.0-dev.3644+496320d93

### Steps to Reproduce and Observed Behavior

I have observed an issue when using a value from std.rand.Random.uintLessThan(which is backed by rdrand) in the sense that the value passed to a function that puts it into struct receives an improper value(from looking at assembly it for some reason passes entire u16 uncapped by lessthan). This is ONLY observed in ReleaseFast. If you add a print statement before sending values into the function, the issue goes away in ReleaseFast too. This issue is not observed in Debug.

Please see the attached paste for minimal reproduction. That code contains is an application that will run and check uintLessThan return value using a function that passes a structure internally and immediately exit.
Please note that because this issue is only observed using randomness generator, sometimes the randomness roll will be within the bounds and will not crash the program.
The expected behavior for the minimal reproduction is to never crash regardless of the randomness roll.
Tip: To avoid having to spam zig build run -Doptimize=ReleaseFast in order to observe the miscompilation, you can wrap the code into a loop that will run 1000 times to ensure that you will hit a roll that makes the uintLessThan optimization produce incorrect value in another function.
* By crash I mean returning an error in main.

https://paste.sr.ht/~electrosssnake/139fad8a952c3d9e95d8c01c742db58ff2b556b7

### Expected Behavior

I expect std.rand.Random.uintLessThan pass value to a structure properly even on ReleaseFast and not requiring a print statement to stop incorrect behavior :)

**Comment by eLeCtrOssSnake** [comment]
Forgot important note, only the X value in the struct is improperly passed. The Y is correctly capped.

**Comment by jacobly0** [comment]
`[out] "=rax" (-> u64),` tells the compiler to pick any of a general purpose Register, the A register, or any sse register (X), to store the `u64` result.  Naturally, it picks a random register and then the code continues to clobber `rax` without telling the compiler about it.  The compiler continues to generate code as if `rax` was unchanged, and some other register was changed instead.

A proper asm statement looks like this:
```
    return asm volatile ("rdrand %[out]"
	: [out] "=r" (-> u64),
	:
        : "cc"
    );
```
Here we still let the compiler pick a random Register, but we actually output to the register that the compiler picked in the assembly code.  We also mark the Condition Codes (eflags) as being clobbered by `rdrand`, and use `volatile` so that the compiler knows that the assembly can output different values for the same inputs.
