### ISSUE TITLE
error.ArbitraryName should be rejected

### ISSUE THREAD

**Issue by ZigC-Lang** [ziglang/zig#16129]
### Zig Version

0.11

### Steps to Reproduce and Observed Output

```zig
const std = @import("std");
 
const e1 = error { ErrX };

pub fn main() !void {
    if (errorable(100)) |x| {
        std.debug.print("{}\n", .{x});
    } 
    else |e| {
        std.debug.print("{}\n", .{e});
    }
}

fn errorable(a: u8) !u8 {
    if (a < 10) {
        return a *% 3;
    } else { 
        return error.Errx; // Spelling Error of the error name
    }
}
```
--
error.Errx

### Expected Output

This code should be rejected, because 'Errx' is not a member of any error set.

**Comment by rohlem** [comment]
> This code should be rejected, because 'Errx' is not a member of any error set.

Strictly speaking, this is currently untrue: By mentioning it in reachable source code, it is put into the global `anyerror` error set.
Also, by returning it from a function with deduced error union type `!u8`, it becomes a part of that function's deduced return type `error{ErrX!u8}`.

The behavior you want can be achieved by explicitly specifying `errorable`'s return type to be `e1!u8`.

In status quo, if you want to sanitize the "global error set", I think it would be easiest to manually specify all errors
into a custom `GlobalError` type, and then specify the return type of `main` as `GlobalError!void`.
That way the compiler will immediately complain about any discrepancies due to typing errors.

---

From the way you stated this issue, it seems more a language proposal, for Zig to require every error name to also be present in an `error{...}` type expression.
I see two general issues with this (just my interpretation of your post):
1. Zig is designed around lazy evaluation: What isn't referenced in a compilation isn't analyzed.
   In the case of your example, `e1` isn't referenced from `main` nor `errorable`.
   This could be fixed by also requiring an explicit "usage", f.e. the no-op statement `_ = e1;`, somewhere in your code.
   However, note that this in fact isn't any less typing than explicitly specifying the error union return type, as you can already do in status-quo.
2. Currently error sets can be freely defined, conditionally used, and combined.
   As soon as we have two error sets, `error{a1, b2}` and `error{a1, c3}`, if we introduce a typing error into one of them,
   say we write `error{A1, c3}`, the compiler would now also silently recognize `A1` as correct.
   It could be argued that these error set definitions have less "surface area", i.e. give less opportunities for mistakes,
   but it would still be less ideal than explicitly specifying the error union return type.
