### ISSUE TITLE
my code stopped compiling with the new @min builtin function

### ISSUE THREAD

**Issue by iury** [ziglang/zig#16139]
### Zig Version

0.11.0-dev.3739+939e4d81e

### Steps to Reproduce and Observed Behavior

I've downloaded the latest dev build today and made a change to the new `@min` builtin, since the std.math.min is now deprecated but I can't get my code to compile in the same way.

here is a snippet to simulate the problem:

```
const std = @import("std");

pub fn main() !void {
    var rgb_color: u32 = 0xFFFF0000;
    var red: f32 = 1.0;

    var x = @as(u32, 0xFF);
    var y = @intFromFloat(u32, @floatFromInt(f32, (rgb_color & 0xFF0000) >> 16) * red);
    var z = @min(x, y) << 16;

    // if I inline the statements above then it won't compile.
    var _z = @min(@as(u32, 0xFF), @intFromFloat(u32, @floatFromInt(f32, (rgb_color & 0xFF0000) >> 16) * red)) << 16;

    std.debug.print("{}\n", .{ z, _z });
}
```

### Expected Behavior

shouldn't inlining `@min` to a single statement have the same result?

**Comment by mlugg** [comment]
This is caused by the [new semantics of `@min` and `@max`](https://github.com/ziglang/zig/issues/14039). These semantics cause the builtin to refine the result type as small as possible: for instance, `@min(my_u32, 255)` guarantees the result is in the range `[0,255]`, so the result can safely be a `u8`. If the value is runtime-known, we can still refine to the smallest operand type.

In your case, the inlining changes the behavior because it changes whether the first parameter to `@min` is comptime-known. In the non-inlined case, since `x` is in a `var`, it is not comptime-known, so the `@min` later can't refine the bounds any tighter than its type of `u32` allows. This means the `@min` also results in a `u32`, so can be shifted 16 bits. However, in the inlined case, the first argument to `@min` is comptime-known, so the expression will result in a `u8`, which can't be safely shifted by 16 bits (and if it could would give you an unexpected result). You'll note that if you change the definition of `x` to `const x = ...`, which allows its value to be comptime-known, you get an error on `z`.

In general, it's probably a good idea to annotate the result type of `@min`/`@max` when you rely on it later or (for e.g. bitwise operations like this one).

**Comment by iury** [comment]
understood. I've got confused because the signature given by the auto complete is `@min(a: T, b: T) T`, therefore if I passed two u32 then I expected to get a u32 back, so, maybe we should add a clarification in the description? regardless thank you for the quick response. I've managed to compile it now.

**Comment by mlugg** [comment]
Yeah, the langref needs updating there for sure. I'll make sure to sort that out soon, thanks for pointing it out!
