### ISSUE TITLE
Uniform array[a..b] syntax in runtime and compile time

### ISSUE THREAD

**Issue by Araminosian** [ziglang/zig#16184]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

``` zig
var array : [3]u8 = .{1,2,0}

// &array syntax shows that it is a pointer, that is ok
var pointer_to_array1 : *[3]u8= &array; 

// array[0..] looks like a slice, but it is a pointer, that is disappointing  
var pointer_to_array2 : *[3]u8 =array[0..]; 

// array[0..3] looks like a slice, but it is a pointer, that is disappointing  
var pointer_to_array3 : *[3]u8 =array[0..3]; 

//array[0..runtime_len] is a slice. That is clear. 
var slice : []u8 = array[0..runtime_len]; 
```

### Expected Behavior

``` zig
var array : [3]u8 = .{1,2,0}

// &array syntax shows that it is a pointer, that is ok
var pointer_to_array1 : *[3]u8= &array; 

// &array[0..] looks like a pointer, that is ok. array[0..] cause an error : "In comptime slices are backed on pointer to array. Use &array[0..] instead"
var pointer_to_array2 : *[3]u8 =&array[0..]; 

// &array[0..3] looks like a pointer, that is ok. array[0..3] cause an error : "In comptime slices are backed on pointer to array. Use &array[0..3] instead"
var pointer_to_array3 : *[3]u8 =&array[0..3]; 

//array[0..runtime_len] is a slice. That is clear. 
var slice : []u8 = array[0..runtime_len]; 
```

**Comment by InKryption** [comment]
This isn't an issue. `*[n]T` coerces to the equivalent or more-qualified `[]T`.

**Comment by Araminosian** [comment]
> This isn't an issue. `*[n]T` coerces to the equivalent or more-qualified `[]T`.

Issue that is very hard to understand this syntax.

**Comment by mlugg** [comment]
Not a bug. A pointer to an array is, in essence, a slice with a comptime-known length. That's why this isn't a counterintuitive behavior: a pointer-to-array is effectively a specialization of a slice, and you can for all intents and purposes just treat it as one.

Pointers to arrays are meant to support all operations slices do, so the distinction doesn't matter for most use cases. If you find an operation supported by slices but unsupported by pointers to arrays, *that* is likely a bug.
