### ISSUE TITLE
Adding whitespace in code changes assembly generation

### ISSUE THREAD

**Issue by ManDeJan** [ziglang/zig#1635]
Hi!, I was playing around with how to I could use Zig for embedded and noticed that if I changed whitespace in my code on godbolt compiler explorer, the assembly generation of the example sumOverArray function changed.

Here is the first example
https://godbolt.org/z/6WIsw3

In the second example I added a lot more whitespace:
https://godbolt.org/z/-ubWTs

As you can see adding this whitespace (or adding a comment) somewhere to the first example changes the assembly for the sumOverArray fucntion to use entirely different x86 vector registers.

It is as if adding a little extra whitespace made the compiler decide that it doesn't have the time to further optimize the sumOverArray function

**Comment by ManDeJan** [comment]
Interesting, as soon as I posted the two links the assembly on godbolt changed again so they are now the same, I will provide screenshots then to illustrate the issue

**Comment by ManDeJan** [comment]
example 1: [link](https://i.imgur.com/42Q1ZsI.png)
example 2: [link](https://i.imgur.com/OAMq0PM.png)

**Comment by andrewrk** [comment]
It's highly unlikely that this is a zig bug. Whitespace does not affect zig's AST or code generation. For this to be a bug report on ziglang/zig we need a way to reproduce it that does not include the possibility of it being a problem with Godbolt.

**Comment by andrewrk** [comment]
Btw I did notice that zig 0.3.0 and zig trunk have the same differences as in your screenshots. Only one `vextracti128` in the `LBB0_11:` label is what I get with a master build on my computer, and 2 `vextracti128` instructions in that label is what I get with zig 0.3.0.

So the godbolt bug could be that it accidentally used 0.3.0 instead of trunk or something like that.
