### ISSUE TITLE
CMake "add_library" for Zig in non-Zig build pipeline

### ISSUE THREAD

**Issue by binary132** [ziglang/zig#1653]
Hi.  If I were to use Zig to build a lib dependency in, say, a C++ project using CMake, how would I go about doing it?  Has anyone explored adding Zig as an option for CMake targets?

**Comment by andrewrk** [comment]
Zig has a command line interface just like C compilers. You can use cmake's custom command target. Even better than C/C++, since Zig has smallish (25MB) static builds, you could have cmake download+cache the zig compiler as part of the build, and have a 100% reproducible build, no dealing with users having different zig versions installed. (you can make this optional, or do it if the installed version is not new enough, etc)

I think the only thing that's missing is to have a way for zig to output a list of source files that it depends on, so that you could add those as dependencies in cmake. That would be pretty straightforward to add, since Zig already computes this list for its own cache.
