### ISSUE TITLE
PTR fail in while loop condition

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#16595]
### Zig Version

0.11.0-dev.4282+0f21d3d4d

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test {
    var good = false;
    while (foo() catch null) |_| {
        good = true;
        break;
    }
    try std.testing.expect(good);
}

fn foo() ![]const u8 {
    return "hello";
}
```

```
test.zig:5:18: error: expected optional type, found '[]const u8'
    while (foo() catch null) |_| {
           ~~~~~~^~~~~~~~~~
```

### Expected Behavior

all test pased

**Comment by mlugg** [comment]
This isn't actually a bug - `foo` has no path which returns an error, so its inferred error set is empty, so the RHS of the `catch` isn't analyzed, meaning the `null` isn't considered in type resolution. This can be a useful pattern (e.g. `foo() catch @compileError("there's an error now")`) but this is an unfortunate consequence of it.

**Comment by nektro** [comment]
hmm. that makes me wish it said `error: unreachable code` instead. as for the title issue, knowing that logic, i'd have to look back at my original code to see if that was indeed a representative reduction

**Comment by mlugg** [comment]
> that makes me wish it said `error: unreachable code` instead

That would make empty error set unions literally impossible to use. You have to `catch` the error to get at the underlying value, but the RHS of such a catch would always be unreachable. (I also just gave an example where this specific case is useful.)

Code which is known to be unreachable **due to semantic analysis** is ignored: this is an intentional and useful feature of Zig. It's the same thing as, for instance, a comptime-known `if` condition only analyzing the taken branch, and is core to Zig's lazy analysis model.

**Comment by rohlem** [comment]
> its inferred error set is empty, so the RHS of the catch isn't analyzed, meaning the null isn't considered in type resolution

So, more generally speaking, the type of `(runtime E!T) catch (runtime ?T)` depends on whether `E` is empty or not.
To me that seems a bit surprising, though the fix of inserting `@as(?T, )` it is manageable.
Would it be helpful (and realistically possible) for a type mismatch error such as this to point at a branch (within the local expression) that was discarded due to `comptime`-known decision value?

**Comment by bibo38** [comment]
The error indicates, that the compiler expects an optional value in the argument to the `while` loop, which is correct:
> When the |x| syntax is present on a while expression, the while condition must have an [Optional Type](https://ziglang.org/documentation/master/#Optional-Type).

(https://ziglang.org/documentation/master/#toc-while-with-Optionals)

If you want to iterate the string, you need a `for` loop!
