### ISSUE TITLE
bitCast (possibly) misreports size of arbitrary bit-width integer arrays

### ISSUE THREAD

**Issue by rsepassi** [ziglang/zig#16767]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```zig
test "bw" {
    // u8 works
    {
        const x: u48 = 1024; // 2**10
        const z: [6]u8 = @bitCast(x);
        // the 10th bit will be set to 1
        // so the 2nd bit in the 2nd u8 entry
        try std.testing.expectEqual(z[1], 4);
        for (0..6) |i| {
            if (i == 1) continue;
            try std.testing.expectEqual(z[i], 0);
        }
    }

    // u4 does not
    {
        const x: u48 = 1024; // 2**10
        const z: [12]u4 = @bitCast(x);
        // the 10th bit will be set to 1
        // so the 2nd bit in the 3rd u4 entry
        try std.testing.expectEqual(z[2], 4);
        for (0..12) |i| {
            if (i == 2) continue;
            try std.testing.expectEqual(z[i], 0);
        }
    }
}
```

```bash
$ zig env | grep target
 "target": "aarch64-macos.13.1...13.1-none"
$ zig test foo.zig
error: @bitCast size mismatch: destination type '[12]u4' has 92 bits but source type 'u48' has 48 bits
        const z: [12]u4 = @bitCast(x);
```

### Expected Behavior

For `[12]u4` to have 48 bits.

**Comment by rsepassi** [comment]
Possibly related to https://github.com/ziglang/zig/issues/14219

**Comment by der-teufel-programming** [comment]
Integer arrays aren't packed by default, u4 has 4 bits but takes up 1 byte in memory if I remember correctly

**Comment by rohlem** [comment]
As pointed out above, because `u4` has a native alignment `@alignOf(u4)` of `1` (in bytes), builtin arrays `[N]u4` take up more space.
The builtins `@bitSizeOf` and `@bitCast` currently react interestingly to this: They count full bytes for _all but the last_ element  (`@sizeOf([N-1]T)` in bytes, * 8 to convert to bits), which is added verbatim (`@bitSizeOf(T)`).
So `@bitSizeOf([N]u4)` = 8 + 4 = 12, and bit-casting from `[2]u4` to `u12` is allowed.

IMHO this is incorrect / confusing behavior, because the padding bits are converted to the new value verbatim.
At `comptime` they're 0, not sure about what the compiler decides will be done at run-time.

I think an `std.meta` function for bit-packing conversions between arrays would be useful.
I also think the language behavior of this should be reconsidered - though the easiest path forward would be to just disallow `@bitCast` on types with padding bits.
(Question: Is that the same concept as "undefined layout" types?)

**Comment by jacobly0** [comment]
Array elements are byte aligned to the alignment of the element type, so the size of an array has always been `array.len * @sizeOf(ElemType)`.

**Comment by rohlem** [comment]
@jacobly0 Is the interaction of the padding bits of all but the last array element (which participate in ` @bitSizeOf` and `@bitCast`, see my last comment) formally defined anywhere, or still open for discussion?
