### ISSUE TITLE
use vs pub use

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1680]
`use` statements bring the symbols from the module into the current scope, but `pub use` statements bring the module's symbols into the scope of whatever module `@import`s or `use`s that module. is this the intended behavior?

**Comment by tiehuis** [comment]
Yes this is the intended behavior. `use` is generally most useful for C libraries/wrappers which otherwise already namespace their functions anyway. It is generally recommend to avoid `use` where possible however as it affects compilation speed and also makes it less explicit about where specific symbols in the source are defined.

See here for an example of `pub use` which otherwise would require far too many imports: https://github.com/tiehuis/zig-sdl2/blob/master/src/index.zig
