### ISSUE TITLE
anonymous struct literal miscompilations

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#16862]
### Zig Version

0.12.0-dev.89+913511557

### Steps to Reproduce and Observed Behavior

The code below shows how using `var foo = .{ .field = ...};` and then passing `foo` by reference results in miscompilations.  In the first example, it just misbehaves, failing to perform an assign operation.  But in the second and third, it leads to a runtime segfault.

```zig
// /tmp/tmp4.zig
const std = @import("std");

// 1. doesn't actually assign the bitset
const BitSet = std.StaticBitSet(256);
const Class = struct { bitset: BitSet };
fn setBitset(class: *Class) void {
    class.bitset = BitSet.initFull();
}

// 2. segfaults at runtime
const Foo = struct { a: u8 };
fn setFoo(foo: *Foo) void {
    foo.a = 1;
    // Test [1/1] test_0... Segmentation fault at address 0x203a18
    // /tmp/tmp4.zig:13:8: 0x226ef4 in setFoo (test)
    //     foo.a = 1;
    //        ^
}

// attempt to make a simpler reproduction of 1.
// 3. segfaults at runtime
const Bar = struct { a: [4]usize };
fn setBar(bar: *Bar) void {
    bar.a = .{ 1, 1, 1, 1 };
    // Test [1/1] test_0... Segmentation fault at address 0x210a20
    // /tmp/tmp4.zig:25:8: 0x226b2c in setBar (test)
    //     bar.a = .{ 1, 1, 1, 1 };
    //        ^
}

test {
    var class = .{ .bitset = BitSet.initEmpty() };
    setBitset(&class);
    try std.testing.expectEqual(@as(usize, 256), class.bitset.count());

    var foo = .{ .a = 0 };
    setFoo(&foo);
    try std.testing.expectEqual(@as(u8, 1), foo.a);

    var bar = .{ .a = .{ 0, 0, 0, 0 } };
    setBar(&bar);
    try std.testing.expectEqual(@as([4]usize, .{ 1, 1, 1, 1 }), bar.a);
}
```

### Expected Behavior

I think using struct literals like this is supported.  If so, the above test should pass.

**Comment by travisstaloch** [comment]
My use case and the reason I discovered this was similar to the first example above.  It was difficult to track down and I spent a few hours wondering why my code wasn't working.  The fix was not using anonymous syntax but instead:
```zig
var class = Class{ .bitset = BitSet.initEmpty() };
````

2 and 3 above are my attempts to reproduce 1.

**Comment by mlugg** [comment]
This code should be a compile error for a slightly subtle reason related to anonymous literals.

In your test, `class`, `foo`, and `bar` don't have type annotations, so Zig doesn't know the exact type to give them. As such, it creates an "anonymous struct type" for them. These types look kind of like this:
```zig
const Class = struct { bitset: BitSet };
const Foo = struct { comptime a: comptime_int = 0 };
const Bar = struct {
    comptime a: struct {
        comptime comptime_int = 0,
        comptime comptime_int = 0,
        comptime comptime_int = 0,
        comptime comptime_int = 0,
     } = .{},
};
```
They're getting a bit of a mouthful towards the end, but the point is, they are not the same as your own types. (Even `Class`, which *appears* the same, is a distinct type, because Zig does not use structural equality for struct types.) These are "anonymous struct" types, which means they coerce to structurally equivalent types (this is to allow these inits to coerce to the type you're actually trying to construct). So I think what the compiler's getting wrong here is that it's allowing the coercion from `*T` to `*S` where `T` is an anonymous struct type which can coerce to `S`: that transformation isn't valid.

The fix in your code here is just to annotate the types of your variables:
```zig
var class: Class = .{ .bitset = BitSet.initEmpty() };
// ...
```
(this is exactly equivalent to typed initializations, `var class = Class{ .bitset = BitSet.initEmpty() }`)

**Comment by travisstaloch** [comment]
Thanks!  That makes a lot of sense.  I can see why this should be a compile error now.  This seems like a common footgun for many users due to the anonymous init syntax being fewer characters.

**Comment by mlugg** [comment]
No worries, glad it made sense! As a general rule, Zig's type inference is quite localized. For instance, it'll never reach across statements in a block to infer the type of a variable, which is sort of what you wanted here. For a `const` or `var`, the type is inferred using only the initialization expression; for cast builtins which infer their result type (like `@intCast`) the result comes from local information in the same expression; etc.
