### ISSUE TITLE
Valid base64 doesn't decode properly

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#16942]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    var buf: [4096]u8 = undefined;
    try std.base64.standard.Decoder.decode(&buf, data);
}

const data = "Cxgg/wwZIf8NGiL/DRoi/wwZIf8LGCD/Cxgg/woXH/8KFx3/Chcd/wsYHv8LGB7/Cxge/woXHf8JFh3/CRYd/wkWH/8JFh//CxUe/wwVHv8QFx//FRwj/xgdI/8WGyH/Exkf/xIZIP8QGSL/Dhgi/w0YIv8LGSL/Chgj/woXIf8KFyD/Chcg/wkWH/8JFSD/CBQg/wYUH/8GFB//BhQf/wYUH/8JFiD/DBki/w0aI/8OGyP/DBkg/wwZH/8MGSH/Cxgh/woXH/8JFh7/CBUd/wgVHf8KFx7/Cxge/wkWHP8HFBr/BhMa/wYTG/8HFB3/CBUe/wcTHv8HFB7/CRMb/wkVG/8HFBr/BhQZ/wUUGf8GFRr/BhUa/wYUGf8GExn/Aw8V/wMME/8HEBf/AgsS/wQNE/8HEBX/Bg4U/wYNFf8FDBT/AwoS/wYME/8LEBb/DBEX/w4TGf8RFhz/DxQa/wwRFv8LEBb/ChAW/wcOFP8FDBL/AwoQ/wYNFf8GDRb/BQ0V/wMME/8EDhT/CBMX/wwXGf8PGhz/Dhse/wwaHf8JFxr/CBYZ/woYGv8NGxv/ER4e/xUhIP8XIyP/FiIi/xIeH/8SHR//EiAi/xQiJf8RHiT/Cxge/wgVG/8IFRv/CBUb/wkWHP8JFhr/CRca/wcVFv8GFBX/DRoi/w0aIvP=";
```

### Expected Behavior

This should decode. I tested decoding in:

- Ruby
- Python
- PHP
- Go

And it succeeds in all.

Note the data is some garbage binary, its actually a chunk of relatively meaningless RGB data. But it is valid.

**Comment by mitchellh** [comment]
FYI talking with @jacobly0, this base64 has invalid padding. The other implementations don't seem to care. I think its reasonable to ask if Zig's base64 decoder should have a "relaxed" decoding mode to follow suit. This data in particular is from a 3rd party application and I'm expected to decode it without error... I can validate the data later because it is meant to be a valid PNG in addition to its pixel data matching the dimensions and bit depth it advertises.

So I'm forced at the moment I think to copy/paste the Zig impl and delete these checks.

**Comment by jacobly0** [comment]
Indeed, the padding is valid as most decoders verify it (aka the number of `=` characters is correct), however there can be trailing bits that are defined to be encoded as zeroes, and the zig decoder notices this and returns `error.InvalidPadding`.

However, after looking at the implementation, the only errors that can occur before the payload has been fully decoded are the initial `error.InvalidPadding`, which can be fully worked-around by not specifying a `pad_char`, `error.InvalidCharacter`, which already has a fully functional workaround by using `Base64DecoderWithIgnore` instead (in theory you could pass every character not in the selected alphabet).

The rest of the possible errors are detected after the payload has already been fully written to `dest`, and so in the case that you know these errors to be non-fatal for your use-case, is seems perfectly reasonable in a language like Zig to special case ignore `error.InvalidPadding` and continue on (hopefully with a comment about accepting invalid input).

I think the only reasonable improvements that could be made to the standard library are specifically documenting this use case to make sure that the payload is always fully decoded before these errors are checked in the future, or even better, adding test cases that specifically test these sorts of invalid input, expect the error, and then proceed to verify the full output.  Closing, as I consider ignoring the error a sufficent workaround, but can reopen if anyone shows interest in making these changes to track that.

**Comment by jedisct1** [comment]
The encoded string includes bits that are set, but can't be decoded into a valid sequence. No base64 encoder will ever produce such a string. 

The standard MacOS `base64` tool refuses to decode it:

```sh
base64: stdin: (null): error decoding base64 input stream
```

Crypto libraries refuse it, as malleability is not an expected property, and can have security implications. If a signature is base64-encoded, it means that an adversary can trivially find equivalent signatures. That would be catastrophic in a blockchain.

Rust's `ct-codec` crate refuses it.

Python only accepts it if the `validate` parameter is set to `True`. Otherwise, it's rejected as well.

Intuitively, most people expect `base64_encode(base64_decode(x))` to be idempotent, just like hex encoding. 

IMHO, implementations violating that expectation and silently ignoring these bits are buggy. I also don't think they do it intentionally. It's rather an inheritance from legacy implementations that were copy&pasted or translated to multiple languages, or a case that was unintentionally forgotten.

If bits that cannot be decoded are present in the encoded string, either there's a bug in the application having created it (once again, no base64 encoder can produce such a string), or the string has been specifically crafted for an attack.

In either case, I don't think adding an option to accept invalid strings would be a good thing.
