### ISSUE TITLE
The behaviour of `addCSourceFile` has changed in Windows

### ISSUE THREAD

**Issue by kimmolinna** [ziglang/zig#16946]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

You have to write
```
shell.addCSourceFile(.{
            .file = std.build.LazyPath.relative("tools/shell/shell.c"), 
            .flags = &.{}
            });
```

### Expected Behavior

`shell.addCSourceFile("tools/shell/shell.c", &.{})` should still work. Compare it to behaviour of `addCSourceFiles`.

**Comment by rohlem** [comment]
That's not a bug, but an intentional API change introduced in https://github.com/ziglang/zig/pull/16446 .
I didn't check, but see no reason to believe this would in any way be related to Windows (as either host or target OS) either.

I think the reason it wasn't done to `addCSourceFiles` is that it's a convenience wrapper for a list of multiple files that are non-lazy file paths.
If you already have `LazyPath` objects, looping over them and calling the singular version isn't too much of a burden (as opposed to converting `[]const []const u8` to `[]const []std.Build.Step.Compile.CSourceFile` or what the exact type is).

If you want you can advocate for, propose, or even PR a utility function accepting a `[]const u8` instead. I personally wouldn't mind, but be aware that it might not be accepted.
