### ISSUE TITLE
Langref: document switch capture |value, tag|

### ISSUE THREAD

**Issue by ityonemo** [ziglang/zig#17009]
this (main language syntax) feature for switching over tagged unions is currently undocumented.

Example

```zig
switch (u) {
    .a, .b => |value, tag| {
      _ = value;
      _ = tag;
    }
}
```

**Comment by mpfaff** [comment]
Just leaving my anecdotal justification for documenting this in case anyone cares:

When I first learned about this syntax, I found it counter-intuitive. When I think about tagged unions, or algebraic data types in general, I picture it as `(tag, union)` (which is not necessarily true in memory, but makes sense conceptually because you need to know the tag before you can use the data), and so I would often get the order of the variable bindings reversed.

With that being said, it certainly makes more sense in terms of clarity of syntax and possibly implementation complexity for the optional parameter to be second, rather than the presence of a second parameter changing the meaning of the first.

**Comment by robinheydon** [comment]
I'm happy to work on this. Please set me as the assignee.

**Comment by mlugg** [comment]
We do not generally set assignees on issues, particularly for contributors who are not core team members. Feel free to work on this and PR it, but the issue will not get assigned to you in the meantime.

**Comment by robinheydon** [comment]
Actually - this is already in the docs. It was added by Vexu in commit (17eea91)[https://github.com/ziglang/zig/commit/17eea918aee98ca29c3762a7ecd568d2f14f66ef].

I think this issue can be closed.

**Comment by robinheydon** [comment]
I've create a [PR](https://github.com/ziglang/zig/pull/18524) for this.

**Comment by thyecust** [comment]
This issue could be closed since https://github.com/ziglang/zig/pull/18524 is merged.
