### ISSUE TITLE
Compile-Time Pointer Evaluation Miss

### ISSUE THREAD

**Issue by pascaldekloe** [ziglang/zig#17028]
### Zig Version

0.12.0-dev.17+49244dc0c

### Steps to Reproduce and Observed Behavior

The following code fails on the `@compileError` check.

```zig
test "compile-time pointer check" {
    var x: usize = 0;
    f(&x);
}

fn f(p: *usize) void {
    if (p.* != 0) @compileError("initial value not zero");
}
```

### Expected Behavior

The example should either compile or explain why it can't evaluate p.

**Comment by nektro** [comment]
this fails because `p` is not marked `comptime` and is not a comptime-only type and so `f` runs at runtime, triggering the `@compileError` to be analyzed and raised

**Comment by pascaldekloe** [comment]
If p needs to be a `comptime` argument to work, then the compiler should state so (instead of failing).

**Comment by rohlem** [comment]
> If p needs to be a `comptime` argument to work

The main issue is that when the compiler encounters `@compileError` in an evaluated branch, it doesn't ask "why have I chosen this branch" (which may be arbitrarily many branches and functions deep), it just reports the compile error.
Under current semantics the code does "work" in that triggering the `@compileError` for the runtime branch is a **feature** asserting the behavior of your code. You can use `@compileError` when you **want** to be informed of this branch ends up being compiled (because you intend it not to be).

Upon seeing the compile error, if you intended the condition to be evaluated at compile time, you can express this using the `comptime` keyword:

```zig
fn f(p: *usize) void {
    if (comptime p.* != 0) @compileError("initial value not zero"); // add `comptime` keyword
}
```

With this updated code, the compiler now understands that you want compile-time evaluation instead, and explains quite why it can't do that:

```
main.zig:7:22: error: unable to evaluate comptime expression
    if (comptime p.* != 0) @compileError("initial value not zero");
                 ~~~~^~~~
main.zig:7:19: note: operation is runtime due to this operand
    if (comptime p.* != 0) @compileError("initial value not zero");
                 ~^~
referenced by:
    test.compile-time pointer check: main.zig:3:5
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

So the next step is to mark non-comptime variables/constants involved (here `p`) as `comptime` - if that is what you want (which would also require you making `x` in `main` a `comptime var` - it's no longer a runtime variable).

If you instead want to keep the condition to be evaluated for a runtime value, then `@compileError` isn't the right tool - you would probably instead want `unreachable` (also provided via `@import("std").debug.assert`).

**Comment by pascaldekloe** [comment]
> You can use @compileError when you want to be informed ifthis branch ends up being compiled …

When you put it like that, the behaviour as seen totally makes sense now. 😀 I just saw `@compileError` as a safety measure to ensure the check won't sneak into runtime.

The documentation of @compileError states “This function, when semantically analyzed, causes a compile error with the message msg.” at the moment. This is too technical for me to understand. If more people feel the same, then perhaps we should document it with something like "This function causes the compiler to fail with msg if it is not optimized away. As such, this method can be used to verify `comptime` values only.”.

**Comment by mlugg** [comment]
Documentating it like that would be unclear and, in fact, incorrect. The semantics of comptime evaluation aren't really anything to do with "optimizing away" branches: comptime *can* be used to guarantee certain optimizations, but that's definitely not the primary use case, and values which are not semantically comptime-known may still be obvious to the actual optimizer.

You can think of an expression "being semantically analyzed" as essentially just meaning "the compiler looks at it". When a condition is comptime-known, the compiler only "looks at" the taken branch, while if it's runtime-known, the compiler has to look at both branches. The lamgref could do well to clarify this meaning if it doesn't already.

Lastly, "this method can be used to verify comptime values only" would be very weird to write in the documentation, because it implies `@compileError` is intrinsically related to validating values, which is absolutely not true. In fact, I much more commonly use it to mark TODOs for myself, or to assert that certain code paths are unreachable (e.g. `errdefer @compileError("bad")` ensures there are no errors past one point in a function).

**Comment by pascaldekloe** [comment]
Sure @mlugg. So how would you describe the behaviour correctly without "semantically analyzed"?
