### ISSUE TITLE
stdlib suggests using selfExePathAlloc instead of selfExePath on wasi even though the former calls the latter

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#17085]
### Zig Version

0.12.0-dev.278+0e8f130ae

### Steps to Reproduce and Observed Behavior

attempt to use `std.fs.selfExePath` with wasi as the target OS
met with error message `std.fs.selfExePath not supported for WASI. Use std.fs.selfExePathAlloc instead.`
https://github.com/ziglang/zig/blob/b0d9bb0bb844cb647942f7f1e3e7d06fc12e8df6/lib/std/fs.zig#L3072
use `selfExePathAlloc` as suggested but same error
https://github.com/ziglang/zig/blob/b0d9bb0bb844cb647942f7f1e3e7d06fc12e8df6/lib/std/fs.zig#L2977

### Expected Behavior

compile error should give a correct message

**Comment by squeek502** [comment]
The `Use std.fs.selfExePathAlloc instead.` part of that compile error is obsolete and should be removed.

Here's where the compile error was added along with some special casing in `selfExePathAlloc`:
https://github.com/ziglang/zig/pull/11024/commits/922d8378e724063063e709223e90e3a577e4566a

And here's where that special casing was moved outside the standard library since it was Zig-specific:
https://github.com/ziglang/zig/pull/11469

And here's the reasoning:
https://github.com/ziglang/zig/pull/11024#discussion_r852467808

Side note: I'm not sure it's possible to implement `selfExePath` for WASI.
