### ISSUE TITLE
Possible compiler bug in handling of comptime conditionals

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#17106]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

When compiling this code
````
pub fn bind_text(comptime T: type, stmt: *s.sqlite3_stmt, column: c_int, value: T) void {
    if (T == []const u8) {
        const buffer_size: u8 = 128;
        const buffer: [buffer_size:0]u8 = undefined;
    }
    var result_code: c_int = s.sqlite3_bind_text(
        stmt,
        column,
        if (T == [:0]const u8 or T == [:0]u8)
            &value[0]
        else if ((T == [*:0]const u8) or (T == *const u8) or (T == [*c]const u8))
            value
        else if (T == []const u8) {
            blk: {
                if (value.len >= buffer_size)
                    panic("bind_text: buffer too small to hold null-terminated value\n", .{});
                @memcopy(buffer[0..value.len], value);
                buffer[value.len] = null_char;
                break :blk &buffer[0];
            }
        } else panic("Bind-text called with invalid type: {s}", .{@typeName(@TypeOf(value))}),
        -1,
        s.SQLITE_STATIC,
    );
    if (result_code != s.SQLITE_OK) {
        panic("bind_text failed. Result code was {d}, column was {d}", .{ result_code, column });
    }
}
````
I get the following errors:
````
zig build-exe  --verbose-link --main-pkg-path .. -fsingle-threaded -I/usr/include  -lc -lsqlite3 vanguard_importer.zig
/usr/home/dca/Software/newcash_c/zig_library/library.zig:180:15: error: unused local constant
        const buffer: [buffer_size:0]u8 = undefined;
              ^~~~~~
/usr/home/dca/Software/newcash_c/zig_library/library.zig:191:34: error: use of undeclared identifier 'buffer_size'
                if (value.len >= buffer_size)
                                 ^~~~~~~~~~~
````
The first line of code is line 177.

This occurred on a FreeBSD 13.2 system. I built zig from the source code on 9/3.

### Expected Behavior

I think this function should compile without error. The 'if' at line 178 should cause the definitions
of buffer and buffer_size to be emitted and the 'if' at line 189 should cause the block labeled 'blk' to be emitted, that reference 'buffer' and 'buffer_size'.

Perhaps I've missed something, but I don't understand why these errors are occurring.

**Comment by nektro** [comment]
`buffer` is being reported as unused because its definition is scoped to the `if` block

**Comment by donaldcallen** [comment]
I don't think that's correct. The if block to which you refer is part of a comptime conditional. The block should not appear in the generated code. See the comptime documentation in the Language Reference. Particularly test_comptime_max_with_bool.zig:
````
fn max(comptime T: type, a: T, b: T) T {
    if (T == bool) {
        return a or b;
    } else if (a > b) {
        return a;
    } else {
        return b;
    }
}
test "try to compare bools" {
    try @import("std").testing.expect(max(bool, false, true) == true);
}
````
And then compiler_generated_function.zig, which shows the code generated by the above:
````
fn max(a: bool, b: bool) bool {
    return a or b;
}
````
The block surrounding the 'return' is gone.

**Comment by Vexu** [comment]
Unused identifiers are detected before any comptime logic is run.

**Comment by rohlem** [comment]
```zig
if (T == []const u8) {
        const buffer_size: u8 = 128;
        const buffer: [buffer_size:0]u8 = undefined;
}
```
> The 'if' at line 178 should cause the definitions of buffer and buffer_size to be emitted

These constants are indeed "emitted", as in they exist, but as @nektro pointed out, only within this `if` scope.
Zig scopes variables and constants not to the function, but to the inner-most block they appear in.
This shouldn't be an issue for your use case however, because if a constant (or variable) ends up as unused in a particular instantiation, the compiler is (or at least should be) smart enough to elide it, as if it hadn't been declared at all.

(The error that is actually generated hints at this fact: `unused local constant`, because the if-block closes without any uses of `buffer`. This is certainly wrong, because it's impossible to refer to `buffer` from outside of the block.)

The solution is to simply move the two declarations out of the if-block; that block is wholly unnecessary:

```zig
pub fn bind_text(comptime T: type, stmt: *s.sqlite3_stmt, column: c_int, value: T) void {
    if (T == []const u8) {
        const buffer_size: u8 = 128;
        const buffer: [buffer_size:0]u8 = undefined;
    }
    // rest of the function ...
}
```

**Comment by mlugg** [comment]
Put differently, the point is that variables are scoped syntactically, based on the block (`{ ... }`) they're in. Comptime evaluation is never involved here.

**Comment by donaldcallen** [comment]
I simply cannot reconcile the points that all of you are making with my quotations from the Language Reference, which says that code that is in a prong of a comptime 'if' that is satisfied is emitted inline. The block surrounding that code is a *comptime* block and is not emitted into the runtime code, according to the documentation, those const declarations should be in the scope of the function block.

But it appears from what you are all saying that variable declarations are independent of comptime logic. I must say I find this bizarre from a language design standpoint. And I would ask one of you to point me to where this is discussed in the documentation. You seem to know how the compiler handles this; I'd like to know how you learned it.

And thank you to all for trying to help me understand what is going on here.

**Comment by Vexu** [comment]
Unused identifiers are not allowed in false branches in the same way as syntax errors are not allowed. It seems like unused identifiers are not even mentioned in the langref.

**Comment by rohlem** [comment]
[The relevant section of the langref](https://ziglang.org/documentation/master/#Compile-Time-Parameters):

> This works because Zig implicitly inlines `if` expressions when the condition is known at compile-time, and the compiler guarantees that it will skip analysis of the branch not taken.

AFAICT this is an oversimplification, and effectively wrong.
The condition, if `comptime`-evaluated, is replaced by its result.
Blocks matter to the semantics of the language, due to scoping of names and `defer/errdefer` statements.

```zig
comptime {
  comptime var a = 0;
  if (true) {
    defer a += 1;
  } //defer runs here
  if (a != 1) unreachable; // does not trigger
}
```

When you see a block (braces `{ }` that aren't an aggregate literal `.{ }`), you can be sure of the end of that block.
`comptime` will never inline it into its parent block. The langref is wrong in this regard and needs to be corrected.

(Another error in the phrasing here is the fact it talks about `if` _expressions_, when the surrounding code only contains `if` _statements_ (guarding non-expression blocks).)

**Comment by mlugg** [comment]
@rohlem's comment is good - I do think the langref phrasing here is a bit poor. But I was partway through writing this comment, so here it is anyway:

> I must say I find this bizarre from a language design standpoint.

Why? Any language that I can think of which has local variable scoping decides scopes based on syntax like this. For instance, consider this C code:
```c
{
    int x = 123;
}
x = 456;
```
This is clearly invalid. The block at the top here may not actually "emit a block" (for some definition of that; it's not like blocks exist in machine code!) in many C compilers, but this code is still invalid, because syntactically, `x` is scoped within the block, and can't be accessed from outside of it.

Zig comptime aims to effectively be as unsurprising as possible. So, if a condition happens to be comptime-known, we don't really want that to be able to *cause* compile errors. Consider this code:
```zig
if (foo) {
    var x: u32 = 456;
    _ = x;
}
var x: u32 = 123;
```
If this worked how you expected, it would be a compile error if `foo` was comptime-known, and not otherwise, which would be quite confusing!

When the langref says that "Zig implicitly inlines `if` expressions", it doesn't mean the entire block is inlined. It just means that effectively, the whole `if` statement is replaced by its body: the block itself remains. So, if you want to think of this in terms of comptime evaluation "rewriting" Zig code (which isn't really accurate, but works as a loose analogy):
```zig
if (true) {
    var x: u32 = 123;
}
x = 10;
```
...becomes...
```zig
{ // the block is still here!
    var x: u32 = 123;
}
x = 10;
```

**Comment by donaldcallen** [comment]
@mlugg What you persist in ignoring in what I have written is that if you believe the Language Reference (which is apparently a bad idea), comptime blocks are not the same as blocks in the emitted code.

You don't need to explain lexical scoping to me. I've been doing this for a *very* long time and have written a ton of Scheme (and C) over the last 40 or 50 years. Jerry Sussman and Guy Steele are old friends.

The issue, again, is that the comptime logic as presented in the Language Reference looks a lot like macro processing in Scheme or using m4 or the C pre-processor. The comptime logic runs, spits out some code that gets fed to the compiler. That's the simple-minded model the Lang Ref would have you believe and is apparently wrong.

And you say "When the langref says that "Zig implicitly inlines if expressions", it doesn't mean the entire block is inlined. It just means that effectively, the whole if statement is replaced by its body: the block itself remains." Look again at the quotes I provided from the Lang Ref. According to them, the whole if statement is *not* replaced by its body; the block does *not* remain. Now I'm not arguing that you are wrong, because the behavior I'm seeing says you are right. I'm arguing that the documentation is wrong.

I think it is quite clear that my error was trying to use zig for real work before it is ready. Yes, I've seen the warnings, but I was hopeful that after the years of work that have been devoted to this project, I might have gotten away with ignoring the warnings. I am not saying this in a negative way -- I've built a lot of software in my long career and it's not ready until it's ready. And the project has not been deceptive about this. But it seems that it still isn't ready. I've said it before in posting other issues that not enough attention has been paid to zig's documentation. It's essential that the documentation be clear and accurate even during development, in my opinion. Otherwise, people will just get frustrated and you will lose your testers.

Again, thanks for the help.

**Comment by mlugg** [comment]
> Now I'm not arguing that you are wrong, because the behavior I'm seeing says you are right. I'm arguing that the documentation is wrong.

Yes, okay, that code example probably ought to retain the enclosing block for clarity. (However, I've never actually seen anyone confused by its omission: I think this behavior is more reasonable than you believe, and wasn't even something I thought about when I learnt Zig myself, because the answer seems fairly clear.)

> I think it is quite clear that my error was trying to use Zig for real work before it is ready.

Yes, if this kind of minor documentation issue/ambiguitiy is a genuine roadblock to using the language for you, then it's definitely not going to be reasonable for you to use until 1.0 - and that's okay, this isn't meant to be snarky!

> It's essential that the documentation be clear and accurate even during development, in my opinion.

I'm going to disagree with this. Good documentation is always desirable of course, and as we approach 1.0 we definitely need to put much more work into it, but ensuring the documentation is perfect for every single release would take up a huge amount of time which could instead go towards genuine progress on the language and the compiler. That seems much more desirable, particularly since a lot of documentation you'll write becomes out of date maybe a few months later.

**Comment by donaldcallen** [comment]
"Yes, okay, that code example probably ought to retain the enclosing block for clarity."

No, not for clarity -- for ACCURACY.

(However, I've never actually seen anyone confused by its omission: I think this behavior is more reasonable than you believe, and wasn't even something I thought about when I learnt Zig myself, because the answer seems fairly clear.)"

Well just because you haven't seen it doesn't mean it hasn't happened. Whether those braces get included in the emitted code is crucial and the document leads you completely astray.

"Yes, if this kind of minor documentation issue/ambiguitiy is a genuine roadblock to using the language for you, then it's definitely not going to be reasonable for you to use until 1.0 - and that's okay, this isn't meant to be snarky!"

Being completely wrong is a "minor documentation ambiguity"?? You and I see the world in very different ways.

Ok, I'm done with this. See you when zig is released. Maybe.
