### ISSUE TITLE
Strange behaviour occurred for cyclic type functions calls

### ISSUE THREAD

**Issue by lovely-error** [ziglang/zig#17191]
### Zig Version

0.11.0 (also checked it on 0.12.0-dev.378+4f952c7e0
 and got identical outcome)

### Steps to Reproduce and Observed Behavior

Zig compiler refuses to handle this lil snippet 😬
```
fn fooo1(comptime T:type) type {
    return struct {
        header: struct {
            ptr: fooo2(fooo1(T))
        }
    };
}
fn fooo2(comptime T:type) type {
    return std.meta.Int(std.builtin.Signedness.unsigned, @bitSizeOf(T));
}
test {
    const T = fooo1(u8);
    const fake : T = undefined;
    if (@sizeOf(T) != @sizeOf(@TypeOf(fake.header))) @compileError("booo");
}
```
It throws this error 
```
error: struct 'driver.fooo1(u8).fooo1(u8)__struct_1062' depends on itself
```
This doesn't make sense because:
1) when I replace definition of fooo2 with this...
```
return ?*T;
```
...compiler accepts it just fine.
2) The code I provided is somewhat representative of this rust snippet: 
```
struct Foo1<T>(T);
struct Foo2<T>(std::marker::PhantomData<T>, usize);
struct Cyc(Foo2<Foo1<Cyc>>);
```
...which is accepted by stable recent rustc 

### Expected Behavior

Zig should compile my code

**Comment by IntegratedQuantum** [comment]
The size of your type is defined recursively:

You want a type `fooo1(u8)` that contains an integer `fooo2(fooo1(u8))` that has the same size as `fooo1(u8)`.
But the size of `fooo1(u8)` depends on it's content:
 `fooo1(u8)` contains an integer `fooo2(fooo1(u8))` that has the same size as `fooo1(u8)`.
But the size of `fooo1(u8)` depends on it's content....

It works when you use `?*T` because the size of a pointer is always 8 bytes(on 64 Bit) regardless of the content. So the recursion breaks.

The given rust snippet also works for a similar reason: `PhantomData<T>` has size 0, and usize always has a size of 8 bytes.

**Comment by lovely-error** [comment]
Oh, you're right. Got it now 👀
