### ISSUE TITLE
Bitshift reads shift-distance as u3, when shifting a variable.

### ISSUE THREAD

**Issue by Banacial** [ziglang/zig#17201]
### Zig Version

0.12.0-dev.414+461036069

### Steps to Reproduce and Observed Behavior

```
const std = @import("std");

pub fn main() void {
    const max_u8: u8 = std.math.maxInt(u8); // == 255
    const shifted = max_u8 << 16;
    std.debug.print("{}", .{shifted});
}
```
Results in: 

```
C:\Users\7743l\OneDrive\Zig2\Apps\Documentation\test.zig:5:31: error: type 'u3' cannot represent integer value '16'
    const shifted = max_u8 << 16;
                              ^~
referenced by:
    callMain: C:\Users\7743l\OneDrive\Zig2\Zig_w_x86_64_0.12.0-dev.414\lib\std\start.zig:564:17
    initEventLoopAndCallMain: C:\Users\7743l\OneDrive\Zig2\Zig_w_x86_64_0.12.0-dev.414\lib\std\start.zig:508:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces 
```

### Expected Behavior

Expected the value to be shifted, resulting in 16711680

When replacing the variable with the actual value it works:

```
const std = @import("std");

pub fn main() void {
    //const max_u8: u8 = std.math.maxInt(u8); // == 255
    const shifted = 255 << 16;
    std.debug.print("{}", .{shifted});
}
```

**Comment by mlugg** [comment]
`max_u8`, as annotated, has type `u8`, which is a fixed-width 8-bit unsigned integer. Fixed-width integers can only be shifted by valyes below their bit width - in this case that means you can only shift a `u8` 7 bits or less.

In C, performing a shift outside of these bounds is UB(*); in Zig, we have better type safety for it, by making the RHS of shift operators be the "log-2 integer type" of the LHS. In this case, `u3` can store the values 0 through 7, so gives perfect type safety.

In order to shift a value by a bit count larger than its type's bit size, you need to first coerce the LHS to a larger integer type, such as `u32`. You can do this with `const shifted = @as(u32, max_u8) << 16;`.

_(*): you wouldn't actually run into this UB in C in this specific case due to its integer promotion rules, but you could when trying to shift a value by over 32 bits._
