### ISSUE TITLE
Use a better random range implementation

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#1721]
(Thanks to @tommyettinger in https://github.com/ziglang/zig/pull/1578#issuecomment-438200151 for bringing this up.)

The standard library should use a better implementation for `uintLessThan()` and provide an implementation for `uintLessThanBiased()` using the algorithms described here: http://www.pcg-random.org/posts/bounded-rands.html

**Comment by tommyettinger** [comment]
I like the idea of separate biased and unbiased algorithms, and I should note that even when there is bias, it usually takes an extremely large number of results to show it. I'm inclined to prefer biased implementations because they use a fixed number of calls to the generator, so their speed is predictable and they have the same effect on a random number generator's state as a call that just generates a 32-bit uint. Lemire's integer multiply technique seems optimal both with and without debiasing: (pseudocode) `((cast randomU32() to u64) * bound) right-shifted by 32`, or `(instruction_that_does_a_64_bit_multiply_on_32_bit_operands randomU32(), bound) right-shifted by 32`. I've only really tested this for bias with a test that imitates 64x64->128-bit multiplication in Java (which has no 128-bit numbers), and if a number shows up one less time over 2 to the 64 results, it usually isn't detectable because I can't produce 2 to the 64 random values in a reasonable timeframe. There may be noticeable bias with 32-bit results only on some bounds, possibly very high ones, but I don't know for sure. I don't know whether the default should be unbiased (which takes variable amounts of time per call, due to rejections) or biased (which is unsuitable for tasks where the probability must be perfectly fair, due to favoring some results), but having both available is a strength that other languages/platforms don't usually acknowledge.
