### ISSUE TITLE
CLI: default `zig <path>` to be `zig run <path>` to allow drag-and-drop execution on Windows

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17212]
On windows, if you drag and drop a file onto an executable, it is equivalent to running `<exec file> <dropped file>`. 

This is particularly useful for the “teach your friend to code” use cases where the quick-start instruction boils down to:

1. Download and extract zig
2. Write your Hello World and drop it onto zig.exe

I know ideally one should teach the “proper way” starting off learning how to use the CLI or IDE, but I think reducing these kinds of minute “gateway friction” really goes a long way in minimizing the initial intimidation factor esp for those who are *not yet* technically inclined. 

Zig being relatively “small” is ideal as a first language so I think there is a great opportunity here to polish some of these trivial details that are typically overlooked in other languages.

**Comment by andrewrk** [comment]
I've already thought a lot about this and decided against it. For the "teach your friend to code" use case, what I think should happen is the VSCode Zig extension should automatically install zig for you and walk you through creating an application. Ideally it would even have a template for gui programming so that new programmers don't have to learn about terminals.
