### ISSUE TITLE
packed struct @sizeOf 

### ISSUE THREAD

**Issue by User65-87-11** [ziglang/zig#17246]
### Zig Version

0.12.0-dev.278+0e8f130ae

### Steps to Reproduce and Observed Behavior

Shouldn't the packed struct have the same size as a sum of subtypes ? 
the @sizeof (struct) != @sizeOf(u32) +@sizeOf(u16)
```

test "Hello @Sizeof" {
    const s1 = packed struct {
        a: u32,
        b: u16,
    };

    const s2 = packed struct {
        a: u8,
        b: u16,
    };
    print("sizeof : s1:{d}, s2:{d}\n", .{ @sizeOf(s1), @sizeOf(s2) });
    
       try std.testing.expect(@sizeOf(s1) == @sizeOf(u32) + @sizeOf(u16));
    try std.testing.expect(@sizeOf(s2) == @sizeOf(u8) + @sizeOf(u16));
}
```

// @Sizeof... sizeof : s1:8, s2:4

### Expected Behavior

  const s1 = packed struct {
        a: u32,
        b: u16,
    };
    
    @sizeOf(s1) == 6

**Comment by slonik-az** [comment]
`u32` is 4-byte aligned. Therefore, `s1` starts at 4-byte boundary making  sizeof `s1`  8 bytes. Similarly, `u16` is 2-byte aligned, therefore sizeof `s2` is 4 bytes. This is correct behavior not a bug.

**Comment by IntegratedQuantum** [comment]
> Shouldn't the packed struct have the same size as a sum of subtypes ?

Only the `@bitSizeOf` is meant to sum together:
```zig
try std.testing.expect(@bitSizeOf(s1) == @bitSizeOf(u32) + @bitSizeOf(u16));
try std.testing.expect(@bitSizeOf(s2) == @bitSizeOf(u8) + @bitSizeOf(u16));
```
Otherwise packing together booleans for example would be really inefficient:
```zig
try std.testing.expect(@sizeOf(packed struct {a:bool, b:bool}) == 1);
try std.testing.expect(@sizeOf(bool) + @sizeOf(bool) == 2); // The size that you expected
```

Now with the size given by `@bitSizeOf` the compiler is now somewhat free to choose a size when using it in arrays or variables. CPUs are optimized for powers of 2. For example if you try to load a non-aligned piece of memory, the CPU might need to fetch 2 cache-lines instead of 1.
So it makes sense to go for the next power 2 for size+alignment:
```zig
    try std.testing.expect(@alignOf(s1) == 8);
    try std.testing.expect(@alignOf(s2) == 4);
```

If you really want to have it packed in memory, you can check out `PackedIntArray`/`Slice` from the standard library(you might need some `@bitCast`ing or make a wrapper to make it work with packed structs).
