### ISSUE TITLE
differences in whitespace and symbol naming causing large differences in generated code

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#17357]
### Zig Version

0.12.0-dev.601+f4c884617

### Steps to Reproduce and Observed Behavior

i have 3 simple cases that are logically identical but creating significantly different assembly
https://godbolt.org/z/56Er1M1Eh
https://godbolt.org/z/fE9asb67E
https://godbolt.org/z/bEPx4jaTf
these generate 37, 101, and 128 instructions respectively with the only difference being the name of the function.
this behavior no longer happens if you set `-target` or `-mcpu` to (as far as i can tell) anything but `native`, other flags may change this as well.

### Expected Behavior

whitespace and symbol naming should not affect generated code

**Comment by andrewrk** [comment]
If you can reproduce this without godbolt, I'll re-open it. Probably what's happening here is that godbolt has a bunch of different servers with different CPU feature sets and it's arbitrary which one the code gets compiled on. In order to use godbolt as a tool, an explicit CPU feature set should be used. Arguably it would make sense to open an issue on godbolt and have it always pass a CPU feature set to zig.

**Comment by xdBronch** [comment]
thanks, after a bit of local testing i couldnt reproduce it so it seems youre right, ive opened an issue on the compiler-explorer github
