### ISSUE TITLE
zig local import proposal mechanism

### ISSUE THREAD

**Issue by ptutak** [ziglang/zig#17371]
I am new to the zig community and recently I started using the language and I like it very much.
Apart from some of the issues regarding explaining new language functionalities in the [documentation](https://ziglang.org/documentation/master/) or in the [getting started tutorial](https://ziglearn.org/chapter-0/) I have some feedback regarding building new zig package.

Typically in languages like Python or Java, we can pretty easily relate to other parts of the code. In Zig we can only do that for the code that's on the same level or in a subfolder. In order to do the import to other parts of the code, we have to do some "magic" in the build.zig.

I've recently created a [post](https://stackoverflow.com/questions/77192323/how-to-import-zig-module-from-another-module) on StackOverflow for this for which I've found an answer after a few days of experimenting by trial and error with the zig build system (which is not well documented by the way).

What I propose is to present a special function to the `std.Build` which could look something like this:
```
b.discoverModules(.{root_source_path="src/"})
```
And what it could do is to create a module for each `.zig` file in the `src` dir, provide it with a conventional name, discover all the import statements that are in the convention, and attach a dependency to those modules.

For example if we have a structure:
```
src/
   module_a/
      file_a.zig
   module_b/
      file_b.zig
   tools/
      tools.zig
```
Where `module_a/file_a.zig` uses `tools/tools.zig` by a statement `const some_name = @import("tools.tools")` the command should create all three modules:
- `module_a.file_a`
- `module_b.file_b`
- `tools.tools`
by running commands similar to `b.addModule("module_a.file_a", .{ .source_file = .{ .path = "src/module_a/file_a.zig" } });`
and then updating the dependencies hash map with proper modules discovered when looking for `@import` statements, for example like this:
```
module.dependencies.put("tools", tools_tools) catch |err| {
    @panic("Failed to add dependency");
};
```
The step is optional so it's not mandatory, but it would really simplify the experience of entering the language for someone who comes from those languages, because it would provide the same experience when it comes to creating proper import structure.

**Comment by mlugg** [comment]
> In Zig we can only do that [imports] for the code that's on the same level or in a subfolder.

This isn't true: as is usual with relative paths, you can use `..` to go up the directory tree, for instance `@import("../foo.zig")`.

The rest of this issue reads to me like the wrong approach to your problem due to this misunderstanding. Modules should be self-contained pieces of code - generally either external packages (either vendored or through the package manager), or pieces of code which you expect and intend to be somewhat self-contained and separate from other parts of your codebase. Here, it looks like you're effectively just trying to use modules to emulate path-based imports. The reason there isn't a utliity in `std.Build` like you're describing is simply because this isn't really how you're meant to use modules - they should be fairly rare, and have meaningful purposes, certainly *not* just automatically created based on the directory hierarchy.

`tools` may be reasonable to have as a module here if it doesn't depend on any code from your other subdirectories, but I probably wouldn't expect the other files to be modules. It's a good thing that the build system requires you to explicitly create modules - this requires you to put some thought into it, and ask yourself "should X really be a module?". This utility would also cause issues with the fact that Zig does not allow a single source file to simultaneously exist in multiple modules - it wouldn't work to just create them all over the place and only use a few.

Lastly, just to address a point in your StackOverflow post, you definitely *don't* want to be using `usingnamespace` to include tests from other files. `usingnamespace` is a complex feature which may not even remain in the language. Instead, [the documentation describes](https://ziglang.org/documentation/master/#Nested-Container-Tests) the standard method to run tests from other files or containers: simply reference them from an unlabeled `test` block, as in:
```zig
test {
    _ = @import("module_a/file_a_test.zig");
    _ = @import("module_b/file_b_test.zig");
    _ = @import("tools/tools_test.zig");
}
```

I'm going to close this issue for now since I believe it stems from a misunderstanding. If you still think there's good reason for this utility to exist, feel free to expand on its usefulness in a comment and I'll re-open the proposal.

**Comment by ptutak** [comment]
@mlugg thanks for the clarification, and the tests example. It seemed for me that you cannot import with "../some_file.zig" because when I tried to zig test `src/my-package/some_file_test.zig` I received an error if the file was testing something that was importing with `@import("../some-other-package/other_file.zig")` but in fact when I started using `zig build test` with the above setup there is no problem anymore with those tests.

So If I understand correctly one cannot `zig test some_path.zig` if there is an import to a directory above that level, but because `build.zig` is on the top level of the repository (in most cases) it itself imports everything that is either on the same level or in a subdirectory, which resolves this issue.

**Comment by mlugg** [comment]
You've more-or-less got it. More specifically, what's going on is that every Zig module has a "root path", outside of which it cannot import files from. When you run `zig test ./some/file.zig` without overriding the module's root path, it is set to the dirname of the file being tested, so `./some` in that case. A build script will do the same thing by default, however, I'm guessing your script is actually testing a file in your root `src` directory or something like that, so `src` is the module's root path.

If you need to override the root path, you can do it with the `--main-pkg-path` CLI flag (for manual invocations, e.g. `zig test`, `zig build-exe`) or with the `main_pkg_path` field on `std.Build.Step.Compile` (when using the build system). (Note that these flags call it the "main *package* path" for legacy reasons - module, not package, is the correct term here.)

**Comment by ptutak** [comment]
Yes, thanks for the clarification. It could probably be better described in the docs, or presented in an easier way to comprehend, because when it comes to "user experience" for someone coming from other languages, this is... well... poor quality to say the least (I mean introducing the build system and how someone should use it). Not mentioning that by default I would expect just something like:
```
const my_module = @import("path.to.module")
```
It's such a common pattern that I think it could be useful for the "beginners" to have something familiar from other languages.
I still think there could be maybe a "common" function for this that just dicovers all the `.zig` files and creates modules for them. And when someone get's more familiar with the build system, he may change this to a more custom setup (although I think for 99.99% of projects, that would everything that's needed).

**Comment by mlugg** [comment]
> It could probably be better described in the docs

Yep, that's true. Zig is a v0 language which is still undergoing major changes, so unfortunately its documentation is currently expected to be a bit lacking in places. If you'd like, you're always welcome to PR improvements to the language reference.

> Not mentioning that by default I would expect just something like:

The way `@import` works is [described fairly well](https://ziglang.org/documentation/master/#import) in the documentation already.

> I still think there could be maybe a "common" function for this that just discovers all the `.zig` files and creates modules for them.

Such a function would encourage antipatterns: you are really *not* meant to create modules very often. Many projects would do best to only have 1, and most will certainly use no more than 2 or 3 - for instance, all ~250k SLOC of the Zig compiler itself are in a single module. Furthermore, this would lead to compilation errors in any non-trivial project because of the thing I mentioned where a file cannot exist in multiple packages. (So if `foo.zig` was imported directly but was also the root of a package `foo`, you would get a compilation error.)

**Comment by ptutak** [comment]
But also importing via `@import("../../../../my/long/tools/path.zig")` does not seem to be a clean way of solving it.
If there is other simpler mechanism, that would provide me a convenience that's compared to this: `@import("my.long.tools.path")` I would be happy to know it. If there is not, I think It would be a good idea to provide such a mechanism.
It will provide a better overall beginner experience than it is now.
