### ISSUE TITLE
Interactive way to query compilers (e.g. "What is the type of <my expression>?")

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17505]
I'm tripping up with strings and pointers and comptime, and when I try to write a throwaway script to tell me what the types of certain expression are, the debug print statement itself errors out or just straight up crashes without printing any output whatsoever.

All I want to do is to be able to ask the compiler what is the type that it thinks my expression is, without dealing with the catch-22 of needing to know what that answer is in order to get it to print the answer in the first place.

**Comment by xdBronch** [comment]
if this is just for learning purposes and not meant to be part of an program, you can use `@compileLog`
for example the statement `@compileLog("this is a string literal");` you get the output
```
Compile Log Output:
@as(*const [24:0]u8, "this is a string literal")
```

**Comment by IntegratedQuantum** [comment]
I think the main problem here is that the error message isn't descriptive enough.
So I suggest that we try to figure out what the issue was in your example and then you can try to propose a better error message.

It's probably just a simple issue, like a forgotten const: `[]const []const u8` in the function type or a forgotten `&` at the callsite.
If you would share a bit more of your code, especially how you created the array of strings and how you passed it to the function, I can see if I can help you further.

Also: Next time it would be better to ask for help in one of [zig's community spaces](https://github.com/ziglang/zig/wiki/Community) first. You'll usually get a faster answer there.

**Comment by Vexu** [comment]
There is a proposal that would enable a feature like this to be added #615
