### ISSUE TITLE
zig c++ link error when targetting older glibc

### ISSUE THREAD

**Issue by xxxbxxx** [ziglang/zig#17536]
### Zig Version

0.12.0-dev.933+b0f031f573

### Steps to Reproduce and Observed Behavior

```c++
#include <stdlib.h>
int main(int argc, char* argv[]) {
	return strtoul(argv[1], 0, 10);
}
```

```
$ zig c++  main.cpp -target x86_64-linux.4.4.0-gnu.2.23
LLD Link... ld.lld: error: undefined symbol: __isoc23_strtoul
>>> referenced by main.cpp:4
>>>               /var/home/xavier/.cache/zig/o/b7dd90f0bc6f5ecf441dda49947e658a/main.o:(main)
```

also concerns, at least:
```
error: ld.lld: undefined symbol: __isoc23_strtoll_l
error: ld.lld: undefined symbol: __isoc23_strtoull_l
error: ld.lld: undefined symbol: __isoc23_vsscanf
error: ld.lld: undefined symbol: __isoc23_sscanf
error: ld.lld: undefined symbol: __isoc23_strtol
error: ld.lld: undefined symbol: __isoc23_strtoll
error: ld.lld: undefined symbol: __isoc23_strtoul
error: ld.lld: undefined symbol: __isoc23_strtoull
```

### Expected Behavior

 it did work prior to glibc upgrade in zig.

and it still works when targeting native libc (which is 2.38).
`$ zig c++  main.cpp `

**Comment by xxxbxxx** [comment]
some investigations:

```bash
$ find ~/.cache/zig/ -name libc.so.6
/var/home/xavier/.cache/zig/o/9b3169c14cedda9534a11ca419e2b2e8/libc.so.6
$ ls -l /var/home/xavier/.cache/zig/o/9b3169c14cedda9534a11ca419e2b2e8/libc.so.6
-rwxr-xr-x 1 xavier xavier 195024 Oct 15 18:47 /var/home/xavier/.cache/zig/o/9b3169c14cedda9534a11ca419e2b2e8/libc.so.6
$ cp /usr/lib/libc.so.6 /var/home/xavier/.cache/zig/o/9b3169c14cedda9534a11ca419e2b2e8/libc.so.6
$ ls -l /var/home/xavier/.cache/zig/o/9b3169c14cedda9534a11ca419e2b2e8/libc.so.6
-rwxr-xr-x 1 xavier xavier 1948832 Oct 15 19:02 /var/home/xavier/.cache/zig/o/9b3169c14cedda9534a11ca419e2b2e8/libc.so.6
$ /var/home/xavier/src/zig/zig/build/stage3/bin/zig c++  main.cpp -target x86_64-linux.4.4.0-gnu.2.23
```

that produces a working binary, but I guess it won't work on actual glibc 2.23 systems...

```bash
$eu-strings a.out 
/lib64/ld-linux-x86-64.so.2
__libc_start_main
__gmon_start__
__isoc23_strtoul
libc.so.6
GLIBC_2.34
GLIBC_2.38
```

**Comment by xxxbxxx** [comment]
oh and, if converted to c:
`zig cc  main.c -target x86_64-linux.4.4.0-gnu.2.23` -> ok
`zig cc -std=c17  main.c -target x86_64-linux.4.4.0-gnu.2.23` -> ok
`zig cc -std=c2x  main.c -target x86_64-linux.4.4.0-gnu.2.23` -> error
```
LLD Link... ld.lld: error: undefined symbol: __isoc23_strtoul
>>> referenced by main.c:5
>>>               /var/home/xavier/.cache/zig/o/febb58e42d8183cf12f3d33fd4052780/main.o:(main)
```

**Comment by rootbeer** [comment]
I think the __isoc23_strtoul dependency comes via the glibc stdlib.h header file: https://github.com/ziglang/zig/blob/master/lib/libc/glibc/include/stdlib.h

I'm not entirely sure how this is supposed to work in Zig, but I would expect a set of header files for each supported glibc version because (I believe?) glibc header files can create dependencies on the symbols from the version of glibc the headers are associated with?  I think that's what is happening here?  (The 2.38 glibc headers depend on a symbol, `__isoc23_strtoul`, that is only provided by 2.38 glibc versions?). 

That said, I'm really not familiar with all the magic in the Zig compat code, so this may be fixed in some other way than duplicating headers.   You might dig into exactly which stdlib.h is being linked into your code to see if you can track down the specific source of the dependency?
