### ISSUE TITLE
Different behaviour in Debug and ReleaseFast builds.

### ISSUE THREAD

**Issue by theunixer** [ziglang/zig#17569]
### Zig Version

0.12.0-dev.926+3be8490d8

### Steps to Reproduce and Observed Behavior

Setting everything up:
```
$ git clone https://notabug.org/unixer/slearner
$ cd slearner/
$ git checkout 56fe0145
```

This is what I get in Debug build:
```
$ zig build run 
$ cat test/1.txt 
�M 

2

It's back.

It's front.
```

Dont't forget to:
```
git restore test/1.txt
```

This is what I expect and what I get in ReleaseFast build:
```
$ zig build run -Doptimize=ReleaseFast
$ cat test/1.txt 
17.10.2023

2

It's back.

It's front.
```

### Expected Behavior

I expect the program in Debug build to behave as the program in ReleaseFast build.

**Comment by IntegratedQuantum** [comment]
You are causing undefined behavior in the `Date.toString()` method:
```zig
pub fn toString(self: Date) ![]u8 {
    var buffer: [11 + maxDateStringLen]u8 = undefined; // This buffer is on the stack and is only valid inside this scope.
    ...
    return try result.toOwnedSlice(); // You return a slice into the buffer
}
```
Once you return from the function the buffer is no longer valid and can be overwritten by the next function call.
You just got lucky here that it works in release.

In order to return valid memory, you can either use a global allocator, or pass an allocator to the function:
```zig
pub fn toString(self: Data, allocator: Allocator) ![]u8 {...}
```
or, since you seem to know the maximum length of the buffer you could also return the entire array, though that is a bit more complicated to use in practice:
```zig
pub fn toString(self: Data) struct{buf: [11 + maxDateStringLen]u8, len: usize} {
    ...
    return .{.buf = buffer, .len = result.items.len};
}
```

**Comment by theunixer** [comment]
@IntegratedQuantum  Thank you very much!
