### ISSUE TITLE
resinator should not observe any environment variables

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#17585]
One of zig's principles as a toolchain is to reduce dependencies on global state of the system, so that collaborators on wildly different systems can have a seamless experience working with each other.

To that end, this code should be deleted:

https://github.com/ziglang/zig/blob/7a9500fd80990a3dc47821e627162bf769eecbba/src/resinator/compile.zig#L112-L123

All include paths that are intended to be observed by resinator should be provided explicitly by the user, and explicitly for resinator and no other files, and it should be per invocation rather than global.

I noticed this when enhancing `zig env` to tattle on what environment variables are possibly observed by the compiler, and it's unfortunate that `INCLUDE` is in this list.

cc @squeek502

**Comment by squeek502** [comment]
This is already the case for everything except `zig rc`:

`ignore_include_env_var` is unconditionally set to true when compiling `.rc` and `.manifest` files:

https://github.com/ziglang/zig/blob/aeadcb3918f7e6bc7abb08e70ffe3b3c25fb9c22/src/Compilation.zig#L4873

https://github.com/ziglang/zig/blob/aeadcb3918f7e6bc7abb08e70ffe3b3c25fb9c22/src/Compilation.zig#L4675

It is controlled by the `/x` flag in `zig rc` for compatibility with `rc.exe` but I could be persuaded against that if you feel it would be an improvement (the `INCLUDE` env var is only really set when setting up a "Visual Studio development environment" via the `vcvarsall.bat` and friends scripts, and `resinator` doesn't depend on it being set since it autodetects the system include paths by default anyway).

**Comment by andrewrk** [comment]
Nice, that all makes sense and I think your intended way for it to work is perfectly reasonable.
