### ISSUE TITLE
Pattern: `Lot` data structure for scope-lifetime nonresizable arrays of runtime-known length 

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17656]
I've been using this pattern a fair bit when interfacing with C APIs that require a temporary buffer of runtime-known length.

Since it's only a temporary buffer, it does not need to be resized, and *should be dropped immediately upon exiting the current scope.*

For this purpose, stack allocation fits all of the requirements _except_ for its length being runtime-known. 

I just want a runtime-sized stack allocation that don't overflow, the full dance of ArrayList+Allocator is a bit overkill when the data assuredly never outlives the current scope.

So the idea is to just have  one _permanent arena_ ("permarena") per each datatype that ever instantiates fixed-lifetime fixed-length dynamic arrays.

(i.e. having `Lot(MyType)` anywhere will instantiate, at compile time, a single homogeneous arena shared by all instances of MyType Lots, which lives for the duration of the program)

Due to the scope-lifetime constraint, the `defer` train always frees in order and the arena stays contiguous.

This approach is an ergonomic middleground with only a single extra `defer buffer.free()` compared to dynamic languages.

*Foregoing the ability to outlive the current scope* allows it to have a very simple interface not worrying about which allocator to use, since the allocation strategy is constrained.

```zig

pub fn Lot(comptime T: type) type {
    return struct {
        items: []T,

        var permarena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
        const allocator = permarena.allocator();

        const Self = @This();

        pub fn free(self: Self) void {
            allocator.free(self.items);
        }

        pub fn new(count: usize) ?Self {
            const items = allocator.alloc(T,count) catch { return null; };
            return .{
                .items = items,
            };
        }
    };
}

```

Example Usage:

```zig
const std = @include("std");
const net = @include("net.zig");
const Lot = @include("Lot.zig").Lot;

const Person = struct {
    height: u32,
    weight: u32,

    const Self = @This();
    const Selves = Lot(Self); // this instantiates the arena for type Lot(Person)
    pub fn newLot(count: usize) ?Selves {
        return Selves.new(count);
    }
};

pub fn main() void {
    const src = net.listen("localhost");
    const num = src.numPeopleInQueue(); // runtime-known length, unknown upper-bound

    if (Person.newLot(num)) |lot| { // could also just use Lot(Person).new(num) directly
        defer lot.free();
        var items = lot.items;
    
        _ = src.getPeopleInQueue(items.ptr, items.len); // c api that takes a ptr and a len
        
        for (items) |item| {
            std.debug.print("{?}",.{item});
        }
    }
}
```

**Comment by IntegratedQuantum** [comment]
While this is definitely a neat idea, I don't think it is safe enough to be added to the standard library:
- It is really easy to generate memory leaks with this approach. The ArenaAllocator can only free the top-most element. So if you allocate two buffers and free them in the wrong order then you generate a leak.
- It is not thread safe. So it would only work in quasi single-threaded applications.

**Comment by nektro** [comment]
ArrayList has `ensureUnusedCapacity` and `appendAssumeCapacity` for this use case, I use it often

**Comment by mlugg** [comment]
As well as the issues mentioned by IntegratedQuantum, I think there's a more fundamental problem with this idea.

> [...] not worrying about which allocator to use.

This is an explicit antipattern in Zig. In almost all cases, it's desirable to know where your allocations live for efficiency. In fact, the approach in your example of using an arena backed by `std.heap.page_allocator` is often a bad idea, since it can result in a lot of syscalls. When interfacing with C, it's generally a good idea to use `std.heap.c_allocator`.

Your example snippet isn't actually really any more complicated or less readable when just using an allocator directly:
```zig
pub fn main() void {
    const src = net.listen("localhost");
    const num = src.numPeopleInQueue(); // runtime-known length, unknown upper-bound

    if (std.heap.c_allocator.alloc(Person, num)) |items| {
        defer std.heap.c_allocator.free(items);
    
        _ = src.getPeopleInQueue(items.ptr, items.len); // c api that takes a ptr and a len
        
        for (items) |item| {
            std.debug.print("{?}",.{item});
        }
    }
}
```

All this proposal would really do is add a kind of global allocator into the standard library, which is an explicit non-goal.

Don't be afraid to manage your memory manually - it's rarely that difficult, and writing such code directly can make it easier and less daunting to make things more efficient, for instance using batched allocations.

**Comment by squeek502** [comment]
Probably worth looking at `std.heap.MemoryPool` if you haven't seen it, it seems very similar to what you're proposing: https://github.com/ziglang/zig/blob/master/lib/std/heap/memory_pool.zig

You can use the `MemoryPoolExtra` option `.growable = false` to disable further allocations.

**Comment by squeek502** [comment]
@mlugg

> using an arena backed by `std.heap.page_allocator` is often a bad idea, since it can result in a lot of syscalls

This would be news to me. Here are the results from my attempt at verifying this, let me know if there's something I'm missing.

The test allocates 1000 times using random sizes under 512 bytes and then 1000 more times using random sizes under 10KiB. Both arenas make the exact same allocations (the PRNG seed is the same for each run).

<details>
<summary>Test code</summary>

```zig
const std = @import("std");
const Allocator = std.mem.Allocator;

pub fn main() !void {
    const c_counts = try arenaAllocStuff(std.heap.c_allocator);
    std.debug.print("c_allocator:\n", .{});
    c_counts.summary();

    const page_counts = try arenaAllocStuff(std.heap.page_allocator);
    std.debug.print("page_allocator:\n", .{});
    page_counts.summary();
}

pub fn arenaAllocStuff(allocator: Allocator) !Counts {
    var counting_allocator = CountingAllocator.init(allocator);
    var arena_state = std.heap.ArenaAllocator.init(counting_allocator.allocator());
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var rng = std.rand.DefaultPrng.init(0);
    const rand = rng.random();

    var requested_bytes: u64 = 0;

    const num_small_allocs = 1000;
    for (0..num_small_allocs) |_| {
        const len = rand.uintAtMostBiased(usize, 512);
        _ = try arena.alloc(u8, len);
        requested_bytes += len;
    }
    const num_allocs = 1000;
    for (0..num_allocs) |_| {
        const len = rand.uintAtMostBiased(usize, 1024 * 10);
        _ = try arena.alloc(u8, len);
        requested_bytes += len;
    }
    // hacky way to return all the counts
    return .{
        .allocated_bytes = counting_allocator.total_bytes,
        .requested_bytes = requested_bytes,
        .allocs = counting_allocator.allocs,
        .attempted_resizes = counting_allocator.attempted_resizes,
        .in_place_resizes = counting_allocator.in_place_resizes,
    };
}

const Counts = struct {
    allocated_bytes: u64,
    requested_bytes: u64,
    allocs: u64,
    attempted_resizes: u64,
    in_place_resizes: u64,

    fn summary(self: Counts) void {
        std.debug.print(" allocated {} total bytes for {} requested bytes\n", .{ self.allocated_bytes, self.requested_bytes });
        std.debug.print(" alloc was called {} times\n", .{self.allocs});
        std.debug.print(" {} out of {} attempted resizes were able to resize in place\n", .{ self.in_place_resizes, self.attempted_resizes });
    }
};

const CountingAllocator = struct {
    child_allocator: std.mem.Allocator,
    total_bytes: u64 = 0,
    allocs: u64 = 0,
    attempted_resizes: u64 = 0,
    in_place_resizes: u64 = 0,

    pub fn init(child_allocator: std.mem.Allocator) CountingAllocator {
        return .{ .child_allocator = child_allocator };
    }

    pub fn allocator(self: *CountingAllocator) std.mem.Allocator {
        return .{
            .ptr = self,
            .vtable = &.{ .alloc = alloc, .resize = resize, .free = free },
        };
    }

    fn alloc(ctx: *anyopaque, len: usize, ptr_align: u8, ret_addr: usize) ?[*]u8 {
        var self: *CountingAllocator = @ptrCast(@alignCast(ctx));
        self.allocs += 1;
        const ptr = self.child_allocator.rawAlloc(len, ptr_align, ret_addr) orelse return null;
        self.total_bytes += len;
        return ptr;
    }

    fn resize(ctx: *anyopaque, buf: []u8, buf_align: u8, new_len: usize, ret_addr: usize) bool {
        var self: *CountingAllocator = @ptrCast(@alignCast(ctx));
        self.attempted_resizes += 1;
        const old_len = buf.len;
        const stable = self.child_allocator.rawResize(buf, buf_align, new_len, ret_addr);
        if (stable) {
            self.in_place_resizes += 1;
            if (new_len > old_len) {
                self.total_bytes += new_len;
                self.total_bytes -= old_len;
            } else {
                self.total_bytes -= old_len;
                self.total_bytes += new_len;
            }
        }
        return stable;
    }

    fn free(ctx: *anyopaque, buf: []u8, buf_align: u8, ret_addr: usize) void {
        var self: *CountingAllocator = @ptrCast(@alignCast(ctx));
        return self.child_allocator.rawFree(buf, buf_align, ret_addr);
    }
};
```

</details>

On Linux:

```
$ zig run arena_syscalls.zig -lc
c_allocator:
 allocated 6562306 total bytes for 5282291 requested bytes
 alloc was called 19 times
 2 out of 20 attempted resizes were able to resize in place
page_allocator:
 allocated 6161443 total bytes for 5282291 requested bytes
 alloc was called 14 times
 82 out of 95 attempted resizes were able to resize in place
```

Sycall count from `strace -c` (running only one `arenaAllocStuff` at a time):

```
c_allocator:
 15           mmap
  8           munmap
page_allocator:
 22           mmap
 15           munmap
```

On Windows:

```
> zig run arena_syscalls.zig -lc
c_allocator:
 allocated 6679747 total bytes for 5282291 requested bytes
 alloc was called 19 times
 0 out of 18 attempted resizes were able to resize in place
page_allocator:
 allocated 6161443 total bytes for 5282291 requested bytes
 alloc was called 14 times
 82 out of 95 attempted resizes were able to resize in place
```

Syscall count (gotten via [`nttrace`](https://github.com/rogerorr/NtTrace)):

```
c_allocator:
 36    NtAllocateVirtualMemory/NtAllocateVirtualMemoryEx
 10    NtFreeVirtualMemory
page_allocator:
 31    NtAllocateVirtualMemory/NtAllocateVirtualMemoryEx
 17    NtFreeVirtualMemory
```

So there are differences, but it doesn't seem to be remotely in the realm of warranting "don't use page_allocator with ArenaAllocator" advice.

**Comment by squeek502** [comment]
@expikr

> Would you say that this is the optimal allocator where the list grows monotonously without upper bound at a constant rate that minimizes slow syscalls?

That sounds like `ArenaAllocator` to me, but I'm not super knowledgeable about allocators so I could be wrong.

`MemoryPool` is different because it's an `ArenaAllocator` + a free list, so you are able to destroy an item in the pool and its memory will be re-used for future items.

https://github.com/ziglang/zig/blob/e354aac8f21ffb1a30602b32fbacf64e5067278e/lib/std/heap/memory_pool.zig#L141-L154

**Comment by mlugg** [comment]
@expikr

> Actually, that's what I originally wanted to use -- always force an immediate `defer.free()` after what's basically `malloc`, but for some reason the compiler refuses to let me use c_allocator saying that "I must link against libc" etc. What's the deal with that?

When you compile a C program, the compiler (GCC, Clang, MSVC, etc) implicitly links against libc, which contains all of the C standard library (including `malloc` and `free`). You can usually tell the compiler *not* to link against libc by passing a flag, but you rarely want that (because libc is basically necessary to do anything useful in C), so linking against libc is the default. In Zig, we don't need to use libc most of the time, since the Zig standard library is mostly standalone (basically everything ends up as direct system API calls or inline assembly) - therefore, it's not linked by default. Instead, to link libc when compiling a Zig program (which is required to use the C allocator - otherwise it won't actually exist in your program!), you need to explicitly tell the compiler to do it. If you're using `zig build-exe`, `zig test`, etc, you can do that with `-lc`, whilst if you're using the build system, you use the `std.Build.Step.Compile.linkLibC` function, e.g. `exe.linkLibC()`.

---

I'd also like to make a few more quick arguments against this datastructure.

Firstly, the arena is never actually `deinit`ed, so underlying pages are not actually returned to the OS. This isn't a *huge* deal - literally every OS will handle that gracefully and free up your allocated pages on process exit - but it does mean that `Lot` essentially allocates non-reclaimable memory, since freeing from an arena will never free from the backing allocator. That's not great.

Secondly, another case where this pattern encourages inefficiency is when you don't know for *certain* a bound at comptime, but you have a *likely* limit. In this case, `std.heap.StackFallbackAllocator` can be used to avoid heap allocations in most cases, and only fall back to the heap when the region requested is too large. This is another example of how having this kind of pattern in the standard library discourages people from making choices which can, in some cases, significantly affect performance. We always want to *encourage* thinking about where your memory is: it matters!

---

@squeek502

> This would be news to me. Here are the results from my attempt at verifying this, let me know if there's something I'm missing.

Nice performance analysis - that was a somewhat careless statement of me, apologies. Let me try to be a bit more specific.

Of all the places to use an arena backed by a page allocator, this one isn't *too* bad - you're making single big allocations which you're never resizing. However, it definitely has problems.

The main one is that because this creates a separate arena for every instantiation of `Lot`, you end up requesting memory from the OS potentially a lot more often than you need. If you already have a general-purpose allocator in your application (be that `c_allocator`, `std.heap.GeneralPurposeAllocator`, or, yes, even a page-allocator-backed arena) then it's really wasteful to construct a bunch more - each one will initiate the growing process from a baseline of a small handful of pages, when there might in reality be many KiB or even MiB of heap space all ready to use.

It's also worth noting that `ArenaAllocator` starts off by allocating very small amounts of memory from its backing allocator - around 1.5x your initial alloc size. This generally isn't a huge deal, but it means your initial allocation might only be a single page, resulting in rapid syscalls during the initial growth of the arena. This isn't a huge problem, but it's exacerbated by having all these separate arenas.

Overall, the issue is not so much that backing an arena with a page allocator is *fundamentally* inefficient, but that doing it *in the context of the existence of other allocators* is a pointless inefficiency. There are absolutely cases where it's a valid approach - for instance, for a one-shot CLI program where we can safely throw all allocations into an arena, we can accept a little bit of wasted memory from some allocated pages not being quite big enough for future allocations, and it's our only allocator so we don't really ever request pages when there's already memory available. But if we're already using a `c_allocator` elsewhere, we already have potentially a lot of heap space available to us, which could be more than sufficient for our allocation - why go to the trouble of making another trip to the OS?
