### ISSUE TITLE
Convention: `do: { break :do }` instead of `blk: { break :blk}`

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17670]
It might just be my preference but I feel like reusing something more aligned to other languages' `do` notation for procedural blocks is more legible than a keyword-looking `blk`.

```zig

do: {
    var temp = GetInput() catch { break :do; };
    defer temp.cleanup();
    DangerousSideEffect(input);
}

const thing: ?Thing = do: {
    var temp = MaybeThing() orelse { break :do null; };
    const success = MutateThing(temp);
    break :do if (success) temp else null;
}

```

**Comment by wooster0** [comment]
or how about we use neither of those and just use names specific to the thing we're returning or doing? example:
```zig
const thing: ?Thing = thing: {
    var temp = MaybeThing() orelse { break :thing null; };
    const success = MutateThing(temp);
    break :thing if (success) temp else null;
}
```

**Comment by mlugg** [comment]
`blk:` isn't really a suggested convention in the first place. It's been historically used a lot, but it's generally recognised that there's pretty much always a more suitable descriptive name for the block which should be used instead, as wooster0 said.

> The `do` preference is more for freestanding blocks that need a break point.

There'll still be a more suitable name for the situation: what is this block actually doing? For instance, if it's a common "fast path" for some block of code, maybe the block should be labeled `simple` or `fast`. Since you're having to apply control flow to the block, this implies the block is doing something meaningful, so - like if the block were instead split out into a function - it can and should be given a meaningful name.

I'm going to close this issue since it doesn't really propose anything concrete (primarily since `blk` isn't really a standard convention to begin with). If you have a concrete proposal, feel free to comment or edit the original issue.

**Comment by mlugg** [comment]
Langref proposals/issues do belong here, rather than the website repo.

I think the way of describing this is that `blk` is to labeled blocks as `x` is to local variables: it's a good "dummy" name for example code, but generally shouldn't be used in real code. Just because those examples use `blk`, doesn't mean it's a suggested convention when writing actual code; just as the examples calling variables `x`/`y`/`val1` isn't indicative of a convention for actually naming variables that. As with those names, it's sometimes reasonable to actually use the label `blk` - such as in trivial cases where a descriptive name seems verbose and redundant - but such cases aren't too common.

Regardless, I don't really see any advantage to your proposed alternative of `do`. In particular, I find the point about "keyword-looking" identifiers odd, since `do` looks a heck of a lot more like a keyword in my opinion (it literally *is* a keyword in a whole bunch of other languages!).
