### ISSUE TITLE
zig cc -c -fPIE stopped working

### ISSUE THREAD

**Issue by markus-oberhumer** [ziglang/zig#17928]
### Zig Version

0.12.0-dev.1504+81219586b

### Steps to Reproduce and Observed Behavior

At https://github.com/upx/upx-test-build-with-zig we are continuously testing building UPX for 104 different build targets, and it seems that recently `-fPIE` as used in `zig cc -c -fPIE` stopped working

Possible cause: commit https://github.com/ziglang/zig/commit/aa76ca2

```sh

# create empty file
touch x.c 

# works
./zig-linux-x86_64-0.12.0-dev.1108+aeadcb391/zig cc -target x86_64-linux-musl -fPIE -c x.c

# FAILS
./zig-linux-x86_64-0.12.0-dev.1504+81219586b/zig cc -target x86_64-linux-musl -fPIE -c x.c
error: unable to create compilation: OutputModeForbidsPie
```

### Expected Behavior

No error.

**Comment by rootbeer** [comment]
I think https://github.com/ziglang/zig/issues/17575 is the relevant discussion that inspired the recent change.  Zig is reserving `-fPIE` for building executables, and these commands are just building objects.  Hrm ... I think that discussion was focused on the compilation of Zig code, though (not Zig as a C compiler).

When pretending to be a C/C++ compiler, Zig should probably let these through.  The gcc doc (https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Code-Gen-Options.html) says that `-fPIE` can be used on intermediate objects, but only if they're intended to be linked into an executable.  And its implies `-fPIC` is meant for intermediate objects destined for a shared library.

Digging into these some more (see https://www.mjr19.org.uk/IT/pic_pie.html), both PIE and PIC make the code relocatable, but it looks like the PIC option additionally implies a GOT (Global Offsets Table), so that symbols can be interposed on (required by shared libraries).  PIE does not use a GOT, so the resulting code, though relocatable, is not suitable for a shared library.  That said, all my experience and doc reading has been focused mostly on x86_64, so there might be other subtle issues on other platforms?  (E.g., the gcc doc above notes differences in `-fpic` and `-fPIC` where the latter overrides platform GOT size limits?)

**Comment by kubkon** [comment]
I just wanted to clarify that `-fPIC` is a generic flag used by compiler frontends that will emit machine code that is position-independent be it in an executable (PIE) or a dynamic shared library. `-fPIE` is weird. It implies `-fPIC` indeed but also passes `-pie` to the linker which will make different choices when resolving certain relocations compared to if no flag was passed or `-shared` was specified. Neither option however controls the GOT. If a generated relocatable is importing an extern variable, the compiler will emit a GOT relocation regardless of the machine code model used. Then it is up to the linker to either actually put that reference in the GOT or relax it (do a direct load).

**Comment by kubkon** [comment]
One more thing - the compiler really has no control over GOT since it is a linker-generated synthetic section. That is unless you tell it that you promise all imports in one relocatable will be available in another translation unit which will be enough to elide any indirection via GOT. I'm not sure if a flag like this exists though. I know that `gcc` and `clang` used to have a corresponding flag for PLT `-fno-plt` however.

**Comment by kubkon** [comment]
Finally, I think it should be possible to build a static PIE which musl kinda implies.

**Comment by kubkon** [comment]
> I think @mikdusan 's patch just didn't consider `zig cc` , so this should be updated.
> 
> And JFYI here are some interesting PIC/GOT/PLT links:
> 
>     * https://ewontfix.com/18/
> 
>     * https://maskray.me/blog/2021-09-19-all-about-procedure-linkage-table

I don't think the 32-bit codegen is still accurate. If you compile the example from the first link with and without PIC on x86_64 linux, you will get the same result.

```
$ cat repro.c
void bar(void);

void foo(void) {
  bar();
}
$ gcc -c -fno-PIC -static repro.c
$ readelf -r repro.o

Relocation section '.rela.text' at offset 0x158 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000005  000400000004 R_X86_64_PLT32    0000000000000000 bar - 4

Relocation section '.rela.eh_frame' at offset 0x170 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000020  000200000002 R_X86_64_PC32     0000000000000000 .text + 0
```

And with `-fPIC`:

```
$ gcc -fPIC -c repro.c
$ readelf -r repro.o
Relocation section '.rela.text' at offset 0x158 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000005  000400000004 R_X86_64_PLT32    0000000000000000 bar - 4

Relocation section '.rela.eh_frame' at offset 0x170 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000020  000200000002 R_X86_64_PC32     0000000000000000 .text + 0
```

Generated machine code is also identical.

**Comment by mikdusan** [comment]
We're going to have to allow `-fpie` or `-fPIE` for objects too because gcc/clang define macros:
```c
$ uname -a
Linux archlinux 6.6.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000 x86_64 GNU/Linux

$ gcc --version
gcc (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc -E -dM x.c | grep -i pie
#define __pie__ 2
#define __PIE__ 2

$ /opt/llvm-arch2.38-x86_64-17.0.4-release/bin/clang --version
clang version 17.0.4 (https://github.com/llvm/llvm-project.git 309d55140c46384b6de7a7573206cbeba3f7077f)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm-arch2.38-x86_64-17.0.4-release/bin

$ /opt/llvm-arch2.38-x86_64-17.0.4-release/bin/clang -E -dM x.c | grep -i pie
#define __PIE__ 2
#define __pie__ 2
```

**Comment by kubkon** [comment]
We decide on a per-target basis: https://github.com/ziglang/zig/blob/9ad03b628f5d4770f9f26e646019292b5ae9cf9b/src/target.zig#L194 Please also note that we cannot have PIE enabled unconditionally - when building a shared library having PIE enabled will produce a malformed shared object.

**Comment by mikdusan** [comment]
> CLANG_DEFAULT_PIE_ON_LINUX

IIRC, zig does not take that into account for any PIC/PIE decisions.
