### ISSUE TITLE
Compile error when attempting to use printf on amdgcn-amdhsa

### ISSUE THREAD

**Issue by arctic-marmoset** [ziglang/zig#18208]
### Zig Version

0.12.0-dev.1785+72568c131

### Steps to Reproduce and Observed Behavior

```zig
pub extern fn printf(format: [*:0]const u8, ...) c_int;

export fn kernel() callconv(.Kernel) void {
    if (@workGroupId(0) == 0 and @workItemId(0) == 0) {
        _ = printf("Hello from kernel!\n");
    }
}
```
Compile with:
```
zig build-lib -target amdgcn-amdhsa main.zig
```
Full `build.zig` for reference:
```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    // Replace this with your GPU model.
    const gpu_model = &std.Target.amdgpu.cpu.gfx1030;
    const optimize = b.standardOptimizeOption(.{});

    const device_code = b.addSharedLibrary(.{
        .name = "kernel-" ++ gpu_model.name,
        .root_source_file = .{ .path = "src/main.zig" },
        .target = .{
            .os_tag = .amdhsa,
            .cpu_arch = .amdgcn,
            .cpu_model = .{ .explicit = gpu_model },
        },
        .optimize = optimize,
    });
    b.installArtifact(device_code);
    device_code.bundle_compiler_rt = false;
    device_code.force_pic = true;
    device_code.linker_allow_shlib_undefined = false;
}
```
Compiling the above produces the following error message:
```
error: main.zig:5:19: in function kernel void (): printf format string must be a trivially resolved constant string global variable
```

### Expected Behavior

Assuming I'm not missing anything else, I think the above should compile.

The error message comes from LLVM:
[lib/Target/AMDGPU/AMDGPUPrintfRuntimeBinding.cpp:135](https://llvm.org/doxygen/AMDGPUPrintfRuntimeBinding_8cpp_source.html#l00135) (diagnoseInvalidFormatString)
[lib/Target/AMDGPU/AMDGPUPrintfRuntimeBinding.cpp:166](https://llvm.org/doxygen/AMDGPUPrintfRuntimeBinding_8cpp_source.html#l00166) (AMDGPUPrintfRuntimeBindingImpl::lowerPrintfForGpu)

I wasn't able to get a dev build of Zig to compile cleanly, so unfortunately I wasn't able to investigate further.

**Comment by Snektron** [comment]
Interesting, thanks for the quick investigation @Vexu.

This seems to be partially caused by the fact that `printf` is special-cased in clang. There is no real reason for this other than optimizing those calls, but it does require that the format is known at compile time.

I guess the right course of action is to make const globals be placed in this address space behind the scenes automatically. That should be fine probably.

By the way, likely you will need to change the prototype for `printf` to `pub extern fn printf(format: [*:0]addrspace(.constant) const u8, ...) c_int;`. This won't work yet, it seems that these pointers are forbidden right now. I'll make a quick MR to fix both of these things up.

**Comment by Snektron** [comment]
On a side note, we might be able to side step printf if we want to roll our own GPU runtime. Clang emits code for printf that calls into the hostcall routines implemented in [ROCm-Device-Libs](https://github.com/ROCm/ROCm-Device-Libs/blob/amd-stg-open/ockl/src/services.cl).

**Comment by Snektron** [comment]
As I also wrote on the merge request, I've fixed the compilation issues, but that won't make this working. The problem is that to use printf() you need to actually link the ROCm-Device-Libs, which is in ROCm done by [comgr](https://github.com/ROCm/ROCm-CompilerSupport/tree/amd-stg-open/lib/comgr). You might be able to do this by compiling to bitcode and then linking using comgr, see [here](https://github.com/MathiasMagnus/spirv2bin/blob/1bf751c6e808db3020b65055b498921e8721a7a6/examples/comgr-test/OpenCL-Cpp-SAXPY.cpp#L478-L599) for how that might be done. Alternatively, as pointed out above, you can avoid linking with ROCm by rolling the relevant parts of the printing function yourself.
