### ISSUE TITLE
type weirdness when switching on errors in comptime

### ISSUE THREAD

**Issue by adrian4096** [ziglang/zig#18276]
### Zig Version

0.11.0, 0.12.0-dev.1821+a38af5f54

### Steps to Reproduce and Observed Behavior

in any comptime context, like global scope
```
const ip = std.net.Address.parseIp("::1", 8090);
```
this produces the following output in 0.11.0:
```
zig build-exe http_test Debug native: error: the following command failed with 1 compilation errors:
/home/user/projects/tar/zig-linux/zig build-exe /home/user/projects/home/http_test/src/main.zig --cache-dir /home/user/projects/home/http_test/zig-cache --global-cache-dir /home/user/.cache/zig --name http_test --listen=- 
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install http_test transitive failure
   └─ zig build-exe http_test Debug native 1 errors
/home/user/projects/tar/zig-linux/lib/std/net.zig:28:13: error: expected type 'error{InvalidCharacter}', found 'error{Overflow}'
            error.Overflow,
            ^~~~~~~~~~~~~~
/home/user/projects/tar/zig-linux/lib/std/net.zig:28:13: note: 'error.Overflow' not a member of destination error set
src/main.zig:3:35: note: called from here
const ip = std.net.Address.parseIp("::1", 8090);
           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
referenced by:
    server: src/main.zig:24:14
    main: src/main.zig:11:5
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

I'd expect this to work in comptime and to return something like described in `@compileLog` as `@as(@typeInfo(@typeInfo(@TypeOf(net.Address.parseIp)).Fn.return_type.?).ErrorUnion.error_set!net.Address, [runtime value])
`

**Comment by adrian4096** [comment]
This could also be worked around in the standard library.

**Comment by Vexu** [comment]
`parseIp` should define an explicit error set.

**Comment by ArtemKolichenkov** [comment]
Seems like an simple fix for my first contribution, I'll take it.

**Comment by adrian4096** [comment]
> `parseIp` should define an explicit error set.

Please correct me if i'm wrong, but shouldn't this be a compiler fix? If not, should all switch cases in the standard library be tested in comptime?

**Comment by ArtemKolichenkov** [comment]
> > `parseIp` should define an explicit error set.
> 
> Please correct me if i'm wrong, but shouldn't this be a compiler fix? If not, should all switch cases in the standard library be tested in comptime?

ah, I see what you mean.
Seems there are actually 2 issues

## Issue 1: Comptime behaviour

Consider this contrived example (same what `parseIp` does):

```zig
const strGood = myFunction("Hellof");

pub fn main() !void {
    @compileLog(strGood);
    std.debug.print("\nNoop\n", .{});
}

fn myFunction(string: []const u8) !bool {
    if (isGoodString(string)) |res| return res else |err| switch (err) {
        error.Empty,
        error.TooLong,
        error.TooShort,
        => {},
    }

    return error.Fatal;
}

fn isGoodString(string: []const u8) !bool {
    if (string.len == 0) {
        return error.Empty;
    }
    if (string.len == 1) {
        return error.TooShort;
    }
    if (string.len > 5) {
        return error.TooLong;
    }
    return true;
}
```

if you run this, you will get this error for the first line inside switch statement
```
error: expected type 'error{TooLong}', found 'error{Empty}'
        error.Empty,
        ^
```

This might be a compiler bug, since it's unclear what is even meant by this. It seems compiler expects the very first case to match err and when it doesn't - it freaks out.
But even if you change assignment to `const strGood = myFunction("");`, you will get this:
```
error: expected type 'error{Empty}', found 'error{TooLong}'
        error.TooLong,
       ^
```
So it actually seems to stumble on every possible case of switch statement.
Unfortunately I don't know why it behaves like this in comptime specifically 🤷 

You can avoid it with proper error sets when going over errors in a switch statement (i.e. Issue 2 below).

## Issue 2 - Lack of proper error typing in `net`

`parseIp` doesn't know what errors can occur in the switch statement, it's just some kind of error. If we define proper error set for `parseIp` (and well, all the stuff that can have defined error set) - the "Issue 1" actually goes away. I tested it quickly now and seems that I can get rid of comptime errors that way.
Moreover there is some minor "bugs", like Overflow being [defined as a possible case](https://github.com/ziglang/zig/blob/master/lib/std/net.zig#L28) in `parseIp4`, even though no branch returns Overflow inside of it.

---

I'll play around a bit more, looks like I can fix it at least for the stuff in `net`. But yeah, I agree that those errors probably should not happen in compiler. Or at least if their intent is to tell that "hey you're iterating over random errors, please use Error Set" then the error message should be improved 🤔 
Need someone with a bigger brain than me for the compiler part though.

**Comment by Vexu** [comment]
> Issue 1: Comptime behaviour

This is not a bug in the compiler but rather a "feature" of the language #2736

**Comment by mlugg** [comment]
See #17125 as a potential solution to this.
