### ISSUE TITLE
@as(@Vector(x,x), @bitCast(x)) type confusion in test

### ISSUE THREAD

**Issue by aqrit** [ziglang/zig#18365]
### Zig Version

0.12.0-dev.1849+bb0f7d55e

### Steps to Reproduce and Observed Behavior

```
const std = @import("std");

/// bad - produces compile error
pub inline fn min_bad(a: @Vector(4, i32), b: @Vector(4, i32)) @Vector(4, i32) {
    return @bitCast(@min(
        @as(@Vector(16, u8), @bitCast(a)),
        @as(@Vector(16, u8), @bitCast(b)),
    ));
}

/// works
pub inline fn min_okay(a: @Vector(4, i32), b: @Vector(4, i32)) @Vector(4, i32) {
    const aa: @Vector(16, u8) = @bitCast(a);
    const bb: @Vector(16, u8) = @bitCast(b);
    const res: @Vector(16, u8) = @min(aa, bb);
    return @bitCast(res);
}

test "bug?" {
    const a: @Vector(4, i32) = @splat(7);
    const b: @Vector(4, i32) = @splat(9999);
    const ref: @Vector(4, i32) = .{ 7, 7, 7, 7 };
    std.debug.print("a => {any} {any}\n", .{ @TypeOf(a), @typeInfo(@TypeOf(a)) });
    std.debug.print("b => {any} {any}\n", .{ @TypeOf(b), @typeInfo(@TypeOf(b)) });
    try std.testing.expectEqual(ref, min_bad(a, b));
}
```

zig test bug.zig

```
bug.zig:5:12: error: @bitCast size mismatch: destination type '@Vector(4, i32)' has 128 bits but source type '@Vector(16, u3)' has 48 bits
    return @bitCast(@min(
           ^~~~~~~~
bug.zig:25:45: note: called from here
    try std.testing.expectEqual(ref, min_bad(a, b));
```

where `u3` seems to be the bit-width of `7`. 

### Expected Behavior

Expect `min_okay` and `min_bad` to be equivalent.

**Comment by Vexu** [comment]
`min_okay` and `min_bad` are not equivalent, `min_okay` has a widening cast before the bitcast.

**Comment by aqrit** [comment]
How should I write min_bad without temporaries?

**Comment by aqrit** [comment]
This doesn't make sense to me.
A `u3` vector is never declared, so where does it come from?
Does `@min` just randomly `@truncate`?

**Comment by xdBronch** [comment]
`@min` returns the minimum size required to represent the returned value, e.g. passing a u8 and a u32 to `@min` returns a u8 since the minimum will always been in the range of a u8. the reason this truncates in your example is because the vectors you pass in are comptime known and the function is inline. in zig an inline function is more than an optimization and has semantic implications. to the compiler, you're directly passing a vector full of 7s into `@min` and a u3 is the smallest integer required to represent that number

**Comment by aqrit** [comment]
Thx @xdBronch.

I still believe this is unsafe behavior.
The compiler ignores the cast to `u8` but still slices it into 16 lanes... so I have no idea what value ends up those other 12 lanes.
Also, the behavior changes based on how far ahead the compiler can see...

**Comment by xdBronch** [comment]
while this behavior is certainly surprising, i dont believe its unsound or dangerous. it doesnt ignore the cast into a u8 but rather turns the u8s into u3s, the vector of u3s that it is returning is exactly identical in value to the vector of u8s you gave it so the value in the other 12 lanes should not be surprising. this also is only happening because the function is inline and the vectors are comptime know meaning all of this is happening at compile time where, in a sense, types matter less. in my opinion this is something to be aware of, not something to avoid

**Comment by aqrit** [comment]
The function(s) have different behavior depending on whether they are called from real code or whether they are called from a unit test. This meets my definition of unsound.

I can't drop `inline` given the nature of my project.
