### ISSUE TITLE
Code in else statements sometimes gets away with invalid syntax!

### ISSUE THREAD

**Issue by Oglo12** [ziglang/zig#18526]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

This Zig code compiles and works!:

```zig
if (1 == 1) {
    std.debug.print("Hello, world!", .{});
} else {
    std.debug.print("Wait, what?"); // Forgot .{}
}
```

This Zig code fails to compile! (Literally just changed '1 == 1' to '1 == 2'):

```zig
if (1 == 2) {
    std.debug.print("Hello, world!", .{});
} else {
    std.debug.print("Wait, what?"); // Forgot .{}
}
```

This Zig code fails to compile! (Strangely enough, you would expect it to compile based on the prior examples, but it doesn't!):

```zig
if (1 == 1) {
    std.debug.print("Hello, world!", .{});
} else {
    asdfjkghasdkfghasdkfjhg; // I guess this is just blatantly obvious for the compiler? I am lost for words! XD
    std.debug.print("Wait, what?"); // Forgot .{}
}
```

### Expected Behavior

I would expect the compiler to be smart enough to know that there is a syntax error, even if it is in an else statement that will never actually run! (I would expect it to detect this, considering this is the same language that fails compilation if a variable is not used!)

**Comment by nektro** [comment]
I personally have theories on how Zig might be able to avoid this in the future that will eventually turn into proposals but as Zig stands today this is entirely expected behavior.

> I would expect the compiler to be smart enough to know that there is a syntax error

`std.debug.print("Wait, what?");` contains no syntax error. missing parameters and type checking does not happen in branches that are not analyzed, which you pointed out above happens because your if statement contains a comptime-known condition.

**Comment by Oglo12** [comment]
> I personally have theories on how Zig might be able to avoid this in the future that will eventually turn into proposals but as Zig stands today this is entirely expected behavior.
> 
> > I would expect the compiler to be smart enough to know that there is a syntax error
> 
> `std.debug.print("Wait, what?");` contains no syntax error. missing parameters and type checking does not happen in branches that are not analyzed, which you pointed out above happens because your if statement contains a comptime-known condition.

But the weird part is it still panics at the obvious gibberish!

**Comment by Oglo12** [comment]
This feels more like an oversight than intended behavior!

**Comment by Rexicon226** [comment]
> > I personally have theories on how Zig might be able to avoid this in the future that will eventually turn into proposals but as Zig stands today this is entirely expected behavior.
> > > I would expect the compiler to be smart enough to know that there is a syntax error
> > 
> > 
> > `std.debug.print("Wait, what?");` contains no syntax error. missing parameters and type checking does not happen in branches that are not analyzed, which you pointed out above happens because your if statement contains a comptime-known condition.
> 
> But the weird part is it still panics at the obvious gibberish!

Correct, it panics because it's caught by the parser, which runs over everything no matter what.

**Comment by mlugg** [comment]
As discussed, this is expected behavior. The way Zig handles comptime control flow is that if a branch is comptime-known to not be taken, its body is not semantically analyzed. This has a bunch of nice properties - such as being able to put code which only compiles on Windows behind a simple conditional - but does have the unfortunate side effect that you could sometimes miss bugs like this. However, certain errors (like your gibberish example) are caught in the parser or in another stage of compilation before semantic analysis, and these are caught globally. In general, if an error is known purely from _syntax_ (without any semantic knowledge), it will be reported globally. This is the same class of errors caught by the `zig ast-check` command.
