### ISSUE TITLE
Comptime anonymous structs should not be allowed to coherce to `*const anyopaque`

### ISSUE THREAD

**Issue by leath-dub** [ziglang/zig#18522]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

I have a simple example of how this is a foot gun:

```zig
const std = @import("std");

fn iGiveth() void {
    iTaketh(&.{ 1, 2, 3 });
}

fn iTaketh(ref: ?*const anyopaque) void {
    const result = @as([*]const comptime_int, @ptrCast(@alignCast(ref.?)));
    std.debug.print("{}\n", .{result[0]});
}

pub fn main() void {
    iGiveth();
}
```

### Expected Output

This segfaults as the anonymous struct is entirely comptime so it is zero sized at runtime.
Ideally this would raise a compiler error as it is almost certainly not something you would want to happen.

The error should just say

"Not allowed to coherce `*const struct { comptime ... }` to type `*const anyopaque`, references to comptime structures cannot be coherced to `*const anyopaque`"

**Comment by mlugg** [comment]
You've got this the wrong way around. It's perfectly valid to type-erase any pointer, even if comptime-only or (as in this case) referring to a zero-bit type. The invalid thing here is casting a runtime-known pointer (the `iTaketh` parameter) to a comptime-only pointer type `[*]const comptime_int`. It is a bug that this does not emit a compile error, since `[*]const comptime_int` is a comptime-only type, so values of said type must be comptime-known.

Taking pointers to zero-bit values is entirely valid and will not be needlessly disallowed.

**Comment by xdBronch** [comment]
this issue was extracted from a problem trying to pass `&.{SOME_INT}` to a C function. despite the function *really* wanting a pointer to/array of u32s, the function accepted a `const void *` which was translated to `*const anyopaque`. the solution being to pass `&[_]u32{SOME_INT}`
i believe a more accurate example for this would be 
```zig
const std = @import("std");

fn iGiveth() void {
    iTaketh(&.{ 1, 2, 3 });
}

fn iTaketh(ref: *const anyopaque) void {
    const result: [*]align(1) const u32 = @ptrCast(@alignCast(ref));
    std.debug.print("{}\n", .{result[0]});
}

pub fn main() void {
    iGiveth();
}
```
i believe this better showcases the issue. running this gives a general protection exception or incorrect alignment panic if the `align(1)` is removed

**Comment by Vexu** [comment]
This now results in an error:
```
a.zig:15:30: error: runtime-known argument passed to parameter of comptime-only type
    std.debug.print("{}\n", .{result[0]});
                            ~^~~~~~~~~~~
lib/std/debug.zig:84:40: note: declared here
pub fn print(comptime fmt: []const u8, args: anytype) void {
                                       ^~~~
```
