### ISSUE TITLE
zig cc -target x86_64-windows.win7-gnu stopped working

### ISSUE THREAD

**Issue by markus-oberhumer** [ziglang/zig#18690]
### Zig Version

zig-linux-x86_64-0.12.0-dev.2334+aef1da163

### Steps to Reproduce and Observed Behavior

At https://github.com/upx/upx-test-build-with-zig we are continuously testing building UPX for 104 different build targets, and it seems that recently `zig cc -target x86_64-windows.win7-gnu` stopped working

Possible cause: recent upgrade from msvcrt to ucrt

```sh

# create a simple main() file
echo 'int main() { return 0; }' > x.c

# works
./zig-linux-x86_64-0.12.0-dev.2285+b80cad248/zig cc -target x86_64-windows.win7-gnu x.c

# FAILS
./zig-linux-x86_64-0.12.0-dev.2334+aef1da163/zig cc -target x86_64-windows.win7-gnu x.c

zig-linux-x86_64-0.12.0-dev.2334+aef1da163/lib/libc/mingw/libsrc/dloadhelper.c:31:3: error: unknown type name 'PDELAYLOAD_FAILURE_DLL_CALLBACK'
   31 |                 PDELAYLOAD_FAILURE_DLL_CALLBACK FailureDllHook,
      |                 ^
zig-linux-x86_64-0.12.0-dev.2334+aef1da163/lib/libc/mingw/libsrc/dloadhelper.c:52:66: error: use of undeclared identifier '__pfnDliFailureHook2'
   52 |         return ResolveDelayLoadedAPI(&__ImageBase, DelayloadDescriptor, __pfnDliFailureHook2, DelayLoadFailureHook, ThunkAddress, 0);
      |                                                                         ^
2 errors generated.
```

### Expected Behavior

No error.

**Comment by rootbeer** [comment]
Reproduced.  Fails for `windows.win7` and earlier (e.g., `windows.xp`) targets, but passes for later Windows targets (e.g., `windows.win8`).

`lib/libc/mingw/libsrc/dloadhelper.c` includes `delayloadhandler.h` (which has the missing definition), but that file hides the required definition behind a version check:
```
#if NTDDI_VERSION >= NTDDI_WIN8
```
(I'm guessing this is the source of the inconsistency, but haven't verified.)

The changelog in https://github.com/ziglang/zig/pull/16109 explicitly calls out the "New libdloadhelper.a, like libdelayimp.a but using Windows 8 and later APIs.", so the bug is probably that Zig is including `dloadhelper.c` when building the CRT for older targets.

`zig/src/mingw.zig` includes `dloadhelper.c` in its `mingwex_generic_src` list, which is, AFAICT the list of files to unilaterally compile into the `CRTFile.mingwex_lib` CRT target.

I'm guessing that mingw.zig should somehow know to skip this file for older Windows targets.  Or the dloadhelper.c itself should hide symbols when targeting older targets.

**Comment by ypsvlq** [comment]
I think the correct approach is to always build the CRT with the latest version, then `_WIN32_WINNT` should be defined only when including the headers to restrict what declarations are visible (see the [upstream Makefile](https://github.com/mingw-w64/mingw-w64/blob/569e8c01bc449022210404c7b38a5fad965827c2/mingw-w64-crt/Makefile.am#L23)).

UCRT is supported on XP and above.

**Comment by mikdusan** [comment]
This regresses `-target x86_64-windows-msvc -lc` to no longer define `_WIN32_WINNT`. Note `.msvc` ABI, because `.isMinGW()` specifically applies to only `.gnu` ABI.

caveat: I'm not sure, is `-msvc` still a supported/desired thing? Because it doesn't show up in the output of `zig targets` in the `libc:` section.

**Comment by sskras** [comment]
> caveat: I'm not sure, is `-msvc` still a supported/desired thing? Because it doesn't show up in the output of `zig targets` in the `libc:` section.

@mikdusan, since `-target x86_64-windows-msvc` is currently mentioned in the CI script, line 98:
https://github.com/ziglang/zig/blob/1e0739f0c6c7d731771ea3df140a1e5462f27a7e/ci/x86_64-windows-release.ps1#L90-L100

... I guess it's still a thing. 

Did you ever file/find another issue about that?
