### ISSUE TITLE
no field named 'root_source_file' in struct 'Build.CreateModuleOptions'

### ISSUE THREAD

**Issue by qcjxberin** [ziglang/zig#18725]
### Zig Version

0.11

### Steps to Reproduce and Observed Behavior

An error is reported when using a third-party library https://github.com/karlseguin/log.zig：
 error: no field named 'root_source_file' in struct 'Build.CreateModuleOptions'
  .root_source_file = .{ .path = "src/logz.zig" },

### Expected Behavior

Compilation works fine

**Comment by ianprime0509** [comment]
The `root_source_file` field in `Build.CreateModuleOptions` was named `source_file` in 0.11. This was one of the breaking changes made in #18160. It seems that the log.zig library you're trying to use only supports Zig master for now and not 0.11, since it's using the new name of the field unconditionally.

**Comment by qcjxberin** [comment]
Thanks, with your help I've solved the problem.
