### ISSUE TITLE
Support -Bsymbolic-functions 

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#18804]
This seems to be a blocker in my fork of zig-bootstrap when rebuilding LLVM 17.0.6 with zig.
```
...
error: unsupported linker arg: -Bsymbolic-functions
[4360/4881] Building CXX object tools/lld/COFF/CMakeFiles/lldCOFF.dir/InputFiles.cpp.o
ninja: build stopped: subcommand failed.
```

See https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/clang/tools/clang-shlib/CMakeLists.txt#L54

The current solution is to either patch LLVM or to disable shared libraries entirely with `-DLLVM_ENABLE_PIC=OFF`.

**Comment by kassane** [comment]
```bash
# archlinux (lld llvm-16)
$> ld.lld --help | grep -e "Bsymbolic-functions"
  --Bsymbolic-functions   Bind default visibility defined function symbols locally for -shared
# zig v0.12.0-dev/master
$>  zig ld.lld --help | grep -e "Bsymbolic-functions"
  --Bsymbolic-functions   Bind default visibility defined function symbols locally for -shared
# GNU ld (GNU Binutils) 2.42.0
$>  ld --help | grep -e "Bsymbolic-functions"
  -Bsymbolic-functions        Bind global function references locally
```

**Comment by kassane** [comment]
@theoparis , see https://github.com/ziglang/zig-bootstrap/commit/451966c163c7a2e9769d62fd77585af1bc9aca4b

**Comment by theoparis** [comment]
yeah, patching clang with that patch solves it.

**Comment by xdqi** [comment]
Using zig c++ to compile LLVM 18.1.8 (latest) fails with this problem as well. Why would zig patches LLVM source code instead of fixing this bug?

**Comment by andrewrk** [comment]
The use case described here is not compelling because the purpose of zig-bootstrap is to build a static zig compiler, which makes this flag irrelevant. However the feature is still OK to support.

**Comment by xdqi** [comment]
Okay that seems to make sense.

**Comment by diekleinekuh** [comment]
I'm using `zigg cc` to compile code as a dynamic library that is loaded as a plugin at runtime. My library has statically linked versions of dependency libraries and I want to make sure those are being picked up by the linker instead of being overwritten by versions of those libaries coming from the process that loads the plugin.  I'm using the switch `-Wl,-Bsymbolic-functions` for that with gcc/clang so without the flag I cannot use zig cc as a drop in replacement. 

What seems to be supported is `-Wl,-Bsymbolic` so also supporting `-Wl,-Bsymbolic-functions` would be reasonable from by point of view. Could you please reopen this issue?

**Comment by diekleinekuh** [comment]
Meanwhile I found a couple of workarounds for my use case. I use `-Bsymbolic` which has a broader effect but works for me. I also tested linker scripts that also worked but were a bit more maintenance heavy.

So I would be fine moving this to a later milestone or closing again.
