### ISSUE TITLE
Proposal: support using the compiler as a zig.zon package

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#18834]
## Use Cases

1. Use the native zig backends (once they are ready, of course) as an alternative to using libLLVM*.a
2. Use the compiler as a library

Use case 2 is what I'm in need of since I want to make an alternative to Nix flakes but with a `flake.zig`. A build.zig does not fit my use case since I want to have a nix-like CLI with a `zix develop` similar to nix devShells. This would mean using the compiler to parse the flake.zig, checking types and running the `outputs` function to extract devShells.default.

**Comment by Arnau478** [comment]
The parser and lexer are already on the `std`. Maybe what we should do is move the other stages to the `std` as well.

**Comment by VisenDev** [comment]
+1

Related to this, a similar idea I had was being able to use the zig compiler as a library, such that one could use zig as a scripting language.

You would be able to embed the compiler as a library, then have it compile different zig files at runtime into dylibs. This would allow you to use zig for the same purposes as one currently uses scripting languages like lua.

The advantage to this would be that there would not be any complex interfacing functions or anything required. Zig can easily interface with other zig code since it's the same language.

The use case for this would be things that need to be easily user extensible, such as games and text editors.

**Comment by VisenDev** [comment]
@theoparis has this been implemented?

**Comment by theoparis** [comment]
No. I have given up on using zig after what happened on the Zig discord. Additionally, there is nowhere else for me to go because it is the only active Zig community.

**Comment by sin-ack** [comment]
Regardless of your feelings about the Zig community, it would still be worthwhile to keep the issue open because it allows the Zig developers (distinct from the community) to track it. You can re-open and then click "Unsubscribe" on the sidebar to not receive notifications about it.
