### ISSUE TITLE
build fails on openSUSE

### ISSUE THREAD

**Issue by qjnr** [ziglang/zig#1899]
Following the documentation, `cmake` build fails at detecting LLVM.
```
CMake Error at cmake/Findllvm.cmake:24 (message):
  expected LLVM version >=7 but found
Call Stack (most recent call first):
  CMakeLists.txt:50 (find_package)
```
I'm on openSUSE and installed the llvm packages (`llvm`, `clang`, `lld` and their dependencies). Please help!

**Comment by wilsonk** [comment]
@qjnr It looks like your version of OpenSuse installs a version of LLVM that is lower than 7.0! 

 You will probably have to install LLVM/clang/lld by hand from llvm.org. Or possibly update your yast/zypper package management tool to point to a newer (possibly experimental) repo, so that it can download the newest LLVM.

**Comment by andrewrk** [comment]
I recommend downloading the pre-built static binaries from the download page.

https://ziglang.org/download/

**Comment by qjnr** [comment]
> @qjnr It looks like your version of OpenSuse installs a version of LLVM that is lower than 7.0!
> 
> You will probably have to install LLVM/clang/lld by hand from llvm.org. Or possibly update your yast/zypper package management tool to point to a newer (possibly experimental) repo, so that it can download the newest LLVM.

Nope, it downloaded the latest version.
