### ISSUE TITLE
Invalid @sizeOf of packed struct

### ISSUE THREAD

**Issue by dteod** [ziglang/zig#19150]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

I wrote the following minimalistic example:

```zig
const assert =  @import("std").debug.assert;

const PS = packed struct {
    m1: u32,
    m2: u32,
    m3: u32,
    m4: u32,
    m5: u32,
};

test {
    comptime {
        @compileLog("size of PS: ", @sizeOf(PS));
        @compileLog(@offsetOf(PS, "m1"));
        @compileLog(@offsetOf(PS, "m2"));
        @compileLog(@offsetOf(PS, "m3"));
        @compileLog(@offsetOf(PS, "m4"));
        @compileLog(@offsetOf(PS, "m5"));
        assert(@sizeOf(PS) == 5 * @sizeOf(u32));
        
        @compileLog(@typeInfo(PS));
    }
}
```

Compilation stops because the size of the packed struct is 24:

```
/usr/lib/zig/std/debug.zig:343:14: error: reached unreachable code
    if (!ok) unreachable; // assertion failure
             ^~~~~~~~~~~
packerr.zig:29:15: note: called from here
        assert(@sizeOf(PS) == 5 * @sizeOf(u32));
        ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compile Log Output:
@as(*const [12:0]u8, "size of PS: "), @as(comptime_int, 24)
@as(comptime_int, 0)
@as(comptime_int, 4)
@as(comptime_int, 8)
@as(comptime_int, 12)
@as(comptime_int, 16)

@as(builtin.Type, .{ .Struct = .{.layout = .Packed, .backing_integer = u160, .fields = .{ .{ ... }, .{ ... }, .{ ... }, .{ ... }, .{ ... } }, .decls = .{  }, .is_tuple = false} })
```

### Expected Behavior

I would have expected the size of `PS` to be 20. Even the backing integer is `u160` (20 bytes).

Removing `packed` and using a plain `struct` or an `extern struct` works. This was used to model registers of a memory-mapped device, I will probably use an `extern struct` at this point to match the device ABI but I wanted to highlight this anyway.

**Comment by mlugg** [comment]
This behavior is not a bug, although I can see how it would be confusing. The important thing here is that packed structs are just integers wearing a fancy hat. So this struct is represented in memory just like a `u160`, and all of the same load/store rules apply to it. Since `u160` is over 64 bits, on 64-bit platforms (which you're presumably compiling for here), it has a natural alignment of 8 bytes (`@alignOf(u160) == 8`), and thus the byte size is rounded up to a multiple of 8 (so `@sizeOf(u160) == 24`). Put simply, the size is higher because there are 4 padding bytes on the end.

Of course, if you use `PS` in a packed context - e.g. within another `packed struct` - it will use up precisely 160 bits.

If you have more questions about this, I'd encourage you to join a Zig [community](https://github.com/ziglang/zig/wiki/Community)!
