### ISSUE TITLE
make `std.math.sign` a builtin (`@sign`)

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#19198]
The behavior seem well-defined for intrinsic types including vectors, and is a fairly small branchless operation, so I'm wondering if there are any good reasons why it should not just be made into a builtin?

A quick search in the issues didn't seem to turn up any immediate results, so opening this issue to discuss.

**Comment by nektro** [comment]
things, particularly math related, are typically turned into builtins when there's evidence that there's architecture specific instructions that programs would benefit from being able to easily use. so if such instructions exist for `@sign` and using `std.math.sign` in ReleaseFast mode is unable to produce them, there may be a case here. otherwise you may want to add a `const sign = std.math.sign;` at the top of your file.

**Comment by castholm** [comment]
There is `_mm256_sign_epi8/16/32` which is not quite a unary `sign(x)` function but more like a `copysign(mag, sign)` equivalent for integers that also returns 0 if `sign` is 0.
