### ISSUE TITLE
resolve the +1 or not in windows thread local storage initialization and and document the reasoning

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1926]
https://github.com/ziglang/zig/blob/89ffb5819703c81514e4f29d2cadb5b74ea1f840/std/os/windows/tls.zig#L10-L11

`std/os/windows/tls.zig`:

```zig
// TODO also note, ReactOS has a +1 on StartAddressOfRawData and AddressOfCallBacks. Investigate
// why they do that.
```

Relevant hints:

https://github.com/mirror/mingw-w64/commit/a49e5853c54b5c46fd967b958560b1b68c63d9a8
(added the +1)
>       * tlssup.c (_tls_used): Remove +1 form _tls_start to avoid
>       section-relative offset displacement.

https://github.com/mirror/mingw-w64/commit/70359bf95cceebe74520c19b50dcecb033666099
(removed the +1)
>  Avoid a pre-initialized tls of one byte.

**Comment by kroepke** [comment]
AFAIK the reason is given in the original discussion when the MinGW change was proposed: https://mingw-w64-public.narkive.com/B69qM5w0/patch-tls-support-fixes

> The first diff is an actual bug fix; it corrects the TLS start address
written to the TLS dictionary (`_tls_used`). It is used to determine the
size and initial contents of the TLS area for new threads. If it does
not point to the start of the section, all the initial data will be
off (as well as the size), because the Windows TLS model uses offsets
relative to the section start (`@SECREL`).
