### ISSUE TITLE
Cross-compilation to i386 Linux/Mac from Windows seems broken in latest release (7fc99c33).

### ISSUE THREAD

**Issue by AlexKotik** [ziglang/zig#1928]
![test](https://user-images.githubusercontent.com/24991384/52411161-d58d5000-2aeb-11e9-9c22-da1c531e7b18.jpg)

**Comment by andrewrk** [comment]
Have a look at the support table in the readme: https://github.com/ziglang/zig#support-table

Linux x86_64 and MacOS x86_64 have tier 1 support, and in your screenshot they are working fine.
Linux i386 and MacOS i386 have Tier 2 support right now.

Quoting from the readme about what Tier 2 support means: 
 > *  There may be some standard library implementations, but many abstractions will give an "Unsupported OS" compile error. One can link with libc or other libraries to fill in the gaps in the standard library.
> *   These targets are known to work, but are not automatically tested, so there are occasional regressions.
> *    Some tests may be disabled for these targets as we work toward Tier 1 support.

So we can have open issues for the specific things we need to fix in order to work towards getting these targets from Tier 2 to Tier 1, but in general, it is known that not everything works for those targets.

**Comment by andrewrk** [comment]
I created 2 tracking issues for you:
 * #1930 (Tier 1 support for MacOS i386)
 * #1929 (Tier 1 Support for Linux i386)

**Comment by AlexKotik** [comment]
Ok, I see.
