### ISSUE TITLE
[Regression] Opening absolute paths no longer works with WASI

### ISSUE THREAD

**Issue by linusg** [ziglang/zig#19336]
### Zig Version

0.12.0-dev.3290+b9cca3b63

### Steps to Reproduce and Observed Behavior

This used to work with WASI (still does on linux):

```zig
const std = @import("std");

pub fn main() !void {
    const file = try std.fs.cwd().openFile("/tmp/foo.txt", .{});
    defer file.close();
    std.debug.print("ok\n", .{});
}
```

Run like this:

```
$ touch /tmp/foo.txt
$ zig build -Dtarget=wasm32-wasi
$ wasmtime --dir /tmp --dir . zig-out/bin/test.wasm
error: AccessDenied
Unable to dump stack trace: not implemented for Wasm
```

This is also problematic because of how `openDirAbsolute()` is implemented:

https://github.com/ziglang/zig/blob/294f51814f491ae4a09348d9e7221ae3e550c16f/lib/std/fs.zig#L272-L275

May be a regression in https://github.com/ziglang/zig/commit/7680c5330cbc9141b9a5444e30c512b6068ab50d.

I noticed because it broke the Wasm-based [kiesel playground](https://kiesel.dev/playground) and can also be reproduced there.

### Expected Behavior

Opening absolute paths against an arbitrary `Dir` should still work.

**Comment by squeek502** [comment]
My understanding is that absolute paths are not a concept that exist in WASI, but `wasi-libc` does try to support absolute paths using some complicated gymnastics, so you can likely fix this by linking libc (`wasi-libc` is the default libc for wasi)

I'm unsure why this worked previously, as AFAIK Zig dropped trying to support absolute paths a while ago in https://github.com/ziglang/zig/commit/d5312d53a066092ba9efd687e25b29a87eb6290c. When was the last version that this worked for you?

**Comment by linusg** [comment]
I don't know when it stopped working exactly, it definitely still was working earlier this year and I noticed the breakage a few weeks ago but only got around to investigating today.

The relevant code is here: https://codeberg.org/kiesel-js/website/src/commit/f87585fae24ea31a6d8cd1850723ae040ebb1c28/src/kiesel.ts#L30-L46

**Comment by linusg** [comment]
> so you can likely fix this by linking libc

Kiesel always links libc - so no, that doesn't fix it.

**Comment by squeek502** [comment]
> Kiesel always links libc - so no, that doesn't fix it.

Ah, ok, then this is the problem:

https://github.com/ziglang/zig/blob/54f6e74cda07a1153fd205afc8973665397f6cc7/lib/std/fs/Dir.zig#L777-L799

Before https://github.com/ziglang/zig/commit/7680c5330cbc9141b9a5444e30c512b6068ab50d, this instead checked for `builtin.os.tag == .wasi and !builtin.link_libc`, so it would fall through to `wasi-libc` if libc was linked. Now, that's no longer the case in `std.fs.Dir` but is still the case in `std.os.open`/`std.os.openat`.

According to the commit message, this is the new intended behavior ("go through wasi native APIs even when linking libc because the libc APIs are problematic and wasteful"), so @andrewrk will need to weigh in.

**Comment by andrewrk** [comment]
Please excuse the regression. I did not realize the detour through libc in this case was load-bearing. I will be sure to document this fact when restoring the functionality to prevent it from being removed again in the future.

**Comment by linusg** [comment]
Thanks Andrew, much appreciated! Also thanks Ryan for quickly finding the root cause of this :^)
