### ISSUE TITLE
A GeneralPurposeAllocator inside a struct causes segmentation fault when alloc is called.

### ISSUE THREAD

**Issue by Nebularzz** [ziglang/zig#19432]
### Zig Version

0.12.0-dev.3437+af0668d6c

### Steps to Reproduce and Observed Behavior

OS: Windows 11 64 bit

The code below causes the segfault.

```Zig
const std = @import("std");

pub fn main() !void {
    var gpa_wrapper = GpaWrapper.init();
    _ = try gpa_wrapper.alloc_and_free(2);
}

const GpaWrapper = struct {
    gpa: std.mem.Allocator,

    pub fn init() GpaWrapper {
        var gpa = std.heap.GeneralPurposeAllocator(.{}){};

        return GpaWrapper{
            .gpa = gpa.allocator(),
        };
    }

    pub fn alloc_and_free(self: GpaWrapper, size: usize) !void {
        const arr = try self.gpa.alloc(u8, size);
        self.gpa.free(arr);
    }
};
```

Different optimization levels and architectures cause different behavior.
x86:
`ReleaseFast` and `ReleaseSmall` segfault with no output.
`Debug` segfaults with error info.
`ReleaseSafe` is a little more interesting. I don't exactly know how to describe it, but it recursively segfaults.
The output is:

```
...
Segmentation fault at address 0x24
Segmentation fault at address 0x24
Segmentation fault at address 0x24
Segmentation fault at address 0x24
Segmentation fault at address 0x24
Segmentation fault at address 0x24
Stack Overflow
```

Replace ... with more `Segmentation fault at address 0x24` lines.

x86_64:
`ReleaseSmall` and `ReleaseFast` segfault with no output.
`ReleaseSafe` segfaults without running main.
`Debug` segfaults with error info.

### Expected Behavior

`alloc_and_free` should be allocating 2 bytes and free them right after, without any crashes.

**Comment by xdBronch** [comment]
the problem here is that the result of `gpa.allocator()` stores a pointer to the `gpa` variable but when it returns from the `init` function the pointer becomes invalid since `gpa` is out of scope
the solution is to either store the gpa itself or accept an allocator parameter in `init`

**Comment by castholm** [comment]
```zig
    pub fn init() GpaWrapper {
        var gpa = std.heap.GeneralPurposeAllocator(.{}){};

        return GpaWrapper{
            .gpa = gpa.allocator(),
        };
    }
```
This is not a bug with GPA, this is incorrect code. This function is storing the GPA state on the stack, then returning the result of calling `gpa.allocator()` which returns a struct that holds a pointer to that `gpa` stack variable. When the function returns, that `gpa` stack variable goes out of scope and will be overwritten with garbage by the next function call.

The fix is to either take `std.mem.Allocator` or `*std.heap.GeneralPurposeAllocator(.{})` as a parameter to `init`, or make the `gpa` field of type `std.heap.GeneralPurposeAllocator(.{})` and use `gpa_wrapper.gpa.allocator()` to obtain a `std.mem.Allocator`.

**Comment by Nebularzz** [comment]
Thanks, I'm very new to this language and was very confused when I ran into this.
