### ISSUE TITLE
Labeled defer

### ISSUE THREAD

**Issue by DerpMcDerp** [ziglang/zig#19691]
We should be able to specify the scope `defer` attaches to:

```
blk: {
	a;
	if (coin_flip()) {
		b;
		defer :blk AAA();
		c;
		if (coin_flip())
			defer :blk BBB();
		d;
	} else {
		e;
		for ("") |_| {
			defer :blk CCC();
		}
		f;
	}
	g;
}
```

=>

```
blk: {
	flag: u32 = 0;
	a;
	if (coin_flip()) {
		b;
		flag |= 1;
		c;
		if (coin_flip())
			flag |= 2;
		d;
	} else {
		e;
		for ("") |_| {
			flag |= 4;
		}
		f;
	}
	g;
	if (flag & 4) {
		CCC();
	} else if (flag & 1) {
		if (flag & 2)
			BBB();
		AAA();
	}
}
```

**Comment by InKryption** [comment]
What happens to a labelled defer inside of a loop?

**Comment by jklw10** [comment]
I'd assume it would just do it at the end of current loop iteration. if i wanted to move the defer outside of it i would wrap the whole loop in another block to defer to that.

**Comment by rohlem** [comment]
The main hurdle in implementing this feature is the compilation / optimization semantics compared to status-quo.
- By always attaching (`err`-)`defer`-ed statements to the current block in status-quo, it becomes a relatively trivial task of shuffling code around for the compiler:
  You're telling it "put this code into the block that is run when exiting this current block (via error return for `errdefer`).
- Allowing (`err`-)`defer`-ed statements to outer blocks behind runtime branching instead means "attach this code to a runtime-determined list of code that is run when this parent block exits".

Because source code is (usually) not executed 1:1, but goes through many layers of translation,
the current "static" nature helps giving guarantees and freedom to the various optimization passes to
inline, merge, reorder the accumulated statements - as a single "ok-exit" and "error-exit" block.

With the proposed runtime-decided nature however, since every inner block has its own list of statements,
only those couple statements can be analyzed that effectively - and the exit blocks will (virtually) always have to include additional branching.
In the case of loops, where multiple iterations may execute `defer`-s, we now also need a loop in the exit blocks.

For `while`-loops, because their executions aren't numerically bounded, that is a potentially-unbounded number of
elements making up this exit block - meaning we have an unbounded number and unbounded exit block growth.
Those are even more elements complicating language implementation,
loosening the guarantees programmers can expect from the language.
(For Zig it's certainly easier, and probably less controversial, not to solve issues
 with such non-trivial implementation strategies with different tradeoffs by a language feature,
 and instead burden programmers to come up with a solution to their particular use case in userspace.)

The current "static" approach is also simpler to reason about for someone reading the code
than parsing where (in which outer block) which `defer`-s are going to run how many times,
potentially, if the respective runtime code path was taken.

```zig
blk: {
  defer f();
  if (...) {
    // (... arbitrary number of lines ...)
  }
  g();
}
```

Under status-quo, if I know `g()` was executed I can be sure `f()` will execute next.
With this proposal, I would have to make scan through all nested scopes for whether
any of them `defer` something to execute in-between.

**Comment by DerpMcDerp** [comment]
> Under status-quo, even without looking at any nested scopes we know that if g() was executed, f() will execute next.

Under the status-quo you'd be lost in a maze of code and `bool`s manually keeping track of whether or not to call the `defer` and wondering if you got it correct.

> With this proposal, we would instead have to scan through all nested scopes for whether any of them defer something to :blk, which would execute in-between.

But the code would be smaller and known to be correct since it's managed by the compiler.

>  (It's also not quite clear whether you're allowed to include, for example, the loop counter in the defer statement - meaning the defer becomes a closure that has to save the value somewhere to the stack - or not. No such ambiguity with the limited feature of status-quo.)

The `defer` doesn't capture variables. Though I suppose the following syntax:

```
:blk {
	{
		defer :blk |some_capture| something(some_capture);
	}
}
```
=>
```
:blk {
	flag: u32 = 0;
	some_capture_gensym: whatever;
	{
		some_capture_gensym = some_capture;
		flag |= 1;
	}
	if (flag & 1)
		something(some_capture_gensym);
}
```

could be used to capture any variable it needs.

> For while-loops, because their executions aren't numerically bounded, that is a potentially-unbounded number of elements making up this exit block - meaning we have an unbounded number and unbounded exit block growth.

The `defer` blocks don't accumulate.
