### ISSUE TITLE
installHeader not working with addModule and local .path dependency: C import failed, file not found

### ISSUE THREAD

**Issue by actondev** [ziglang/zig#19840]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

This is weird to describe, so I'm attaching a minimal reproduction project with a build.zig file. Even though in the passed `-I` generated directory the `foo.h` is there, the compilation fails
[foo.zip](https://github.com/ziglang/zig/files/15194535/foo.zip)

Another related issue that came up when doing the reproduction scenario is https://github.com/ziglang/zig/issues/19839 . In my own project where this issue came up when trying to upgrade to 0.12, apart from the missing header issue (which could be bypassed by hardcoding the header path to an absolute path), the compiler was just crashing. I hope that these 2 issues take care of the 0.12 issues I encountered. I also tried `0.13.0-dev.46+3648d7df1` but got the same results

### Expected Behavior

Expecting the given project to compile with `zig build`

**Comment by ianprime0509** [comment]
This is a consequence of #18160: include paths (`-I`) are per-module now, so the `clib` library has to be linked to the `binding` module. If I change `exe.linkLibrary(lib.artifact("foo"));` to `binding.linkLibrary(lib.artifact("foo"));`, your example project builds for me (since `binding` is the module that's importing `foo.h`).

**Comment by actondev** [comment]
Oh, I see! Thank you so much!
