### ISSUE TITLE
allocator.create local variable is never mutated

### ISSUE THREAD

**Issue by SamuelBonilla** [ziglang/zig#19876]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

```zig
const Node = struct { data: u32, next: ?*Node = null };
var newNode = try self.allocator.create(Node); 
newNode.* = Node{ .data = 32 };
```

```
src/main.zig: error: local variable is never mutated
src/main.zig: note: consider using 'const'
```

### Expected Behavior

In this case, newNode is a variable pointing to a newly allocated Node, and its contents are being explicitly mutated after creation. Despite this, the compiler fails to compile the code with var and suggests using const, which does not align with the actual usage where the newNode is clearly being mutated.

This error prevents the program from compiling, suggesting an issue with how the compiler interprets mutability for pointers to newly created struct instances. Could you please clarify if this is the intended behavior or if there might be a bug in the compiler's analysis of variable mutability?

**Comment by nektro** [comment]
the error is not a false positive. `newNode` is of type `*Node` so therefore `newNode.*` changes the value that `newNode` is pointing at, not the address `newNode` itself represents.

**Comment by mlugg** [comment]
nektro is correct - `newNode` is a *pointer*, and the last line of your example isn't mutating `newNode` itself, but rather the memory it points to.

I can guarantee that there are no false positives for this error message. If you see it, the thing can definitely be `const`!

**Comment by SamuelBonilla** [comment]
@nektro Thank you for the quick response.

I appreciate the clarification regarding newNode of type *Node and the distinction between changing the value that newNode points to and the address it represents. However, I'm still a bit puzzled about the recommendation to use const for newNode. My understanding is that using the assignment operator (=) to modify the contents of newNode, as in newNode.* = Node{ .data = 32 };, indeed alters the data within the struct that newNode references.

In typical programming terminology, mutating the contents of a memory location would still generally be considered as modifying the variable, even if the address it holds remains constant. Could you please elaborate on why the distinction between the address and its content is treated differently in this context in Zig? I'm eager to understand the rationale behind this design choice better, as it seems to challenge conventional notions of mutability.

**Comment by nektro** [comment]
Zig's philosophy about const-ness is that it only applies to memory. so `newNode` being `const` only refers to the `usize`-sized block of stack/memory that holds the `*Node` address. if for instance you wanted `newNode` to also not be writable then since it is a pointer in this case you would have to coerce its type to `*const Node` instead.

`var` + `*T`
`const` + `*T`
`var` + `*const T`
`const` + `*const T`

each of these combos communicate a different amount of writability and are valid. A common question to ask oneself when reading/writing Zig is [Where are the bytes?](https://ziglang.org/documentation/master/#Where-are-the-bytes). The answer to that question guides much of Zig's design.

**Comment by SamuelBonilla** [comment]
@nektro  Thanks for the clarification
