### ISSUE TITLE
`ESRCH` is not handled by file io operations

### ISSUE THREAD

**Issue by breavyn** [ziglang/zig#19875]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

Reading or writing files under `/proc/<pid>/` on linux can result in an `ESRCH` error if the related process has terminated.

Functions `read`, `pread`, `readv`, etc. and their `write` counterparts, `seek`, and possibly others, return `error.Unexpected` in this case.

### Expected Behavior

Functions should return `error.ProcessNotFound` on `ESRCH`.

**Comment by chrboesch** [comment]
> Reading or writing files under /proc/<pid>/ on linux can result in an ESRCH error if the related process has terminated.

Linux returns the ENOENT error for a process (aka file) that no longer exists when trying to read or write to it. So I added 'ProcessNotFound' on this.

> Functions should return error.ProcessNotFound on ESRCH.

This error occurs when you try to kill a process or process group that no longer exists.

**Comment by KilianHanich** [comment]
> > Reading or writing files under /proc// on linux can result in an ESRCH error if the related process has terminated.
> 
> Linux returns the ENOENT error for a process (aka file) that no longer exists when trying to read or write to it. So I added 'ProcessNotFound' on this.

Ehm, I get `3`/`ESRCH` on an error, not `2`/`ENOENT`, which also wouldn't really make a whole lot of sense since we already have an open file descriptor.

Here's how to check that too:
1. Start some process you can kill later, e.g. `sleep 60m` and get its pid.
2. Run this but insert the pid you got:
```C
#include <sys/syscall.h>
#include <unistd.h>
#include <stdio.h>
#include <fcntl.h>
#include <errno.h>

int main() {
        int proc = open("/proc/<PID>", O_DIRECTORY | O_RDONLY);
        if (proc < 0) return 1;
        int fd = openat(proc, "cpuset", O_RDONLY);
        if (fd < 0) return 2;
        getchar();
        char buf[5];
        if (0 > read(fd, buf, 5)) {
                perror("read");
                printf("%d\n", errno);
                return -1;
        }
        close(fd);
}
```
3. Before hitting enter enter after starting, kill the process you created.
4. Hit Enter.
5. I got the following error message:
```
read: No such process
3```

**Comment by chrboesch** [comment]
Thanks, I'll look into this again.

**Comment by chrboesch** [comment]
As far as I can tell, the Linux kernel issues both 'ENOENT' and 'ESRCH', depending on whether the operation is at the file or process level. Therefore, it makes sense to catch both errors and return 'error.ProcessNotFound' accordingly, because that's what it boils down to.
I've added this and tested it with different variations; all the error messages now seem understandable to me.
PR follows shortly.

**Comment by chrboesch** [comment]
Here is my Zig test program, which causes the correct error after merging the PR.

```zig
const std = @import("std");

pub fn main() !void {
    const proc = try std.posix.open("/proc/<PID>", .{}, 0);
    std.debug.print("proc={d}\n", .{proc});

    const fd = try std.posix.openat(proc, "cpuset", .{}, 0);
    defer _ = std.posix.close(fd);
    std.debug.print("fd={d}\n", .{fd});

    // wait for a key
    const reader = std.io.getStdIn().reader();
    _ = try reader.readByte();

    var buf: [5]u8 = undefined;
    const res = try std.posix.read(fd, buf[0..]);

    std.debug.print("res={d}\n", .{res});
}
```
