### ISSUE TITLE
Allow coercing ref to anonymous array init to [*c]

### ISSUE THREAD

**Issue by Pyrolistical** [ziglang/zig#19883]
### Zig Version

0.13.0-dev.73+db890dbae

### Steps to Reproduce and Observed Behavior

Missing case for https://github.com/ziglang/zig/issues/18924

```zig
const std = @import("std");
const expectEqual = std.testing.expectEqual;

test "ref to anon array init coerced to many-c-ptr" {
    const values: [*c]const i32 = &.{ 5, -6 };
    try expectEqual(5, values[0]);
    try expectEqual(-6, values[1]);
}
```

Fails to compile:
```
error: type 'i32' does not support array initialization syntax
    const values: [*c]const i32 = &.{ 5, -6 };
```

### Expected Behavior

Expected test to pass

**Comment by castholm** [comment]
When I worked on https://github.com/ziglang/zig/issues/18924 and the related PR I considered including `[*c]` pointers but decided against it because the expected behavior is not as clear cut as with `[*]`. For example, should something like `const msg: [*c]const u8 = &.{ 'a', 'b', 'c' }` include a sentinel element or not? Let's say we decide that it should be treated as `[*]const u8` without a sentinel, `[*c]const u8` is treated as `?[*:0]const u8` by most of the standard library, so a user might incorrectly assume that a 0 sentinel will be inserted, resulting in bugs.

So I personally believe explicitness is the better option here for maximum clarity, requiring an explicit init expression like `&[_:0]u8{ 'a', 'b', 'c' }`.

**Comment by Pyrolistical** [comment]
> `[*c]const u8` is treated as `?[*:0]const u8` by most of the standard library

that seems like a bug then. [c-pointers](https://ziglang.org/documentation/master/#C-Pointers) doesn't say it is has a sentinel.

**Comment by mlugg** [comment]
@Pyrolistical C-pointers don't say anything -- that's sort of the point of them. **You should never, ever, ever be using C pointers in your own code.** They exist solely so that `zig translate-c` can function. It happens that C functions often pass sequences using sentinels, particularly null-terminated strings. The type system does not model this, because this is precisely why C-pointers exist in the first place: to allow easier interfacing with C APIs which do not provide this information via the type system.

FWIW, I think I agree with @castholm that it's not a good idea to allow this, for the exact reasons he outlined. The type `[*c]T` is quite vague, and could be used in a variety of circumstances, so it's not generally safe to assume the type being provided.

There's also an awkward edge case: how do we handle result types when array-initializing something like a `[*c][2]u32`? Does `&.{ a, b }` assume the type "meant" `*[2]u32` (so `a` and `b` are both `u32`), or assume that it "meant" `[*][2]u32` (so `a` and `b` are both `[2]u32`)? There isn't a correct answer to this question, and this proposal makes the syntax subtly confusing, whichever we were to choose.

**Comment by silversquirl** [comment]
> `const values: [*c]const i32 = &.{ 5, -6 };`

You should never do this. `[*c]` pointers are purely for use in the output of `translate-c` and should never be used in user code. Being explicit about how to initialize C pointers is extremely important, as C APIs often have unusual sentinel requirements that can't be documented in the types.

**Comment by Pyrolistical** [comment]
TIL
> `[*c]` pointers are purely for use in the output of `translate-c`

The documentation does not state that we should not directly use `[*c]` in our code.
