### ISSUE TITLE
Optionals of optionals

### ISSUE THREAD

**Issue by lassade** [ziglang/zig#19982]
### Zig Version

0.13.0-dev.75+5c9eb4081

### Steps to Reproduce and Observed Behavior

Both this test fails, I know the second one is kinda dumb but the first one is might be more relevant

```zig
test {
    const A = struct { ?*usize = null };
    try std.testing.expectEqual(@sizeOf(A), @sizeOf(?A));
}

test {
    try std.testing.expectEqual(@sizeOf(?*usize), @sizeOf(??*usize));
}
```

### Expected Behavior

The sizes in both tests should the same

**Comment by lassade** [comment]
Sorry for closing and reopening this

**Comment by mlugg** [comment]
Why would they be the same size? One extra bit of information (at least) is required to represent the `null` value. The only types which don't grow when made optional are definitely-nonzero pointers.

**Comment by Trevor-Strong** [comment]
My understanding of optionals in zig is that `?T` is effectively `struct { value: T, is_null: bool }` for everything _except_ pointers. 

Since pointers in zig normally aren't allowed to point to address 0, optional pointers have their null value represented as being address 0, allowing `*T` and `?*T` to have the same size. However sometimes you want a pointer to address 0 because something actually exists at that address, for this zig has `allowzero` pointers which let the pointed to address be zero and even let you assign these pointers to `null`. Since 0 is a valid value for `allowzero` pointers, **optional** `allowzero` pointers must fall back to the generic optional layout mentioned earlier. This layout difference is also why `?*T` is allowed in `extern` types but `?*allowzero T` isn't. 

In both cases you show, you have an optional, of an optional pointer - meaning the final type is effectively `struct { value: ?*T, is_null: bool }`, so the sizes just can't be the same.

In concrete terms, your first example of `A` and `?A`, zig needs to be able to tell you if the `A` struct is `null` and if the `?*usize` contained within is `null` separately.
