### ISSUE TITLE
setting global cache directory to relative path causes build failure of dependencies

### ISSUE THREAD

**Issue by Jan200101** [ziglang/zig#20129]
### Zig Version

0.13.0-dev.344+b2588de6c

### Steps to Reproduce and Observed Behavior

Build a project with dependencies (what exactly is needed is unclear, but I managed to cut it down to a minimal example https://github.com/Jan200101/zig-bug-local-cache-dep) and a global cache directory being set to a local path (e.g. `zig build --global-cache-dir zig-cache`)

This will result in the following error:
```
error: unable to open source directory 'zig-cache/p/1220b81f6ecfb3fd222f76cf9106fecfa6554ab07ec7fdc4124b9bb063ae2adf969d/include': FileNotFound
```

### Expected Behavior

Everything works as expected

**Comment by nektro** [comment]
I think this is known and you need to do `--global-cache-dir $PWD/zig-cache`

**Comment by Jan200101** [comment]
> I think this is known and you need to do `--global-cache-dir $PWD/zig-cache`

figured, but I'd rather just fix it outright (god knows I already sunk enough time into figuring out solution to this)

Solutions that I see so 
1. turn global cache path into absolute path when argument is parsed
    - this would make sure it works everywhere but I've heard that apparently relative paths are preferred for build system stuff?
2. never change the working directory
    - this would break projects that expect this behavior

personally I think 1 is better solution here

**Comment by castholm** [comment]
I believe this is be fixed by changing line 2048 of https://github.com/ziglang/zig/blob/e54fcdb5b290f2a7b2dad73f23e35289ad2ebefe/lib/std/Build.zig#L2047-L2055 to `.path = b.pathFromCwd(build_root_string),`. #20132 might be redundant if this fix is used instead.

The source of the problem seems to be this:

In the generated `dependencies.zig` file, relative dependencies will have their `build_root` set to absolute paths, while remote dependencies will have them set to paths resolved from the provided global cache dir. When building with a relative global cache dir like `--global-cache-dir my-cache`, all remote dependencies will have `build_root` paths that are relative:

```zig
pub const packages = struct {
    pub const @"1220b81f6ecfb3fd222f76cf9106fecfa6554ab07ec7fdc4124b9bb063ae2adf969d" = struct {
        pub const build_root = "my-cache\\p\\1220b81f6ecfb3fd222f76cf9106fecfa6554ab07ec7fdc4124b9bb063ae2adf969d";
        pub const deps: []const struct { []const u8, []const u8 } = &.{};
    };
    pub const @"1220cc5411d0624dd44d1eb476fe4285fb1a45fa17e5dcf1812dfe387b74404b2887" = struct {
        pub const build_root = "C:\\tmp\\zig-bug-local-cache-dep\\pkg/freetype";
        pub const build_zig = @import("1220cc5411d0624dd44d1eb476fe4285fb1a45fa17e5dcf1812dfe387b74404b2887");
        pub const deps: []const struct { []const u8, []const u8 } = &.{
            .{ "freetype", "1220b81f6ecfb3fd222f76cf9106fecfa6554ab07ec7fdc4124b9bb063ae2adf969d" },
        };
    };
};

pub const root_deps: []const struct { []const u8, []const u8 } = &.{
    .{ "freetype", "1220cc5411d0624dd44d1eb476fe4285fb1a45fa17e5dcf1812dfe387b74404b2887" },
};
```

When instantiating a dependency, `b.build_root.path` is set to the dependency's `build_root`. If `build_root` is relative, it means that `b.build_root.path` will also be relative, which in turn means that `b.pathFromRoot()` and subsequently `LazyPath.getPath2()` will return relative paths.

This will cause problems in build steps like `WriteFile` and `InstallDir` since code like `b.build_root.handle.openDir(full_src_dir_path, .{ .iterate = true })` needs `full_src_dir_path` to be absolute to work correctly.

**Comment by Jan200101** [comment]
That works too
Though I am concerned that this would try to resolve the path for every build_root.



Going down the chain its
- `dependencies.zig` gets its values set by `Fetch.run`
https://github.com/ziglang/zig/blob/30a35a897f2220d1b252d211c389cf0319170a94/src/Package/Fetch.zig#L377-L380

- `Fetch.run` gets the global cache from the job queue
https://github.com/ziglang/zig/blob/30a35a897f2220d1b252d211c389cf0319170a94/src/Package/Fetch.zig#L301

- the job queue is created by main
https://github.com/ziglang/zig/blob/30a35a897f2220d1b252d211c389cf0319170a94/src/main.zig#L5015
https://github.com/ziglang/zig/blob/30a35a897f2220d1b252d211c389cf0319170a94/src/main.zig#L4975-L4984

which just gets it from either a command line flag, env var or a default location
