### ISSUE TITLE
addConfigHeader stopped reporting error for missing property names

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#20230]
### Zig Version

0.14.0-dev.1+aab5cccc7

### Steps to Reproduce and Observed Behavior

```console
andy@bark ~/t/abc> ls
build.zig  foo.h.in
andy@bark ~/t/abc> cat foo.h.in
#define a @b@
andy@bark ~/t/abc> cat build.zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const out_h = b.addConfigHeader(.{
        .style = .{ .cmake = b.path("foo.h.in") },
    }, .{});
    const install_file = b.addInstallFileWithDir(out_h.getOutput(), .header, "foo.h");
    b.getInstallStep().dependOn(&install_file.step);
}
andy@bark ~/t/abc> zig build
andy@bark ~/t/abc> cat zig-out/include/foo.h
/* This file was generated by ConfigHeader using the Zig Build System. */
#define a 
andy@bark ~/t/abc> 
```

### Expected Behavior

error: missing configuration value 'b'

and a stack trace pointing at the addConfigHeader.

----

cc @MrDmitry

**Comment by MrDmitry** [comment]
Huh, I will take a look over the weekend

**Comment by MrDmitry** [comment]
Looking at https://github.com/ziglang/zig/blob/0884a434117dee3458eea8890b2e47e432844ac3/lib/std/Build/Step/ConfigHeader.zig#L760-L762 I'm not sure I'd classify this as _regression_, because it behaves like the test expects. However I agree that it's undesirable behavior. I will push a PR addressing this over the weekend.
