### ISSUE TITLE
Wrong packed/extern/plain struct size 

### ISSUE THREAD

**Issue by gaultier** [ziglang/zig#20265]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

This fails:

```zig
    const Request = packed struct {
        endianness: u8,
        pad1: u8,
        major_version: u16,
        minor_version: u16,
        authorization_len: u16,
        authorization_data_len: u16,
        pad2: u16,
    };
    comptime std.debug.assert(@sizeOf(Request) == 12);
```

(This is the [X11 connection setup](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#Encoding::Connection_Setup) struct).

### Expected Behavior

The size of the struct should be 12, but is in fact 16.

This happens even if the struct is `packed`, `extern`, or plain.

It sounds like a bug to me because the equivalent C struct is indeed 12 bytes long:
```c
#include <assert.h>
#include <stdint.h>

struct Request {
  uint8_t endianness;
  uint8_t pad1;
  uint16_t major_version;
  uint16_t minor_version;
  uint16_t auth_len;
  uint16_t auth_data_len;
  uint16_t pad2;
};

int main() { assert(sizeof(struct Request) == 12); }
```

The issue manifests when sending this struct as bytes to the X11 server, and instead of 12 bytes, 16 are sent, which breaks the protocol:

```zig
    var req = Request{};
    try stream.writeAll(std.mem.asBytes(&req));
```

**Comment by Vexu** [comment]
The `packed` structs in Zig are just integers so it has a larger size due to alignment.
```zig
comptime {
    const Request = packed struct {
        endianness: u8,
        pad1: u8,
        major_version: u16,
        minor_version: u16,
        authorization_len: u16,
        authorization_data_len: u16,
        pad2: u16,
    };
    @compileLog(@bitSizeOf(Request) / 8, @sizeOf(Request), @alignOf(Request));
    // Compile Log Output:
    // @as(comptime_int, 12), @as(comptime_int, 16), @as(comptime_int, 16)
}
```
`extern` and plain is 12 bytes as expected.

**Comment by rohlem** [comment]
To expand on the previous comment, the information is indeed 12 bytes (= 96 bits) in size, which you can even assert in the code by writing the backing type: `packed struct (u96) { ... }`.
However, this backing type `u96` is assigned a higher alignment of 16 bytes by the compiler / type system.

So, because Zig wants a `u96` to usually be 16-byte aligned, it adds padding around it for example in an array of `[2]u96`, or when written in a non-packed struct.
(Afaik the exact logic that determines this alignment and padding is build-configuration specific, and pretty much arbitrary from user perspective.)

What you can do however is to under-align a particular location (see https://ziglang.org/documentation/master/#Alignment), which will effectively remove the padding at this point.
It is also possible to specify alignment in pointer types, f.e. `*const align(4) Request`.

> The issue manifests when sending this struct as bytes to the X11 server, and instead of 12 bytes, 16 are sent, which breaks the protocol: ...

Generally, for C interop, `extern struct`-s are preferred.
However, if you're dealing with a binary protocol, I'd argue that `packed struct`-s are actually more apt.

In this particular case I'd say the issue is the fact that `std.mem.asBytes` blindly uses `@sizeOf`, which includes the padding bits.
For your use case, it should instead only reinterpret `@divExact(@bitSizeOf(T), 8)` bytes, aka check that the bit size is a multiple of 8 and only return a slice of those bytes.
IMO that's a defect of `std.mem.asBytes`, but we could also add a more strict variant `std.mem.asBytesNoPadding` if there is an argument for keeping the current version.

**Comment by gaultier** [comment]
Thank you for your replies, they make sense. 

> Generally, for C interop, extern struct-s are preferred.
However, if you're dealing with a binary protocol, I'd argue that packed struct-s are actually the correct choice here.

I agree, declaring the structure extern in the client opens the door to it using a different ABI when compiled for a different OS…I’ll experiment with packed with a custom alignment.

Maybe it’s a documentation issue that led to this misunderstanding regarding ‘packed’, and the docs could be expanded in that regard?

 Thank you in any case.
