### ISSUE TITLE
Proposal: Code after provably-reachable unreachables should error

### ISSUE THREAD

**Issue by presentfactory** [ziglang/zig#20456]
Currently if you write some code like this, you'll get an error when compiling it:

```zig
const std = @import("std");

pub fn main() void {
    unreachable;
    std.debug.print("Test", .{});
}
```

Output:

```
main.zig:5:20: error: unreachable code
main.zig:4:5: note: control flow is diverted here
```

This code on the other hand will compile fine and crash at runtime despite the fact that the compiler can in theory prove this unreachable is always hit via static analysis, and thus the print after it should certainly be considered past unreachable code:

```zig
const std = @import("std");

pub fn main() void {
    const i = 1;
    if (i != 2) unreachable;
    std.debug.print("Test", .{});
}
```

As such, I propose that if the compiler can prove an `unreachable` is hit in all control flow paths then it should generate a compiler error for any code beyond that point as expected.

As an aside, this proposal is only about code beyond an `unreachable`, but this sort of this also compiles fine which is a bit odd (no code after the unreachable but it's still always hit in execution):

```zig
pub fn main() void {
    unreachable;
}
```

Perhaps this is because the compiler cannot actually know if this function is ever called (the `unreachable` could just be used as an annotation here to say it's unimplemented for instance), but given `main` is the entrypoint on most targets it feels like the compiler if equipped with that assumption could generate better errors when unreachable is reached in general. Maybe it can't make that assumption though, but just thought I'd point that out.

**Comment by travisstaloch** [comment]
Being able to add
```zig
if (true) unreachable;
if (true) @panic("");
```
is nice when you want your program to crash while debugging and means you don't have to comment out any code below that spot.  So I think this is a good feature and I would miss it if it was gone.

**Comment by presentfactory** [comment]
@travisstaloch That's not a valid use case, sure it might be useful for you, but that's incorrect behavior and there's no gaurantee it's going to crash. Keep in mind if you're in Debug or ReleaseSafe unreachable will panic, that's not what I am talking about, I'm talking about actual undefined behavior in ReleaseFast.
Also `@panic` is not `unreachable` so this does not change the behavior of your second example.

**Comment by travisstaloch** [comment]
thats a fair point that i should be using `@breakpoint()` instead if `if (true) unreachable;`.  the downside to that is that it doesn't show a stack trace.

**Comment by xdBronch** [comment]
this is how it used to work and the effects were undesirable, see https://github.com/ziglang/zig/issues/8631

**Comment by presentfactory** [comment]
@xdBronch I don't see what's undesirable about that, people were putting unreachables in unreachable portions of code which is just a correctness issue. If the code is unreachable then why do you need to annotate that twice?

**Comment by rohlem** [comment]
Seems related to https://github.com/ziglang/zig/issues/18226 and https://github.com/ziglang/zig/issues/17234.

I think making `unreachable` behind a branch a compile error (if I understand this current proposal correctly) is difficult to formalize.
Assume you have a utility function, which just for your use case / build configuration always leads to an `unreachable` - there is some code you never hit.
Is the function wrong, because it covers a case you don't hit? Or is the set of your usage site wrong for not exercising that code path?

Moving code around from one function to the other via inlining, or making this detectable by marking arguments `comptime`, would also be transformations that, while ultimately non-functional, influence whether this new compile error is encountered.
To me it seems like we _could_ do this, if we really wanted, but I'm not sure where the benefit sweet-spot in realistic use cases is.
In my eyes the ultimate value add would be better code pipeline analysis, so people who want to can be informed of unreachable code, rather than compile errors that might be frequently unwanted. In the sense that perfect code is optimal, but enforcing perfection isn't always the next logical step.
