### ISSUE TITLE
std.process.Child.wait crashes when stdin is closed

### ISSUE THREAD

**Issue by g2mt** [ziglang/zig#20485]
### Zig Version

0.14.0-dev.142+1905137d0

### Steps to Reproduce and Observed Behavior

The following code reaches an `unreachable` statement in the stdlib:

```zig
const std = @import("std");

pub fn main() !void {
    var general_purpose_allocator = std.heap.GeneralPurposeAllocator(.{}){};
    const gpa = general_purpose_allocator.allocator();
    var process = std.process.Child.init(&[_][]const u8{"cat"}, gpa);
    process.stdin_behavior = .Pipe;
    process.stdout_behavior = .Ignore;
    process.stderr_behavior = .Ignore;
    try process.spawn();
    _ = try process.stdin.?.writer().writeAll("test\n");
    process.stdin.?.close();
    _ = try process.wait();
}
```

Errors out with a backtrace starting at

https://github.com/ziglang/zig/blob/fe66a12a23eda90b89b06dc28957f3baac01ee89/lib/std/posix.zig#L250

### Expected Behavior

Related to  #15664.

Several programs (notably scripting language interpreters and clipboard managers on Linux) read input from stdin, and will only start processing user input when and end of file is read (the stream is closed). I used cat as an example, but the code will error with other programs. The `wait` method should not fail if an input stream is closed.

**Comment by matklad** [comment]
To fix this, set `stdin` to null after closing it:

```zig
process.stdin.?.close();
process.stdin = null;
```

I'd probably say that this is working as designed right now, and the bug is in the caller, rather than in the standard library. You can't really test whether fd is closed, so there needs to be _something_ that the caller uses to signal that the fd doesn't require closing, and _something_ is settings the corresponding field to `null`. 

Perhaps there's some nice library design that removes this footgun, but I don't see a solution which doesn't require making the API more complicated.
