### ISSUE TITLE
ignore "local variable is never mutated" error if ignoring with "_ = myvar"

### ISSUE THREAD

**Issue by silbinarywolf** [ziglang/zig#20584]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Output

```zig
var myblah = 5; // <- "local variable is never mutated" error occurs
_ = myblah; // autofix
```

### Expected Output

If I'm purposefully ignoring using a variable for now, I don't want it to throw an error as I then need to change it to `const`, then remove the ignore statement, then revert from `const` to `var` while I'm prototyping things.

```zig
var myblah = 5; // <- no error should occur
_ = myblah;
```

**Comment by Rexicon226** [comment]
Not a bug. The intended way to discard `var`s is with `_ = &myblah;`.

**Comment by rohlem** [comment]
(as pointed out above)
This is currently mentioned in the [langref](https://ziglang.org/documentation/master/) twice, in unrelated tests (about vectors about pointer arithmetic).

The current compile error has a `note: consider using 'const'`.
We could additionally add notes `use '_ = &x' to suppress this error` (and `use '_ = x' to suppress this error` for the `const` case) to make it easier for people to find out about this.
Not sure what the consensus of this is -we don't want to *encourage* unclean code,
but IMO features like this currently aren't very discoverable otherwise.
We could also, or instead, add a section on `suppressing errors` to the langref.

**Comment by mlugg** [comment]
`_ = &x` is a dirty secret, and not to be encouraged. There's no intended workaround in this case: just make your variable `const`. The only reason we ever use the `_ = &x` trick in tests is to ensure something is runtime-known to demonstrate runtime behaviour.

Even in prototyping, what is your use case for this?

**Comment by silbinarywolf** [comment]
The use case is usually prototyping new behaviour within a game loop, so putting a new variable at the top of the loop:
```zig
var some_variable_we_want_to_retain_across_frames: [256]u8 | i32 // could be a buffer, an int, a struct, whatever
while (!has_game_exited) {
```

Then deeper within this large game-loop, hundreds of lines below, I'm making this variable be used for *something*.
- If its a buffer, maybe its an ImGui text field I'm testing out. 
- If it's an int/Timer, maybe im tracking time elapsed.
- If its a struct, maybe its a new entity, like a moving platform and I'm just testing it out before pulling it out into an ArrayList of that type/etc.

With Zig, the unused variable rule was initially not a big issue for me because ZLS could auto-generate the unused logic with `_ = myvar; // autofix`. This was until requiring `const` came in and broke that functionality.

**Comment by rohlem** [comment]
> initially not a big issue for me \[due to\] ZLS \[...\] until requiring const came in and broke that functionality.

I would suggest creating an issue for an autofix `_ = &x;` [in ZLS](https://github.com/zigtools/zls/issues) (surprisingly I couldn't find one already existing);
it doesn't seem like upstream Zig wants to improve usability in this regard.
