### ISSUE TITLE
--search-prefix doesn't integrate with the value of --sysroot during crossbuild

### ISSUE THREAD

**Issue by tranzystorekk** [ziglang/zig#20591]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

When testing the 0.13.0 bump for the zig package on Void Linux, trying to build a package like `river` 0.3.3 in cross errors when `--sysroot <sysroot>` is set but `--search-prefix /usr` is used, instead of `--search-prefix <sysroot>/usr`:

[river_aarch64_do_build.log](https://github.com/user-attachments/files/16189811/river_aarch64_do_build.log)

### Expected Behavior

`--search-prefix /usr` should work when correct sysroot is provided in `--sysroot`

**Comment by BratishkaErik** [comment]
> ### Zig Version
> 
> 0.13.0
> 
> ### Steps to Reproduce and Observed Behavior
> 
> When testing the 0.13.0 bump for the zig package on Void Linux, trying to build a package like `river` 0.3.3 in cross errors when `--sysroot <sysroot>` is set but `--search-prefix /usr` is used, instead of `--search-prefix <sysroot>/usr`:
> 
> [river_aarch64_do_build.log](https://github.com/user-attachments/files/16189811/river_aarch64_do_build.log)
> 
> ### Expected Behavior
> 
> `--search-prefix /usr` should work when correct sysroot is provided in `--sysroot`

IIRC it's recommended to use `--search-prefix` + `--libc` with prepended paths instead of using `--sysroot`, and (at least on Linux) it's used by compiler only to pass it to LLD so that it enables cross-compiling mode and doesn't complain about "dynamic linker not found". <sysroot> prefix should be added to the parameter and zig_libc.txt manually before invocation then.
 https://github.com/ziglang/zig/pull/19044#issuecomment-2010631603

IIRC it's also planned to remove `--sysroot` option entirely when self-hosted linker replaces lld, because it would serve no purpose.

Smth like this should work:
```bash
cat <<- _EOF_ > "zig_libc.txt"
			# Note: they are not prepended by "--sysroot" value, so repeat it here.
			include_dir=${XBPS_CROSS_BASE}/usr/include/
			sys_include_dir=${XBPS_CROSS_BASE}/usr/include/
			crt_dir=${XBPS_CROSS_BASE}/usr/lib/
			# Windows with MSVC only.
			msvc_lib_dir=
			# Windows with MSVC only.
			kernel32_lib_dir=
			# Haiku only.
			gcc_dir=
		_EOF_

--sysroot "${XBPS_CROSS_BASE}/" --search-prefix "${XBPS_CROSS_BASE}/usr/" --libc zig_libc.txt
```

https://github.com/gentoo/gentoo/pull/37283

**Comment by tranzystorekk** [comment]
Ah okay, we already had zig_libc.txt set up as above. So I understand that prepending the sysroot to search prefix is the correct approach here after all?
