### ISSUE TITLE
ziglings when building throws error 

### ISSUE THREAD

**Issue by Hitomamacs** [ziglang/zig#20775]
### Zig Version

0.14.0

### Steps to Reproduce and Observed Behavior

Trying to build ziglings with an ubuntu machine

### Expected Behavior

build process terminates without errors

**Comment by rohlem** [comment]
I see an open issue https://codeberg.org/ziglings/exercises/issues/127 and PR https://codeberg.org/ziglings/exercises/pulls/130 about recent build errors in their repository.
It's unclear whether you are double-reporting the same thing here, or something completely different.
A report here is only helpful if you are convinced that there is an issue with Zig rather than ziglings.

(Also note that Zig version `0.14.0` will be the next release and doesn't exist yet.
The nightly builds, named `0.14.0-dev...` are development versions. If you are using one of those, please provide the full version id.)

**Comment by andrewrk** [comment]
not a good enough bug report to remain open.
