### ISSUE TITLE
'var' slice declaration not triggering 'variable is never mutated' error when array contents are modified

### ISSUE THREAD

**Issue by aakashns** [ziglang/zig#21074]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Run the following code using `zig test`:

```
test "pointer slicing" {
    var array = [_]u8{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    var slice: []u8 = array[2..4];
    slice[1] += 1;
}
```

### Expected Behavior

The above code should result in a "variable is never mutated" compilation error, because `slice` itself i.e. the pointer and the length are never mutated. 

Because `slice` itself is never mutated, the following code compiles and runs fine: 

```
test "pointer slicing" {
    var array = [_]u8{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    const slice: []u8 = array[2..4]; // replaced 'var' with 'const' here
    slice[1] += 1;
}
```

Also, if I remove the `slice[1] += 1` statement, then a compilation error shows up when `slice` is declared as a var:

```
test "pointer slicing" {
    var array = [_]u8{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    var slice: []u8 = array[2..4]; // this will result in a compilation error
    @import("std").debug.print("{}\n", .{slice[1]});
}
```

It looks like `slice[1] += 1;` causes the compiler to accept both `const` and `var` declarations for `slice`.

**Comment by mlugg** [comment]
The check works like this by design -- unfortunately, anything more sophisticated is impossible with Zig's current design due to conditional compilation. Since `x[1] = y` *could* mutate `x` if it were an array value rather than a slice, it permits `x` to be a `var`. Put differently, this error message is unaware of types.

**Comment by aakashns** [comment]
Thanks for the explanation @mlugg. 

I have a couple of follow-up questions (just to improve my understand of how Zig works).

> impossible with Zig's current design due to conditional compilation

What does the term "conditional compilation" mean in this context? 

> Put differently, this error message is unaware of types.

Maybe I'm missing something, but that doesn't seem to be the case. The following code leads to a compilation error:

```zig
test "pointer slicing" {
    const array = [_]u8{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    array[1] += 1;
}
```

But the following code compiles just fine:

```
test "pointer slicing" {
    var array = [_]u8{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    const slice: []u8 = array[2..4]; // replaced 'var' with 'const' here
    slice[1] += 1;
}
```

The compiler seems to know based on type information that `slice` can be a `const`, which implies it must not be a `var` (since a `var` must be mutated or dereferenced, and therefore cannot be a `const`).

**Comment by mlugg** [comment]
Consider this code:
```zig
test {
    const x: u32 = 0;
    if (comptime_cond) {
        x += 1;
    }
}
```
This code emits a compile error only if `comptime_cond` is `true`, because if a branch is comptime-known to not be reached, it doesn't undergo semantic analysis. This is "conditional compilation", and it's a handy feature of Zig, since it allows doing the kind of thing that you might otherwise do with a preprocessor or macro system -- for instance, you can write `if (builtin.os.tag == .windows) { windows_only_logic }` and it won't emit a compile error on non-Windows. So, this example shows that emitting an error for mutating a `const` is a property of *semantic analysis*.

The opposite error -- having a `var` which is never mutated -- is more difficult. Let's suppose we did the same thing, and made it a property of semantic analysis, detecting at the end of the variable's scope whether it was ever mutated. In that case, the above example (with `var` instead of `const`) would actually emit a compile error if `comptime_cond` were `false`, because the block of code which mutates `x` is never analyzed. This is a false positive, as compiling differently -- perhaps for a different target, or with different compilation options, or maybe even calling a function containing this code with different arguments -- would *require* `var`. So, we can't have this error be triggered by semantic analysis. Instead, what we do is trigger it based on analysis of the surrounding AST. **The rule is that if a variable is ever evaluated as an lvalue -- that is, you get a pointer to it -- we assume it can be mutated, since it might be mutated via that pointer.** Proving that the variable is never mutated through this pointer is an arbitrarily complicated task (it's actually Turing-complete, since there could be arbitrary comptime logic, with a maybe-reachable-maybe-not code path which ultimately mutates the variable). So, unfortunately, this rule is as good as we can reasonably do. It's not brilliant, but it does well enough that it stops people writing `var` by default, which is the main problem!

**Comment by aakashns** [comment]
Thanks for the explanation, this is very helpful!
