### ISSUE TITLE
make all bit manipulation builtin functions take an explicit type parameter

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2119]
```
@bitReverse(value: var) @typeOf(var)
@bSwap(value: var) @typeOf(var)
@clz(value: var) math.Log2Int(@intType(false, @typeInfo(@typeOf(var)).Int.bits + 1))
@ctz(value: var) math.Log2Int(@intType(false, @typeInfo(@typeOf(var)).Int.bits + 1))
@popCount(value: var) math.Log2Int(@intType(false, @typeInfo(@typeOf(var)).Int.bits + 1))
```

**Comment by andrewrk** [comment]
> There is still not a clear way to represent the return type (even though it is well defined) for this as `math.Log2Int(T)` is incorrect...

please elaborate

**Comment by shawnl** [comment]
The return type is `math.Log2Int(@intType(false, @typeOf(T).Int.bits + 1))`. Like for `u8` they can return 0-8 inclusive, so 9 possible values.

**Comment by shawnl** [comment]
While the type is irrelevant to `@ctz()`, for consistency I think it should follow suit.

**Comment by andrewrk** [comment]
I'm still thinking about this one. Taking an explicit argument can avoid a footgun in some situations. for example `@clz` has vastly different results depending on the integer type used.

I'm also not sure what you were talking about with regards to the return types. I definitely want to examine closely whatever changes you are proposing in that regard.

**Comment by shawnl** [comment]
>  @clz has vastly different results depending on the integer type used.

They are all like that except `@popCount` for positive integers. Even `@ctz` because of the case of the integer being 0.

**Comment by shawnl** [comment]
> I'm also not sure what you were talking about with regards to the return types.
It is the same as before. Hardware makes it this way. Nothing special to what I am doing.
> I definitely want to examine closely whatever changes you are proposing in that regard.
* change function prototypes to above
* cut down on a bunch of unsafe implicit casting. `comptime_int` is no longer allowed (but comptime integers of known width are allowed), except when positive for `@popCount`.

**Comment by shawnl** [comment]
> Taking an explicit argument can avoid a footgun in some situations.\

I can code it up either way. I prefer with a type.

**Comment by andrewrk** [comment]
OK this issue went through a bunch of edits changing its meaning. But now it's exactly as described in the title. If accepted, it means that Zig has the policy that all bit manipulation intrinsics will have an explicit `comptime T: type` parameter.

 * `@popcount` - for unsigned integers it would make sense to be any type, because it doesn't really matter the bit width; a 1 is a 1. However given that it matters for signed integers, probably best to have the explicit type.
 * `@clz` - explicit type could prevent footgun
 * `@ctz` - explicit type could prevent footgun when the value is zero
 * `@bswap` - seems better to always have the type
 * `@bitreverse` - seems better to always have the type
 * `@fshl` (planned in #767) - safe bet that explicit type is OK
 * `@fshr` (planned in #767) - safe bet that explicit type is OK

Looking at this list, it seems quite reasonable to me to have a policy of explicit type parameters on bit manipulation intrinsics.
