### ISSUE TITLE
Issue when Writing to StdOut

### ISSUE THREAD

**Issue by its-popplewell** [ziglang/zig#21221]
### Zig Version

0.14.0-dev.1307+849c31a6c

### Steps to Reproduce and Observed Behavior

Here is my code and it is running generally fine and generating no errors.

`const std = @import("std");

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();

    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();

    var fin = try std.fs.cwd().openFile("./dayinputs/day1.in", .{});
    defer fin.close();

    const fin_contents = try fin.readToEndAlloc(allocator, 1024);
    var split_contents = std.mem.splitAny(u8, fin_contents, ", ");

    var next: []const u8 = undefined;
    while (true) {
        next = split_contents.next() orelse break;
        try stdout.print("{s}\n", .{next});
    }
}`

### Expected Behavior

It is supposed to be printing out each comma separated value on a new line, but the writer is putting TWO newline (or other characters like pipes) afterwards.

**Comment by Littleote** [comment]
The issue seems to be the use of `std.mem.splitAny` instead of `std.mem.splitSequence`, as the first one splits any time it finds one of the characters so for example "field1, field2" is being split like so "[field1],[] [field2]". Meanwhile, the behaviour that you want seems to be to instead split it when it find that complete sequence, so it ends like this "[field1], [field2]".
The reason for the extra new line is because the split from `std.mem.splitAny` between the comma and the space is also being printed on its own new line.

**Comment by travisstaloch** [comment]
@its-popplewell if you run into any other issues like this, please seek help in one of the [communities](https://github.com/ziglang/zig/wiki/Community).  Posting here should be a reserved for definite bugs and people in the communities can help you determine if something is a bug.
