### ISSUE TITLE
zig don't get remote package rootpath

### ISSUE THREAD

**Issue by kassane** [ziglang/zig#21232]
### Zig Version

zig-0.14.0-dev.1342+1a178d499

### Steps to Reproduce and Observed Behavior

project: https://github.com/kassane/anotherBuildStep (build-sytem add-on)
src: https://github.com/kassane/anotherBuildStep/blob/449e179e966ba95b8a2308a9982cde490b57b3d3/toolchains/zigcc.zig#L18-L20

```zig
//! in abs build.zig (from toolchains/zcc.zig)
const full_path = (comptime std.fs.path.dirname(@src().file) orelse ".") ++ "/../tools/zigcc.zig"
std.debug.print("PATH: {s}\n",.{full_path});

// in another project build.zig
const x = X.BuildStep(.{
    // [...]
   .use_zigcc = true,
   .zcc_options = try zcc.buildOptions(b, target),
});

// output
// 0.13.0 
// /home/kassane/.cache/zig/p/12206fb7ac14d6c6151e36878490fbe147687887df036398a2253fe2f59be2481183/tools/zigcc.zig
// 0.14.0-dev 
// tools/zigcc.zig (isn't local package)
```

**Note:** `/home/kassane/.cache/zig` is default `ZIG_GLOBAL_CACHE_DIR=$HOME/.cache/zig` and `/p/12206fb7ac14d6c6151e36878490fbe147687887df036398a2253fe2f59be2481183` package hashid.

- **Scheme**

```
$ zig build
---------------    -----------------
| abs-package | -> | build_project |
---------------    -----------------
```

## Reference

- https://ziggit.dev/t/how-to-get-fullpath-on-build-zig-from-v0-14-0-dev/5469

### Expected Behavior

no issue or show-me any alternative solution to get same result previously.

**Comment by mlugg** [comment]
Not a bug, see #20864. Use the `LazyPath` abstraction to deal with paths relative to `build.zig`, e.g. by using `b.path("tools/zigcc.zig")`.

**Comment by kassane** [comment]
@mlugg `b.path` not solve. Unless it is in the same subfolder.

Zig v0.14.0 interprets Path as local project and not absolute path.

**Comment by InKryption** [comment]
`b.path(rel)` returns a path `rel` which is interpreted as relative to the build root of `b`.

**Comment by kassane** [comment]
> `b.path(rel)` returns a path `rel` which is interpreted as relative to the build root of `b`.

How would I get the absolute path to `.root_source_file`?
Is there an alternative? Because I already tried `fs.realpath` and got an error during execution.

**Comment by mlugg** [comment]
You don't. The build system handles this for you. You shouldn't ever need to access the absolute path.

**Comment by kassane** [comment]
> You don't. The build system handles this for you. You shouldn't ever need to access the absolute path.

Then my zigcc-wrapper could only work (as an external package) in the current situation being:

1 - remote dependency (gist) - [get `b.dependency` path.]
2 - autogenerated and built by build.zig (main).

**Comment by kassane** [comment]
> If you want help, you'll need to actually explain your use case.

There is a mention of it in the initial description and in the diagram. This project is an add-on for the build system.
The idea is to use build.zig to call other compilers (preferably llvm-based) and optionally use `zigcc-wrapper` (without spaces [zig cc] and some hacks) to compile and/or link.

For example, this project allows me to build for `swift 6`/`flang`/`dlang`, especially fortran/flang. This is done by compiling the runtime with `zig c++` and replacing the linker with `zigcc-wrapper` and the builtins provided by zig.

Everything is also hooked to `.zig-cache`. It's unofficial support.

**Comment by kassane** [comment]
> If you want help, you'll need to actually explain your use case and the problem you're encountering.

The package is sent to rebuild the `zigcc-wrapper` with a fixed target in the `.zig-cache` for each target defined by the main `build.zig` in `zcc_options`.

**Comment by mlugg** [comment]
As explained above, you should use `b.path` for this. Replace your `.root_source_file = .{ .cwd_relative = ... }` path with `.root_source_file = b.path("../tools/zigcc.zig")`.

**Comment by kassane** [comment]
> As explained above, you should use `b.path` for this. Replace your `.root_source_file = .{ .cwd_relative = ... }` path with `.root_source_file = b.path("../tools/zigcc.zig")`.

In Both cases it always returns the same path and doesn't find `tools/zigcc.zig`.
This forces you to create a copy of the file in each project.

**Comment by kassane** [comment]
> If you still can't make it work, please open an issue which actually fills out the template adequately. You have not included precise steps to reproduce, nor the actual bug which is being caused. Include steps with the precision of "download/clone this, and run this command"; in your case, the command should emit an _unexpected error_.

Simple, please try: https://github.com/kassane/anotherBuildStep?tab=readme-ov-file#usage

Try in zig v0.13.0 and master w zcc enabled:

```zig
.use_zigcc = true, // enable zigcc-wrapper
.zcc_options = try zcc.buildOptions(b, target), // send target to zcc-wrapper
```

**Comment by mlugg** [comment]
Firstly, these steps are still not sufficient. Maintainers don't have a lot of time on their hands: if I can't reproduce your issue by pasting a sequence of commands, or cloning a single repository and running `zig build`, your reproduction is not detailed enough. Your reproduction requires me to manually set up a project based on that readme, and fix the compile error in your untested example code (!). Nevertheless, I have done this on this occasion.

Note that you also disregarded my instruction to file a new issue which contains these details. These things may not seem like a big deal to you, but they are a drain on contributors' time, because they happen a *lot*. Please try to make our lives a little easier in the future.

Regarding your actual issue here: your usage of the package manager is incorrect. You cannot just use the `std.Build` from the root package: you need to call `b.dependency`, and use the `*std.Build` in the returned `Dependency` for every file access within the package.

Something like this:
```zig
const std = @import("std");
const abs = @import("abs");
const swiftc = abs.swift;
const zcc = abs.zcc;

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // if `abs` is using `standardTargetOptions` or `standardOptimizeOption`, also pass through
    // `target` and `optimize` in the options struct here
    const abs_b = b.dependency("abs", .{}).builder;

    const exeSwift = try swiftc.BuildStep(abs_b, .{
        .name = "swift_example",
        .target = target,
        .optimize = optimize,
        .sources = &.{
            "examples/main.swift",
        },
        .use_zigcc = true,
        .zcc_options = try zcc.buildOptions(b, target),
    });
    b.default_step.dependOn(&exeSwift.step);
}
```
This fails later, because you'll now try to resolve `sources` relative to the *package*; this would need to be a slice of `LazyPath`. Also note that you still need to change your `cwd_relative` path to a `b.path(...)` as discussed above.

I recommend you avoid using custom steps; they're almost certainly going to be removed in the future, and are generally quite awkward. Instead, compile small utility programs doing whatever the step does and use `Run` steps to run them.
