### ISSUE TITLE
Pointer Arithmetic with If Ternary Expression Fails with `+=` Operator

### ISSUE THREAD

**Issue by evanlin96069** [ziglang/zig#21341]
### Zig Version

0.14.0-dev.1504+5f3d9e0b7

### Steps to Reproduce and Observed Behavior

1. Compile the following code:
```
pub fn main() !void {
    var ptr: [*]const u8 = "1234";
    ptr += if (true) 1 else 2;
}
```
2. You will observe the following error message:
```
src\main.zig:3:22: error: expected type '[*]const u8', found 'comptime_int'
    ptr += if (true) 1 else 2;
                     ^
```

### Expected Behavior

The code should compile successfully. The ternary expression should be evaluated as a `usize` and valid for pointer arithmetic.
Working examples:
```
pub fn main() !void {
    var ptr: [*]const u8 = "1234";
    ptr = ptr + if (true) 1 else 2;
}
```
```
pub fn main() !void {
    var ptr: [*]const u8 = "1234";
    const offset: usize = if (true) 1 else 2;
    ptr += offset;
}
```

**Comment by mlugg** [comment]
Caused by this incorrect result type assigned in AstGen:

https://github.com/ziglang/zig/blob/fb81522e0ba97294a475df040ccfea493342498d/lib/std/zig/AstGen.zig#L3789

This might have made sense before we had pointer arithmetic (although I think it ought to be `ty` rather than `coerced_ty`, since `add` won't necessarily perform that exact coercion!), but is incorrect now. Probably we need to add special cases for `add` and `sub` to use a new instruction to compute the result type.
