### ISSUE TITLE
Linux Native build => LibCStdLibHeaderNotFound, explicit target works fine

### ISSUE THREAD

**Issue by JohanRimez** [ziglang/zig#21376]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

_(I use Debian Bookworm)_

No matter how I try to compile a simple project in Linux, I get the same error message (LibCStdLibHeaderNotFound) when using just `zig build` or `zig build-exe ...`. 
However, everything works fine for me when using the explicit parameter `-Dtarget=x86_64-linux-gnu` or `-target x86_64-linux-gnu`

Console output:

`zig build-exe -I/usr/include/SDL2 -D_REENTRANT -lSDL2 -ODebug -I /root/my-documents/SDLTest/ZigFlowers/src -I /usr/include -I /usr/include/x86_64-linux-gnu -L /usr/lib/x86_64-linux-gnu -Mroot=/root/my-documents/SDLTest/ZigFlowers/src/FlowersMain.zig -lc --cache-dir /root/my-documents/SDLTest/ZigFlowers/.zig-cache --global-cache-dir /root/.cache/zig --name ZigFlowers --listen=-`
error: unable to create compilation: **LibCStdLibHeaderNotFound**

### Expected Behavior

I expect zig to build the executable natively in linux, without needing to explicitly specify the target.

**Comment by chrboesch** [comment]
What do you mean with "simple project", your own or just created with `zig init`?

**Comment by JohanRimez** [comment]
By that simple project, I meant a fully functional program that would need
at least some functionality from the standard c-library (using the -lc
flag, in this particular project, the SDL2-library refers to it).
The code for the project can be found here, if that would help:
https://github.com/JohanRimez/ZigFlowers
The only way I found to compile this in Linux (at least on my machine), is,
as mentioned, to add "-Dtarget=x86_64-linux-gnu" to the command line (which
shouldn't be necessary)


Op wo 18 sep 2024 om 17:30 schreef Chris Boesch ***@***.***>:

**Comment by chrboesch** [comment]
I've looked at your project and found some issues like "file 'cImport.zig' is missing" and in the build file some settings are not working. So to me it doesn't seem to be a Zig bug. Maybe discuss your project in a Zig forum (ziggit.dev or Discord) and get help there to get it working.

**Comment by JohanRimez** [comment]
Thanks for replying.
My code works like a charm. The cImport.zig is supposed to be constructed by a "`zig translate-c ... > cImport.zig`" call first. The build.zig can be used unaltered in different (cross-)compilation scenarios.

Anyway: here's a small example that won't immediately compile either in (my) Linux:
```
extern fn time(*c_longlong) callconv(.C) c_longlong;
pub fn main() void {
    var current: c_longlong = undefined;
    _ = time(&current);
    @import("std").debug.print("Time: {}\n", .{current});
}
```
Console output:
```
# zig build-exe GetTime.zig -lc
error: unable to create compilation: LibCStdLibHeaderNotFound
# zig build-exe GetTime.zig -lc -target x86_64-linux-gnu
# ./GetTime
Time: 1726682045
# 
```
I admit it's not a big deal (besides the many lost hours to pinpoint the fix): it can be easily circumvented. Still, to me, the behaviour is not in line with ZIG's prescriptions regarding "native build".

**Comment by rootbeer** [comment]
I'm on Debian Bookworm too, and your small example works for me (with or without the explicit `-target`).  I'm on a 64-bit host, are you?  I wonder what your target is defaulting to ... Can you try explicitly targeting the 32-bit and musl variations?  E.g., `-target x86-linux-musl` and see if you can trigger the problem with one of those?)  If I target the 32-bit gnu or either musl, they both still work for me, so I'd be surprised if that is different for you ...

If that doesn't help, the `LibCStdLibHeaderNotFound` error is only returned here: https://github.com/ziglang/zig/blob/feaee2ba170766cc905a6aa9c799f3105cdc8145/lib/std/zig/LibCInstallation.zig#L355  From what I can tell, in the normal case Zig will parse the output of  `cc -E -Wp,-v -xc /dev/null` to find the two default include paths.  My output looks like:

```
$ cc -E -Wp,-v -xc /dev/null
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/12/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/12/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 0 "/dev/null"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "/dev/null"
```

The lines in this output that start with a space are checked to see if "stdlib.h" and "sys/errno.h" can be found (to determine the `include_dir` and `sys_include_dir` paths respectively.)  In my case, the first path has a `sys/errno.h` and the last one has the `stdlib.h`.   If this isn't working for you, you might have environment variables set that influence the C compiler?

**Comment by rootbeer** [comment]
Yeah, I've no idea what's going on either, but it is very curious....  

Hrm, I'm guessing you don't have the 32-bit GNU linker installed (if you run `ldd` on your `x86-linux-gnu` targeted binary it will tell you which linker and libraries are expected.)  I have the required files from the Debian `libc6:i386` package (See [debian's Multiarch doc](https://wiki.debian.org/Multiarch/HOWTO)) for details on getting that set up.  If you want.   Actually ... I don't think this is the root of your problem, because the binary is obviously building just fine ...

The musl binary is statically linked, so it runs.  The fact that it prints the wrong result is probably a result of hardcoding the wrong signature for `time` when linked with musl (I see the same result).  I think this is also not relevant to your initial problem.  (Though it seems a bit odd too.)

Its odd that these explicit targets are not triggering the `LibCStdLibHeaderNotFound` not found error.  Either your default target is something else, or the poking-around-for-header-files code only runs when no explicit target is specified?  (Actually, I think this may be how Zig works, but I am not entirely sure ... I now recall something like: when you specify an explicit target, you get Zig's built-in headers, but the default target uses the system headers?)  Perhaps you're missing the glibc developer files, and just have the runtime installed?  For me its the `libc6-dev` Debian package that provides the stdlib.h header.

I'm not sure if Zig should issue a more explicit warning in this error path (e.g., something like "unable to find 'stdlib.h' C header file in any default compiler paths, cannot build against the default C library", or if this code path triggers in other cases).  But, now I know to trust that the `LibCStdLibHeaderNotFound` means exactly what it says.  :)

**Comment by JohanRimez** [comment]
Yes, well, there seems to be something with the installation of libc6 & libc6-div on my machine, which I'm not able to solve at the moment. These packages seem to be in an obscure dependency conflict.

Anyway, nothing specifically wrong on ZIG's side; just wished that Linux distros would come right out-of-the-box in a better shape, then.

I got my solution anyhow; maybe be have ZIG give more details what exactly is going wrong, might be an idea for the future.

Thanks for your time.
