### ISSUE TITLE
decl literals work through optionals but not pointers

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#21387]
### Zig Version

0.14.0-dev.1534+218cf059d

### Steps to Reproduce and Observed Behavior

not entirely sure if this is a bug or not but i didnt see any mention of either case so lmk.
```zig
test {
    const v: ?T = .init;
    _ = v;
}

const T = struct {
    const init: ?T = .{};
};
```
this passes
```zig
test {
    const v: *const T = .init;
    _ = v;
}

const T = struct {
    const init: *const T = &.{};
};
```
`error: type '*const a.T' has no members`

### Expected Behavior

i would expect this to work, though i wouldnt be too surprised if this is just a subtle rule im unaware of

**Comment by xdBronch** [comment]
a possibly less contrived example to show why this should work
```zig
const std = @import("std");
test {
    const v: *T = try .init(std.testing.allocator);
    _ = v;
}

const T = struct {
    fn init(allocator: std.mem.Allocator) !*T {
        const v = try allocator.create(T);
        v.* = .{};
        return v;
    }
};
```

**Comment by nektro** [comment]
imo the bug here is that it does work through optionals, not that it doesnt work through pointers

**Comment by xdBronch** [comment]
possibly, but it does work similarly through error unions

**Comment by Trevor-Strong** [comment]
What about something like this?

```zig
const S = struct {
    const init: S = .{};
};

fn foo(_: ?S) void {}

pub fn main() void {
    const s: ?S = .init;
    _ = s;
    foo(.init);
}
```

**Comment by mlugg** [comment]
@andrewrk this one should be an easy accept I think -- I honestly would have done this in the initial impl if I'd thought to. It's basically just saying:
```zig
// this is already allowed
const x: T = .init();
// we should also allow this
const x: *T = .create(gpa);
```
There's zero extra implementational complexity (it's a single `.pointer => break` in an existing switch in Sema), and no ambiguity or potential confusion.

**Comment by castholm** [comment]
Just want to point out that once #21390 is merged, this will allow a type nested in multiple levels of optionals/pointers/error to participate in the decl literal syntax, for example:
```zig
test {
    const s: ?**const S = try .getGlobal();
    _ = s;
}

const S = struct {
    x: usize,
    var g: *const S = &.{ .x = 1 };
    fn getGlobal() anyerror!?**const S {
        return &g;
    }
};
```
I'm not sure if this is a problem ("candidates are looked up in type the furthest to the right in the `anyerror!?**const S` token soup" is pretty easy to reason about), but it is different from the lookup for method syntax candidates which is a bit more conservative (e.g. it considers `?S` but not `??S`).
Since the method syntax and decl literals share some similarities, perhaps it would make sense to (eventually) unify these lookup/resolution rules?

**Comment by andrewrk** [comment]
Accepting based on the idea that the same rules of method call syntax should apply to decl literals.
