### ISSUE TITLE
hard float ABI passed to arm32 android compilations, which require softfp ABI

### ISSUE THREAD

**Issue by Beyley** [ziglang/zig#21488]
### Zig Version

0.14.0-dev.1632+d83a3f174

### Steps to Reproduce and Observed Behavior

Clone the `1ed2bd6b00604eceeb4cc28937eec4e962e2ea30` commit of [this repo](https://github.com/LittleBigRefresh/scetool).

install the android NDK version 21

uncomment these lines
https://github.com/LittleBigRefresh/scetool/blob/1ed2bd6b00604eceeb4cc28937eec4e962e2ea30/build.zig#L72

receive this error
```
error: sub-compilation of libunwind failed
    /home/beyley/zig-versions/master/lib/libunwind/src/UnwindRegistersRestore.S:1:1: note: clang exited with code 1
    :1:1: note: unsupported option '-mfloat-abi=hard' for target 'armv4t-unknown-linux-android'
    :1:1: note: '-mfloat-abi=hard': selected processor lacks floating point registers
```

### Expected Behavior

Compilation succeeds

**Comment by alexrp** [comment]
#21269 regressed this case inadvertently because `std.Target.Abi.floatAbi()` is not aware of Android ABIs; it's incorrectly considering these to be hard float.

However, it's a bit more complicated because `Abi.android` is not enough information to go on; it would be incorrect to report soft float for `Abi.android` for aarch64 and x86. It needs to be split into `android` (for aarch64, x86, and x86_64), `androideabi` (for arm, soft float), and `androideabihf` (for arm, hard float). Or, alternatively, `floatAbi()` needs to be changed to also take the `Cpu.Arch` value. I think I like the former approach more because it's in line with what we've done for other targets.

I'll fix this as part of my follow-up work on float ABI stuff.

**Comment by Beyley** [comment]
> #21269 regressed this case inadvertently because `std.Target.Abi.floatAbi()` is not aware of Android ABIs; it's incorrectly considering these to be hard float.
> 
> However, it's a bit more complicated because `Abi.android` is not enough information to go on; it would be incorrect to report soft float for `Abi.android` for aarch64 and x86. It needs to be split into `android` (for aarch64, x86, and x86_64), `androideabi` (for arm, soft float), and `androideabihf` (for arm, hard float). Or, alternatively, `floatAbi()` needs to be changed to also take the `Cpu.Arch` value. I think I like the former approach more because it's in line with what we've done for other targets.
> 
> I'll fix this as part of my follow-up work on float ABI stuff.

For reference, [the docs](https://developer.android.com/ndk/guides/abis) seem to say that hardfloat ABI is never used on android
