### ISSUE TITLE
proposal: remove `pub` from the language

### ISSUE THREAD

**Issue by gooncreeper** [ziglang/zig#21503]
# Proposal
Remove the `pub` qualifier from the language

# Pros

### Documentation
Removing `pub` will encourage top-level declarations to be more precisely documented on what the major and minor versions of a library is protecting. In cases where functions should really be private, their names can have a common prefix such as `internal` which also improves readability when such function is called. A language enforced-protection is just not needed.

### Increases code reusability
An example of a function where being public would serve well is `std.debug.printLineFromFileAnyOs` which has useful and **well tested** code which for example can be utilized when creating a custom stack trace output. Another example can be found in `std/zig/system/x86.zig` with `cpuid`. While these functions could easily be made public, there are hundreds more alike.

Another example is error sets which are often mistakenly kept private. Just take a look at `std.unicode`, wrangled with private error sets such as `Utf8DecodeError` and `CalcUtf16LeLenError`.

It could be argued that the lack of these being public indicates their instability but this could be solved once again with proper documentation. It could also be argued that these functions could just be duplicated though this severely hurts maintainability.

### Simplifies the language
This brings consistency with struct fields, where public / private qualifiers have been rejected. (#9909)
`pub fn main` > `fn main`

# Cons
Filtering functions on a tooling level becomes more difficult, such as with `autodoc`, though with a naming conventions such as `internal` this becomes a nonproblem.

**Comment by paperdave** [comment]
i've sometimes wanted handles to private functions, but if i recall any of those moments, they are all trying do something i should not have. in the rare case it does, just mark it `pub`!

a more objective reason this is a bad idea is to do with imports, as they are just decls initialized with `@import`, it would mean they all become public re-exports. which is terrible. consider that this code would now function, since `const windows` in `posix.zig` and `const mem` in `windows.zig` would be public decls.

```zig
const std = @import("std");
test {
  _ = std.posix.windows.mem.indexOfScalar(u8, "hello", 'l');
}
```

this makes it more confusing to find the public API manually, and impossible for tooling such as autodoc, zls, and future software to know what is an import and what is an intentional part of the api. that's what `pub` is for.

**Comment by pfgithub** [comment]
> Another example is error sets which are often mistakenly kept private. Just take a look at std.unicode, wrangled with private error sets such as Utf8DecodeError and CalcUtf16LeLenError.

This could be fixed by requiring that "pub" fns only reference types in their arguments and return value that are also public, like rust does. That way if a function is public and it returns Utf8DecodeError!u21, Utf8DecodeError would have to be made public too.

**Comment by andrewrk** [comment]
Please do not file a proposal to change the language
