### ISSUE TITLE
Incorrect 'enum tag already taken' error

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#21526]
### Zig Version

0.14.0-dev.1660+444228865

### Steps to Reproduce and Observed Behavior

```zig
pub const Op = enum(u8) { plus = '+', star = '*', bang };
pub fn main() void { _ = Op; }
```
```
$ zig build-exe src/main.zig
src/main.zig:1:51: error: enum tag value 43 already taken
pub const Op = enum(u8) { plus = '+', star = '*', bang };
                                                  ^~~~
src/main.zig:1:34: note: other occurrence here
pub const Op = enum(u8) { plus = '+', star = '*', bang };
                                 ^~~
referenced by:
    Op: src/main.zig:1:16
    main: src/main.zig:4:9
    5 reference(s) hidden; use '-freference-trace=7' to see all references
```

### Expected Behavior

`bang` to be assigned one of the 253 free values in the `u8`.

**Comment by rohlem** [comment]
Currently (as I think is the case in C), tags without an explicit value are assigned by incrementing from the previous tag's value.
I'm pretty sure this is intended behavior, see [`test "enum implicit ordinal values and overridden values"`](https://ziglang.org/documentation/master/#enum) in the langref.

Your example can be fixed by reordering `plus` and `star`, so that `bang` is assigned the value `'+' + 1`.
Does that address your original use case?

**Comment by leecannon** [comment]
Ah, yea good catch.
