### ISSUE TITLE
New Architecture: Parallax Propeller

### ISSUE THREAD

**Issue by ikskuh** [ziglang/zig#21559]
i'm planning to work on a project with the [Parallax Propeller 2](https://www.parallax.com/propeller-2/documentation/) and i didn't want to waste my time with C again.

I want to use the C backend to compile Zig to C and leverage existing compilers to work with Zig instead of C.

Can we add a `propeller` and `propeller2` architecture with each having only a `generic` cpu with no cpu features?

Byte size is 8 bit, word/register size is 32 bit

The required address spaces are `ram` and `cog` for both architectures, and propeller2 has an additional `lut` address space.

Related: #7202

I'll try doing that myself when it's accepted to be done

**Comment by alexrp** [comment]
Based on Andrew's previous comment [here](https://github.com/ziglang/zig/pull/20835#issuecomment-2257329427), I would suggest just going ahead with a PR. It doesn't seem to me like this would be controversial.

That said, a couple of questions:

* What sets `propeller2` apart from `propeller` that makes it worthwhile to have it be a separate `Arch` tag rather than modelling it with a CPU feature?
* Has this architecture been used in the GNU ecosystem at all? If so, is there a precedent for what the architecture component of the triple should be called, and are we following it?

**Comment by ikskuh** [comment]
> What sets propeller2 apart from propeller that makes it worthwhile to have it be a separate Arch tag rather than modelling it with a CPU feature?

Completely different ISA :rofl: 

> Has this architecture been used in the GNU ecosystem at all? If so, is there a precedent for what the architecture component of the triple should be called, and are we following it?

https://www.parallax.com/propeller-2/programming-tools/

Not that i know of, but there's a LLVM port: https://github.com/ne75/p2llvm

**Comment by andrewrk** [comment]
Go for it :+1:

**Comment by alexrp** [comment]
https://github.com/parallaxinc/propgcc/blob/b280e7a77103d479e82cc687711de6a45579ad70/gcc/gcc/config.gcc#L404-L406

FWIW, it doesn't seem like they're using a distinct `propeller2` component. That's not to say that wouldn't make sense, just that it might be interesting to investigate why.
