### ISSUE TITLE
Slicing bypasses "local variable is never mutated" error

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#21576]
### Zig Version

0.14.0-dev.1694+3b465ebec

### Steps to Reproduce and Observed Behavior

`zig run` the following file:

```zig
pub fn main() void {
    var buf: [1]u8 = .{0};
    var ptr = &buf;
    _ = ptr[0..];
}
```

Observed: no compile error

### Expected Behavior

Compile error "local variable is never mutated" on the line `var ptr = &buf;`

**Comment by wooster0** [comment]
This is a valid way to discard the error. You're taking a mutable pointer `*[1]u8` using `ptr[0..]`, same as `&ptr`.

**Comment by mlugg** [comment]
The error message should not be reworded.

Mutable reference is the heuristic we use to determine whether a local variable might ever be mutated; it's easy to work around, but it catches common cases. Having a completely accurate check for whether `var` is unnecessary is a Turing-complete problem, and analysis is particularly constrained in Zig due to `comptime` execution. Making the error message here more "technically accurate" would hide what it's actually trying to tell the user; in fact, the existing message is completely accurate, we just don't catch all code where that error would be applicable.

This is the case for all kinds of errors. For instance, you can write code which *always* performs illegal operations with `undefined` values, but does not trigger a `error: use of undefined value causes undefined behavior` compile error. This is exactly the same thing: you *can* write code with a never-mutated `var` which doesn't trigger the error message, but that doesn't mean the error message is wrong when it does happen.

**Comment by dbandstra** [comment]
Thanks for the explanation.

Btw, the case I actually encountered before making this issue was more like 

```
    var buf: [1]u8 = .{0};
    var ptr: []const u8 = &buf;  // rather than *[1]u8
    _ = ptr[0..];
```

Maybe this special case could have been caught by the compiler but I can see why you might want to stick with a simple rule.
