### ISSUE TITLE
utf32 in std.unicode

### ISSUE THREAD

**Issue by bugsbugsbux** [ziglang/zig#21733]
Hi, I kindly ask to add support for utf32 to the std.unicode module! Since the use of emoji became widespread, utf16 does not cut it anymore as a way of representing most contemporary western texts in same-width elements, which makes it much easier to work with.

Kind regards

**Comment by neurocyte** [comment]
Unicode codepoints are represented as u21 in std.unicode because the maximum allowed codepoint in UTF-32 (aka UCS-4) only requires 21 bits. The term UTF-32 is not used, but the support is there. Whenever you see a function with `Codepoint` in the name, or `u21` as an argument or return value type, it supports UTF-32 encoded codepoints.

I hope this helps.
