### ISSUE TITLE
compiler_rt function `__aeabi_memcpy` calls itself (ARM/Thumb)

### ISSUE THREAD

**Issue by GalaxyShard** [ziglang/zig#21831]
### Zig Version

0.14.0-dev.2051+b1361f237

### Steps to Reproduce and Observed Behavior

```zig
// build.zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const optimize = b.standardOptimizeOption(.{});
    // make a empty Zig file
    const stub_file = b.addWriteFile("stub.zig", "\n");
    const stub_path = stub_file.getDirectory().path(b, "stub.zig");

    const target = b.resolveTargetQuery(.{
        .cpu_arch = .arm,
        .os_tag = .freestanding,
        .abi = .eabi,
    });
    //const target = b.standardTargetOptions(.{});

    const compiler_rt = b.addObject(.{
        .name = "compiler_rt_hack",
        .target = target,
        .optimize = optimize,
        .root_source_file = stub_path,
        .strip = true,
    });
    compiler_rt.bundle_compiler_rt = true;
    compiler_rt.link_data_sections = true;
    compiler_rt.link_function_sections = true;

    b.getInstallStep().dependOn(&b.addInstallFile(compiler_rt.getEmittedBin(), "compiler_rt.o").step);
}
```

Running `zig build --release=safe` and `llvm-objdump -D zig-out/compiler_rt.o | less` will produce the following:

```asm
Disassembly of section .text.__aeabi_memcpy:

00000000 <__aeabi_memcpy>:
       0: eafffffe      b       0x0 <__aeabi_memcpy>    @ imm = #-0x8
```

This also occurs when compiling in debug mode, with/without link_data_sections/link_function_sections, and on thumb-freestanding-eabi.

### Expected Behavior

The function should have an actual implementation that isn't just a call to itself.

**Comment by alexrp** [comment]
The problem here is that whoever translated these routines (`__aeabi_memcpy`, `__aeabi_memcpy4`, etc...) from LLVM's compiler-rt converted them from assembly code to normal Zig code. In the original assembly, these contain calls to `memcpy()` which can't be touched by the compiler. That's obviously not the case for normal Zig code.

The immediate fix for this is to make these functions use inline assembly to call `memcpy()`. Long term, it would be nice if we had something like `std.builtin.CallModifier.never_intrinsify` which would correspond to LLVM's `nobuiltin`...
