### ISSUE TITLE
Zig not consuming buffer from stdio

### ISSUE THREAD

**Issue by Dispersia** [ziglang/zig#21968]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```
const std = @import("std");

pub fn main() !void {
    var buffer: [1]u8 = undefined;

    const reader = std.io.getStdIn().reader();
    var fbs = std.io.fixedBufferStream(&buffer);
    try reader.streamUntilDelimiter(fbs.writer(), '\n', fbs.buffer.len);
}
```

if you pass a value like `1echo "Hello World"` it will instantly exit correctly, however then run echo "Hello World" and instantly execute it

### Expected Behavior

the buffer should be consumed by the zig program and not return the rest to the terminal? I don't actually know how the buffer is read in or at what stage is the "correct" thing to do, but the above seems relatively easily exploitable. I tested on arch with fish/sh/zsh just to make sure it wasn't a shell specific thing

**Comment by prathik-kaliyambath** [comment]
I experienced this too when trying to run something.
Is this an issue though?
I maybe wrong here, but you're writing the program which allocates 1byte, how can that program consume any more?

**Comment by prathik-kaliyambath** [comment]
I ran into something similar when testing something out.
Is this an issue though?
You are writing a program that expects 1 byte of input from the user and it reads exactly that. I thought this is the expected behaviour.
Additionally, I maybe wrong here, but I don't think you can exploit this, as someone running zig run main.zig on a terminal and entering 1echo "Hello World" as Input, already has access to this terminal, so you could just write echo "Hello World" anyway.

**Comment by AndrewKraevskii** [comment]
As a temporary fix you can add this to consume the rest of the line 
```zig
const std = @import("std");

pub fn main() !void {
    var buffer: [1]u8 = undefined;

    const reader = std.io.getStdIn().reader();
    errdefer |e| if (e == error.StreamTooLong) reader.streamUntilDelimiter(std.io.null_writer, '\n', null) catch {};
    // ^^^^
    var fbs = std.io.fixedBufferStream(&buffer);
    try reader.streamUntilDelimiter(fbs.writer(), '\n', fbs.buffer.len);
}
```
