### ISSUE TITLE
zig fetch: inconsistent redirect handling between http and git+http remotes

### ISSUE THREAD

**Issue by rockorager** [ziglang/zig#21976]
### Zig Version

0.14.0-dev.2059+cdd8e82f0

### Steps to Reproduce and Observed Behavior

```sh
# Fails to follow redirect
zig fetch git+https://codeberg.org/dude_the_builder/zg#v0.13.2

# Successfully follows redirect
zig fetch https://codeberg.org/dude_the_builder/zg/archive/v0.13.2.tar.gz
```

### Expected Behavior

Both methods (`git+http` and `http`) of retrieving a package at a given URL should have the same redirect behavior. Either both should fail on redirect, or both should succeed.

Currently any `git` protocol redirect fails to fetch.

I make no recommendations on the behavior that *should* happen, other than the behavior should be the same.

**Comment by ianprime0509** [comment]
I agree that the behavior should be consistent. Banning redirects for HTTP(S) packages would not be viable: GitHub's release artifact URLs, for example, redirect to temporary S3 URLs which should definitely not be considered canonical in any way. I've opened #22022 to update the Git package fetching logic to behave the same as HTTP(S) and transparently follow redirects.

It might be arguable that the old "strict" behavior has a place in cases where the HTTP response code indicates a _permanent_ redirect rather than a temporary one, but in the context of this issue, https://codeberg.org/dude_the_builder/zg responds with an HTTP 307 ("Temporary Redirect") to https://codeberg.org/atman/zg rather than a permanent redirect, so it's probably not worth the trouble if servers aren't using the correct semantics regardless.
