### ISSUE TITLE
&arr make a copy of the array

### ISSUE THREAD

**Issue by wangzaixiang** [ziglang/zig#22140]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Given a zig source:

```zig
const std = @import("std");

const SIZE = 1024 * 256;
pub fn main() !void {
    var arr: [SIZE]u32 = undefined;
    for (arr, 0..) |_, i| {
        arr[i] = @intCast(i);
    }
    std.debug.print("main &arr = {*}\n", .{&arr});
    std.debug.print("main &arr = {*} same as above \n", .{&arr}); // same as above

    std.debug.print("\npassArray for mutable array\n", .{});
    passArray(arr);
}

fn passArray(arr: [SIZE]u32) void {
    const p1: *const [SIZE]u32 = &arr;
    const p2 = &arr;
    const p3: [*]const u32 = &arr;
    std.debug.print("inside passArray &arr = {*} p2 = {*} p3 = {*}  p1 != p2 != p3 \n", .{ p1, p2, p3 });

    const LOOP = 3; // when LOOP = 14, the program will crash

    std.debug.print("LOOP = {} \n", .{LOOP});
    inline for (0..LOOP) |_| {
        std.debug.print("inside passArray, &arr = {*} not same as above.\n", .{&arr}); // &arr increase SIZE * 4 every time
    }
}

```

It runs with result `zig run -O ReleaseFast demo.zig`:

<img width="1367" alt="image" src="https://github.com/user-attachments/assets/7084e8c2-87fe-415e-af6d-628f2f23e643">

Also, if the LOOP here is 14, the program will crashed because of stack OOM.

### Expected Behavior

&arr should return the address without copy the array.

**Comment by mlugg** [comment]
This is caused by some weird logic in `AstGen.rvalueInner` whose purpose I don't understand:

https://github.com/ziglang/zig/blob/6188cb8e50882a55c90578114556c6d1b7073e9d/lib/std/zig/AstGen.zig#L11205-L11206

This code is explicitly disabling `ref` deduplication for parameters and inferred stack allocations (note that the latter case would actually correspond to `&&some_local`). I'm pretty sure this logic should just be deleted, but I'll take a look at the blame before I do that to try and understand why this is here.

**Comment by mlugg** [comment]
It looks like this logic was added for the `isParam` case by Andrew in f4d5fcd without explanation, and expanded to the `isInferred` case by Veikka in 4ac8ec4. The latter at least has test coverage, so I expect that if removing this logic triggers a bug, CI will catch it.

@andrewrk, @Vexu; long shot, but do either of you happen to remember why this special case is here?
