### ISSUE TITLE
Calling as member function disables never mutated error

### ISSUE THREAD

**Issue by patrik-gustavsson** [ziglang/zig#22184]
### Zig Version

0.14.0-dev.1472+3929cac15

### Steps to Reproduce and Observed Output

In the following code I correctly get the error "local variable is never mutated", but if the last line in the main function is uncommented, the error disappears even though the same function call is made with the same variables.
```zig
const std = @import("std");

const V2 = struct {
    x: f32,
    y: f32,

    const Self = @This();
    pub fn mul(self: Self, other: Self) Self {
        return .{ .x = self.x * other.x, .y = self.y * other.y };
    }
};

pub fn main() void {
    var v0 = V2{ .x = 1, .y = 2 };
    const v1 = V2{ .x = 2, .y = 1 };

    std.debug.print("{d}", .{V2.mul(v0, v1).x});
    //std.debug.print("{d}", .{v0.mul(v1).x});
}
```
I assume this is wrong behavior since the function uses Self without pointer, therefore, it can never mutate. I also noticed that if `*const Self` is used then the error is also disabled, I assume that this is wrong behavior as well since the value can never mutate.

### Expected Output

To always receive `error: local variable is never mutated` even if calling as member function.

**Comment by rohlem** [comment]
I don't think this is reasonably implementable in the perspective Zig currently takes here.
Example scenario:
```zig
const M = struct {
    fn method(_: *M) void {} //able to mutate argument
};
const C = struct {
    fn method(_: C) void {} //unable to mutate argument
};
pub fn callMethod(comptime T: type) void {
    var x = T{};
    x.method(); //mutates if T == M, not if T == C
}
test callMethod {
    const include_mutating_variant = false; //could be a build setting, depend on target, etc.
    if (include_mutating_variant) { //this if's body is only semantically analyzed if the condition results in true
        callMethod(M);
    }
    callMethod(C);
}
```

As far as I know, the current error is implemented purely based on the AST, which means it can be done before / regardless of any type checking.
This also makes it consistent regardless of any `comptime` evaluation that might be happening in the code.

If we go forward with your proposal, then to know whether the expression `a.b()` passes a mutable pointer to `a` in a particular instantiation,
we need type information, which is only available at a later stage during semantic analysis, and can depend on other code, as seen in my example:
`callMethod(M)` calls an instantiation where `x` needs to be `var`, while `callMethod(C)` calls an instantiation where `x` could have been `const` as well.

Because the set of instantiations can vary based on build settings
(such as the target platform - maybe the windows implementation needs mutable data where the unix path wouldn't),
this would affect whether a `var` is ever passed by pointer-to-mutable or not.
The status-quo rules can be decided without having to analyze every function instantiation of every possible build configuration.

**Comment by patrik-gustavsson** [comment]
I see your point and understand why this cannot really work with the current implementation of Zig. It would be feasible if the syntax enforces a distinction between calling mutable and non-mutable functions, but having to use `x.*.method()` and introducing a way to distinguish mutable/non-mutable functions with comptime types seems like a lot of effort for little benefit.
