### ISSUE TITLE
It should be possible to run tests without installing first

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2221]
It should be possible to test zig after compiling but before installing it.

Currently `./zig build --build-file ../build.zig test` fails with `Unable to find zig lib directory`,
as it tries to access the non-existant `/usr/lib/zig`.

**Comment by andrewrk** [comment]
Not supported. Zig requires being installed in order to function correctly, and the test suite tests a fully functional Zig.

**Comment by tiehuis** [comment]
I think this is the best strategy for pre system install testing. Only requires recompilation of link.cpp and a relink.

```
mkdir test_dir
cmake .. -DCMAKE_INSTALL_PREFIX=test_dir
make install
./test_dir/bin/zig --build-file ../build.zig test
rm -rf test_dir

cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make install
```

**Comment by daurnimator** [comment]
> Zig requires being installed in order to function correctly

Why?

Could you just make the zig_lib_dir configurable either via command line arg or env var?

**Comment by andrewrk** [comment]
Let me reconsider this. None of the installed files are "modified" versions of the files in the source directory, so if we have the source directory mirror the install directory, it should be reasonable to override the install directory for tests.

**Comment by andrewrk** [comment]
#2892 brought us one step closer to this. Shipped files, except std/, are all in `lib`, and --override-lib-dir can be used on that directory. I'll move `std` in there too but first would like to merge more PRs first to prevent conflicts.

**Comment by andrewrk** [comment]
#3315 mostly solves this problem. The only thing left is that it seems impossible in cmake to add a custom command for `make install`. Because of that, lib/ files are getting installed during `make`. (as well as `make install`). But after #3315, `./zig build test` will run the test suite without requiring installing.

The only workaround I can think of here is adding a cmake option `-DSKIP_INSTALL=ON` which simply disables copying lib/ files during `make` (and `make install`). Then you'd do your tests. Then you'd run cmake again with `-DSKIP_INSTALL=OFF`, and `make install`. I'm pretty sure this would work. Would it solve your use case?

I believe @Sahnvour would be interested in such an option as well, since he was asking about avoiding these file system operations.
