### ISSUE TITLE
Semantic analysis takes too long

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#22236]
In Bun's repo, semantic analysis for a debug build takes 19 seconds on a high-end M3 mac:

```zig
❯ vendor/zig/zig build check --summary new
info: zig compiler v0.13.0
Build Summary: 4/4 steps succeeded
check success
└─ zig build-obj bun-debug Debug native-native.13.0 success 19s MaxRSS:1G
   └─ options success
```

This is not compiling Bun - this is like `-fno-emit-bin`.

For `ReleaseFast`, semantic analysis takes 27 seconds:
```zig
❯ vendor/zig/zig build check --summary new -Doptimize=ReleaseFast
info: zig compiler v0.13.0
Build Summary: 4/4 steps succeeded
check success
└─ zig build-obj bun ReleaseFast native-native.13.0 success 27s MaxRSS:1G
   ├─ options success
   └─ translate-c success 50ms MaxRSS:44M
```

If we run `htop` while it runs,, we can see that semantic analysis in single-threaded (there are other things running on my computer at the same time): 

<img width="618" alt="image" src="https://github.com/user-attachments/assets/84bde00a-b471-4053-bb7a-37197ad8bfa6" />

If our code is spending a lot of time in comptime, how can we see what is taking up time (an equivalent of `-ftime-trace`)?

Is there a tracking issue for improving the performance of semantic analysis? Is it going to become multi-threaded?

### Why does this matter?

Sema is the bottleneck for how long it takes to see compiler errors. To cope with the compile times, we have to do sema in our head and batch up changes into less frequent builds. This hurts iteration velocity.

**Comment by mlugg** [comment]
This is sort of a duplicate of #4055; while that issue focuses on comptime code execution, improving that will also improve overall semantic analysis speed, since those things are one and the same in Zig.

Compiler performance is more generally tracked by https://github.com/orgs/ziglang/projects/2.

Compiler performance remains our main focus at the minute. That's why we're working on incremental compilation, self-hosted code generation, and, yes, parallelizing semantic analysis. The "Roadmap" sections at the ends of release notes always outline our main focuses for the following release cycle; the [0.13.0 release notes](https://ziglang.org/download/0.13.0/release-notes.html#Roadmap) list our focuses for the current release cycle as including incremental compilation and concurrent semantic analysis.
