### ISSUE TITLE
std.math.pow does not support vectors

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#22354]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test {
    const vec4 = @Vector(4, u32);
    const a: vec4 = .{ 1, 2, 3, 4 };
    const b: vec4 = @splat(2);
    const c: vec4 = .{ 1, 4, 9, 16 };
    try std.testing.expectEqual(c, std.math.pow(vec4, a, b));
}

test {
    const vec4 = @Vector(4, f32);
    const a: vec4 = .{ 1, 2, 3, 4 };
    const b: vec4 = @splat(2);
    const c: vec4 = .{ 1, 4, 9, 16 };
    try std.testing.expectEqual(c, std.math.pow(vec4, a, b));
}
```

```
/home/meghan/.local/share/zig-0.13.0/lib/std/math/pow.zig:39:9: error: pow not implemented for @Vector(4, u32)
        @compileError("pow not implemented for " ++ @typeName(T));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/meghan/.local/share/zig-0.13.0/lib/std/math/pow.zig:39:9: error: pow not implemented for @Vector(4, f32)
        @compileError("pow not implemented for " ++ @typeName(T));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

all tests passed

**Comment by mlugg** [comment]
[No proposals on the issue tracker, please.](https://github.com/ziglang/zig/wiki/Language-Proposals)

**Comment by nektro** [comment]
didn't see this as a proposal

**Comment by bg-thompson** [comment]
> didn't see this as a proposal since it represents missing behavior
> 
> edit: also this isn't a language proposal

@nektro I don't see this missing behavior, since a power function doesn't feel like a natural fit for SIMD instructions.

Consider for example `@min()` and `@floatFromInt()`. In both of these cases there are already SIMD instructions that do these operations for certain types of vectors. (E.g. `MINPS`, `CVTPI2PS` --- see https://en.wikipedia.org/wiki/X86_SIMD_instruction_listings for more.) Therefore it's natural for a programming language to support them.

Now consider a more complicated arithmetic function like `@sin()`. While there does exist a x86 instruction for it, (`FSIN`) at least to my knowledge there does not exist a SIMD instruction for it. This is still okay since a SIMD algorithm has been worked out for it. (See for example Intel's *Short Vector Math Library (SVML)*). It's also such an essential math function that we may very well see CPU makers roll out a new SIMD instructions for `@sin()` in the future.

In contrast, at least to my knowledge, there is no obvious way to do a power function in a SIMD manner, at least for integers. In my experience it's also not as common or important compared to things like @sqrt or @exp(). Therefore it's not a natural fit for SIMD, so I don't see this as missing behavior.
