### ISSUE TITLE
add an error for using `var` when one could have used `const`

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#224]
```zig
fn add(a: i32, b: i32) {
    var x = a + b;
    return x;
}
```

Should give error: x should be declared const

**Comment by daurnimator** [comment]
I think this should be a warning; not an error.

When debugging/prototyping, it's useful to comment out a line without having to refactor, e.g.

```zig
fn foo(a: i32, b: i32) {
    var x = a + b;
    // x = x + 4
    return x;
}
```

**Comment by tgschultz** [comment]
Zig doesn't have warnings.

I feel like, if we're not going to trust the programmer on this, and the compiler can tell if a variable should be const or not, then why even make the programmer specify that information?

**Comment by vi** [comment]
If such error is implemented, it should be ignorable at function / scope / var level using some attribute.

Unused non-constness can arise from generic / code generation context.

**Comment by user00e00** [comment]
Maybe there should be warnings in zig, but instead of calling them "warnings", they should be called "debug-suppressed errors".

* When releasing a project, you want to optimize for readability and maximize the amount of assumptions the reader can make while reading code.
* When debugging, you want as little friction as possible while modifying code.

I think both of these are valid requests, but you cannot really have both (at the same time).

Some compile time checks should be skipped in debug mode if they add too much friction, IMO.

**Comment by vi** [comment]
Suppressing this error should not be debug-only.

For example, in following code and in similar code, but generated outside Zig (code generation), `var q` should not require changing to `const q` if both blocks are happen to be excluded.

```zig
pub fn chunk_by_chunk(comptime a : bool, comptime b: bool) u32 {
    var q : u32 = 0;
    if (a) {
        q += 4;
    }
    if (b) {
        q += 1;
    }
    return q;
}

pub fn main() void {
    var q : u32 = chunk_by_chunk(false, false);
    @import("std").debug.warn("{}\n", q);
}
```

**Comment by hryx** [comment]
I love this because it further guides authors to optimal code.

Questions:

1. Will this affect non-pub globals too? Or just statements?
2. One use case for intentionally using `var` over `const` is forcing non-comptime values in tests. Will underscore come to the rescue here?

```zig
test "var" {
    var x: u8 = 1;
    _ = x;
    switch (x) {
        // test some behavior here
    }
}
```

**Comment by Sobeston** [comment]
Too add to this, how about disallowing self: *@This() when self is not modified. Perhaps these sanity checks could be moved to zig fmt, or a new tool like "zig vet" or similar.

**Comment by ThomasKagan** [comment]
Also, will authors be guided to pass by copy when a pass by pointer is not mutated?

**Comment by SpexGuy** [comment]
>To add to this, how about disallowing `self: *@This()` when self is not modified.

This check may not be possible to do robustly.  Here's an example:
```zig
pub const DualRandom = struct {
    seeds: [2]u64,
    salt: u64,
    
    pub fn next(self: *@This()) u64 {
        if (global_use_first_random) {
            return self.computeNext(&self.seeds[0]);
        } else {
            return self.computeNext(&self.seeds[1]);
        }
    }
    
    fn computeNext(self: *@This(), seedPtr: *u64) u64 {
        const oldSeed = seedPtr.*;
        const salt = self.salt;
        // do math with old seed and salt
        const newSeed: u64 = ...;
        const nextRandom: u64 = ...;
        seedPtr.* = newSeed;
        return nextRandom;
    }
};
```

With only information available at function scope, the compiler will require the `self` parameter of computeNext to be const.  But because const guarantees that the underlying data will not be modified, making `self` const creates unchecked UB when seedPtr is written.  If the compiler decides to inline `computeNext`, it may recognize that the call is unconditional UB and "optimize" it away completely.

**Comment by LakeByTheWoods** [comment]
> For example, for the unused variable error, you could use _ = x; to explicitly silence the error. For the "should have used const" error, I actually don't have a recommendation other than to change the var to const.


You could have a `@used() ` builtin which is a nop but takes a pointer to a non-const var.

**Comment by pmwhite** [comment]
> When debugging/prototyping, it's useful to comment out a line without having to refactor, e.g.

To improve the developer experience in this case, and in other cases where the structure of some new code is still unclear, `zig fmt` could have a a "--auto-change-constness" option. The option would cause the formatter to change `const` to `var` when the variable is actually mutated, or `var` to `const` when it was not. This would remove the programmer's burden of changing between `var` and `const` without the sacrifice to readability. In addition, it would remove the initial burden of choosing between `var` and `const` when declaring a variable - it is often difficult to tell whether the variable will have to be mutated or not. The downside, which probably means this should be an opt-in option, is that if a programmer wants to use `const` as a coding guarantee to himself that he will not change a variable later, he might accidentally modify the variable and never know that his `const` changed to a `var`.

**Comment by pixelherodev** [comment]
```
With only information available at function scope, the compiler will require the self parameter of computeNext to be const. But because const guarantees that the underlying data will not be modified, making self const creates unchecked UB when seedPtr is written. If the compiler decides to inline computeNext, it may recognize that the call is unconditional UB and "optimize" it away completely.
```

@SpexGuy That doesn't sound right. In the example you gave, even if you make self const it should be fine, since it's being modified through seedPtr, which is passed explicitly as a pointer-to-mutable data, and not through self.

**Comment by SpexGuy** [comment]
You are right, my understanding of const was incorrect when I wrote that.  I'll update it to reflect that.  But I believe there is still a similar case that is UB.  If the parameter were changed to `self: @This()`, the mutable pointer was written, and then the value backing the mutable pointer was read from `self`, that read would be UB since `self` is a const value.  But if the parameter were `*const @This()` or the modified value was not read back, `self` is a const view and there is no UB.

**Comment by SpexGuy** [comment]
Setting the UB argument aside though, there are three reasons that I don't like the idea of enforcing const on pointers.

### 1) It leaks implementation details

As an example, consider an array list struct:
```zig
const Array = struct {
    capacity: usize,
    items: []u32,
    
    fn initPresized(allocator: *Allocator, size: u32) !Array {
        const items = try allocator.alloc(u32, size);
        return .{ .items = items, .capacity = size };
    }
    
    fn set(self: @This(), index: usize, value: u32) void {
        items[index] = value;
    }

    // other functions omitted
};
```

For some use cases of this struct, it is const, even if we are semantically modifying it.
The `const`-ness of `arr` in the following example is purely an implementation detail.
```zig
const arr = Array.initPresized(32);
var i = arr.items.len;
while (i > 0) {
    i -= 1;
    arr.set(i, 31 - i);
}
```

And it's something that can change.  Say we now wish to optimize this array to use an inline buffer:
```zig
const Array = struct {
    const BUFFER_SIZE = 10;
    const T = u32;

    capacity: usize,
    len: usize,
    data: union {
        inline: [BUFFER_SIZE]T,
        external: [*]T,
    },
    
    fn initPresized(allocator: *Allocator, size: T) !Array {
        if (size > BUFFER_SIZE) {
            const items = try allocator.alloc(T, size);
            return .{ .len = size, .capacity = size, .data = .{ .external = items.ptr } };
        } else {
            return .{ .len = size, .capacity = BUFFER_SIZE, .data = .{ .inline = undefined } };
        }
    }
    
    fn set(self: *@This(), index: usize, value: T) void {
        self.span()[index] = value;
    }
    
    fn span(self: *@This()) []T {
        return if (self.capacity <= BUFFER_SIZE)
            data.inline[0..self.len]
        else data.external[0..self.len];
    }

    // other functions omitted
};
```

Now our example doesn't compile, because `arr` must be mutable.  This  is a problem with both the original proposal and the extension to require it on pointers, but with the original proposal this effect is bounded to local variables.  With const required on pointers, we have problem 2:

### 2) It's viral

Let's refactor the above example a bit.
```zig
fn fillReverseSequence(arr: *const Array) void {
    var i = arr.len;
    while (i > 0) {
        i -= 1;
        arr.set(i, arr.len - 1 - i);
    }
}
```

In this new example, the constness of the pointer to Array depends on whether `arr` uses an inline array or not.  This decision bleeds to every caller of this function.  If callers of this function take arr as a pointer parameter, the decision bleeds out to their callers.  This effect is unbounded, and can make optimizations that change the constness of an operation require a prohibitive number of changes throughout the entire source.  People who dislike const sometimes refer to this as 'const poisoning'.  The way to avoid const poisoning is to make sure that the `const`-ness on your function boundaries is semantic constness, not implementation constness.  If the compiler enforces that all function boundaries use implementation constness, it will cause const to be extremely viral, and we will need something akin to C++'s `mutable` or `const_cast` for any sort of refactor.  This could lead to an erosion of the usefulness of const over time in very large codebases, as more and more refactors introduce mutable fields because changing constness would require massive alterations to parameter lists throughout the codebase.  Even changing a field to be const when it wasn't before becomes prohibitive.

### 3) It interferes with metaprogramming

Consider this function:
```zig
fn callFooOnAll(slice: var) void {
    for (slice) |item| {
        item.foo();
    }
}
```
What are the requirements for this to compile with the current rules?
- if `foo()` takes a const self parameter, the slice can be any of `[]T`, `[]*T`, `[]const T`, `[]*const T`, `[]const *const T`, `[]const *T`.
- if `foo()` takes a mutable self parameter, the slice must be one of `[]*T`, `[]const *T`.  `[]T` doesn't work because the loop capture is const, you would need `*item` for that case.

The safe set of types to call this with if the constness of foo's parameter is unknown is the union of these two sets, which is `[]*T` and `[]const *T`. Changing const to be enforced would mean that when `foo()` takes const self, the function would only compile for `[]const T` and `[]const *const T`, which reduces the safe set to zero.  Since the parameter is `var/anytype`, all callers of `callFooOnAll` must know whether or not foo() is const and adjust the type they are passing in accordingly.  If the caller is also generic, that means they would have to write code to inspect the parameters of `foo` and cast to the correct constness in order to make the code compile.  This becomes exponentially difficult as the number of parameters increases.  In this example, there need to be four code paths to call this function depending on the constness of `foo`'s two params:

```zig
fn zip(slice: var, params: var) void {
    for (slice) |item, i| {
        item.foo(params[i]);
    }
}
```

Having all implementations of `foo()` always be const or non-const doesn't work either, because that's also enforced by the compiler.  It could be made always non-const with workarounds like `_ = &self`, but this still greatly increases the difficulty of writing correct generic code, and the new types of mistakes are only detected if specific instantiations are compiled.

**Comment by pixelherodev** [comment]
```

**Comment by pixelherodev** [comment]
```
If the parameter were changed to self: @This(), the mutable pointer was written, and then the value backing the mutable pointer was read from self, that read would be UB since self is a const value.
```

This is only UB with specific calling conventions (callconv(.C) would be correct, for instance, since the argument will always be a copy), so an extension of aliasing rules would allow the compiler to process this in a defined manner (requiring self to be a copy), but that's still far from ideal.

**Comment by Hadron67** [comment]
Doesn't the original proposal interfere with metaprogramming as well?
```zig
fn test1(comptime T: type, comptime func: fn() T) void {
    var a = func();
    a.foo();
}
pub const A = struct {
    i: i32 = 0,
    pub fn init() A { return .{}; }
    pub fn foo(self: *A){ self.i += 1; std.debug.print("A.i = {}\n", .{self.i}); }
};
pub const B = struct {
    pub fn init() B { return .{}; }
    pub fn foo(self: B){ std.debug.print("B.foo called\n", .{}); }
};

pub fn main() void {
    test1(A, A.init);
    test1(B, B.init); // error, `a' should declare const in test1
}
```

**Comment by amfogor** [comment]
Not a good idea. At first sight it might seem great, but for an experienced programmer it will only be a hindrance. Because `const` and `var` convey the intent and assumptions.
For things like that there should be a separate tool that has nothing to do with the actual build. Something the programmer will use only when finishing writing code.

I dunno... it's just not something to worry about, seems like overthinking

**Comment by Jarred-Sumner** [comment]
The `comptime` version of this tripped me up yesterday. Had to dig through compiler source to find where it was generating the error to understand it

![image](https://user-images.githubusercontent.com/709451/127236816-2ce64789-8b98-47f3-bfb1-0f8d34057195.png)

In the `comptime` case, I set a variable in an upper comptime scope and then pass it down to child structs without modifying it.


<img width="780" alt="CleanShot 2021-07-27 at 15 44 15@2x" src="https://user-images.githubusercontent.com/709451/127237057-25f82ee1-df48-49cd-b394-aaaf680704cc.png">

The fix was:
```patch
+    const MaxAlign = max_align;

    return struct {
        const Allocator = std.mem.Allocator;
        const Self = @This();

        const Block = struct {
-            items: [count]UnionValueType align(max_align) = undefined,
+            items: [count]UnionValueType align(MaxAlign) = undefined,
```

For the `comptime` version, instead of forcing the developer to copy the var to a `const`, why not error when trying to write a `comptime var` outside the scope it's "writable" in?

**Comment by InKryption** [comment]
Could `x = x;` be the `_ = x;` equivalent for this?

**Comment by mlugg** [comment]
I'm relatively sure this is impossible to _reliably_ implement. Consider the following:
```zig
fn f() void {
    var x = foo();
    x.something();
}
```
This requires semantic analysis to determine whether `x` can be `const`. Fine so far, but now, consider this:
```zig
fn f() void {
    var x = foo();
    if (comptime bar()) {
        x.something();
    }
}
```
If `comptime bar()` evaluates to `false`, the `something` call is never analyzed, meaning we *cannot* know whether `x` could have been `const`. That's a problem!

Of course, this doesn't mean there *aren't* cases where we know `const` would have worked. If a `var x` is (syntactically) never used as an lvalue (i.e. with `ri.rl == .ref` in `AstGen`), we know that it can never be assigned to. It would be possible to emit the error during `AstGen` in such cases. This would catch things like basic numeric variables, where you basically never write `&x` nor can you perform method calls; e.g. it would successfully catch the example given in the original issue.

The question then is whether we want to push forward with that path, and just not emit the error in ambiguous cases. I'm a bit on the fence about this. On the one hand, I don't really like the idea of "best-effort" errors, where we can only detect bad cases *sometimes*. However, I'm leaning slightly towards implementing it, because I think in practice it'll be useful for getting people into the *habit* of making variables `const` by default, which is very much *not* standard for most people coming from C. This habit is particularly good for things like numeric variables, so I think this proposal would still probably be a good idea.

**Comment by FeldrinH** [comment]
@andrewrk Since this proposal has been accepted, are there any plans to address the issues raised in [@SpexGuy's comment](https://github.com/ziglang/zig/issues/224#issuecomment-629835478)? Those seem like fairly big drawbacks to me.

**Comment by mlugg** [comment]
I'm not sure what Andrew's vision for this is, but revisiting it a couple of months later, I'm highly in favour of implementing it in the manner discussed above. This avoids the issues raised by SpexGuy since it never enforces const-ness on pointers (which is what those issues are fundamentally about): if you ever write `foo.bar()`, then `foo` will be allowed to be `var`.

**Comment by Srekel** [comment]
My two cents on this is, if this gets implemented, please release at the same time (or before) an update to the autoformatter that you can run on the entire project to automatically change const to var and vice versa.

**Comment by Jarred-Sumner** [comment]
I think there have been times where `var` was used in Bun's codebase because `const` would cause a miscompilation. Hopefully the miscompilations have been fixed by now though

**Comment by brownd-oclc** [comment]
**Use case**

I have seen another real world use case that doesn't appear to be covered above. It's a variation of "const poisoning" of sorts.

I worked for several years in "stability" (e.g. how to systematically prevent bugs from being written, or catch them automatically when they inevitably sneak in) working on a Linux kernel driver at a major corporation. When a bug was found, it was fixed on mainline, and depending on severity, back propagated to potentially hundreds of release and major version development branches. What that meant in practice was that mainline nearly always has feature code that stable branches didn't, which strongly incentivized a code style that avoids unnecessary changes to lines of code not directly involved with the actual logic being changed. In this context, one of the style items that comes up is the use of "const".

Liberal use of "const" was a problem for us because modifying otherwise unrelated lines of code could induce the need to change yet other lines of code. Just because mainline may or may not use "const", doesn't mean all applicable branches do as well. When you are propagating highly focused, security sensitive bug fixes, you really don't want to be forced into additional cascading code changes. You also end up in a pretty bad failure mode where the patch applies cleanly, but the source no longer builds. When propagating to hundreds of branches, dealing with this for even trivial patches is a pretty significant time sink. Simply not using "const" for most cases resolved the issue for us, and we honestly didn't miss it.

We played with various ways to use const, and the only place we encouraged its use was for function pointer parameters to help convey intent (e.g. the compiler enforces that foo(const char*) isn't going to modify my string; as a caller of an unfamiliar API, this is useful information). Most of all other uses were discouraged because they caused otherwise unnecessary problems.

**Why is manual intervention needed?**

The way I look at this personally is: if the compiler can reliably detect when I "should" have used const enough to make this a hard build time failure, why shouldn't it just do the right thing automatically? You get the same benefits without the need to micromanage your code. 

**What are the benefits?**

So, from a cost-benefit perspective, what is the benefit of forcing users to deal with this manually? This issue seems to do a decent job of enumerating some of the very real downsides. The argument that code with "const" is easier to read seems subjective at best (for what it's worth, I seem to unconsciously ignore var-vs-const in general as irrelevant noise; YMMV).

**Comment by brownd-oclc** [comment]
Something else I forgot to add regarding not wanting to have build warnings: I totally get this. I'm usually the guy who says the same thing about warning-level logging.

Many other languages have the concept of linting, which seems to be a pretty good fit for this kind of check. Any kind of code quality recommendations that don't have a high enough signal-to-noise ratio to be hard build failures end up in the linter instead. You run it as a separate pass (maybe `zig lint`) if you want suggestions, but otherwise you're not bound to those recommendations if you disagree or they don't apply. Zig still avoids having warnings this way, and I can think of a few other things that could neatly fall into this bucket of recommendations but not errors (e.g. unused parameters, encouraging idiomatic zig patterns, etc.).

**Comment by rootbeer** [comment]
One difference with the Linux code base is that much of it predates strong `const` usage and enforcement by tooling, so perhaps there were more changes to "fix the constness" (i.e., in code that was logically const but wasn't literally const) that showed up over time to exacerbate this issue?  Whereas with Zig, if the constness is enforced uniformly from the beginning, it may be less of a problem?  (I don't have any actual numbers or experience to back this up, though.)

That said, I do see how language features that encourage refactoring (e.g., flagging of unused variables will have a similar impact), might be less helpful when a code base is in maintenance mode than active development.

**Comment by nektro** [comment]
> if the compiler can reliably detect when I "should" have used const enough to make this a hard build time failure, why shouldn't it just do the right thing automatically?

Zig is a toolchain focused not just with creating optimal code for the compiler but also optimal code for its readers. the compiler might be able to trivially figure out if code should be const but a human in peer review or viewing the code online might have a much harder time, that's who this feature is for. const/var is about intention and in that regard this enforcement fixes bugs; it already has for me in my own code.

**Comment by ahaldane** [comment]
Sorry for drive-by comment, but Linus Torvald's rant on const seems too apropos not to post. For your interest: [Anything that *can* take a const pointer should always do so.](https://yarchive.net/comp/const.html).

**Comment by brownd-oclc** [comment]
> so perhaps there were more changes to "fix the constness" (i.e., in code that was logically const but wasn't literally const)

This wasn't my observation. It came up more in new code for us.

> const/var is about intention and in that regard this enforcement also fixes bugs;

I actually see it the opposite way. There is *intentional* const (things that are important to be const) and *incidental* const (things that just happen to be assigned once). By forcing const in incidental cases, you actually erase the original intention and lower the visibility of the important cases. As someone modifying unfamiliar code, I have to tease these cases apart to decide if changing a const will break something.

> Anything that can take a const pointer should always do so.

That seems to align with what we settled on: functions should *take* const pointers when possible.

**Comment by tuket** [comment]
I don't like this "feature".
It makes Zig a worse language for prototyping.
Many times when I'm coding I just want to try out things and not be bothered by this.
Also, when debugging, you sometimes just comment out a section of code to see what happens, and then suddenly variables become unmodified.
I hate when a language adds such a restriction, trying to force good practices to lazy/careless programmers. These restrictions add friction to the "good" programmers that would normally apply good practices but, at the moment, they just want to experiment, prototype, debug, or write throw-away code.
It's definitely a good idea to have those checks as a warning; even good programmers can make mistakes.
The suggestion of doing this as linting seems reasonable too.

**Comment by mlugg** [comment]
Please read the previous comments of issues such as this one before commenting. To sum up the current state of affairs for you and others who may stumble across this thread:
* Experienced Zig developers, including myself and (I believe) other core team members, have found this error to be very helpful when ensuring correctness of code. Notably, its implementation caught multiple subtle bugs in the compiler and standard library.
* The points you are making have been made many, many times before.
* Zig very intentionally does not have warnings. Various other languages serve as proof that if warnings are not hard errors, they inevitably proliferate through the ecosystem, leading to a culture of just ignoring them.
* (This point was not mentioned here AFAICT, but worth noting:) Code can be "commented out" with `if (false)`, in which case it will not trigger this error. This is generally a better way to temporarily disable code in Zig. 
* Speaking for myself, I write Zig for a significant portion of my waking hours, and have not once felt restricted or frustrated by this error. More than once it has picked up bugs in code I'm writing, because when I write `var` that communicates that I *intend* to change this state, and not changing it indicates I forgot what I was doing at some point. If I did change how I were using a variable, I would want to immediately change its declaration to communicate that.

Please, if you do not have anything new to add to the conversation, don't just echo points which have already been made.

**Comment by tuket** [comment]
> * Experienced Zig developers, including myself and (I believe) other core team members, have found this error to be very helpful when ensuring correctness of code. Notably, its implementation caught multiple subtle bugs in the compiler and standard library.

That no reason for it to be an error - if it was a warning those bugs could have been caught too.

> The points you are making have been made many, many times before.

Even though some of my points have already been made, some have not. Also, you only seem to be bothered by people repeating the arguments **against** this feature. You and other people have been repeating the arguments in favor over and over (actually your whole post is just repeating them again xD), and that's okay?

I think it's okay for people to express their opinion, even if their point has already been made. It's not just about the point itself, it's also about how you support it.

> Zig very intentionally does not have warnings. Various other languages serve as proof that if warnings are not hard errors, they inevitably proliferate through the ecosystem, leading to a culture of just ignoring them.

That's my point. Bad programmers will ignore warnings. Good programmers won't. Don't add friction to good programmers. Help them.

It's not inevitable. Some companies have zero-warnings policies.

> (This point was not mentioned here AFAICT, but worth noting:) Code can be "commented out" with if (false), in which case it will not trigger this error. This is generally a better way to temporarily disable code in Zig.

Good to know!

> Speaking for myself, I write Zig for a significant portion of my waking hours, and have not once felt restricted or frustrated by this error. More than once it has picked up bugs in code I'm writing, because when I write var that communicates that I intend to change this state, and not changing it indicates I forgot what I was doing at some point. If I did change how I were using a variable, I would want to immediately change its declaration to communicate that.

Thanks for sharing your experience. Speaking for myself, this feature pisses me off, sometimes, when I'm doing experimentation and prototyping. And the thing is, I don't even write as much code in Zig as you do (I just write Zig as a hobby) and I already find it frustrating. So I can't image if I had to program more often.

And, again, that's not a valid point, you could have caught the mistake if it was exposed though a warning.

> Please, if you do not have anything new to add to the conversation, don't just echo points which have already been made.
Specially, if the points are against, right ;)
