### ISSUE TITLE
support dynamic libraries in the standard library

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2294]
1. Add the dl functions to `std/c.zig`.
 * `dl_iterate_phdr`
 * `dladdr`
 * `dladdr1`
 * `dlclose`
 * `dlerror`
 * `dlinfo`
 * `dlmopen`
 * `dlopen`
 * `dlsym`
 * `dlvsym`

2. Update `std/dynamic_library.zig` and/or `std/os.zig` to have a cross-platform API for dynamic library loading. When linking libc on POSIX it should use the above C functions. Windows has its own DLL functions. Functionality that can be abstracted across platforms should have the same API; functionality only available on some platforms should also be exposed, be documented as such, and compile error when used on unsupported platforms.

3. Implement dynamic library loading for Linux in pure Zig, for the case of not linking libc.

4. Add tests to the zig test suite.

**Comment by suirad** [comment]
@emekoi in saying "`pure zig`" do you mean manually memory mapping the dll? Instead of just calling `LoadLibraryA/W`

**Comment by emekoi** [comment]
yes, that's what i meant.

**Comment by suirad** [comment]
@emekoi I believe the only value added of doing it in pure zig would be:
* Being able to load dlls from memory without saving to disk first
* Having the `pe` format parsing & handling being available for other projects

While I personally would enjoy those features available, not using the default winapis also bring some downsides via non standard behaviour:
* May potentially trigger antivirus(AV) hueristics due to dynamically mapping executable pages
* Another AV trigger would be that the mapped exectutable pages are not backed by an image on the filesystem
* Avoids the kernel managing/cleaning up some resources associated with that dll
* May affect interaction with external libraries

---
I would recommend going the route of `LoadLibrary`

**Comment by daurnimator** [comment]
>     * `pe` format parsing & handling

May want into some of the midipix code including https://git.midipix.org/cgit.cgi/pemagine/

**Comment by cshenton** [comment]
How are dynamically loaded functions meant to be called currently? I get the following error when trying to use `@call` on a dynamically loaded function on windows:

```
 error: expected function, found '*std.os.windows.bits.FARPROC'
```

**Comment by andrewrk** [comment]
This is now generally available (but experimental), and it's time for separate issues to address things that come up when using this feature.

**Comment by Sobeston** [comment]
> 
> 
> How are dynamically loaded functions meant to be called currently? I get the following error when trying to use `@call` on a dynamically loaded function on windows:
> 
> ```
>  error: expected function, found '*std.os.windows.bits.FARPROC'
> ```

You need to @ptrCast that function pointer to an extern function of the correct type.
