### ISSUE TITLE
global @This

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#2350]
Is this expected? I can pass This() as a type but actually call members of it:

    // main.zig
    use @import(“shapes.zig”);
    pub fn main() void {
        drawLine(@This());
    }

    pub fn drawPixel() void {
    }

    // shapes.zig
    pub fn drawLine(comptime view: type) {
        view.drawPixel();
        view.drawPixel();
        view.drawPixel();
    }

main.zig uses shapes.zig. To draw a line, main calls drawLine which calls back drawPixel some number of times to get the job done.

**Comment by Hejsil** [comment]
Pretty sure this is expected behavior. `@This` returns the inner most `type` (the file itself in this case), and this type has a number of global functions in its namespace that can be called (`main`, `drawPixel`, `drawLine`). `@This` is actually behaves the same as `@import("the_name_of_the_current_file.zig")` when the inner most type is the file itself.

**Comment by markfirmware** [comment]
Thanks. I had to read up on namespace, dot syntax, and especially var within a struct to understand. Your comment regarding “global functions in its namespace” was the clue that I needed.
