### ISSUE TITLE
Chat platform

### ISSUE THREAD

**Issue by rishavs** [ziglang/zig#2538]
Not an issue but more of a general discussion.

I was wondering if you folks are open to having a Gitter room for community chat. While I understand that IRC is beloved to many, some of us really do not prefer to use it.
A proper chat platform like Gitter is much preferable. 
Gitter and the IRC nodes can exists side by side and use bridges to join the two community platforms.
Languages like Crystal use this approach and Gitter essentially has become the defacto comunity center for Crystal. Overall, it will be friendlier initiation for a lot of new users. 

Other platforms that may be looked into are Slack and Discord. I have also heard good things about Signal but never used it.

**Comment by daurnimator** [comment]
> IRC is beloved to many, some of us really do not prefer to use it.

What issues do you have in particular?

> Gitter and the IRC nodes can exists side by side and use bridges to join the two community platforms.

The Gitter IRC bridge does not work very well at all. I recommend against picking Gitter for any projects not already in it.

> Other platforms that may be looked into are Slack and Discord.

Slack is not a good choice for open source communities.
Discord, although a propriety ecosystem, isn't the worst choice... their audio is the least buggy out of all the systems I use.

Matrix is probably the best compromise right now. And it's already bridged to IRC.
We *could* upgrade that bridge to a proper one though, instead of relying on the 'default' bridging.

**Comment by rishavs** [comment]
> What issues do you have in particular?

For me the aesthetics are a big turn off to start with. I haven't even stuck around in IRC to see what functional difference there might be. Mind you, this is just personal preference but i think a lot of newer devs will share similar opinion.

> Slack is not a good choice for open source communities.
Not very sure about this. I am using Slack for f# and there has no major issues against it. Why do you think its bad for OSS projects? 

> Matrix is probably the best compromise right now. And it's already bridged to IRC.
I have not used Matrix and I am wary of joining a new platform for the chat (part of my issue with IRC as well)
Gitter for me at least, has great github integration and I can use my exiting sign-ons for it without doing any fiddling. It would still be my first choice.
Though for me anything would be better than IRC. :D

**Comment by merlynmg** [comment]
IRC at least isn't tied to a company. Using many of these "modern" chat produts (e.g. Slack or Discord) does that nasty new web business thing of entrenching users and turning them into a product. Matrix doesn't, at least.

A couple ways this could be improved without switching off IRC:

- Fix the web UI so that all the options are documented inline (e.g. the cryptic `Auth to services`). Fix the sign-up process so that it can be driven entirely by web forms instead of chatbots that are buried in a wall of freenet welcome text. Have the verification link be a link, instead of a command you have to copy/paste back. Or as a stopgap, just add a "quickstart" document right next to the IRC web interface link(s), with short instructions on how to get into the channel (just a numbered list)

- Add a welcome bot that messages you on join, with link to the FAQ, rules on posting/crossposting, etc. Even if these rules are "yeah, this is all fine!", would be an improvement over joining a channel and hearing crickets, and worrying about if you're gonna get kicked for writing your first message. Old IRC channels a decade-plus ago have trained me to be careful about joining then immediately writing a message

**Comment by andrewrk** [comment]
I'm not interested in re-evaluating the chat platform at this time. Feel free to bring this up again in 1 year.

**Comment by pr-yemibedu** [comment]
Hello,
 Just checking back in with this great language. Gitter has low overhead and I already use it to talk about good languages like Nim and Rust. Not sure if it **has** to connected IRC. If so great. I just like its simple and approachable web interface. It also has a more integrated set of touch points with GitHub. It should be low or now maintenance for you and your team.
 
Should I put this in a new open ticket? Thank you. Good day.

**Comment by andrewrk** [comment]
Check https://github.com/ziglang/zig/wiki/Community: 

 >The Zig community is decentralized. Anyone is free to start and maintain their own space for the community to gather, and edit this wiki page to add a link. There is no concept of "official" or "unofficial", however, each gathering place has its own moderators and rules.
