### ISSUE TITLE
docs: explain why one cannot divide comptime_float by comptime_int

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2568]
```zig
pub fn main() void {
  var f: f32 = 54.0 / 5;
}
```
```
/home/shawn/projects/shared/comptime.zig:2:16: error: float value 54.000000 cannot be implicitly casted to type 'comptime_int'
  var f: f32 = 54.0 / 5;
               ^
```

**Comment by andrewrk** [comment]
I think a compile error is appropriate because this is an ambiguous expression. Which one should it be?
 * Cast the `54.0` to `comptime_int(54)` and produce `comptime_int(10)`, which then gets casted to `f32(10)`
 * Cast the `5` to `comptime_float(5.0)` and produce `comptime_float(10.8)`, which then gets casted to f32(10.8)`

**Comment by shawnl** [comment]
This may just be a documentation bug.

**Comment by vegerot** [comment]
> * Cast the `54.0` to `comptime_int(54)` and produce `comptime_int(10)`, which then gets casted to `f32(10)`
> * Cast the `5` to `comptime_float(5.0)` and produce `comptime_float(10.8)`, which then gets casted to `f32(10.8)`

As a Zig noob, what is the best way to specify which one I want?  I wish I could simply say

```zig
pub fn main1() void {
  var f: f32 = 54.0 / @floatFromInt(5);
}

pub fn main2() void {
  var f: f32 = @intFromFloat(54.0) / 5;
}
```

but that doesn't work.  Do I really have to say

```zig
pub fn main1() void {
  var f: f32 = 54.0 / @as(f32, @floatFromInt(5));
}
```
?

**Comment by nektro** [comment]
you can do `var f: f32 = 54.0 / 5.0;`
also this is a question best suited for a [Community](https://github.com/ziglang/zig/wiki/Community).
