### ISSUE TITLE
system wide zig-cache

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2599]
I would like to have a system wide zig-cache for common artifacts.

e.g. `zig fmt` is slow every time you run it from a new directory. Not to mention that it ends up littering zig-cache directories all over the place.

**Comment by tiehuis** [comment]
There is already a system-wide cache for shared files across compilations (e.g. compiler_rt). `zig run` artifacts go there currently, for example. This is under `~/.local/share/zig` on linux.

Also, `zig fmt` was changed recently to not have to run a child process, therefore I don't believe it should have to cache its binary anyway.

Could you clarify commands/environment? I can't reproduce something similar on latest master.

**Comment by daurnimator** [comment]
> This is under `~/.local/share/zig` on linux.

I would love to be able to include such cached files for zig commands in distro packages, which would necessitate a non-user-specific location.

> Could you clarify commands/environment? I can't reproduce something similar on latest master.

For day-to-day use I use the lastest release (0.4.0), only when working on zig itself (or things destined for the standard library) do I use master

**Comment by tiehuis** [comment]
Of course. I've overlooked the system part of system-wide.

I'm not sure if I think the distribution of cached zig command files will be a concern going forward. In 0.4.0 it was only a stop-gap measure to get something working for the majority of users who did not install the stage2 compiler.

There may be other things which could be globally cached reasonably, though. c header processing comes to mind, there may be more, I'm not sure right now. Would like to see a how this would affect initial start-up cache time and storage space changes.

**Comment by jorangreef** [comment]
> Not to mention that it ends up littering zig-cache directories all over the place.

I came here thinking the same, after finding `zig-cache` throughout my repo.

**Comment by data-man** [comment]
> Not to mention that it ends up littering zig-cache directories all over the place.

I propose new `clear` or `clear-cache` command.

**Comment by erikarvstedt** [comment]
Why was this closed? I'm dealing with this issue (and hoping for a resolution) everytime I'm using zig.

**Comment by andrewrk** [comment]
What issue are you dealing with specifically?

**Comment by erikarvstedt** [comment]
My interactions with Zig have so far been limited to casually checking out repos and running `zig build` or running `zig build-exe` on smaller code snippets.
Still, the `zig-cache` dirs created in the source directories stroke me as very irritating in various ways:

1. If I forget to delete the cache dirs after working on a project, they needlessly consume space in my source directories.
2. They consume space in automatic backups of my source code.
3. When using a `find file in repo` tool (via text editors or otherwise), the large amount of cache files clutter the search results.
4. They clutter the search results when searching for strings in a repo.

Points 2, 3, 4 can be mitigated by manually adding filters to backup and search tools.
But I'd vastly prefer if temp files could easily be kept out of source dirs.

This issue is less relevant for large personal projects where setting `--cache-dir` can be part of the build toolchain, but it's important in all other cases.

### Design

As a workaround, I'm running [this patch](https://github.com/erikarvstedt/zig/commits/global-cache) on top of Zig which sets `<global zig cache dir>/per-project/<project dir>` as the default cache dir instead of `<project dir>/zig-cache`.

A shippable design of a system-wide dir for per-project caches could include:
- Support for all OS platforms
- Activatable by setting an env var like `ZIG_USE_GLOBAL_CACHE_DIR`
- Instead of recreating the whole project dir path inside `<global zig cache dir>/per-project/`, use the hashed path as the dir name.
- A `zig cache prune` command for deleting cache items for deleted files or files exceeding a certain age.

Maybe a `zig cache prune` command would allow us to share the global cache (`~/.cache/zig`) among all projects, obviating the need for per-project caches. @andrewrk, what do you think?

**Comment by tbillington** [comment]
Hope this is okay to post here!

If you're okay to use a 3rd party cli tool @erikarvstedt a contributor added support for cleaning Zig projects in [kondo](https://github.com/tbillington/kondo) recently.

**Comment by COD3HUNT3R** [comment]
Related
https://github.com/ziglang/zig/issues/25307
