### ISSUE TITLE
will zig become completely self-hosted?

### ISSUE THREAD

**Issue by catastrop** [ziglang/zig#2645]

**Comment by hryx** [comment]
This seems like a good candidate for an FAQ in the GitHub wiki. @catastrop Here's the answer as far as I understand it.

There will forever be a minimal bootstrap (C++) compiler included in the official code base, in addition to a full-featured self-hosted compiler. The reasons are so that:
- bootstrapping Zig from source on win/lin/mac remains possible with existing official tools
- some package managers discourage or disallow binary-only distributions, so this would let Zig conform to that requirement and be included in those package channels

This does not mean that the C++ compiler needs to be optimized or full-featured. In the future, the self-hosted compiler will be the real deal; stage1 will remain for bootstrapping only.

**Comment by shawnl** [comment]
This is very similar to D, except the C++ compiler is a very old version of the compiler, that they make sure the compiler can always be build with.

**Comment by daurnimator** [comment]
See #89

**Comment by andrewrk** [comment]
Yeah dupe of #89
