### ISSUE TITLE
zig build has no logic to install header files

### ISSUE THREAD

**Issue by ErikMcClure** [ziglang/zig#2684]
When using the `install` step, it is expected that you use `b.installArtifact()` to install the compilation results. However, `InstallArtifactStep.make` has no logic for handling header files, so the only way to extract header files out of the `zig-cache` is to use `setOutputDir`, which simply dumps _all_ the files to a single directory.

`InstallArtifactStep.make` should be modified so that it understands header files and copies them to an `/include/` directory (or some user specified directory).

**Comment by andrewrk** [comment]
There is now

 * `installFile`
 * `installDirectory`

I think `installDirectory` is what you want, since you can include in the options that the destination dir should be the "headers" directory.

These functions properly integrate with caching and other niceties, and are tested by zig's own build system.
