### ISSUE TITLE
Taking address of 0 length array fails

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2692]
```zig
fn foo(a: []u8) void {
}

test "address of 0 length array" {
    var pt: [0]u8 = undefined;
    foo(&pt);
}
```
```
$ bin/zig test bug.zig
Assertion failed. This is a bug in the Zig compiler.
Segmentation fault (core dumped)
```

**Comment by DutchGhost** [comment]
This is maybe the cause of https://github.com/ziglang/zig/issues/2680 ?

**Comment by hryx** [comment]
The triggered assertion is here: https://github.com/ziglang/zig/blob/4606baee072f832ef794d86f428a7f27d91c6a11/src/codegen.cpp#L3116

Null is returned here since the type has no bits: https://github.com/ziglang/zig/blob/4606baee072f832ef794d86f428a7f27d91c6a11/src/codegen.cpp#L2027

Printing out the value of `*actual_type` in gdb confirms:

```
    id = ZigTypeIdPointer,
    ...
    abi_align = 0,
    abi_size = 0,
    size_in_bits = 0,
```

Compared to the results when `pt` is an empty struct:

```
    id = ZigTypeIdPointer,
    ...
    abi_align = 8,
    abi_size = 8,
    size_in_bits = 64,
```

...despite the fact that they are both pointers. Should that be the case?
