### ISSUE TITLE
request: implementation of http, websocket and related protocol in standard library

### ISSUE THREAD

**Issue by catastrop** [ziglang/zig#2754]

**Comment by catastrop** [comment]
Try to have a standard library like go, comes with battery included

**Comment by tiehuis** [comment]
I'm going to close this since there are some existing related issues regarding networking already.

Http Client: https://github.com/ziglang/zig/issues/2007
Http Server: https://github.com/ziglang/zig/issues/910
General Web Discussion: https://github.com/ziglang/zig/issues/942

It is planned to add http for example, but it is currently blocking on a few language changes (which is currently in progress right now). There are some open questions around whether these will be external packages or part of std, but if you have any strong arguments feel free to post in one of the above issues.

**Comment by tiehuis** [comment]
If you have some specific details regarding other protocols (e.g. websockets) and why they should feel free to create another issue. Just note that it is likely that these will be looked closer into regardless when the language changes to allow them are complete.
