### ISSUE TITLE
Is it discouraged to go full on 'snake_case'?

### ISSUE THREAD

**Issue by 4zuree** [ziglang/zig#2756]
I am a fan of a certain code style which is widely used in C++ and C and I also happen to be a fan of a consistent "case style". I got nothing against Zig's origin code style but for myself, in my personal preference, I don't like bringing a thousand different "case styles" into the code.

Would it be that much discouraged if I would go full on 'snake_case' in my open source projects? Technically I don't have to ask but changing code style also means "disrupting" the reader's expectations and "read flow" (because the reader got used to the code style).

Not really an issue but I barely use Discord, IRC is not an option lolz and I don't want to create an account for Reddit. Would love to hear your opinions.

**Comment by dbandstra** [comment]
I'm sure no one will stop you. But in response to your comment about consistency, I'm just going to point out the Zig style guide in case you haven't seen it: https://ziglang.org/documentation/master/#Names

Excerpt:
* If x is a type then x should be TitleCase, unless it is a struct with 0 fields and is never meant to be instantiated, in which case it is considered to be a "namespace" and uses snake_case.
* If x is callable, and x's return type is type, then x should be TitleCase.
* If x is otherwise callable, then x should be camelCase.
* Otherwise, x should be snake_case.

**Comment by andrewrk** [comment]
The style guide is there if people want a canonical reference to look to. Personally I like to focus more on code quality than style conventions. I think it's perfectly fine if projects want to have their own style conventions.
