### ISSUE TITLE
confusing compile error when returning number literal

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#2763]
Apologies if this is a duplicate.

```zig
fn blah(n: i32) ?i32 {
    if (n == 0) {
        return null;
    } else if (n < 0) {
        return -1;
    } else {
        return 1;
    }
}

test "" {
    _ = blah(0);
}
```

Outputs:

```
/home/dbandstra/oxid/test.zig:1:17: error: unable to make maybe out of number literal
fn blah(n: i32) ?i32 {
                ^
```

The solution is to `return i32(1)` but it's not clear from the error.

Also, I think these are usually referred to as "optionals", not "maybes", so the wording could be changed.

**Comment by andrewrk** [comment]
Related: #2749

**Comment by thejoshwolfe** [comment]
> The solution is to `return i32(1)` but it's not clear from the error.

I would call that a workaround, not a solution. The compiler's behavior here makes no sense, since it's obvious which sequence of implicit casts should happen to make it all work.

I just tripped over this issue here: https://github.com/thejoshwolfe/legend-of-swarkland/blob/fail-to-move/src/server/game_engine.zig#L1045-L1075
