### ISSUE TITLE
replace `inline` keyword for `while` and `for` loops with `unroll`

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#2805]
Naïvely, I thought `unroll` might be a better keyword and @andrewrk said he considered it before, but went for `inline` as it's well-known.

I don't have a strong opinion, but still think `unroll` better expresses the intent.

### `unroll`
Pros:
- that's the specific term for what the feature is doing

Cons:
- it might cause some confusion in that it doesn't unroll loops on runtime-known iterator (minor)

### `inline`
Pros:
- that's an usual keyword

Cons:
- it otherwise has a single meaning in zig, which to me is quite different (I didn't go through all keywords, but that's probably a good rule of thumb to have a unique meaning for each keyword ?)
- for people coming from c, c++ and maybe other languages, it might not be clear that in zig `inline` is solely used for inlining functions and is more than a suggestion (minor)

Other propositions ?

**Comment by nodefish** [comment]
Why not `comptime`?

**Comment by andrewrk** [comment]
> Why not `comptime`?

You can, in fact, put `comptime` in front of a loop already, because you can put `comptime` in front of any expression. If you do that, it means the entire loop will not only be unrolled, but also executed at compile time. So you could not, for example, call an external function inside the comptime loop because external function calls are not allowed at comptime.

`inline` (or the proposed `unroll`) is different in that the loop can still do runtime stuff (such as printing to stderr) - it's just that the loop branching and the iteration variable(s) will be comptime-known.

**Comment by nodefish** [comment]
I understand, but since `comptime` followed by runtime stuff is not currently allowed, then there is no ambiguity if the keyword `comptime` were to be used in place of `inline`. You _would_ lose the ability to run comptime-compatible code at runtime, but you might argue that such code should preferentially be run at `comptime` anyway.

**Comment by andrewrk** [comment]
> then there is no ambiguity if the keyword `comptime` were to be used in place of `inline`

There is ambiguity, if you consider that getting a compile error in some cases is desired behavior. `comptime` guarantees that the expression that follows will be executed at compile time or be a compile error. Making it do the `inline` loop functionality, removes the ability to get a compile error when there would be a runtime side effect.

**Comment by andrewrk** [comment]
I think it's a reasonable proposal. I'm ambivalent about it. I'm making an executive decision here to stick with status quo. I do think that `inline` is still correct.
