### ISSUE TITLE
add @atomicStore

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2995]
I previously did not add this builtin because there is a way to do it currently, which is to use [@atomicRmw](https://ziglang.org/documentation/master/#atomicRmw) with the Xchg operation, and ignore the result (assign to `_`).

However this is not very discoverable, and probably better to have a builtin that is only to do an atomic store. Currently even the `@atomicRmw` with assigning to `_` actually gets generated as atomicrmw in llvm, not as an atomic store.

One example from the standard library where this can be improved is: https://github.com/ziglang/zig/blob/6cb4cac5cd1c68f41c62a3c23b09513988337c8d/std/os/linux.zig#L454

I'm not sure why that is a cmpxchg there; I think maybe the code was reworked but now it can be a simple atomic store.

**Comment by andersfr** [comment]
LLVM does support atomic ordering on the StoreInst which means that the semantics for an `@atomicStore()` are meaningful and different from the `@atomicRmw()`, `@cmpxchgWeak()` and `@cmpxchgStrong()` builtins.

**Comment by karrick** [comment]
The referenced line that uses a CMPXCHG and ignores the return value seems itself very fishy, because it is not guaranteed to actually modify the referenced memory.

I know my comment is orthogonal to the issue you raise, but I do believe using a CMPXCHG call as if it were an atomic store is most certainly a mistake. And ignoring its return value is likely an indication of accidentally picking the wrong function for the job.
