### ISSUE TITLE
Odd error message when doing `_ = SomeStruct { ... };`

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#3054]
(Yeah this code is pointless, I just ran into this while moving code around.)

```zig
const SomeStruct = struct { a: i32 };
pub fn main() void {
    _ = SomeStruct { .a = 0 };
}
```
Output:
```
/home/dbandstra/oxid/test.zig:3:22: error: type 'void' does not support struct initialization syntax
    _ = SomeStruct { .a = 0 };
                     ^
```

edit: 
This compiles without error:
```zig
const SomeStruct = struct {};
pub fn main() void {
    _ = SomeStruct {};
}
```

**Comment by LemonBoy** [comment]
This is easily fixed by ignoring the `allow_discard` parameter in `ir_resolve_result`, when the destination slot is `_` I guess it always makes sense to set `result_loc_pass1` to `no_result_loc()`.

Such a modification doesn't cause any regression in the test suite, I'm waiting on @andrewrk to ACK/NACK this idea before submitting a PR.
