### ISSUE TITLE
feature request: better optional syntax

### ISSUE THREAD

**Issue by giann** [ziglang/zig#3265]
I'm finding myself missing some of the syntax and features of Swift around optionals:

- Ability to unwrap an optional in a `if` statement *and* test other things as well:
```swift
// Swift
if let unwrappedA = optionalA, unwrappedA == 42 {
    // ...
}
```
- Ability to unwrap multiple optionals in a single `if` statement:
```swift
// Swift
if let unwrappedA = optionalA, let unwrappedB = optionalB, optionalA == optionalB {
    // ...
}
```
Which would avoid those kind of `if` nesting I'm forced to write right now:
```zig
// Zig
if (optional_a) |unwrapped_a| {
    if (optional_b) |unwrapped_b| {
        if (optional_a == optional_b) {
            // ...
        }
   }
}

```
- Optional chaining:
```swift
// Swift
// `doSomething` won't be called if any optional is nil in the chain
optionalA?.optionalB?.doSomething();
```
- Optional comparison:
```swift
// Swift
var optionalA: String? = nil
var optionalB: String? = nil

assert(optionalA == optionalB) // Both nil => equal

optionalA = "hello";

assert(optionalA != optionalB)
```

**Comment by giann** [comment]
Submitted by error, will reopen once finished

**Comment by daurnimator** [comment]
You use the `.?` operator if you know unwrapping is safe. e.g.

```zig
if (x != null and y != null) {
    std.debug.warn("both non-null: {} {}\n", x.?, y.?);
}
```

**Comment by giann** [comment]
This would the equivalent of:
```swift
```

**Comment by Slaide** [comment]
How is testing for null and then unwrapping less safe? Also, where would you move the line that the result will differ?

**Comment by giann** [comment]
It’s less safe because it’s done in two statements that can mistakenly be moved apart.

**Comment by Slaide** [comment]
`if let unwrappedA = optionalA, unwrappedA == 42 {`
as i understand, this only works, because let evaluates to nil in this case, which is also some kind of false, therefore if is not further evaluated.
accordingly, assignments would have to be rewritten in a way, where an assignment would either return the assigned value, which are in zig currently not evaluated to a boolean value, or return a boolean that represents assigning null or an actual value.
returning the assigned value on assignment is currently used in many other languages, so that `var a=b=2;` is possible, but this leaves the problem that this value would then need to be evaluated to being true or false, and i do not think that is the right way for zig to solve this problem. though since this usage is so widespread, having `var a=b.?;` return true or false depending on b being null or not will confuse many newcomers, since `var a=b=2;` will result in `b` having the value 2, and `a` having the value true. implementing a certain case where the assignment of assigned values varies depending on b being of an optional type or not is just horrible. so this leaves us with implicit casting, which opens a whole new world of pain, that many people tried to escape to zig from.
the best solution here would be some function that evaluates a variable to a boolean, which would then need to be implemented, and called in this case, which would create this following statement:
`if varToBool(let unwrapped=optional.?) and unwrapped==42{...`, which would then not work again, because the scope in which the variable `unwrapped` exists is exited upon evaluation of the function, whereby the whole situation would be in the state it is currently (check for null and unwrap the value later).

`optionalA?.optionalB?.doSomething();`
this is just horrible syntax. i do not know how this works exactly either. either `doSomething` is called without arguments if both optionals are not null, in which case this could be done in a way where the checks for null are written in a single line. or doSomething is called with both unwrapped values if both are not null, which is also just asking for trouble, and could be solved with a single line more than would be necessary for the prior situation.

`assert(optionalA == optionalB) // Both nil => equal`
this is a semantic problem in my opinion. an optional type inherently represents there either being a value, or not, with null representing a state in which there is no value, so there is nothing to compare. if both are null, both have no value, and therefore are not equal, but represent an identical state, which can be checked. since the check for equality also only works for primitive types, and optionals are not primitive, you would have to supply a function for comparison anyway, so you might as well type one for optionals in the first place. this is not out of scope for the language, and probably a common situation, but i dont know if supplying a function that checks for equal state of optional values and afterwards comparing the primitive values is something the language should take care of. for a function of the standard library this seems trivial, but might be done. (though unlikely, given the limited use cases)

the inherent problem with your examples is that swift has implicit casting, and zig wants to be as explicit as possible.

**Comment by Slaide** [comment]
> It’s less safe because it’s done in two statements that can mistakenly be moved apart.

this also is not a problem in my opinion. the unwrapped variable will have to have a new name, since shadowing is not a thing in zig, and therefore using clear naming schemes will solve this problem (compilation error on usage of a undeclared variable at this point). if the unwrapping is done at a large distance below the check for null, that is an issue given in many other cases. the language should not need to take care of proper coding conventions, in this case.

**Comment by Tetralux** [comment]
I've also wanted to do something alongside unwrapping before, several times.
Having something like
```zig
if (opt_1 and opt_2 and opt_3) |v1, v2, v3| {
    // Do something with all three values.
    // Does not execute if any are null.
}
```
..would help with that.

It's worth noting though that you may want to check an optional and some bool conditions, rather than multiple optionals. I'm not sure how best to do that...
```zig
if (opt_1 and should_do_it) |v1| { // values given names left-to-right.
    // ...
}
```

**Comment by Slaide** [comment]
maybe the syntax can look something like
`if(optA, optB, optC) |uA,uB,uC| if (uA==42 and uB>uC){...}`
or
`if(optA |vA| and optB |vB| and optC |vC| and vA==42 and vB>vC ) {...}`
the latter of which is probably easier to implement.

**Comment by andrewrk** [comment]
I will grant you that these constructs could sometimes, perhaps even often, come in useful. However, all of these things are possible with status quo Zig syntax, even though it is a bit more verbose.

One of the features Zig provides is the low cognitive load on reading code. And part of how that is accomplished is by overall reducing the number of syntactic options.
