### ISSUE TITLE
Why using github? It is a proprietary software. 

### ISSUE THREAD

**Issue by lithic** [ziglang/zig#3279]

**Comment by Yardanico** [comment]
What's your exact issue with that? If you want, you can mirror Zig on your own Git server or on GitLab (although you still don't know what's running on it since you don't have access to their servers :P)

**Comment by lithic** [comment]
We can use gitea

**Comment by Yardanico** [comment]
> We can use gitea

But why would you need another service instead of GitHub? GitHub is the most widely used one, and it helps people to discover new stuff (including Zig).
And andrewk uses GitHub sponsor feature to sponsor his work, so there's no possibility of changing GitHub in favor of another service any time soon.
