### ISSUE TITLE
C++ to Zig translation

### ISSUE THREAD

**Issue by lithic** [ziglang/zig#3281]
This will help spreading Zig. Like V

**Comment by Yardanico** [comment]
Zig already has C to Zig translation which kinda works (but not ideal), but I think C++ has some stuff which can't map 1:1 to Zig, my opinion about it is that Zig is like modern C, and Rust - modern C++, but I'm just sharing my opinion here.
And using V as an example is a pretty bad idea since we haven't seen half of the stuff which is supposed to be there, and author claims to make it until the end of December.
