### ISSUE TITLE
Status of nvptx support

### ISSUE THREAD

**Issue by classner** [ziglang/zig#3314]
Hi,

thanks for the great work with ziglang. This is more a question than an issue: what is the status of nvptx support? I see it listed with Tier 4 support in the targets, but is it usable in the current state? Is it possible to emit code to run on NVIDIA hardware directly with zig?

I haven't found anything in the documentation apart from the mention in the targets...

**Comment by andrewrk** [comment]
Hi @classner, welcome.

Support for these targets is entirely experimental.

Here's what I get when I try to make a simple object file:

```zig
export fn entry() void {}
```

```
$ zig build-obj test.zig -target nvptx64-freestanding
unable to write object file ./test.o: TargetMachine can't emit a file of this type
```

This makes sense, since Tier 4 says:

> This target may only support --emit asm and cannot emit object files.

Let's try the suggestion:

```
$ zig build-obj test.zig -target nvptx64-freestanding --emit asm
$ cat test.s
//
// Generated by LLVM NVPTX Back-End
//

.version 3.2
.target sm_20, debug
.address_size 64

.global .align 1 .u6 os;

.func std_$_special_$_panic(
	.param .b64 std_$_special_$_panic_param_0,
	.param .b64 std_$_special_$_panic_param_1
<snip>
```

You're now caught up to everything I've ever done with NVPTX.

If you're interested in using NVPTX with Zig, you'll have to pioneer this work. It could be quite fun, but also could be frustrating.
