### ISSUE TITLE
compiler crash on circular pub use import

### ISSUE THREAD

**Issue by slaide** [ziglang/zig#3333]
test1.zig:
`pub use @import("test2.zig");`

test2.zig:
`pub use @import("test1.zig");`

main.zig:
```
pub use @import("test1.zig");
pub fn main()void{}
```

`$ zig build-exe test.zig`

this will cause a segmenation fault:
`Segmentation fault (core dumped)`
(zig build will just crash the compiler)

**Comment by Slaide** [comment]
the question is what should be done instead.

either do what the compiler is told, which is return an error, because there are multiple redefinitions (not in this case, because the files are empty, but with code included of course, where this example behaves the same by the way), or somehow do a check to see if the file was already included somewhere.

**Comment by hryx** [comment]
Pretty sure this is #3329.

> the question is what should be done instead.

Circular imports are allowed in general, so I think your first suggestion is better -- fix this bug and let the compiler return the name conflict error. Specifically disallowing circular `usingnamespace @import`s would add to the (yet-nonexistent) language spec. We can always make error messages more helpful in the implementation if necessary.

**Comment by andrewrk** [comment]
> Pretty sure this is #3329.

This issue persists with 75e9a722db3335da0e8c254a0e04c5775ebfc160.

**Comment by andrewrk** [comment]
Not a problem anymore. Test coverage by `test/behavior/usingnamespace/*`.
