### ISSUE TITLE
pointer derefernce is misinterpreted on left side of assignment

### ISSUE THREAD

**Issue by Slaide** [ziglang/zig#3468]
```
pub fn main()!void{
  var a:i32=2;
  var b=&a;
  b.*=3;
}
```
if there is no space between a pointer dereference and the equal sign the compiler throws an `error: expected token 'Symbol', found '*='`, which means that it probably read `(b.)*=(3)`, while it should have been `(b.*)=(3)`
if a space is placed there, everything works fine. since the deref operator has precedence over the assignment operator this should not be an issue, but it is one.

**Comment by bhansconnect** [comment]
Hi, I am new and hoping to do this as my first contribution. I just have a few questions.

I was looking into this and it is technically a tokenizer/lang grammar error. Because the tokenizer sees `*=`, it returns the tokens `.`, `*=` instead of the correct `.`, `*`, `=`.  The parser is acting properly given the tokens it read. With that knowledge, I feel like there are a few potential solutions:

1. Make the tokenizer smarter so that it can recognize this case.
2. Specifically create a `.*` token.
3. Add a failure case on the parser for `.` followed by `*=`

To me, 2 feels like the most correct way to go about implementing this. That being said, I am new to zig, so I do not know what repercussions adding the new token would have. 
Any thoughts on the preferred way to implement this? Is there something I am missing?
