### ISSUE TITLE
CPU feature flags (and way to lower SIMD instructions)

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#3515]
This was discussed on IRC, and andrew's solution was to add CPU features support to zig (as the qemu cpu does not always support SIMD), and then zig can ask llvm to lower the simd instructions to scalar ones, which qemu does support.

----
My SIMD patch fails the mips qemu tests, because qemu has always had buggy SIMD emulation. I do not want to skip the offending test if testing on real hardware however.

Such a skip is ugly of course....., but the bug is in qemu.

**Comment by LemonBoy** [comment]
Do you have a minimal LLVM-IR test case to showcase the problem?

**Comment by shawnl** [comment]
Well that would make it a qemu bug, and I am not interested in fixing qemu. My simd patch set is currently failing on mips because of this. If we tested arm32 it would fail there too, despite me having tested my code on arm32 and it works.

**Comment by LemonBoy** [comment]
> Well that would make it a qemu bug, and I am not interested in fixing qemu.

But I am, that's why I asked for some code.

**Comment by shawnl** [comment]
@LemonBoy I opened a generic qemu bug https://bugs.launchpad.net/qemu/+bug/1851095

**Comment by LemonBoy** [comment]
> @LemonBoy I opened a generic qemu bug https://bugs.launchpad.net/qemu/+bug/1851095

That's gonna certainly help the Qemu developers.
Since you've been unable to show me a single line of non-working code nor to point me to a specific point of the test suite that fails I've decided to do some investigation work by myself.

The test suite passes with no problems on ARM32 (are you still using LLVM8? and a recent version of Qemu?) and on MIPSel you're hitting [this LLVM bug](https://bugs.llvm.org/show_bug.cgi?id=43768).

At the end of the day there's still no Qemu bug in sight.
