### ISSUE TITLE
Proposal: for on ranges

### ISSUE THREAD

**Issue by AndreaOrru** [ziglang/zig#358]
```
for (a...b) |x, index| {
    ...
}
```

Where `a` and `b` can be chars, integers, anything that can define a range. This is also better syntax IMHO than:

```
{var i = 0; while (i < n; i += 1) {
    ...
}}
```

**Comment by thejoshwolfe** [comment]
Previously when @andrewrk and I considered this syntax very early in Zig's development, one problematic point was the upperbound inclusivity/exclusivity. With an expression like `i < n`, there's no question that `n` is an exclusive upper bound, but with `a...b`, does that include `b`?

Surely the question can have an answer, and it should probably be exclusive, but the point is that the syntax doesn't clearly say that it's exclusive. And just to confuse things, I've seen languages (coco, for example) use two different syntaxes for `a..b` inclusive and `a...b` exclusive.

I don't think users will have a very good success rate for guessing whether the upper bound is inclusive or exclusive, which makes me dislike this proposal. That being said, iterating over numbers `0` to `n` (exclusive) is a very common pattern, even outside the usecase of array indexes, and I think this deserves more discussion.

**Comment by raulgrell** [comment]
I wouldn't be against the two different tokens, but intuitively I'd say `a..b` is b exclusive and `a...b` is b inclusive. I think Rust and Wren do this too...

If we only keep `...`, I'd say keep it exclusive and consistent with how slices are made, ie array[0...1] has array.len == 1. Python's range() function has this property

**Comment by andrewrk** [comment]
We do have the `[a...b]` slicing syntax, which is exclusive. So it should be clear from this.

On the other hand, an unsolved problem is that in switch statements, `...` is inclusive, for example:

```zig
switch (c) {
    'a'...'z' => {}, // inclusive
}
```

I have 2 ideas to solve this problem:

 * Change `...` syntax for slicing to `..` and keep it exclusive. Keep `...` syntax for switch statements, and keep it inclusive.
 * Change `...` syntax for slicing to `:` (like Python). Keep `...` syntax for switch statements, and keep it inclusive.

**Comment by raulgrell** [comment]
> Change ... syntax for slicing to .. and keep it exclusive. Keep ... syntax for switch statements, and keep it inclusive.

I'm not sure how I feel about using the `:` as a slice. It always has something to do with types. `..` and `...` are more intuitively associated with ranges

**Comment by raulgrell** [comment]
I posted this in #359, just adding the relevant part here, which suggests keeping the two range operators `..` and `...` and add a third `:` that reflects the number of elements in the range as opposed to its start and finish

```
for (0 .. 2 ) | x, i | { }  // Exclusive -> 0, 1
for (0 ... 2) | x, i | { }  // Inclusive  -> 0, 1, 2 
for  (2 : 2)  | x, i | { }  // Range     -> 2, 3
```

**Comment by igalic** [comment]
i haven't seen mention of it yet, so i'll just do so myself:

is there a way to count backwards? will `for ( 2 ... 0) | x, i | { }` count `2`, `1, `0`?

**Comment by raulgrell** [comment]
It was mentioned before, the expected behaviour for that statement would be it would actually loop 0 times - ie, the block would not execute.

To count backwards, you'd do `for(a...b) | x, i | { print(b - i) }`

**Comment by bronze1man** [comment]
I dislike this proposal,it is difficult to know it's meaning without read the document. A function call may be better.

**Comment by AndreaOrru** [comment]
Care to elaborate? Which document? What function call? Can we see an example?

**Comment by monouser7dig** [comment]
http://termbin.com/ggyl

from @Hejsil 
not the most elegant because you have to type `|_,i|` instead of `|I|` but still I'd say usable 

question is if the same can be hacked together for ranges not starting at 0

**Comment by bronze1man** [comment]
I dislike this proposal:
```
for (a...b) |x, index| {
    ...
}
```
what a and b mean? is a include? is b include? what is x mean? what is index mean? If the lang design like this, I have to read the document to understand what it means.

I am looking for something more understandable syntax, may be like this?:
```
for (var i = range0ToNotInclude(100)) {
}
```

**Comment by thejoshwolfe** [comment]
this gets you most of the way there:

```
test "" {
    var j: usize = 0;
    for (times(10)) |_, i| {
        @import("std").debug.assert(i == j);
        j += 1;
    }
}

fn times(n: usize) []const void {
    return ([*]void)(undefined)[0..n];
}
```

**Comment by raulgrell** [comment]
We already have the concept of ranges in slices and in switch statements - for this proposal to be reasonable, we just need to be consistent throughout the language. I know we're optimizing for readability, but we should be able to expect that a person reading Zig code has at least looked through the Zig docs.

That times function returning a `[]const void` is a reasonable work around.

In @bronze1man's proposal, an assignment would have to be an expression that returns whatever was assigned. It might also be unclear that the function only runs once - a reader might expect each iteration of the loop to declare a new variable i set to the result of a new call.

Zig had a "null-unwrap-and-declare" operator `?=` in ifs that was replaced precisely to keep identifier declaration consistent: `control (predicate) | body_names | { body } prong  | prong_names | { body }`

```
// So we could do this:
if (maybe_foo()) | foo | { foo.bar() };

// Instead of 
if (var foo ?= maybe_foo()) { foo.bar() }
```

**Comment by skyfex** [comment]
I think there is a number of things that needs to be thought of here:

1. Settle on a syntax for inclusive and exclusive range operator
  - One suggestion in 1..3 and 1...2 (I gotta say I think this is too hard to read the difference)
  - In Ruby, 1..2 is inclusive and 1...3 is inclusive. 
  - Nim uses 1..<3 and 1..2 (I think the ..< is really clear here, but it leaves .. ambigous)
  - Mathematics ([Interval Notation](https://en.wikipedia.org/wiki/Interval_%28mathematics%29)) uses [1,3) and [1,2] .. it would be great if Zig could somehow use this fact. Maybe [1..3) and [1..2] could be considered.
  - It can be useful to include stride. Like Julia and Python has a:b and a:s:b where s is a stride. It may be too much for a simple language like Zig, but worth considering.
2. Consider making the range operator return a value of a built-in range type. 
 - I think it's a missed opertunity not to use the syntax for range to construct a value of a "range" type, just as with int, float and strings. 
 - This would work well with for loops
 - It's not clear how this would work with the switch statement though.. then range would be a special case
3. Consider generalizing the for loop

If for loops work on slices, arrays and ranges, it's starting to get confusing. What's the pattern? Could it be generalized in a meaningful way? 

I gotta say I'm a big fan of languages where the for loop accepts some kind of "iterator", rather than a few special types. It makes it much more clear and explicit what's going on, and easier to read in my opinion. So if you have an array `items`, maybe it should something like:

```
for (keys(items)) |key| { ... }
for (values(items)) |value| { ... }
for (pairs(items)) |key, value| { ... }
```
And then for ranges you could do:
```
for (range(1..3)) |num| {...}
for (rangePairs(1..3)) |index, num| { ... }
```

But how you make those iterators work is a huge proposal on its own.

**Comment by monouser7dig** [comment]
> I gotta say I'm a big fan of languages where the for loop accepts some kind of "iterator", rather than a few special types.

if only there were something called interfaces ore alike 🥇 

https://github.com/ziglang/zig/issues/1268

**Comment by thejoshwolfe** [comment]
Iterators can be done with `while` instead of `for`.

https://github.com/ziglang/zig/blob/02713e8d8aa9641616bd85e77dda784009c96113/build.zig#L155

**Comment by monouser7dig** [comment]
compare 
```
var i = 0;
var it = get_some_it (thing); // this code may actually look different every time so you never know what you read
while(it.next()) |arg| {
  i++;
}
```

to

```
for(thing) |arg, i| {
}
```

I do not think the first one enhances clarity.

And iterating is one of the most common things so there is that ...

with interfaces its possible to have concise iterators

**Comment by monouser7dig** [comment]
@skyfex 
>  [1,3) and [1,2]

I can't even remember those two (and they look very similar as well) while I find the ruby syntax intuitive so it really depends on the person... 

In the end you just have to remember some syntax so I do not think this is actually such a big deal.

The issue is a very restricted for loop and not a `.` vs a `(`.

**Comment by binary132** [comment]
👍 for : without a variant form since the intent is very clear and unambiguous among a number of languages. Might be nice to add optional stride too ;)

**Comment by raulgrell** [comment]
I'm not sure it's a good idea to couple syntax with the names that are defined in a struct - saying you can use `for` on types that have `iterate()` and `next()` this is basically the same thing as operator overloading.

> Iterators can be done with a while

Yep. The while iterator pattern is both explicit and concise - if you end up having to change how the iterator has to be initialized or continued, the function calls aren't hidden behind the syntax.

If the value of this proposal is good, and the only concerns are regarding syntax, we could accomplish this with built in functions and call it as `for(@range(u8, 'a', 'z')) | c, i | { }`

Example names and signatures. If it's hard to work out what they mean, it's a sign we need better functions.

```
@times(a: var) []const void;
@range(comptime T: type, a: T, b: T) []const T;
@sequence(comptime T: type, a: T, b: T, stride: T) []const T;
@linearSpace(comptime T: type, a: T, b: T, num: int) []const T;
```

Can built in functions be async/generators?

```
@generateRange(comptime T: type, a: T, b: T) yield T;
```

**Comment by skyfex** [comment]
@raulgrell I think if those built-ins end up being needed, it's a failure of language design. Built-ins should be functionality that can not in any way be implemented with library code. There are many of ways to design the language such that these can be implemented as plain code rather than magic built-ins, and I'm sure one of them can keep Zig conceptually simple and explicit.

I agree that there shouldn't be special function calls generated by the `for` syntax though.

I don't really like having to use while-loops to use an iterator pattern, but when I think about it, it's probably the correct choice for Zig.

Is there a proposal for generators (or observable or whatever it should be called)? It would make a lot of sense to extend the async support to allow an async function to yield multiple values. Then it would also make sense to extend for-loops to support those.

**Comment by BarabasGitHub** [comment]
How is a generator any different from an iterator?

You can super easily make an iterator (with next) that generates a range of numbers for you.

The only thing is that you need to type more than just writing it directly into the loop yourself. So... 🤷🏻‍♂️

**Comment by skyfex** [comment]
@BarabasGitHub Generators, as I meant it, would be asynchronous. Iterators are not.

While iterators operates on some state object that you manually initialize and keep track of, generators would just be a single function and the state would be its stack.

It doesn't make sense to add support for generators just to support `for` on a range. But if support for generators is added to support more advanced async programming, then making the for loop support generators and defining range as a generator would make sense.

I found that @andrewrk has commented on supporting generators here: https://github.com/ziglang/zig/issues/1194

The problem with this, is that if the use of generators in a for loop isn't heavily optimized by the compiler, the use of generators for simple things like range would be extremely inefficient.

That could be OK though, you can always use `while` for efficiency.

**Comment by thejoshwolfe** [comment]
This proposal is about making it more syntactically convenient to loop over a range of numbers than:

```zig
var i = a;
while (i < b) : (i += stride) {
}
```

or

```zig
// times() is implemented in an above comment
for (times(10)) |_, i| {
}
```

Can someone link to some existing code that would benefit from this convenience, even code in a different language that uses syntax like what is being proposed here? I'm questioning how common it is to have `a` and `stride` values other than `0` and `1` respectively. I know iterating over an array/slice backwards is useful sometimes, and the OP mentions a range of chars. I think it would help this discussion to look at some real actual usecases.

If the usecase is not sufficiently common, then you can always just use the above code, and we don't need a special language construct.

**Comment by raulgrell** [comment]
Regarding the use with generators, one thing comes to mind:

fn genStuff() yield u8 {

**Comment by raulgrell** [comment]
Another simpler option that bypasses the range syntax issue but still offers some convenience: iterating n times with `for (n) | i | { }`. I'd argue the automatic scoping of `i` and removing the line declaring it is good for readability by reducing noise and preventing accidental reuse of the variable. But then again, this is a much weaker language feature that might violate the "one obvious way to do things" rule with very little expressive benefit.

Whether the range/number syntax is "communicating intent precisely" is probably a bit subjective - i think it communicates a counter better than a while loop where we just recognize the pattern of checking a number and updating it. But @andrewrk and @thejoshwolfe have been pretty clear about hidden allocations and hidden control flow being the devil - so there is also a strong argument for really making you allocate that variable on the stack and do all the comparisons and assignments explicitly, where you communicate intent with a precise implementation.

But then I wonder if it really is more precise or if the optimizer is just going to change the implementation anyway, and whether it would choose a better implementation than us if we give it more information. But I don't know enough about compiler internals to really comment on this.

Regarding generators, I understand them as functions that can be called several times and return different things depending on its internal state. It makes more sense to use them in a while, otherwise we'd need to have a special case for generator functions being called, or make the syntax for calling generator functions different to calling regular functions.

```
while (genRange(2, 5)) | i | {
    //genRange gets called every iteration, yielding one value into n each time
}

for (genRange(2, 5)) | n, i | {
    // suggests genRange gets called once
}
```

**Comment by skyfex** [comment]
You had a very good point in the part of the comment you removed @raulgrell.

`while` communicates that the expression inside it is evaluated/called multiple times.

`for` communicates that the expression is evaluated once, but it yields multiple values, either as a slice, an array or maybe one day a generator.

In that way, maybe `for (a..b)` is a bad idea. The range `a..b` itself doesn't yield or contain multiple values. It's just two numbers.

When I think about what other things in the language `for` could be used on, I'd say that `for` on structs would be pretty neat for introspection. But then you'd need built-in support for boxed values (some kind of Any type)

**Comment by nodefish** [comment]
Not sure if this is helpful, but you could implement ranges as a lib that outputs a "almost free at runtime" comptime array on the stack like so:

```
const std = @import("std");
const assert = std.debug.assert;
const warn = std.debug.warn;

fn abs(comptime x: comptime_int) comptime_int {
    return if (x < 0) -x else x;
}

pub fn range(comptime inclusive: bool, comptime a: comptime_int, comptime b: comptime_int, comptime step: comptime_int) [@divTrunc(abs(b - a), abs(step)) + if (inclusive) 1 else 0](if (a < 0 or b < 0) isize else usize) {
    comptime assert(abs(a) != abs(b));
    comptime assert(abs(a + step) != abs(b));

    comptime var res: [@divTrunc(abs(b - a), abs(step)) + if (inclusive) 1 else 0](if (a < 0 or b < 0) isize else usize) = undefined;
    comptime var idx = 0;
    inline while (idx < res.len) {
        res[idx] = a + step * idx;
        idx += 1;
    }

    return res;
}

test "static ranges" {
    warn("\n");
    for (comptime range(false, 10000, 60000, 10000)) |val| {
        warn("{}, ", val);
    }
    warn("\n");
    for (comptime range(false, -1, 7, 2)) |val| {
        warn("{}, ", val);
    }
    warn("\n");
    for (comptime range(false, -120, 77, 80)) |val| {
        warn("{}, ", val);
    }
    warn("\n");
    for (comptime range(true, -9, 13, 1)) |val| {
        warn("{}, ", val);
    }
    warn("\n");
    for (comptime range(true, 9, -12, -3)) |val| {
        warn("{}, ", val);
    }
}
```

(wrote this ~6 months ago, probably has some issues)

**Comment by Rocknest** [comment]
I propose this syntax: 
```zig
for (a ~~ b) |x, index| {
    // exclusive
}

switch (c) {
    'a' ~~+ 'z' => {}, // inclusive
}
```

**Comment by Rocknest** [comment]
I propose this syntax: 
```zig
for (a ->+ b) |x, index| {
    // inclusive, another variant: a ~~+ b
}
for (a -> b) |x, index| {
    // exclusive, another variant: a ~~ b
}

**Comment by andrewrk** [comment]
Not going to do this, when this is perfectly fine:

```zig
var i: usize = a;
while (i < b) : (i += 1) {}
```

I don't think lack of this range feature is causing any actual problems. However pay attention to the coroutine rewrite issue (#2377) because Zig may gain generators out of it.

**Comment by tuket** [comment]
It would be cool if we could have the `i` in the local scope of the for/while. Just like in C.
`for(int i=0; i < n; i++)`

I know you can do:
```
{var i = 0; while (i < n; i += 1) { 

}}
```
but it looks so verbose and ugly IMHO

Maybe it's just that I'm so used to the C syntax. But I think, the way C does it, is very simple, and easy to understand; no need for range syntax

**Comment by skyfex** [comment]
It should be said that some of the discussion around this topic seems to be continued in #3110 

Regarding @tuket's comment.. I've taught C/C++ at university, and I didn't find for loops very intuitive to teach. The syntax is frankly speaking quite dumb. There's nothing else in the language that works anything like for loops do, and the name tells you nothing about what the statement is actually doing. I am also completely used to how for loops work, and find it nicer than what Zig currently has... but it's not worth adding any special syntax just for "while"... it should be something universal

**Comment by tuket** [comment]
Tanks for the link!
IDK, maybe I've been using it for so long that I've forgotten that it was hard to understand once. The C `for` loop can be used for so many things that it's hard to give it a name that describes what it does.

**Comment by Rocknest** [comment]
Status quo hack:
```zig
for (([number]void)(undefined)) |_| {
  //
}
``` 
From https://github.com/ziglang/zig/pull/3585#discussion_r343812610

**Comment by zzzoom** [comment]
> 
> 
> Not going to do this, when this is perfectly fine:
> 
> ```zig
> var i: usize = a;
> while (i < b) : (i += 1) {}
> ```
> 
> I don't think lack of this range feature is causing any actual problems. However pay attention to the coroutine rewrite issue (#2377) because Zig may gain generators out of it.

I am looking into Zig as a potential language for HPC because of its relative simplicity while providing modern metaprogramming, and having poor ergonomics on a range `for` is a dealbreaker: nested loops over many dimensions, where each dimension might also be tiled, are extremely common.

**Comment by jbsolomon** [comment]
Maybe facilities like multi-variable `for` sugar, or custom operators, should be provided by third-party lang extensions, while keeping the core language lean?  I keep seeing people suggesting abstract source transforms for math and HPC, but in my eyes a major selling point for Zig is that the core language is lean, explicit, and mostly readable (which is a huge plus for a team lead.)

I can certainly see it from both sides, and I think that a good compromise is the ability to extend a lean core language with source transforms or similar source-level metaprogramming capabilities (like in Racket.)  Highly expressive syntax is imperative for some users, and a deal-breaker for others, and "sort of expressive" is a bad compromise.

Failing that, I think most Zig users are coming at it primarily from a "Better C" angle, where they need explicit, detailed, readable source code, and that is also my preference.

**Comment by zzzoom** [comment]
> Maybe facilities like multi-variable `for` sugar, or custom operators, should be provided by third-party lang extensions, while keeping the core language lean?

Look, I'm not asking for multi-variable `for` loops, that's just an example. The issue is that Zig doesn't have a decent single-variable `for` loop atm.

**Comment by pfgithub** [comment]
A workaround right now that supports runtime numbers is
```zig
pub fn range(max: usize) []const void {
    return @as([]const void, &[_]void{}).ptr[0..max];
}
…
for(range(25)) |_, i| {
    print(i);
}
```
Something should be done about this because `{var i = 0; while (i < n; i += 1) { … }` is both hard to read and hard to write

If #6965 gets accepted, a function could be made to do this with no runtime cost and no extra language features:
```zig
range(0, 25, |i| {
    print(i);
});

inline fn range(start: usize, end: usize, body: macro(i: usize) void) void {
    var i = start;
    while(i < end) : (i += 1) {
        inline body(i);
    }
}
```

**Comment by EleanorNB** [comment]
Whenever iteration over a range is desired, there is typically some data structure to act on, so a structural loop would be better -- this may not be immediately obvious, so I think it's actually a good thing that ranged looping is clunky, because then the author is forced to think twice whether that's what they actually want. This functionality is already possible, and we shouldn't make it easier. As noted, a #6965-based solution will be clean, and I don't think we should have tighter language integration than that.

**Comment by tuket** [comment]
> there is typically some data structure to act on, so a structural loop would be better
Not true for my field of programming. There are many use cases where you want to iterate a number of times but you don't have a data structure. For example raytracing.

```
for(int i = 0; i < numSamples; i++) {
  ray = randomRay(i);
  // ...
}
```

I don't think it's a good idea to make the syntax clunky derivelately just because we think it's not a good way to do it. Different programmers, work of different problems, and we don't know what is right for them.

**Comment by BinaryWarlock** [comment]
Huge +1 for the `for(a..b)` syntax. Zig desperately needs this, and:
```zig
var i: usize = a;
while (i < b) : (i += 1) {}
```
Is most definitely not "perfectly fine" if you're doing a lot of iteration. It's also not nice to read. I don't see what's so bad about OP's proposal. Zig aims to be conservative in the wrong ways sometimes. It has an abundance of features it doesn't shy from, but not basic iteration primitives that exist in nearly every other imperative language?

**Comment by cryptocode** [comment]
@andrewrk regarding https://github.com/ziglang/zig/issues/358#issuecomment-491004876

>```
>var i: usize = a;
>while (i < b) : (i += 1) {}
>```

An significant issue here is that the current `while` construct makes it easy to introduce subtle bugs due to the larger scope of referenced variables.

I think a good middle-ground could be to add an **optional** initializer-clause to `while`:

```
while (var i: usize = a; i < b) : (i += 1) {}
```

which is backwards-compatible syntax sugar for an additional scope/block, i.e.
```
{
    var i: usize = a
    while (i < b) : (i += 1) {}
}
```
Doing this manually for nested loops is not something I think most people are going to do.

The point is to avoid polluting the outer scope, and to restrict the scope of `i`, thus avoiding subtle bugs. It's why C99 allowed declarations to go into the initializer clause of the for loop.

Adding brackets could be allowed to put an arbitrary amount of statements in the initializer.

Of course, the above syntax kind of begs for the continue-expression to be moved into the while as well:

```
while (var i: usize = a; i < b; i += 1)
```

leaving us with a for-loop called while 😅  But I would be happy to see the initializer-clause only.

**Comment by MasterQ32** [comment]
I know this proposal is closed already, but one thing to think about is this:
```zig
for(0..@as(u8, 255)) |index| {
  ...
}
```

is way more readable and less error prone than

```zig
var index: u8 = 0;
while(true) {
  ...
  if(@addWithOverflow(u8, index, 1, &index))
    break;
}
```

So my call would be: if done, the range needs to be inclusive to allow such loops to be implemented efficiently and without the requirement of `@intCast` or `@truncate`

**Comment by nodefish** [comment]
FWIW you can always increment a variable with `defer`:

```zig
while(...) {
    defer i = i + 1;
}
```

**Comment by ifreund** [comment]
> FWIW you can always increment a variable with `defer` if you don't like `: (i += 1)`
> 
> ```zig
> while(...) {
>     defer i = i + 1;
> }
> ```

This does not have the same semantics as the `: (i +=1)` continue expression as the defer will be executed on breaking from the loop while the continue expression will not.

**Comment by nodefish** [comment]
> > FWIW you can always increment a variable with `defer` if you don't like `: (i += 1)`
> > ```zig
> > while(...) {
> >     defer i = i + 1;
> > }
> > ```
> 
> This does not have the same semantics as the `: (i +=1)` continue expression as the defer will be executed on breaking from the loop while the continue expression will not.

Consider the following snippet:
```zig
const std = @import("std");
const warn = std.debug.warn;

pub fn main() void {
    var i: u8 = 0;

    while (i < 10) {
        defer i += 1;
        warn("{}\n", .{i});
    }
}
```

The output is:

```
0
1
2
3
4
5
6
7
8
9
```

It's easy to overlook but each iteration of a loop has its own frame.

**Comment by ifreund** [comment]
@nodefish:
```zig
const std = @import("std");
const print = std.debug.print;

pub fn main() void {
    print("loop 1:\n", .{});
    var i: u8 = 0;
    while (i < 10) {
        defer i += 1;
        print("{}\n", .{i});
        if (i == 5) break;
    }
    print("{}\n", .{i});

    print("loop 2:\n", .{});
    i = 0;
    while (i < 10) : (i += 1) {
        print("{}\n", .{i});
        if (i == 5) break;
    }
    print("{}\n", .{i});
}
```
```
loop 1:
0
1
2
3
4
5
6
loop 2:
0
1
2
3
4
5
5
```

**Comment by cryptocode** [comment]
@EleanorNB I'm trying to address the scoping issue. I don't see people adding additional {} scopes in complex/nested loops, leaving the door open to subtle bugs. I see how the ; sequence means a difference syntax is needed, but that's orthogonal.

**Comment by nodefish** [comment]
@EleanorNB 
> Dude's been here for years, please don't be condescending.

Please reconsider your uncharitable reading of what I wrote. I will leave it at that.

@ifreund 

I see, thanks for the clarification. That is rather subtle.

**Comment by thejoshwolfe** [comment]
You can do range iterators in userland:

```zig
fn range(times: usize) RangeIterator {
    return RangeIterator{
        .cursor = 0,
        .stop = times,
    };
}

const RangeIterator = struct {
    cursor: usize,
    stop: usize,

    pub fn next(self: *RangeIterator) ?usize {
        if (self.cursor < self.stop) {
            defer self.cursor += 1;
            return self.cursor;
        }
        return null;
    }
};
```

However, I did some optimization science in godbolt, and i believe there is some optimization benefit to having some kind of builtin range loop.

### Call a function N times

Baseline status quo: https://godbolt.org/z/rdYMq4

```zig
export fn callSomethingNTimes(num: usize) void {
    var i: usize = 0;
    while (i < num) : (i += 1) {
        something(i);
    }
}
```

More convenient syntax using a userland iterator: https://godbolt.org/z/98G5d3

```zig
export fn callSomethingNTimes(num: usize) void {
    var it = range(num);
    while (it.next()) |i| {
        something(i);
    }
}
```

The output is slightly different, but I'm not an expert enough to know which one is better.

### Do math with the iterator variable

using iterator integer: https://godbolt.org/z/Y5Pon5

```zig
export fn mathThing(num: usize) usize {
    var sum: usize = 0;
    var i: usize = 0;
    while (i < num) : (i += 1) {
        sum +%= i * i;
    }
    return sum;
}
```

using iterator object: https://godbolt.org/z/Gh7MPc

```zig
export fn mathThing(num: usize) usize {
    var sum: usize = 0;
    var it = range(num);
    while (it.next()) |i| {
        sum +%= i * i;
    }
    return sum;
}
```

The output looks _very_ different for these two, which declares the iterator integer the clear winner in terms of optimizability.

So it's not as clear cut as "just use a userland iterator object", but the option is still there.

**Comment by andrewrk** [comment]
> The output looks _very_ different for these two, which declares the iterator integer the clear winner in terms of optimizability.
> 
> So it's not as clear cut as "just use a userland iterator object", but the option is still there.

see also the `-OReleaseSmall` optimization mode for these examples which is quite interesting

**Comment by Srekel** [comment]
> The fundamental issue is: almost every single time you want to iterate over a range in real code, it's actually to index into a data structure.

@EleanorNB I don't agree with this. Maybe it is in your domain, but in game development it is quite common to loop over ranges that aren't bound to an exact data structure. 

Or you may have a data structure, but you may want to sample over it in weird ways, for example in a circular pattern.

And it is often two-dimensional, sometimes three, and that makes using the while loop @andrewrk suggested cumbersome.

Not having a programmer-friendly way to write for loops would I think be quite alienating to game programmers. And I'm not sure I see the upside. The appeal of Zig's current for loops *is* very appealing as-is, I will still use them when I can.

Here's some typical code I've written, taken from the map generation code for Hammerting:

```C++

  // Fix foreground in an oval area near the start
  f32 width_sq  = flatten_width * flatten_width;
  f32 height_sq = flatten_height * flatten_height;
  for ( f32 y = -flatten_height; y < flatten_height; y++ ) {
    for ( f32 x = -flatten_width; x < flatten_width; x++ ) {
      f32 ellipse_eq = x * x / width_sq + y * y / height_sq;
      if ( ellipse_eq >= 1 ) {
        continue;
      }

      double influence_x = 1 - wc::abs( x ) / flatten_width;
      double influence_y = 1 - wc::abs( y ) / flatten_height;
      double  influence = influence_x * influence_y;
      i32     map_index = room_pos._x + i32( x ) + ( room_pos._y + i32( y ) ) * i32( MAP_WIDTH );
      double& heightmap_value = heightmap[map_index];
      heightmap_value += ( y <= 0 ? 2 : -2 ) * influence * influence;
      if ( heightmap_value < HEIGTMAP_CUTOFF ) {
        out->_foreground._materials[map_index] = 0;
      }
      else {
        u8 mat                                 = out->_background._materials[map_index];
        out->_foreground._materials[map_index] = mat;
      }
    }
  }
```

**Comment by BinaryWarlock** [comment]
> The fundamental issue is: almost every single time you want to iterate over a range in real code, it's actually to index into a data structure

That's simply not true at all, I've read (and written) mountains of "real code" that does this all the time. Again, I do not see how experienced C programmers have not encountered this more often than some claim. Also, writing a RangeIterator is more verbose than just using the status-quo while loop, which is no good. 

This problem is exacerbated by not being able to shadow locals, and making a new block scope just for iteration is awful. This is a super unergonomic case in Zig right now and *something* should be done about it.

**Comment by ElectricCoffee** [comment]
Getting some form of range functionality would be really nice, if not for readability, then for writeability.

Surely it's possible to have the compiler build an array at compile-time or return a slice at runtime in order to facilitate something like this:

```zig
for (@range(2, 8)) |i| {
    // do stuff
}
```

Maybe even leverage anonymous structs somehow to facilitate optional arguments:

```zig
for (@range(2, 8, .{ .by = 2, .inclusive = true })) |n| {
    // you get it
}
```
It's not as elegant as the equivalent in Python, but it's at least clear in its intent and much harder to mess up than a c-style for loop or a plain while with a `defer`

**Comment by Guigui220D** [comment]
Also to specify the type @ElectricCoffee , like `@range(u8, 0, 10)`

**Comment by ElectricCoffee** [comment]
> Also to specify the type @ElectricCoffee , like `@range(u8, 0, 10)`

I didn't even think of that, but yeah, that's a good logical addition also

**Comment by hazeycode** [comment]
I made a comptime range fn for anyone interested:
https://gist.github.com/hazeycode/e7e2d81ea2b5b9137502cfe04541080e

**Comment by gonzus** [comment]
If we are still looking for a range notation, I find this quite readable and it covers all the cases:
```
a =..< b  // includes a, excludes b; most used case?
a =..= b  // includes a, includes b
a >..= b  // excludes a, includes b
a >..< b  // excludes a, excludes b
```
You could even have `a .. b` as shorthand, equivalent to the first case.

**Comment by dbechrd** [comment]
> If we are still looking for a range notation, I find this quite readable and it covers all the cases:
> 
> ```
> a =..< b  // includes a, excludes b; most used case?
> a =..= b  // includes a, includes b
> a >..= b  // excludes a, includes b
> a >..< b  // excludes a, excludes b
> ```
> 
> You could even have `a .. b` as shorthand, equivalent to the first case.

I assume you meant your `>` to be `<` on the left side? Your suggestion would make significantly more sense that way:
```
a =..< b  // equal to less than
a =..= b  // equal to equal
a <..= b  // greater than to equal
a <..< b  // greater than to less than
```

That said.. exclusive start seems pretty bizarre to me, so why not just:
```
a ..< b  // exclusive
a ..= b  // inclusive
```

**Comment by gonzus** [comment]
Yes, I meant that, brain fart.

I now realise this issue is closed, and I am not sure if any decision was made about this; anybody knows?

**Comment by Vexu** [comment]
#7257 is accepted and will add for loops on ranges.

**Comment by andrewrk** [comment]
Multi-object for loops have landed with #14671, and now for loop syntax supports counters:

```zig
const std = @import("std");

pub fn main() !void {
    for (0..10) |i| {
        std.debug.print("{d}\n", .{i});
    }
}
```

```
$ zig run test.zig 
0
1
2
3
4
5
6
7
8
9
```

**Comment by jkellogg01** [comment]
Are there any plans for inclusive counters as a convenience? obviously the same functionality is achievable by just increasing the end number by one but I would argue there's a readability benefit to the counter being able to specify that it's inclusive.

I know there have been a bunch of suggestions in terms of formatting, but I haven't seen a mention of the fact that Rust already uses the `x..y` syntax for exclusive ranges and simply uses `x..=y` to specify inclusive. The benefit to borrowing this syntax would be that the existing counter syntax wouldn't need to change at all.

**Comment by dje4321** [comment]
> I know there have been a bunch of suggestions in terms of formatting, but I haven't seen a mention of the fact that Rust already uses the `x..y` syntax for exclusive ranges and simply uses `x..=y` to specify inclusive. The benefit to borrowing this syntax would be that the existing counter syntax wouldn't need to change at all.

I agree and I feel like the simplest way to prove the point is to try and reduce the number of options required whether or not a/b is inclusive or not. Simply take the position that A is always inclusive and just specify if B is exclusive or inclusive. You can basically always assume that A is going to be inclusive because otherwise you would just move the start position to where you actually want to start. But you cant really move the end position beyond something like a list

From a human & coding perspective, saying "loop over everything in this box plus one" is alot harder to understand conceptually than "loop over everything except the first item in this box". 

Include A, Exclude B
> a..b

Include A, Include B
> a..=b

Exclude A, Exclude B
> a+1..b

Exclude A, Include B
> a+1..=b
