### ISSUE TITLE
Proposal: @cpuid builtin

### ISSUE THREAD

**Issue by data-man** [ziglang/zig#3622]
**Possible new builtin:**
```zig
@cpuid(id: u32,    // == EAX
       subId: u32  // == ECX
       ) ?[4]u32
```
**New module**: `cpuid.zig` (I can take it)
**Comptime**: returns host's results
**Runtime**:  returns target's results

**Related**: #215, #767, #1018

**Comment by tuket** [comment]
https://en.wikipedia.org/wiki/CPUID
I like the idea

**Comment by daurnimator** [comment]
> **Comptime**: returns host's results

There's nothing in zig (apart from `@embedFile` I guess) that exposes information about the host. Why would you want/need this?

**Comment by pixelherodev** [comment]
I agree; there is no practical benefit to that functionality, so it would just increase the compiler's complexity without providing any real benefits.

**Comment by ElementW** [comment]
This proposal has a couple issues in my opinion:
- This signature is very x86-y:
  - inputs & outputs are 32-bit, but some targets have other lengths for their `cpuid` equivalent; e.g. RISC-V CSRs are of the core's native bit length (`XLEN`), and it's not just left-padding with zeroes
  - not all architectures have dynamically selectable feature registers; e.g. ARM's `mrs` instructions encode the selected register in its instruction directly
  - archs may have more or less than 2 parameter registers/inputs
- It doesn't need to be a builtin really. Since how to get the CPU info and what you get back is very arch-specific you need to wrap that around code to discriminate the features you want, you'll need to either:
  - use said wrapper (possibly this could end up in the standard lib)
  - or roll your own, in which case having to call the target architecture's `cpuid` instruction equivalent by yourself will not make the task any harder
- Returning the host/target's results depending on `comptime` is nothing short of a recipe for making mistakes; the difference of action is invisible to somebody reading the source without knowing of your proposal's idiosyncrasies. At best you'd need to split it into `@hostCpuid` and `@targetCpuid`.
- As @daurnimator said, there's no reason to expose info about the host anyway, as you're producing code to be ran on a target, not the host. If you want the code to run on the host, then the target *is* the host.
