### ISSUE TITLE
Can't pass anonymous struct/list literal to generic function

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#3665]
```zig
fn consumeVec(vec: [3]f32) void {}
pub fn main() void {
    consumeVec(.{0, 1, 2});
}
```

```
Semantic Analysis [700/701] /home/dbandstra/host/asdf.zig:3:17: error: expected type '[3]f32', found 'struct:3:17'
    consumeVec(.{0, 1, 2});
                ^
/home/dbandstra/host/asdf.zig:3:17: note: struct:3:17 declared here
    consumeVec(.{0, 1, 2});
                ^
/home/dbandstra/host/asdf.zig:3:15: note: referenced here
    consumeVec(.{0, 1, 2});
              ^
```

Don't mind me, I'm have fun playing around with this new feature.

---

Here's a weird variation:
```zig
fn consumeVec(vec: [3]u32) void {}
pub fn main() void {
    var v: bool = false;
    consumeVec(.{
        if (v) @as(u32, 0) else @as(u32, 10),
        1,
        2,
    });
}
```

```
Semantic Analysis [704/709] /home/dbandstra/host/asdf.zig:5:16: error: expected type 'c_void', found 'u32'
        if (v) @as(u32, 0) else @as(u32, 10),
               ^
/home/dbandstra/host/asdf.zig:5:9: note: referenced here
        if (v) @as(u32, 0) else @as(u32, 10),
        ^
```

Not sure where `c_void` is coming from.

**Comment by dimenus** [comment]
@dbandstra I think your first example is working as intended. Zig should not implicitly coerce that into an [3]f32.

however, this works:

```
fn consumeVec(vec: [3]f32) void {}
test "anon list to function" {
    consumeVec(@as([3]f32, .{ 0, 1, 2 }));
}
```

**Comment by andrewrk** [comment]
This is supposed to work - `@as` is defined to be identical to the type coercion done by passing fn parameters: https://ziglang.org/documentation/master/#Type-Coercion

See the example "test "type coercion - function call"

**Comment by emekoi** [comment]
where exactly can we find the code for implicit type coercion in the compiler?

**Comment by andrewrk** [comment]
What implicit type coercion looks like in ir.cpp is going through a transition. It used to look like this (in Zig IR pass2, the analysis phase):

```c++
IrInstruction *casted_value = ir_implicit_cast(ira, uncasted_value, dest_type);
```

That was before result location semantics. With result location semantics, the type coercion has to be set up in Zig IR pass1, the generation phase. Here's the implementation of `@as` (with `result_loc` renamed to `parent_result_loc` for clarity):

```c++
AstNode *dest_type_node = node->data.fn_call_expr.params.at(0);
IrInstruction *dest_type = ir_gen_node(irb, dest_type_node, scope);
if (dest_type == irb->codegen->invalid_instruction)
    return dest_type;

ResultLocCast *result_loc_cast = ir_build_cast_result_loc(irb, dest_type, parent_result_loc);

AstNode *arg1_node = node->data.fn_call_expr.params.at(1);
IrInstruction *arg1_value = ir_gen_node_extra(irb, arg1_node, scope, LValNone,
        &result_loc_cast->base);
if (arg1_value == irb->codegen->invalid_instruction)
    return arg1_value;

IrInstruction *result = ir_build_implicit_cast(irb, scope, node, arg1_value, result_loc_cast);
```

Point being that when you generate the zig IR for an AstNode, you have to set up a ResultLocCast to pass in to `ir_gen_node`. This is why @dimenus's example works, because `@as` does this setup. What needs to change is to do this setup for parameters of function calls.

For this particular issue, it's a bit tricky because in some cases, we don't have access to the parameter types (in the code example above, `dest_type`) until analysis phase. For example, the last parameter of a generic function call is only figured out later, inside `ir_analyze_fn_call`. This is the problem I'm currently dealing with in order to solve this issue.

Another way to solve it will be to allow inferred struct types to coerce to other types. This is less ideal because the value will take an unnecessary detour through the inferred struct type before being coerced to the final type, rather than being instantiated as the final type directly. However semantically, this should be undetectable to the programmer, and this is the stage1 compiler after all. When implementing self-hosted, it will be designed from the ground up with result locations in mind.

**Comment by andrewrk** [comment]
This now works for non-generic functions. For generic functions you'll get this:

```zig
fn consumeVec(x: var, vec: [3]f32) void {}
pub fn main() void {
    consumeVec({}, .{0, 1, 2});
}
```

```
/home/andy/dev/zig/build/test.zig:3:21: error: TODO: type coercion of anon list literal to array
    consumeVec({}, .{0, 1, 2});
                    ^
/home/andy/dev/zig/build/test.zig:3:15: note: referenced here
    consumeVec({}, .{0, 1, 2});
              ^
```

**Comment by dbandstra** [comment]
Updated the issue description because this affects struct values too (obviously).

```zig
fn consumeGeneric(comptime T: type, vec: T) void {}

pub fn main() void {
    consumeGeneric([3]f32, .{ 0, 1, 2 }); // doesn't work

    const SomeStruct = struct { a: u32 };
    consumeGeneric(SomeStruct, .{ .a = 0 }); // doesn't work
}
```

This feature would be pretty high on my wishlist. (There are a lot of sides of Zig that I don't personally ever interact with, which get a lot of contributor attention, but I really appreciate the day-to-day QOL stuff like this.) I don't like using `var` args when I can help it, so I want to write functions with signatures like this, but currently it means that calling such a function involves typing out the type name twice (like `consumeGeneric(SomeStruct, SomeStruct{ .a = 0 })`) (example [here](https://github.com/dbandstra/oxid/blob/c738b0ab52c6280bbb9894f59f2b44054f4ba835/src/oxid/systems/creature_take_damage.zig#L94)).

I would also say this issue should be considered a blocker for removing `SomeStruct{...}` initialization syntax in favor of `@as(SomeStruct, .{})`, which I think was proposed at some point. I would like to be able to avoid `@as` whenever possible due to its ugliness.

Is it still accurate to say this is a difficult fix because of the stage1 architecture?

**Comment by SpexGuy** [comment]
This seems to be working now, can this be closed?
