### ISSUE TITLE
Feature request: First class support for "kwargs"

### ISSUE THREAD

**Issue by frmdstryr** [ziglang/zig#3721]
Since zig does not support default arguments or overloaded functions (for good reasons). I think one  good alternative would be to just support "kwargs" or named parameters by populating an anonymous struct (which can have defaults).  

For example, this currently works on zig master:

```zig
fn foo(kwargs: struct{ a: u32, b: []const u8, c: bool = false}) void {
 if (kwargs.a > 1) {
   // etc.. ...
 }
}

foo(.{.a=21, .b="abc"}); // c is omitted and uses struct default

```
See https://godbolt.org/z/J9VY9G (created by mq32)

Which is really nice as it is,  but ideally there could be some syntax sugar on top of this yet.

Or at least this technique should be added to the docs.

**Comment by JesseRMeyer** [comment]
Do you have an actionable syntax proposal?

Generally, Zig supports the use of syntax sugar for semantic purposes (semantic sugar?).   Notice the presence of defer() but no c-style for loop as that's accomplished with a touch more syntax on top of a while loop.

Personally, instead of kwargs, I would define a public struct with default values that both users and functions expect to input or accept.  But that Zig allows this option is a strength as a natural by product of anon structs is a pleasant surprise to me.

**Comment by daurnimator** [comment]
What would "first class support" here imply? You can do this today.

**Comment by MasterQ32** [comment]
I don't think it's a feature the *language* requires. As told earlier (and in my example) you can see that it is little overhead to instantiate "kwargs" behaviour in Zig today and syntax sugar would make the language, grammar and compiler more complex for very little reward (saving roughly 13 characters to use kwargs).

Also i'm divided about default args. They make *writing* code a lot easier (thus as a creator, i love them), but they make maintaing code a lot harder (thus as a maintainer, i hate them).

Having a way to at least signal "you are probably using default args here", it's good that the function requires some syntactical difference (the anonymous struct) to normal function calls. As soon as zig would allow default args in a normal function call, we could also just add full featured function overloading (as default args are just a subclass of overloading) and i think there are pretty good arguments against overloading

¢ Just my two cents here ¢

**Comment by JesseRMeyer** [comment]
> but they make maintaing code a lot harder (thus as a maintainer, i hate them).

I know that user code which uses _outdated_ default values are quite problematic, but are there other reasons that you've felt that default values contribute to code maintenance?  I've found that make my life as a maintainer _easier_ in getting users familiar more quickly with common usage patterns, which is often a substantial time sink for maintainers.  It also provides maintainer the confidence that certain values are set by default (obviously) which prevents an entire class of bugs.  So I'm curious what you find that outweighs these benefits.

**Comment by frmdstryr** [comment]
Sorry the title doesn't make sense. 

In short, you can now pass a struct with default and optional fields but have to wrap it in a struct, then unpack the fields to use it... 

So why not just make that how functions normally work?  No overloading is needed. All functions just make a single struct internally with their args.

**Comment by MasterQ32** [comment]
@JesseRMeyer 

> I know that user code which uses outdated default values are quite problematic, but are there other reasons that you've felt that default values contribute to code maintenance?

Yes: It hides an argument of which the value may be wrong. So if i read a code like `formatNumber(someInt)`, i assume the function has only one argument, but if later there is a `formatNumber(someOtherInt, 10)`, i wonder:
What is the default argument value, now i actually have to look up the function definition instead of "relying on the name of the function"

=> More stuff to remember, as i now not only have to know the list of parameters but also the default value for each of those. kwargs makes this even worse

**Comment by JesseRMeyer** [comment]
@MasterQ32 Ah.  I agree that default function parameters values makes learning APIs less intuitive if the source code or documentation is not readily available, and that kwargs only add to this trouble, as interesting as it was as a thought experiment.

**Comment by Qix-** [comment]
For me, there is no "learning an API". I'm designing a game engine at the moment and I'd go crazy if I had to keep looking at reference docs just to read _my own_ code. Not having default parameters means I am forced to be a bit more explicit where I make calls to external libraries, but that's a small cost for the improved readability.

I can look at just about any part of my code and know exactly how it's behaving (or, at least, what the intent is) because everything is clearly defined and all of the information is available at the call site. This might not matter to some making smaller projects, but in real-world applications, this is pretty crucial.

Meanwhile, at work, we use python (which sports `kwargs`) with a codebase that is built on Django. It uses all the Python-isms and Django-isms correctly, cleverly reduces code using default parameters and whatnot, etc. However, because of all of the magic and cleverness, I can't write any code with confidence. I can't read any code with certainty. I _constantly_ have to look around the codebase to see what may or may not be happening. I work at least 10x slower than in a more strongly (or less "magically") typed language with more explicit syntax, even though I end up writing _more_ code in such languages.

Hitting the keys on the keyboard has never been the bottleneck for me; it's been the incessant referencing of docs to find out how single lines of code work that I find is the usual culprit.

**Comment by andrewrk** [comment]
Note that we have `@call` now which accepts a struct as the parameters. There are some compiler TODOs to solve, but once those are solved, `@call` allows "exploding" a struct into a function call based on parameter names.
