### ISSUE TITLE
Add build-time flag to turn off BUILDINFO subcommand

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#3758]
`zig BUILD_INFO` hardcodes information about the build system into the resulting binary. This is a no-no for good packaging practices.
Currently it's only used to help bootstrap src-self-hosted. If you're not building the self-hosted compiler, then there should be a switch to turn it off.

**Comment by andrewrk** [comment]
Yeah, OK. Once we're shipping self-hosted, we won't need this flag anymore. stage1 will have it, but the self-hosted compiler won't have this command.

**Comment by andrewrk** [comment]
I think we can get rid of BUILD_INFO entirely. My idea to do this is to have build.zig look for the `config.h` file that cmake creates (either that or have cmake create another file in a simpler text format that has the information needed).

The case where we need that information is for:
 * linking the stage2 tests
 * linking the stage2 compiler

I think the only tricky part will be getting build.zig to know where that file is (i.e. where the build folder is). I'm reluctant to hard code it or require explicitly passing it in, and we don't want the binary to have to tell it or it would leave us with the same problem as `BUILD_INFO`.

The only option I can think of is that build.zig will look for the file based on the path to zig, since `zig build` knows the path to the zig executable.

So imagine the following structure:

 * zig/build/zig
 * zig/build/bin/zig
 * zig/build-llvm11/zig
 * zig/build-release/bin/zig

In each example, the correct file is in the build folder, e.g. `build/config.h`. So here's what build.zig would do for each example:

 * zig/build/zig
    1. check `zig/build/config.h` (success)
 * zig/build/bin/zig
    1. check `zig/build/bin/config.h` (not found)
    2. check `zig/build/config.h` (success)
 * zig/build-llvm11/zig
    1. check `zig/build-llvm11/config.h` (success)
 * zig/build-release/bin/zig
    1. check `zig/build-release/bin/config.h` (not found)
    2. check `zig/build-release/config.h` (success)

You can see how this scheme allows multiple builds of zig side-by-side without stage2 getting confused about which llvm, clang, lld, and libzigcpp.a libraries it is supposed to link against.

With this we don't need an option, and we can delete BUILD_INFO.
