### ISSUE TITLE
unable to call function with a new stack with a runtime known new stack slice

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#3857]
With the merge of #3856, calling a function with a new stack regressed a bit:

```zig
export fn entry() void {
    var buf: [10]u8 align(16) = undefined;
    @call(.{.stack = &buf}, foo, .{});
}
fn foo() void {}
```

Used to be OK, now gives: 

```
/home/andy/dev/zig/build/test.zig:3:5: error: unable to evaluate constant expression
    @call(.{ .stack = &buf }, foo, .{});
    ^
```

Need more Runtime Hint Propagation to make this work. However this is a low priority because it's not clear this feature is going to make it into zig.

Above example works if you make the memory global:

```zig
var buf: [10]u8 align(16) = undefined;
export fn entry() void {
    @call(.{.stack = &buf}, foo, .{});
}
fn foo() void {}
```

**Comment by RaphiJS6-13** [comment]
I hate this bug. `@call` is a great feature, but now it's broken.

**Comment by Vexu** [comment]
Stack option removed in #13907

**Comment by 16hournaps** [comment]
I dont understand how are these @call related and .Naked related issues are low prio. The main use of this is embedded which I feel like very important for zig adoption. We can go by with .s but would be much nicer to go full zig with reset handlers written in zig. 

I understand this is WIP, but at 12.0 you would really expect these features to be accessible and stable: creating naked interrupt handlers and startup code that is.

I dont push since I dont know the backlog but seems kinda important language feature along with https://github.com/ziglang/zig/issues/18183
