### ISSUE TITLE
Writing to a file open with read permissions panics instead of returning error

### ISSUE THREAD

**Issue by DanB91** [ziglang/zig#3880]
Hi,

Running macOS Catalina and zig 0.5.0+5874cb04b.

On macOS Catalina, When calling f.write() on a file opened with File.openRead(), zig panics on EBADF, which in has a comment saying "always a race condition" and does not return an error.   This is a single-threaded program.  EBADF seems to be the proper error for writing to a file open for reading and is not a race condition:

`[EBADF]            fildes is not a valid file descriptor open for writing.`

This seems to be related to [this bug](https://github.com/ziglang/zig/issues/2428) but not 100% sure.
Here is the error trace:

```
reached unreachable code
lib/zig/std/os.zig:497:22: 0x105207854 in _std.os.write
            EBADF => unreachable, // Always a race condition.
                     ^
lib/zig/std/fs/file.zig:296:24: 0x105203992 in _std.fs.file.File.write
        return os.write(self.handle, bytes);
                       ^
prog.zig:48:16: 0x105210cc3 in _main.0 
        f.write(bytes[0..]) 
               ^
``` 

Please let me know if you need anything else from me

**Comment by andrewrk** [comment]
The man pages say this:

>        EBADF  fd is not a valid file descriptor or is not open for writing.

Unfortunately, `EBADF` is ambiguous. The "not a valid file descriptor" is always a race condition, but the "not open for writing" is not necessarily a race condition. It would be much better if the kernel gave us an error code to distinguish between these two things, but alas, here we are.

Because of the "or is not open for writing", I believe we need to change this from `unreachable` to `return error.NotOpenForWriting,`. This essentially "asserts" that the "not a valid file descriptor" never occurs. Unfortunately, we have no way to safety-check this assertion.

**Comment by pixelherodev** [comment]
Proposal: on MacOS, add a bit to check what mode we opened the file in? Then, we can check whether we opened it for writing and return an error or `unreachable` based on that.
