### ISSUE TITLE
Improve the error message on missing ':' in while statement

### ISSUE THREAD

**Issue by ofelas** [ziglang/zig#416]
As shown in the following example.

Was expecting it to complain on the `while (...) (...) {`.

```
// -*- indent-tabs-mode:nil; -*-
const std = @import("std");
const print = std.io.stdout.printf;

pub fn main() -> %void {
    const buf : [3]u8 = []u8{'a','b','c'};

    var i : usize = 0;
    const count : usize = buf.len;
    while (i < count) : (i += 1) {
            %%print("{}/{}/{}\n", i, buf[i], count);
    }
}

// zig commit 221e5b

// step 1
// original working program
// build_exe and run
// output:
// 0/97/3
// 1/98/3
// 2/99/3

// step 2
// remove ':' from while line (or forget to put it in)
// while (i < count) (i += 1)
// build_exe
// y.zig:11:52: error: expected token '}', found ';'
//            %%print("{}/{}/{}\n", i, buf[i], count);
//                                                   ^

// step 3
// remove ';' as indicated by error message
// build_exe and run (panics)
// output:
// 1/98/3
// 2/99/3
// index out of bounds
// : snip, snip
// @import("std").debug.panic("{}", message_ptr[0..message_len]);

```

**Comment by thejoshwolfe** [comment]
As with many syntax errors, there are multiple single-token changes that could resolve the error, and it's very difficult for a machine to anticipate what you meant. In your particular case, the machine suggested the wrong thing. But that's just the tip of the iceberg with this example. There's a lot to learn from here.

Ultimately, i think the whitespace should play a bigger role in the syntax, such that even a semantically valid omission of the `:` would still be an error because it *looks* like an error. Teaching a computer how to detect what looks like an error is tricky but not impossible. Perhaps a rule like "if `while` is the first token of a line and `{` is the last, then the `{` has to be the start of the while body.". This fits with zig's goals of being readable.

Another issue is how in the world did your program compile after removing the `;`?? Looks like `(i += 1)` was an expression that evals to `{}`, which is then struct initialized with a single field which is also `{}`? I don't even know if that's right. But whatever your code ended up being should not be allowed. That would have helped the situation, but might not be a perfect ultimate solution.

**Comment by ofelas** [comment]
It seems to be possible to provoke similar issues with a `for` loop.

```
const print = @import("std").io.stdout.printf;

pub fn main() -> %void {
    const buf : [5]u8 = []u8{'a', 'b', 'c', 'd', 'e'};
    var ii : usize = 0;
    const count : usize = buf.len;
    var f:f32 = 3.14;
    for (buf) |val , i| ({ii += i; ii += i; f *= f; }) {
       %%print("{}/{}/{}/{}/{}\n", i, val, count, ii, f) // ;
    }
}
```
uncomment the `// ; ` and
```
for.zig:10:58: error: expected token '}', found ';'
        %%print("{}/{}/{}/{}/{}\n", i, val, count, ii, f);
```
