### ISSUE TITLE
Order of struct field initialization causes segfault with async function call

### ISSUE THREAD

**Issue by svmhdvn** [ziglang/zig#4306]
Here is an example:

```zig
const std = @import("std");
const Allocator = std.mem.Allocator;
const Parser = std.json.Parser;

const Client = struct {
    handle_frame: @Frame(handle),
    parser: Parser,

    pub fn handle(self: *Client) !void {
        const tree = try self.parser.parse("[42]");
    }
};

pub fn main() anyerror!void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = &arena.allocator;

    const client = try allocator.create(Client);

    // NOTE here, the parser is initialized before the handle_frame
    client.* = Client{
        .parser = Parser.init(allocator, false),
        .handle_frame = async client.handle(),
    };
    try await client.handle_frame;
}
```

This program runs with no errors. However, changing the field order for the initialization of `client`:

```zig
client.* = Client{
    .handle_frame = async client.handle(),
    .parser = Parser.init(allocator, false),
};
```

causes a segfault at runtime:

```
Segmentation fault at address 0xffffffffffffffd2
/home/siva/zig/build/lib/zig/std/json.zig:1325:60: 0x230432 in std.json.Parser.transition (test)
                var array = &p.stack.items[p.stack.len - 1].Array;
                                                           ^
/home/siva/zig/build/lib/zig/std/json.zig:1246:29: 0x22e91f in std.json.Parser.parse (test)
            try p.transition(&arena.allocator, input, s.i - 1, token);
                            ^
/home/siva/zig-jmap/test.zig:11:43: 0x22dce5 in Client.handle (test)
        const tree = try self.parser.parse(msg);
                                          ^
/home/siva/zig-jmap/test.zig:22:25: 0x229f64 in main (test)
        .handle_frame = async client.handle(),
                        ^
/home/siva/zig/build/lib/zig/std/start.zig:250:37: 0x2079d5 in std.start.posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/home/siva/zig/build/lib/zig/std/start.zig:114:5: 0x20784f in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
```

Is this behaviour intentional?

**Comment by fengb** [comment]
You have a race condition in the initializer: `async client.handle()` depends on client.parser already being defined. Your first call initializes it first, but in the second call client.parser is still undefined when you try to handle the client.

**Comment by svmhdvn** [comment]
Ah thanks, I see that async function calls are just like regular calls in that they are called immediately. Closing.

**Comment by andrewrk** [comment]
Note that your handle function does not suspend. When async functions are called with `async`, control flows until the first suspend point, and then returns to the caller. Normally a suspend point will happen when I/O is performed, if you enable evented I/O mode in the standard library. This is generally appropriate. However, one may also use std.event.Loop.startCpuBoundOperation() which will (under the right conditions ) cause the function to switch threads for better CPU utilization. 

I'm guessing for your use case, you probably will want to enable evented I/O mode. And then you will run into the problems that I am actively working on solving, since this is my current area of focus in the compiler and std lib.
