### ISSUE TITLE
allow implicit cast from *T to ?*c_void

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#433]
Should we allow implicitly casting pointers to `?*c_void`?

**Comment by raulgrell** [comment]
This looks both convenient for reducing clutter in code, and should be perfectly safe, but seeing the cast to `?&c_void` is a nice reminder that you are interfacing with unsafe/c code.

**Comment by raulgrell** [comment]
I've been interfacing with more and more C code and especially with the new developments around casting I think this feature would be pretty welcome.

**Comment by andrewrk** [comment]
I appreciate that feedback. What do you think about the proposal to add another pointer type specifically for C interop? #1059

**Comment by raulgrell** [comment]
Yet another pointer type sounds awful, but the convenience of not having to manually correct your imports is really tempting... I think Zig has to do everything it can to make C interop completely seamless. I'll comment more on that issue's thread.

Since any 'real' binding to a C library need work beyond what translate-c can do, any problems inherent to this kind of pointer won't be an issue for 'real code'. I say go for it.

**Comment by andrewrk** [comment]
implemented in e2a9f2ef988e6ff4ec9f943ead9285c67c56ffd7 by @raulgrell
