### ISSUE TITLE
rename "traits" to "constraints" or "concepts" in std.meta

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4450]
There's an established nomenclature for this: [C++ Constraints & Concepts](https://en.cppreference.com/w/cpp/language/constraints)

Not to be confused with [Rust's traits](https://doc.rust-lang.org/rust-by-example/trait.html).

**Comment by tgschultz** [comment]
The way terminology is with programming languages, I'm not sure it is worth the effort solely to avoid confusion. A Rust `enum` is different from a zig `enum`, for instance. An alternative name I might suggest would be 'property', except that it is overloaded by even more programming languages.

On the other hand, it is easily changed.

**Comment by afranchuk** [comment]
I'm for this renaming, because while there aren't necessarily any seminal papers/research to clarify or define the terminology, traits (type traits) in rust, haskell, etc. are used both as argument constraints _and_ (importantly) are ascribed onto types directly. This second part is a notable difference; typically implementations will have some compile time metadata which records the type traits that are implemented for a type, such that at call sites a type can be checked against argument constraints efficiently. This differs from the code implemented in `std.meta.traits` as this code will verify types of arguments at call/usage sites the "long" way (though one _could_ implement a trait system in zig as well, and/or memoize type verification).

The current code is much more akin to C++ concepts. There could be a `std.meta.traits` that implements type traits which are ascribed onto types (and thus may operate slightly differently as well, maybe even supporting vtables/trait objects), but I'd feel much better if what was currently in `std.meta.traits` was renamed to `std.meta.concepts` or something else, just to drive home the scheme being used.

**Comment by EnronEvolved** [comment]
This issue is moot since d5e21a4…
