### ISSUE TITLE
`@typeInfo` should return declarations in declaration order

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4495]
Currently `@typeInfo` returns declarations in hash map order, which leaks nondeterminism into builds. It also prevents declarations from being used as data. E.g. here:

https://github.com/ziglang/zig/blob/5e37fc0746a75ed319fc57ae62d8cc966382c592/lib/std/target/riscv.zig#L71-L120

Currently `std.meta.declList` does a comptime sort. But that should be unnecessary, and in some cases declaration order could be meaningful.

A related proposal is to remove declarations from `@typeInfo` altogether. I thought I had an open proposal for that, but I can't find it at the moment.

Another related pull request right now is making `@typeInfo` declarations lazy: #4435

**Comment by FireFox317** [comment]
Is this a stage 2 thing?

For stage1 we could add a list to next to the decl table, which stores pointers to key,value pairs, however this would increase memory usage and since we are not yet at the 3.5GB max memory usages, that is probably not a good idea.

Another option is to change the decl table to a vector, but that would probably slow down the compiler to much, since lookup will change from log(O) to log(N).

**Comment by andrewrk** [comment]
> Is this a stage 2 thing?

Sure, I think it would be reasonable to implement this only in stage 2.
