### ISSUE TITLE
Can't compile an simple Hello World! on **zig-windows-x86_64-0.5.0+1d06c82c3**

### ISSUE THREAD

**Issue by wooowchik** [ziglang/zig#4548]
![zzig](https://user-images.githubusercontent.com/61240425/75204833-4d1f3300-5772-11ea-81bb-ab83d0344455.PNG)

**Comment by JesseRMeyer** [comment]
Yeah, Zig only supports Unix line endings so you'll have to adapt your editor when programming in Zig.

Guys, we're going to see a lot more of this the more popular Zig becomes with Win32 devs, so I think it's time to consider outputting more explanation text for this error -- that it isn't a compiler error, and it's an error by design, etc.

**Comment by wooowchik** [comment]
> Yeah, Zig only supports Unix line endings so you'll have to adapt your editor when programming in Zig.
> 
> Guys, we're going to see a lot more of this the more popular Zig becomes with Win32 devs, so I think it's time to consider outputting more explanation text for this error -- that it isn't a compiler error, and it's an error by design, etc.

How to solve this problem ?

**Comment by andrewrk** [comment]
change your editor to use \n rather than \r\n or, run zig fmt on your code

**Comment by wooowchik** [comment]
> change your editor to use \n rather than \r\n or, run zig fmt on your code

I have solved this problem in a different way some seconds ago :)
Basically on Notepad++ i got selected the following stuff : 
EOL Conversion = Unix 
Encoding = UTF-8
