### ISSUE TITLE
make install doesn't install

### ISSUE THREAD

**Issue by donbright** [ziglang/zig#4685]
following

https://github.com/ziglang/zig

```

mkdir build
cd build
cmake ..
make install

...

[ 99%] Built target zig0
[ 99%] Built target zig_build_libstage2
[100%] Built target zig
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /home/don/src/zig/build/bin/zig
-- Installing: /home/don/src/zig/build/lib

don@oysters:~/src/zig/build$ zig

Command 'zig' not found, did you mean:

```

**Comment by donbright** [comment]
workaround

```
sudo cp -av lib/zig /usr/local/lib/
sudo cp -av bin/* /usr/local/bin/
```

**Comment by ziol** [comment]
You can specify install path via cmake:

```
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_PREFIX_PATH=/usr -DCMAKE_BUILD_TYPE=Release
make install
```

**Comment by andrewrk** [comment]
It's just the `-DCMAKE_INSTALL_PREFIX` that you need here. It's not the default because this is the stage1 compiler, and self-hosted is work-in-progress. You can learn more in README.md. Package managers typically provide an explicit install prefix anyway, and in fact if you are a user building from source it's not recommended to install zig globally; instead it's recommended to leave zig built in a source checkout, and put a symlink to it in your PATH. This allows you to have multiple versions of zig on your system, so that you can easily test your projects with different versions. Until zig is more stable, this is sometimes necessary.
