### ISSUE TITLE
question: how String literals and and an array which has same chars can be mem.eql

### ISSUE THREAD

**Issue by vired** [ziglang/zig#4760]
on https://ziglang.org/documentation/master/#toc-String-Literals-and-Character-Literals it says that "String literals are single-item constant Pointers to *null-terminated* UTF-8 encoded byte arrays."

but on https://ziglang.org/documentation/master/#toc-Arrays it says that this two things have eql mem.
```
const message = [_]u8{ 'h', 'e', 'l', 'l', 'o' };
const same_message = "hello";

```
if string literals are null terminated they will have a null byte at the end. so `same_message` will have 6 bytes.

can you please explain this ?

**Comment by joachimschmidt557** [comment]
When you use `std.mem.eql`, you provide two slices of type T. In your example, both `message` and `same_message` will be coerced to `[]const u8`. When doing that, the null byte at the end will not be included in the resulting slice.

**Comment by vired** [comment]
@joachimschmidt557 thank you, But why 
> When doing that, the null byte at the end will not be included in the resulting slice.

this is done?

**Comment by joachimschmidt557** [comment]
Slices, rather `[]const u8` are the way strings are handled in zig. Because they have a runtime assigned length to them, they don't need a sentinel a.k.a. null byte at the end, because we know how long they are.

If you however, interact with C code which doesn't have this slice feature, you need to use a sentinel-terminated slice which guarantees a null byte at the end. A normal slice (of any type) does not need and does not guarantee a null byte at the end.

**Comment by andrewrk** [comment]
Feel free to keep discussing, it's just not an "open" issue in the language. There are also [other areas to discuss](https://github.com/ziglang/zig/wiki/Community)
