### ISSUE TITLE
unable to build i386 glibc: lld: error: relocation refers to a symbol in a discarded section

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4926]
```
$ ./zig test ../test/stage1/behavior.zig -target i386-linux-gnu -lc
lld: error: relocation refers to a symbol in a discarded section: __x86.get_pc_thunk.bx
>>> defined in /home/andy/.cache/zig/stage1/o/QwPOfrBzzIXOEPuFhvbaQ4pBmiZk1vZIjVDP_sy7CCeeXOl8s6Zh8l0nMcfprTj6/crti.o
>>> referenced by crti.S:68 (/home/andy/Downloads/zig/lib/libc/glibc/sysdeps/i386/crti.S:68)
>>>               /home/andy/.cache/zig/stage1/o/QwPOfrBzzIXOEPuFhvbaQ4pBmiZk1vZIjVDP_sy7CCeeXOl8s6Zh8l0nMcfprTj6/crti.o:(.init+0x5)
>>> referenced by crti.S:88 (/home/andy/Downloads/zig/lib/libc/glibc/sysdeps/i386/crti.S:88)
>>>               /home/andy/.cache/zig/stage1/o/QwPOfrBzzIXOEPuFhvbaQ4pBmiZk1vZIjVDP_sy7CCeeXOl8s6Zh8l0nMcfprTj6/crti.o:(.fini+0x5)
```

**Comment by LemonBoy** [comment]
Oh this is a nice one, there are a few problems:

* The `get_pc_thunk` stubs are actually emitted by gcc when PIC is emitted...
* ...but clang doesn't follow this convention (afaik they're replaced by some inline code)...
* ...anyways, glibc used to define `__x86.get_pc_thunk.bx` in a `.gnu.linkonce` section...
* ...that `lld` correctly discards, hence the error...
* ...but [glibc devs](https://sourceware.org/bugzilla/show_bug.cgi?id=20543) changed that piece of code to use a `comdat` section instead...
* ...and that fix was shipped with glibc 2.32 that Zig supports...
* ...but #6212 forgot to update the `sysdeps` folder!

Many issues (#3340, #3287, #2256, #4927 and this one) have the same root cause in common, missing/stale files in `sysdeps`.

@andrewrk the instructions on the wiki page should be updated, I don't see `sysdeps` being mentioned at all.
The last update was made in 697b1233f0, a while ago. Shipping a mix of old and new header files is no good.

**Comment by zhaozg** [comment]
Ref by https://github.com/ziglang/zig/issues/7440

**Comment by FireFox317** [comment]
@andrewrk Can we make sure that we do the thing that @LemonBoy said in the comment above (https://github.com/ziglang/zig/issues/4926#issuecomment-744326413) before the release of zig 0.8.0? This issue currently causes a lot of problems, as can be seen by all the linked comments in this issue.

**Comment by sundbp** [comment]
Hi. I'm a potential first time zig contributor. I was going to have a go at adding support for glibc-2.33 to play nicely on Arch. In doing so I was pointed towards this ticket. If someone could add a bit of color about the `sysdeps` issue I'll have a go at fixing scripts and making a PR for glibc-2.33 and a separate PR for  updated glibc-2.32 with fixed sysdeps. Hopefully fixing scripts will make the wiki entry be "correct", otherwise I'll update the wiki as well to be complete. (https://github.com/ziglang/zig/wiki/Updating-libc). So any input on the sysdeps would be great! @LemonBoy

**Comment by LemonBoy** [comment]
Well the first step is finding out what to copy (all the `.h` files and some crt-related `.S` files) and the following one to update glibc and check if all the linked errors are solved.

**Comment by sundbp** [comment]
Is there any example of a correct set of `sysdeps` file to use as guidance that you're aware of?

**Comment by LemonBoy** [comment]
Not really, ideally every file that's copied by `make install` is potentially interesting (with a caveat, the set of installed files varies between target architectures).

**Comment by sundbp** [comment]
So I managed to build and sync the headers as per the wiki. I've then looked at all the files in `lib/libc/glibc` to see what there should be sync'd with the new version. It isn't only `sysdeps` as noted. The following list of files has no match in the glibc 2.33 dir:
```
No such file: include/libc-modules.h
No such file: sysdeps/alpha/nptl/bits/pthreadtypes-arch.h
No such file: sysdeps/powerpc/nptl/bits/pthreadtypes-arch.h
No such file: sysdeps/s390/nptl/bits/pthreadtypes-arch.h
No such file: sysdeps/x86/bits/select.h
No such file: sysdeps/ia64/nptl/bits/pthreadtypes-arch.h
No such file: sysdeps/microblaze/nptl/bits/pthreadtypes-arch.h
No such file: sysdeps/sh/nptl/bits/pthreadtypes-arch.h
No such file: sysdeps/init_array/crtn.S
No such file: sysdeps/init_array/crti.S
No such file: sysdeps/unix/alpha/sysdep.h
No such file: sysdeps/unix/mips/mips64/n32/sysdep.h
No such file: sysdeps/unix/mips/mips64/n64/sysdep.h
No such file: sysdeps/unix/sysv/linux/alpha/bits/stat.h
No such file: sysdeps/unix/sysv/linux/hppa/pthread.h
No such file: sysdeps/unix/sysv/linux/powerpc/bits/stat.h
No such file: sysdeps/unix/sysv/linux/powerpc/powerpc32/sysdep.h
No such file: sysdeps/unix/sysv/linux/generic/bits/stat.h
No such file: sysdeps/unix/sysv/linux/s390/bits/stat.h
No such file: sysdeps/unix/sysv/linux/x86/bits/stat.h
No such file: sysdeps/unix/sysv/linux/mips/mips64/n32/sysdep.h
No such file: sysdeps/unix/sysv/linux/mips/mips64/n64/sysdep.h
No such file: sysdeps/unix/sysv/linux/mips/bits/stat.h
No such file: sysdeps/unix/sysv/linux/ia64/bits/stat.h
No such file: sysdeps/unix/sysv/linux/microblaze/bits/stat.h
No such file: sysdeps/unix/sysv/linux/sparc/bits/stat.h
No such file: sysdeps/unix/sysv/linux/m68k/bits/stat.h
No such file: sysdeps/sparc/nptl/bits/pthreadtypes-arch.h
No such file: sysdeps/arm/nptl/bits/pthreadtypes-arch.h
No such file: csu/abi-note.S
No such file: csu/abi-tag.h
```
How should I interpret that?  Are these files no longer required due to changes in glibc?  Do they come from elsewhere?

I see that e.g. libc-modules.h is referenced in `glibc.zig`, and looks generated by a tool. Where does this file come from?

**Comment by sundbp** [comment]
I was afraid that'd be the case - go through things manually until it makes sense basically. 

The one thing I'm a bit lost on is how libc-modules.h is created. It doesn't exist inside of my multi directory and seems to be automatically generated. I'll need to work out how to generate it properly.

**Comment by LemonBoy** [comment]
```make
$(common-objpfx)libc-modules.h: $(common-objpfx)libc-modules.stmp; @:
$(common-objpfx)libc-modules.stmp: $(..)scripts/gen-libc-modules.awk \
				   $(common-objpfx)soversions.i
	$(AWK) -v buildlist="$(subst -,_,$(built-modules))" -f $^ > ${@:stmp=T}
	$(move-if-change) ${@:stmp=T} ${@:stmp=h}
	touch $@
```

**Comment by sundbp** [comment]
Indeed. I'm putting this on ice for a bit - spoke to @andrewrk about it briefly and it's complex enough that it'll be time better spent by someone else. Thanks for your help - I learnt a fair amount in the process either way :)

**Comment by andrewrk** [comment]
> @andrewrk the instructions on the wiki page should be updated, I don't see `sysdeps` being mentioned at all.

I've done as you requested.

> Many issues (#3340, #3287, #2256, #4927 and this one) have the same root cause in common, missing/stale files in `sysdeps`.

There are no more stale files. Here are updates for each of these issues:

 * RISC-V is stuck on glibc using an undocumented GAS feature that clang does not support: https://github.com/ziglang/zig/issues/3340#issuecomment-995358550
 * `-target arm-linux-gnueabihf -mcpu=generic+v8a` is in the same place it was before, it just needs a few more files copied over from upstream.
 * powerpc is actually looking pretty good. The next issue is that behavior tests are failing at runtime: https://github.com/ziglang/zig/issues/2256#issuecomment-995442253
 * mipsel-linux-gnueabihf is down to `undefined symbol: __mips_syscall5`: https://github.com/ziglang/zig/issues/4927#issuecomment-995543237
