### ISSUE TITLE
Please don't use this opaque non-declarative build.zig's

### ISSUE THREAD

**Issue by safinaskar** [ziglang/zig#5001]
I don't want to repeat myself, please read this Rust issue I reported: https://github.com/rust-lang/rust/issues/71022 . Everything applies to your build.zig's . At least put a warning for future language creators to stop future infecting

**Comment by safinaskar** [comment]
@mikdusan, why the issue is closed?

**Comment by kyle-github** [comment]
I can think of two reasons:

1. This is not at all constructive.  It just says, "you did it wrong", without offering a concrete counter-proposal.  Saying "make it declarative" is about as useful as saying, "make it blue."  It is just bikeshedding.   It does not provide a clear proposal that can be examined.   Provide a clear alternate proposal with examples and clear descriptions of how it would work.   Tell us what requirements you have, why you have them, and why the current system does not satisfy them.   

2. The current build system is the way it is _**by design**_.   It is intentionally using Zig as the build language so that programmers do not need to learn more languages in order to understand how a project works.   This reduces the cognitive load on the programmer.  The current build system satisfies the current set of requirements.   
  
Your comments show that you have not read and understood what Zig is really about.   To be blunt, if you cannot take the time to dive into Zig and really "grok" it, why should the people who put many, many hours of time into the language take the time to redesign a core part just because you do not like it?

Zig is very young.   Everything, including the language syntax, is in flux.   Perhaps the build system will be revisited some day and add a more declarative set of primitives.   There are many, many things that need to be done before then.   

If you come back with a strong set of clear requirements for a build system and an open mind about implementation, you will probably get some positive responses.
