### ISSUE TITLE
WinMain() causes start_windows_tls.zig to not be included.

### ISSUE THREAD

**Issue by JesseRMeyer** [ziglang/zig#5002]
```zig
pub const HINSTANCE = [*c]c_int;
pub const wchar_t = c_ushort;
pub const WCHAR = wchar_t;
pub const PWSTR = [*c]WCHAR;

pub export fn WinMain(hInstance: HINSTANCE, hPrevInstace: HINSTANCE, lpCmdLine: PWSTR, nCmdShow: c_int) callconv(.Stdcall) c_int {
    return 1;
}
```

```zig build-exe test.zig```

```
lld: error: undefined symbol: _tls_index
>>> referenced by C:\dev\Zig\lib\zig\std\debug.zig:258
>>>               .\test2.obj:(std.debug.panicExtra)
>>> referenced by C:\dev\Zig\lib\zig\std\debug.zig:260
>>>               .\test2.obj:(std.debug.panicExtra)
>>> referenced by C:\dev\Zig\lib\zig\std\debug.zig:289
>>>               .\test2.obj:(std.debug.panicExtra)
```

**Comment by AnthonyYoManz** [comment]
I have done a bit more investigation into this than I did yesterday when I made that now-closed PR. There is a deeper underlying issue here where - unlike Visual Studio - Zig does not wrap `WinMain` in a `WinMainCRTStartup` implementation that grabs and passes the correct parameters. With my "fix", your code will compile with `WinMain` as the entry-point, but all parameters will be busted. 

Part of the problem comes from this:
https://github.com/ziglang/zig/blob/09cded209d082c0cbade2fa7c0da9b9f87c840e8/src/link.cpp#L2461-L2471

We shouldn't reeeeaaaaly be specifying the entry-point as `WinMain` or `wWinMain` when linking with `/SUBSYSTEM:WINDOWS` (which expects `WinMainCRTStartup` by default), we should be ensuring that `WinMainCRTStartup` is actually defined. 

Additionally, this snippet needs changing:
https://github.com/ziglang/zig/blob/09cded209d082c0cbade2fa7c0da9b9f87c840e8/lib/std/start.zig#L23-L29

It needs to account for cases where `WinMain` or `wWinMain` is defined without their respective `WinMainCRTStartup` or `wWinMainCRTStartup` and to export some kind of variant on the existing startup code that will call the appropriate user-defined entry-point while passing the correct params.
