### ISSUE TITLE
zig fmt inserts trailing commas instead of formatting on to one line

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#5176]
e.g. if I have:
```zig
    var stream = multiOutStream(.{
        fbs1.outStream(),
        fbs2.outStream()
    });
```
then I expect running `zig fmt` to move it all onto one line.

Instead, it appends a `,`.

**Comment by iansimonson** [comment]
It seems to not apply to function args, e.g.:
```
    foo(
        .{
            .a = 1,
            .b = 2,
            .c = 3
        },
        2,
        3,
        4
    );
```
becomes
```
    foo(.{
        .a = 1,
        .b = 2,
        .c = 3,
    }, 2, 3, 4);
```

**Comment by LewisGaul** [comment]
I'm taking a look into this - have reproduced the issue with a testcase.

**Comment by LewisGaul** [comment]
So I've found a way to address this (see #8260) by checking for a comment in the array initialisation instead of a newline. However, this breaks this testcase, which I don't really see how can be sensibly distinguished (except perhaps always making it multi-line when single-line would be too long?): https://github.com/ziglang/zig/blob/83a2665772578f6262afc858613023738a7d25ef/lib/std/zig/parser_test.zig#L1804

Seems this change in behaviour was probably caused by https://github.com/ziglang/zig/commit/1e3a200ba604c8d19fcc1119d01c2e80f2a8beca.

Any thoughts @ifreund?

**Comment by ifreund** [comment]
> So I've found a way to address this (see #8260) by checking for a comment in the array initialisation instead of a newline. However, this breaks this testcase, which I don't really see how can be sensibly distinguished (except perhaps always making it multi-line when single-line would be too long?):

`zig fmt` should never be aware of line length. IMO breaking (and removing) that test case is fine, it's part of solving the inconsistency this issue is about.

**Comment by LewisGaul** [comment]
Cool, I'm happy with that :) I can change that testcase to have a trailing comma, as would be recommended for users that want to maintain the behaviour.
