### ISSUE TITLE
Proposal: Rename build modes

### ISSUE THREAD

**Issue by pixelherodev** [ziglang/zig#5384]
Currently, we have Debug, ReleaseFast, ReleaseSafe, and ReleaseSmall. When choosing a release mode, people tend to stick with ReleaseFast, because speed is what they want. However, this makes the lost safety implicit. It feels like, as @fengb put it, "you're putting on training wheels." Why would we want to _give up performance_ for safety? We want people to feel the _opposite_; if I'm using ReleaseFast, I'm _giving up safety_ for performance, not the other way around. Safety should be the default assumption.

This violates the zen of zig: "communicate intent precisely," "only one obvious way to do things."

I propose that ReleaseSafe is renamed to Release. If you want to deliberately get rid of safety checks in exchange for performance, you're deliberately choosing an unsafe build; hence, ReleaseUnsafeSpeed (`--release-unsafe-speed`). Similarly, ReleaseSmall should become ReleaseUnsafeSize. `--debug` should remain as is.

With this change, the obvious release mode is `--release`, which is what we want; people should default to using safe releases. Instead of ReleaseSafe feeling like putting on training wheels, ReleaseUnsafe should feel like you're taking off your seat belt.

**Comment by pixelherodev** [comment]
If this is accepted, I'll gladly implement it in the compiler and in the build system :)

**Comment by andrewrk** [comment]
Zig is a general-purpose language, which means that ReleaseSafe will be appropriate for some projects, and ReleaseFast will be appropriate for others. It's not the job of the language or compiler to decide what the default is for everyone at the same time.

However, we do have the concept of a project declaring its preferred release mode:

https://github.com/ziglang/zig/blob/70239802c9f98aa2a7bc9bd87046d1b64deceedb/lib/std/build.zig#L510-L518

Usage example:

https://github.com/ziglang/zig/blob/70239802c9f98aa2a7bc9bd87046d1b64deceedb/build.zig#L14

A project can use this so that there is only one `--release` option available for a given project, so the option does not fall to the user, but the project maintainer.

**Comment by maplethecolor** [comment]
> Zig is a general-purpose language, which means that ReleaseSafe will be appropriate for some projects, and ReleaseFast will be appropriate for others. It's not the job of the language or compiler to decide what the default is for everyone at the same time.

This **isn't** mutually exclusive with renaming the modes to be more explicit, and renaming `ReleaseFast` to `ReleaseUnsafe` would be the correct and consistent nomenclature. The developer should be **very** aware that they are about to let go of every safety-checked illegal behaviour.

While Zig is a general purpose language, and there are certain niche use-cases where `ReleaseFast` may be suitable, the wording is *deceptive* in nature. Arguing that `ReleaseFast` be removed/disabled is out of the scope of this issue, and thus I won't elaborate on that.

The term `ReleaseFast` *advertises* (intentionally or unintentionally) a faster executable without making the costs very clear, which are _very high_. It gives up some of the most basic levels of safety (example: Integer overflow) and lets the compiler free to do everything and anything with illegal behaviour.

To a Zig developer, the name seems suggestive of "I should distribute the faster version of my executables to my consumers", but that 1. teaches newer Zig developers bad practices and 2. misguides the developer. The user should benchmark and profile their software before making such rash decisions. The term `ReleaseFast` promotes a naive thinking that "if I enable ReleaseFast, my software will be faster and my benchmarks will look better :)". Zig the language should responsibly _promote_ better practices in a way that makes using the tool "the wrong way" hard, whereas the current name does the exact opposite.

Since removal of the mode is _out of scope_, I am going to once again propose it being renamed to `ReleaseUnsafeFast` or `ReleaseUnsafe`.

**Comment by maplethecolor** [comment]
While I don't want to beat a dead horse - I am confident that the Zig core team is well-aware of the dangers and prevalence of undefined behaviour.

Both out-of-bounds-read and out-of-bounds-write [are in the top 10 software vulnerabilities](https://cwe.mitre.org/top25/archive/2024/2024_cwe_top25.html#top25list), and both of which are declared undefined behaviour in `ReleaseFast` mode.

By calling it `Release*Fast*`, Zig continues to promote the same bad practices that have ruined software for *decades*.
