### ISSUE TITLE
alignment changes on assigning to variables?

### ISSUE THREAD

**Issue by iansimonson** [ziglang/zig#5582]
I'm not sure what the exact cause of this is but the effect is unexpected:

Given a c file test.h
```
#include <stdio.h>
void print_to(FILE *);
```
and the following zig file

```
const std = @import("std");

const c = @cImport({
    @cInclude("test.h");
});

const stderr = std.io.getStdErr();

pub fn main() anyerror!void {
    c.print_to(stderr.handle);
}
```

The build fails with the following error:
```
./src/test.zig:10:22: error: pointer type '[*c].cimport:3:11.struct___sFILE' requires aligned address
    c.print_to(stderr.handle);
                     ^
```

However, changing `stderr.handle` to `std.io.getStdErr().handle` gets rid of the error.

**Comment by Vexu** [comment]
The biggest issue with your code is that `@TypeOf(getStdErr().handle) == c_int`. The weird behavior you are seeing when assigning to a global constant is that `getStdErr` is made comptime and resolved to `2`. Then when you try to call `print_to` it tries to coerce the integer into a pointer as stated [here](https://ziglang.org/documentation/master/#C-Pointers) which then leads to the alignment error since `@alignOf(c.FILE) != 2`.

These kinds of footguns are why you should never use `[*c]` pointers but it would be nice to have some protection since they are used by `translate-c`.

**Comment by iansimonson** [comment]
Hmm, well it appears in debug mode this code becomes a runtime crash for incorrect alignment. So it's doing the "right" thing as expected. As you pointed out the types are different (c_int vs pointer) which also makes sense since stderr.handle is a file descriptor not a `FILE*`

It might make more sense to close this issue (or edit it?) and replace with: what is the mechanism for interop with `FILE*`s in Zig?

**Comment by Vexu** [comment]
For interop with `FILE*`s you want to use `std.c.fopen` or the currently missing `std.c.std{in,out,err}`.

**Comment by iansimonson** [comment]
So the answer currently would be that anywhere you need to pass a C library a `FILE*` you instead need to create a function prototype (using above as an example)

```
const std = @import("std");
pub extern "c" fn print_to(f: *std.c.FILE) void;

pub fn main() void {
  const f = std.c.fopen("test_file", "w") orelse unreachable;
  defer _ = std.c.fclose(f);
  print_to(f);
}
```

And then somehow have a stderr `*std.c.FILE` handle that actually resolves to `stderr`...somehow
