### ISSUE TITLE
Visibility modifiers on container members

### ISSUE THREAD

**Issue by scurest** [ziglang/zig#569]
Eg. these

```
struct {
    pub x: i32
    pub fn f() {}
    pub const v: i32 = 0;
}
```

which seem to do nothing (you can call private methods from anywhere AFAICT). Basically, I wanted to know if these are just unimplemented and what they're supposed to do.

1. The stated grammar doesn't actually allow visibility modifiers on container members at all. Most of the docs use `pub` on struct methods though and the parser allows them in all the places above.
2. If they were working, what's the intended unit of visibility? (I mean, where would you be allowed to access private members from?) The container, like in C++, or the file, like in Rust?
3. The `export` modifier in particular seems pretty meaningless on fields.

**Comment by andrewrk** [comment]
Good call, I need to address this. 

(3) should be solved with #462

**Comment by PavelVozenilek** [comment]
If possible, tests (but not examples) should be able to invoke private methods and access private members. 

The usual advice for such situations is to restructure the code so that privates could be tested through public interface, or to [extract private code out](http://enterprisecraftsmanship.com/2017/10/23/unit-testing-private-methods/), but this leads to unneeded increase of complexity.

**Comment by andrewrk** [comment]
For fields: `pub` will become invalid syntax with the accepted proposal #2059.

Functions are planned to become the same as variable declarations with #1717.

`pub` on a declaration means that it can be accessed from any scope. Without `pub`, declarations can be accessed from any scope in the same file.
