### ISSUE TITLE
would it be more convenient to use a word other than `else` for `for` blocks?

### ISSUE THREAD

**Issue by anosovic** [ziglang/zig#5723]
from zigdocs:
```zig
test "for else" {
    // For allows an else attached to it, the same as a while loop.
    var items = [_]?i32 { 3, 4, null, 5 };

    // For loops can also be used as expressions.
    // Similar to while loops, when you break from a for loop, the else branch is not evaluated.
    var sum: i32 = 0;
    const result = for (items) |value| {
        if (value != null) {
            sum += value.?;
        }
    } else blk: {
        assert(sum == 12);
        break :blk sum;
    };
    assert(result == 12);
}
```

consider this line:
```zig
} else blk: {
```
suppose the block was longer. then it may be hard to read that the `else` goes to a `for` and not the `if`.  should another word be used, like `nobreak`, `after` or `then`?

_edited for clarity_

**Comment by EleanorNB** [comment]
Well, the `if` is entirely contained within the `for`'s `{}`s and the `else` is outside them. Also, `fmt` will automatically indent for clarity. In cases with no `{}`, we have one rule, and if users want something different they can use `{}`. I really don't think this is necessary.

**Comment by bokunodev** [comment]
I just started learning Zig yesterday, and I think `for elese` is very helpful.
but having `else` after `for` is confusing.
I would suggest replacing `else`  with something more idiomatic.
like `then`

`for then` instead of `for else`

**Comment by anosovic** [comment]
@EleanorNB you are correct. that does answer what I said, but not what I meant

I edited my proposal for clarity. thanks

**Comment by bokunodev** [comment]
@anosovic 

>  should another word be used, like nobreak, after or then 
Yes.

**Comment by MasterQ32** [comment]
Neither `then` or `after` fulfill great communication. I would assume that `after` or `then` will always be executed *after* the for-loop. `else` isn't perfect, but conveys the meaning way better: *This `for` loop has either a value returned from inside the loop or `else` it will yield this*

**Comment by anosovic** [comment]
@MasterQ32 maybe `else` is the best word for english semantic reasons, but zig is not english. while zig syntax is still being finalized, lets prioritize clear coding over clear english. eg `const [_][]u8` is not clear english but is fine zig

**Comment by MasterQ32** [comment]
`else` is english. It's a keyword in english language, so it should adhere the english semantics. *Communicate intent precisely* is one of the parts in the zen and for me (a non-native speaker), `then` or `after` would be way more confusing than `else`.

>  eg const [_][]u8 is not clear english but is fine zig

Yes, because it's non-word syntax. `u8` is also just a shortcut for `unsigned`, the rest is "punctuation"

**Comment by anosovic** [comment]
edited the title--the last one was misleading

**Comment by fengb** [comment]
This has also been a point of contention in Python, where many people don't use for / else because it's not immediately apparent when the else block fires.

### Pros of status quo:
1. `if (optional) / else` <=> `while (optional) / else` and `if (error union) / else` <=> `while (error union) / else`
2. `while / else` <=> `for / else`

### Cons of status quo:
1. `if / else` does not map well to `while / else`. The former does one _**or**_ the other, but `while / else` does _**both**_ unless there's a break.
2. `for / else` language looks confusing. As a native speaker, I wouldn't know how `else` would modify `for` without consulting docs.

Maybe we could consider having a separate keyword? Even though they are internally very similar, the human language doesn't translate too well. Something like `for {} nobreak {}` looks a bit goofy but there's a lot less ambiguity.

**Comment by SpexGuy** [comment]
The intended use of the else block in this case is to supply a default value if no value was yielded by the loop.  So maybe `default` is a better name?
```zig
const x = for (array) |x| blk: {
    if (x % 2 == 0) break :blk x;
} default 4;
```

**Comment by VojtechStep** [comment]
My 2c: it might be worth treating the for loop as an expression returning an optional type. To me, it makes semantic sense (the loop either breaks with a value or doesn't), and we could replace the `else` with the non-forloop-specific `orelse`.

I personally have no problem with the status quo, but if there is a change to be made I would much prefer using idioms already present in the language over adding new keywords ("Reduce the amount one must remember").

**Comment by watzon** [comment]
I agree that `for/else` is confusing. The firs time I heard about it in Python I scratched my head and wondered why someone would ever do that. Now I understand better, and unfortunately no other words make as much sense, semantically speaking, as `else`. `orelse` could certainly work, but we have to keep in mind that change for the sake of change isn't good.

Alternative words like `then` and `after` just don't make sense in this case, as they do convey the idea that said block will execute after the `for` loop. So, while it may seem like `else` is a poor fit, there really doesn't seem to be a good alternative.

**Comment by AssortedFantasy** [comment]
I like `else` because it's equivalent to how it works in Python. So assuming you are familiar with Python it doesn't take much brainpower to also keep in mind that it works identically in Zig.

I do agree that its confusing though, but I really don't like the idea of adding an entire new keyword.

IMO, a good already existing alternative keyword to use other than `else` is `continue`.

It makes sense because it happens if you don't `break` or `return` from a loop so you are `continue` ing into it.
