### ISSUE TITLE
Add documentation for tuples

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#5730]
I want to do something very common that is easy to do in C, Rust, etc.: create an indexable array of strings.

The closest thing I could find in the Zig documentation was:
```
const foo = .{"hello", "goodbye"};
```
The section of the documentation, Anonymous Struct Literals, tells me that the type of foo will be "a struct with numbered field names", which needs to be accessed like so:
```
foo.@"0"
foo.@"1"
```
First problem:  where is the @"0" syntax documented? I don't believe it is, other than in the grammar. Please correct me if I'm wrong. If I'm right, it needs to be documented. In fact, I don't believe the documentation mentions what constitutes a legal identifier at all, other than in the grammar. A section at the beginning of the documentation, before discussing such things as variables, would be a welcome addition.

Second problem: I need to index foo, so referring to the fields with the @"0" construct is problematic at best. On a hunch, I tried
foo[0] and was delighted to find that it works. In the example infer_list_literal.zig, you will find that this definition of the dump function also works:
```
fn dump(args: var) void {
    assert(args[0] == 1234);
    assert(args[1] == 12.34);
    assert(args[2]);
    assert(args[3][0] == 'h');
    assert(args[3][1] == 'i');
}
```
But I was not delighted that it isn't documented, at least that I could find (again, please correct me if I'm wrong about this).

So if I'm correct about the missing documentation, the intent of this issue is to request that those holes be filled.

**Comment by alexnask** [comment]
You are correct, documentation is sparse on this feature (as well as vectors but there are todos there).  
Note that tuples (aka anonymous struct literals) also support `++` and `**` and will support slicing `tuple[a..b]` in the future (accepted unimplemented feature).  
They can also be iterated over in comptime, so basically they are designed to behave exactly like heterogeneous arrays.

**Comment by Vexu** [comment]
> First problem: where is the @"0" syntax documented?

It is mentioned in [`@export`](https://ziglang.org/documentation/master/#export), but it could also be documented separately.

**Comment by donaldcallen** [comment]
I see the reference in @export, but that is written as if the @<string> syntax had been defined previously in the documentation and it has not. And that syntax is not @export-specific, so I would strengthen your 'could also be documented separately' to 'should be documented separately'.

**Comment by SpexGuy** [comment]
We should keep this issue open to track the documentation fix, but FWIW you can also create an array of strings by making an array that contains strings, just like every other language.  Any of these will work, depending on your use case.
```zig
// ptr + len
const arr1 = [_][]const u8 { "hello", "goodbye" };
// ptr + len + null terminator
const arr2 = [_][:0]const u8 { "hello", "goodbye" };
// ptr + null terminator
const arr3 = [_][*:0]const u8 { "hello", "goodbye" };
```

**Comment by donaldcallen** [comment]
@SpexGuy: thank you for the suggestion. But this brings up what is, for me, one of the most frustrating aspects of the design (perhaps aided and abetted by the weakness of the documentation) of Zig. According to the section of the documentation on string literals, the type of "hello" is *const [5:0]u8. To go from this to what you suggested, you need to know that there is an automatic cast to a slice, which is documented in a separate section, with nothing tying the two together. 

That section gives one example that does not clearly apply to this situation (it shows the address of a variable containing an array being automatically cast to a slice). The problem, as I see it, with the documentation-by-example technique used for Zig is that too often the general principles are not spelled out and the examples are not exhaustive, so you are left to fill in the blanks. I've said this before, but I think the documentation is a major weakness of this project and an impediment to the wider adoption of all the good work that is being done here. I realize resources are finite, but I really think the documentation needs greater attention, for this reason.

**Comment by OscarL** [comment]
Just a newbie here, adding my two cents regarding the lack of info about the meaing of "@" and ".":

I'm scratching my head with this:

    try stdout.print("Hello, {s}!\n", .{.@"world"});

and how/why it prints

    Hello, .world!

Can't find any info except the grammar section, and only THERE I see that all built in functions are prefixed with @... and that @"" is an identifier. But what about the `.@"whatever"` syntax?

Sorry if this is too basic, but finding those syntax/symbols without any explanation in the language reference is frustrating for a newbie.

Even finding this issue was kinda hard.

**Comment by SpexGuy** [comment]
@OscarL You're right that the documentation needs improvement.  FWIW, `.` followed by an identifier is an [Enum Literal](https://ziglang.org/documentation/master/#Enum-Literals), and `.` followed by a brace is either an [Anonymous Struct Literal](https://ziglang.org/documentation/master/#Anonymous-Struct-Literals) or [Anonymous List Literal](https://ziglang.org/documentation/master/#Anonymous-List-Literals).  `@"name"` can be used in place of any name, and allows you to declare identifiers which wouldn't otherwise be allowed.  For example, tuple structs have fields whose names are numbers, and can be referenced with `tuple.@"0"`.  Or you can export a function named `anytype` with `export fn @"anytype"() void {}`, even though `anytype` is a reserved keyword.  If you visit a [Community Location](https://github.com/ziglang/zig/wiki/Community) like the IRC or Discord, you'll find a welcoming community of people happy to answer more questions like these 😄

**Comment by OscarL** [comment]
Thanks a lot @SpexGuy! It does helps indeed.

I know, by personal experience, that writing docs is a PITA and sometimes a really difficult task (not always easy to put yourself on the shoes of a newcomer, in order to explain what it's all too obvious for you at that point). Sadly a rough first impression can be hard to overcome.

I saw that `tuple.@"0"` usage elsewhere, but it seems I can write it as `tuple[0]`, which makes more sense. I'm surely still missing some use case. Maybe something akin to `tuple.@"some_reserved_keyword"`?

In any case, thanks a lot for your help and your work on Zig! Off I go to read some more docs and code.
