### ISSUE TITLE
Proposal: forbid ambiguous math on comptime_float

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#5780]
I brought up how `comptime_float` is ill-defined in #2794, but it was kept because it implicitely casts to any float type. However, which it should be kept, the ill-defined parts can be removed. This proposal is to make it impossible to do any arithmetic on `comptime_float` besides assigning it to a unambiguous type (currently `f16`, `f32`, `f64`, and `f128`) *or* is an arithmetic operation with one of those types (in which case it implicitely casts as part of peer type resolution). In other words this would not be allowed (which currenintly uses f128 math, and *then* converts to f64, which is totally non-obvious, and can produce unexpecting rounding that may appear to conflict with IEEE-754):

`var a: f64 = 4.5 * 2.3;`

But this would be allowed:

`var a = @as(f64, 4.5) * 2.3;`

or the explicit:

`var a = @floatCast(f64, @as(f128, 4.5) * 2.3);`

**Comment by AssortedFantasy** [comment]
I do like your pedantry, because it's important to have rigor in developing a language, but this seems a bit excessive, and looks like it would create a lot of unnecessary friction and terseness in otherwise normal seeming code.

IMO If a developer writes
`var a: f64 = 4.5 * 2.3;`

It's almost guaranteed that what a developer intended was to store the closest 64 bit IEEE floating point number to `10.35` and it's very unlikely that anyone actually wants any other behaviour.

For the few people who actually need specific floating point behaviour, well as you suggest just they can simple use `@as` to get whatever exact behaviour they want. Everyone else can just enjoy not needing to type out (quite a lot of) extra syntax.

Personally I find relying on specific floating point behavior to already be a kind of ridiculous footgun, the IEEE-754 standard isn't actually all that great and has tons of pitfalls for anyone thinking they can get away with getting deterministic behaviour across machines. IEEE-754 isn't actually a portable standard, it can vary in its implementation, particularly in things like GPUs.

This is so much of an issue I don't even think people should be allowed to use the `==` operator on floats. If they want to check if floats are bit for bit the same then bitcast them to integers first. (Don't actually do this though, because then this would force code to have an unnecessary move from float registers to normal registers that probably wouldn't be optimized out).

Also, I'm fairly sure you can't even currently control the rounding mode in Zig, so forbidding something like this seems a bit pointless.

Lastly, and I think this is the most important point of all, I don't believe there is actually an ambiguity here, the fact that everything gets done as `f128`s and rounded at the end is exactly what the documentation on floating point literals says will happen.

https://ziglang.org/documentation/master/#Float-Literals
> Float literals have type comptime_float which is guaranteed to have the same precision and operations of the largest other floating point type, which is f128.

**Comment by andrewrk** [comment]
> Float literals have type comptime_float which is guaranteed to have the same precision and operations of the largest other floating point type, which is f128.

I'm happy with this, I would feel good about this going into the language spec.
