### ISSUE TITLE
how to fix  zig cc InstalledDir

### ISSUE THREAD

**Issue by chenjianxin** [ziglang/zig#5936]
zig cc -v
clang version 10.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
**InstalledDir: C:\Users\a5566**
It is wrong path....
how to edit it Manualy?

**Comment by andrewrk** [comment]
`zig cc` will not use that directory. Zig makes sure to pass flags to clang so that it will not touch your system files outside of the zig installation directory. If you share a little bit more about what problem you are running into and what you are trying to solve, we can help more. [Ask in one of these places](https://github.com/ziglang/zig/wiki/Community)
