### ISSUE TITLE
Stage 2 proposal: `-Denable-llvm` flag

### ISSUE THREAD

**Issue by EleanorNB** [ziglang/zig#5992]
I believe a flag such as this should be mandatory if compiling with LLVM is desired. Compiling without this flag, even in a build of Zig with LLVM support, even in a release mode, shall use a fully self-hosted backend. Some architectures shall require this flag (those that we do not officially support); some shall require its absence (those that LLVM does not support).

Why enabling LLVM by default in release modes is bad:
- Forces the user to choose between maximum compile and execute efficiency when deciding which flavour of Zig to install
- Neither flavour's architecture support is a superset of the other -- again, forcing a choice
    - ...unless whether we use it or not is inconsistent between architectures, surprising the user with long compile times on some
- Builds are not reproducible -- the same command line will yield different results depending on the local Zig flavour

**Comment by andrewrk** [comment]
This proposal is mixing up a few things:

 * The option to `zig build` that will enable the optional LLVM/Clang/LLD integration (**planned**). The title of this issue seems to be talking about this.
 * The pipeline configuration which will be used to generate code when both LLVM and self-hosted backends are available for a given target (**not yet decided** - big topic which will not be settled in a binary manner).

Reproducible builds is not related to this proposal. Reproducible builds always implies using the same build configuration and version of the compiler being used.

Right now, none of the stage2 backends are anywhere near passing the full behavior test suite, and work has not even yet begun on LLVM integration. This topic will become more relevant once we get past these two milestones.

**Comment by andrewrk** [comment]
please see #6251
