### ISSUE TITLE
common iterator pattern for std

### ISSUE THREAD

**Issue by anosovic** [ziglang/zig#6185]
(not #5331 because this isnt about syntax sugar)

its useful to have a common currency to make, read, map, modify, and transform things with. iterators are a hard design problem (just look at c++'s iterators and, recently, ranges. suffice to say---theyre not very ziggy) but could be a big draw if zig nails it for the std library. iterable datastructures are crucial for any language used for eg competitive programming because they make many things generally reusable

luckily theres been some discussion about this already, eg https://www.fluentcpp.com/2019/04/16/an-alternative-design-to-iterators-and-ranges-using-stdoptional/ for if nothing else inspiration

the cpp implementation definitely does not follow zen of zig. it would be better to have more security against invalidation, more control over whether the outcome is place or not, more mapping/hashing/serializing power, etc so usage is consistent in any context

i want to know if anyone has any iterator pattern ideas that would be good for zig to think about for 0.7.0.

**Comment by joachimschmidt557** [comment]
Something similar has been written, though not in the standard library: https://github.com/DutchGhost/Zigerator

**Comment by data-man** [comment]
> Something similar has been written

From my collection :)
[ziglibs/funzig](https://github.com/ziglibs/funzig)
[BraedonWooding/Lazy-Zig](https://github.com/BraedonWooding/Lazy-Zig)
[marler8997/zog](https://github.com/marler8997/zog)
[Hejsil/fun-with-zig/fun/iterators.zig](https://github.com/Hejsil/fun-with-zig/blob/master/fun/iterators.zig)

Huge thanks to @tadeokondrak, now is possible something like this:

```zig
var result = Iterator(users).select(.{"id", "name"}).where("id", .gt, 100);

```

**Comment by DutchGhost** [comment]
> Something similar has been written, though not in the standard library: https://github.com/DutchGhost/Zigerator

This was initially based on Rusts iterator implementation. However, I'm not sure that is the best approach, as many closures are usually involved in operations like filtering and mapping values, and Zig doesn't realy support that (yet). Also an interesting point of discussion is how to deal with deallocation.

If I look at Lazy-Zig's SkipWhile, https://github.com/BraedonWooding/Lazy-Zig/blob/master/src/skipWhile.zig#L13, the callback needs to handle deallocation _if_:
 - `BaseType` is a type that needs to be deallocated
 - The closure returns `true`

otherwise `nxt` leaked.

To me, it doesnt seem that intuitive to manage deallocation from within simple boolean callbacks that act as filters.

(Zigerator also has the same problem)

So yes, I'd like some form of iterators in stdlib, but designing them for Zig is hard, and my attempt is by far from ideal, and I'd even say that the route I took doesn't work in Zig.

**Comment by andrewrk** [comment]
There is no plan for this, however, adding language support for generators is still an open proposal.

**Comment by pjz** [comment]
'There is no plan for this'... okay.  Should there be?  In my experience, it's good to have an anointed implementation of common core utilities like this, otherwise there ends up being a bunch of incompatible, half-wrong implementations, each used by different utilities, which thereby limits their interoperability.  If you want to wait until we get generators nailed down first before deciding, that's totally understandable, but I'd still suggest choosing an iterator impl or at least interface for the stdlib to agree upon.

**Comment by data-man** [comment]
I updated my [comment](https://github.com/ziglang/zig/issues/6185#issuecomment-683261019).

**Comment by marler8997** [comment]
I've also explored this topic through a "range" library: https://github.com/marler8997/zog/blob/master/range.zig

**Comment by data-man** [comment]
@marler8997 
Your project is already on my list. ;)
