### ISSUE TITLE
Ugliness in "Async Function Example"

### ISSUE THREAD

**Issue by crawben20** [ziglang/zig#6222]
Please excuse the fact that there is little in the way of solution proposal in this issue, I'm making it more out of initial reaction to seeing the (seemingly also painfully verbose) "Async Function Example" in the 0.6.0 docs.

Specifically in this syntax:

```zig
errdefer if (!awaited_download_frame) {
    if (await download_frame) |r| allocator.free(r) else |_| {}
};
```
... and hopefully unsurprisingly my concern rests mainly after the `else` clause begins. 

Why is an `else` even required here? Seemingly, the block captures a dummy and does nothing. Is there something I'm missing here? If this syntax is necessary, surely there's something wrong from a design perspective here?

**Comment by tiehuis** [comment]
There are three different forms of an if statement which change what the type passed to if is expected as:
https://ziglang.org/documentation/master/#if

```
// No capture on either, a is boolean
if (a) {
} else {
}
```

```
// Capture on first, a is an optional
if (a) |value| {
} else {
}
```

```
// Capture on first and second, a is an error union
if (a) |value| {
} else |err| {
}
```

I suppose a broader question/proposal here would be whether there is merit in inferring the type of `a`, instead of relying on the structure of the if clause. This would allow errors to be unwrapped without an else clause with capture.

**Comment by subylan** [comment]
What's perhaps more concerning is the guidance in the docs encouraging syntax like this:

```zig
// To check only the error value, use an empty block expression.
if (b) |_| {} else |err| {
    assert(err == error.BadValue);
}
```
I'm not sure I see the utility in enforcing such a syntax when either body is free to be empty. IMO inference of the type of `b`, instead of relying on if clause structure makes orders of magnitude more sense.

**Comment by hbobenicio** [comment]
There are more ways of dealing with only the error value besides this:

```zig
if (b) |_| {} else |err| {
    assert(err == error.BadValue);
}
```
Personally I much prefer this way:

```zig
// you don't need an if-else in this case...
b catch |err| {
    assert(err == error.BadValue);
};
```

https://ziglang.org/documentation/master/#try

As both ways are actually valid, then users must me aware of it in the docs. So IMHO, I think it's ok.

Maybe some note at the end of the if statement section informing users that there is another more concise syntax (catch) that could handle the case of dealing with errors only could make things clearer?

**Comment by Rocknest** [comment]
Maybe we should require to use special keywords with if-captures? 
```zig
if (a) |value| {
  // not null
} orelse {
  // null
}
if (b) |value| {
  // not error
} orcatch |err| {
  // error
}
```

**Comment by MasterQ32** [comment]
@Rocknest i don't think that's a good idea. Right now `while`, `if` and `for` all support `else` for the "non-expected case" which is really orthogonal. I don't want to remember one keyword per other keyword

**Comment by andrewrk** [comment]
This is not a proposal, it's a discussion, so the appropriate place for this is [elsewhere](https://github.com/ziglang/zig/wiki/Community).
