### ISSUE TITLE
Disable panic strings in binary output

### ISSUE THREAD

**Issue by crawben20** [ziglang/zig#6228]
I've compiled a Zig application using `zig build-exe --release-small --strip test.zig`.

Upon looking into the strings within the resultant binary, I spotted a sequence of concatenated error strings. (Please forgive the use of the naive `strings` tool on Windows, here).

```
DiskQuotaFileTooBigInputOutputNoSpaceLeftAccessDeniedBrokenPipeSystemResourcesOperationAbortedWouldBlockUnexpectedOutOfMemoryIsDirConnectionResetByPeerEndOfStreamStreamTooLongOverflowInvalidCharacterTimedOutTimerUnsupportedSymLinkLoopProcessFdQuotaExceededSystemFdQuotaExceededNoDeviceFileNotFoundNameTooLongNotDirPathAlreadyExistsDeviceBusyFileLocksNotSupported
```

Is there any way to not have these included in the output? I'd imagine this would make for some painful size problems in (very) small embedded programs.

**Comment by deingithub** [comment]
They are generated presumably because the stdlib's error handling code uses the [`@errorName`](https://ziglang.org/documentation/master/#errorName) builtin somewhere, most likely either in the startup code or the panic handler. You might have to replace both to avoid referencing that builtin or (dunno if this would work) make your main function not return an error set to avoid it being called.

**Comment by crawben20** [comment]
@deingithub Thankfully, making `main` not return an error set is sufficient to exclude this. Closing.
