### ISSUE TITLE
Float coercion fails in generic

### ISSUE THREAD

**Issue by crawben20** [ziglang/zig#6234]
The following code breaks:

```zig
const assert = @import("std").debug.assert;

fn test_coercion(x: anytype) @TypeOf(x) {
    return x + 2;
}

test "float coercion in generic" {
    // int
    assert(test_coercion(5) == 7);

    // float
    assert(test_coercion(5.8) == 7.8);
}
```
The error received is:
```error: float value 5.800000 cannot be coerced to type 'comptime_int'```

Writing a function to accept `f32` and return `f32` seems to work just fine.

**EDIT**: Okay, so after further investigation, this is likely my bad. The `5.8` literal is passed in as a `comptime_float`, not a `f32`, causing the difference in behaviour. Still, I don't see how this is happening. `x: anytype` in the signature is not labelled `comptime`, as it needs to be labelled in the signature for the `comptime_float` implementation.

As a general note, I don't agree with how Zig deals with "ambiguous" casts here. The example given in the docs isn't ambiguous IMO, and the ambiguity is only introduced by how Zig handles compile-time floats. Zig should recognise that the storage type is `f32` (for example) and prefer `comptime_float` casting over `comptime_int` (i.e. how pretty much every other high-level language deals with this). There seems to be a strong dependence on the use of `@as(...)` when passing values which often looks (and _should_ be) superfluous.

**Comment by pixelherodev** [comment]
Try `@as(@TypeOf(x), 2)`?

**Comment by crawben20** [comment]
@pixelherodev I've already confirmed that works, but it should be superfluous. A float + int -> float. It should be clear that the int should be cast to a float.

**Comment by MasterQ32** [comment]
@crawben20 `comptime_float` is far far more distant to `f32` than to `comptime_int`. Both values are values of infinite precision whereas `f32` is of finite precision. (This is not 100% true due to implementation details, but that's the idea).

But i agree with you that `x + 2` should indeed compile, because `x` should be of type `comptime_float` in the second case and `comptime_int` should coerce to `comptime_float`. If that's not happening atm, try writing `2.0`

**Comment by crawben20** [comment]
@MasterQ32 The code works if written with `2.0` which I think further highlights the issue. Both `comptime_int` and `comptime_float` implementations work with `2.0`, but only the `comptime_int` test works with `2`.

On the point of `comptime_float` and `f32`, I understand there are implementation details, but ultimately a float is closer to another float type than an int, from a programmer's perspective.

**Comment by MasterQ32** [comment]
> @MasterQ32 The code works if written with 2.0 which I think further highlights the issue.

The issue is than that a `comptime_int` does not coerce into a `comptime_float`. The distinction between `comptime_int` and `comptime_float` is not necessary, but allows a communication about allowed values (for `comptime_int` that's only integers).

> but ultimately a float is closer to another float type than an int, from a programmer's perspective.

That's only true if you assign a literal a real type. Zig assigns literals a different type with infinite precision which allows some nice and safe stuff:
```zig
var i: usize = -3.5 * -2.0; // this yields 7, can be assigned to a usize
```
If you assign those values the type `f32`, this will not be possible anymore. Imho the different types are way better than using a specified type as in C or other languages. It's just different and you *sometimes* need a expicit coercion (`@as`), but it's not really often needed

**Comment by crawben20** [comment]
@MasterQ32 I see the benefits here. My only qualm is that these benefits (which are lent to primarily floating-point types thanks to underlying "infinite" precision you mention) shouldn't compromise sensible patterns, such as the snippet I provided above. 

The need to either use `@as(@TypeOf(x), 2)` or switch to using `2.0` in order to cover your bases in generics simply shouldn't be an issue. The compiler should have no issue performing `comptime_float = comptime_float + comptime_int` _without_ casting.

Is there a coherent argument why `comptime_int` cannot coerce to `comptime_float` for this very purpose? The number of beginners who are going to be caught out by this when venturing into generics, I'd imagine will be great.

**Comment by crawben20** [comment]
@MasterQ32 
Closing this for now, despite it being a slightly frustrating language "feature." After all, Zig's versatility around types already far exceeds what C offered, with which Zig competes. Also, I think destination-type-centric coercion is out-of-scope and would likely make more confusion somewhere else.
