### ISSUE TITLE
Proposal: replace some keyword with suffix operator (to reduce parentheses)

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6273]
- dereference operator is `.*`
- unwrap optional operator is `.?`

but

- "unwrap" error union require prepend `try`
- wait async result require prepend `await`
- create async frame require prepend `async` (it is not a big problem, since it is not possible to combine with another operator)

it make combine operators more complex

considering the following two functions:

```zig
fn demo1() ?*u8 { ... };
fn demo2() !u8 { someasyncfn(); ... }
```

call demo1 (unwrap optional),
and demo2 (error union, and await result):
```zig
demo1().?.* = 8;
_ = try await demo2();
```

looks fine? Let's try another combination:

```zig
fn demo3() !*u8 {...}
fn demo4() ?!*u8 { someasyncfunc(); ... }
```

call demo3() and dereference pointer
```zig
(try demo3()).* = 8;
_ = (try (await demo4()).?).*;
```

and the parenthese is also required when you want to access struct field.

yes, use a local variable is a solution, but `.?` and `.*` are already exists, doesn't it?

the real use case for `!*T` type:
try insert key value (in map) but don't want to copy a big struct. `fn insertInPlace(self: *@This(), key: K) !*V`

# Possible solution

1. replace `try` with `.!` (do **not** change the `catch` expression), so above example can be written in `demo().!.* = 8;`
2. maybe use rust-like `.await`? (`demo4().await.?.!.*`)

## Alternative

1. Since `.?` will produce unreachable, `.!` should also be `catch unreachable` for keep consistency.
   And alternative try operator can be `.try`

--------
The difference between try/await and defer/comptime/async:

- defer is a statement, so suffix operator is not suitable
- comptime can be an expression, but it is more like an annotation, not an action.
- async is also represent annotation, not an action

the `try` and `await` represent actions (like `.*` to dereference pointer), and the action should be chainable, so use suffix operator(or magic field like `.await`) is suitable.

**Comment by MasterQ32** [comment]
I'm against suffix operators instead of prefix operators. I really think it's a code smell when you do stuff like `(try demo3()).* = 8;` or `_ = (try (await demo4()).?).*;` as both look like a memory leak to me.

I've written a lot of zig code by now and my only use cases of `.*` where when i pass a value instead of a pointer to a function, and using `(try …)` was mostly in if-statements where i refactored them into a local variable out later to improve readability and maintainability

The reason why some things in zig are harder to type than others is that it's mostly a bad practice to use the longer version (for example: `catch unreachable` should be used with care and requires a comment why the function cannot fail for each single use).

Having a shorter variant for `.!` would move people to use `.!` instead of anything else because it's way shorter. Same goes for `await` and async: Using a *single* async-await statement-pair doesn't sound like something async to me, but is still linear code. As soon as you have two asyncs though you need to do error recovery, memory management and everything, waiting for both async functions before you can do the error handling or `await` them in your error handling routine. So a `.await` sounds like a code smell as well, because it would be used inline a lot

**Comment by codehz** [comment]
> look like a memory leak to me.

consider there is a container, `MyMap`

and the method

```zig
fn tryInsert(self: *@This(), key: K) !*V {
    const kv = try self.allocator.create(KVStorage);
    errdefer self.allocator.destroy(kv);
    kv.key = key;
    try self.unmanaged.insert(kv);
    return &kv.v;
}
```

will not leaks. (if the map can cleanup itself in deinit method)
and I think this pattern is more efficient (then insert(k, v)) in some cases, because subsequent assignment operations will not be performed when memory allocation fails (or other checks fail), especially when the operation has side effects.

**Comment by codehz** [comment]
> Same goes for `await` and async: Using a _single_ async-await statement-pair

This proposal actually make `await async` more ugly, because only `await` changed, so you have to use `await (func().await)` for bad practice...

**Comment by MasterQ32** [comment]
> This proposal actually make await async more ugly, because only await changed, so you have to use (async func()).await for bad practice...

I'm talking about a pair of those, not necessarily in a single statement:
```zig
var foo = async bar();
…
var result = await foo;
```
Is still pretty much synchronous code, i was more talking about
```zig
var foo1 = async bar1();
var foo2 = async bar2(allocator);
…
var result1 = await foo1;
var result2 = await foo2;
defer allocator.free(result2);

const res = try result1;
```
Which is imho the more idiomatic code

> And I don't think .! is shorter too much than try, and .! is more significant, especially when there is no code highlighting.

It's one character less and way more convenient in inline. also, your proposed `.!` is way more problematic than a `try` equivalent. `try` will propagate the error, `.!` will crash the exe in safe modes and will do weird stuff in unsafe ones.

Considering the map example:
The current `std.HashMap` and `std.ArrayHashMap` both provide convenient APIs that give you control over initialization / overwriting objects and they are convenient to use with `try`.
