### ISSUE TITLE
Proposal: Replace 'return' keyword with 'SLAP'

### ISSUE THREAD

**Issue by mattnite** [ziglang/zig#6328]
like so:
```zig
fn add (lhs: i32, rhs: i32) i32 {
    SLAP lhs + rhs;
}
```
;)

**Comment by Tetralux** [comment]
If this isn't a good candidate for an April Fool, I don't know what is. 😏

**Comment by andrewrk** [comment]
I see the value in this, however I think @GoNZooo can confirm, this actually makes it more difficult to return, because now you have to say "screaming say slap" instead of "say return"

**Comment by GoNZooo** [comment]
Just to confirm; `return` is good in part because if you really want to you can just create a command for it and it won't conflict with the rest of your grammar, or you just indeed go "say return something escape semi". You can actually go "uppercase slap something escape semi" and get the same results, ish, but if you made a command for it in your language you'd still have to substitute it with something not in the rest of your fundamental grammars (i.e. not "slap").
