### ISSUE TITLE
Why signed integer types use the 'i' prefix instead of 's'?

### ISSUE THREAD

**Issue by luauser32167** [ziglang/zig#6417]
If ___s___ is used instead of ___i___, then the first character of the type would denote the "signed-ness" (___s___ for signed, ___u___ for unsigned).

| i-prefix  | s-prefix | C equivalent |  description |
| ----------- | ----------- | ----------- | ----------- |
| i8 | s8 | int8_t | signed 8-bit integer |
| i16 | s16 | int16_t |  signed 16-bit integer |
| i32 | s32 | int32_t | signed 32-bit integer |
| i64 | s64 | int64_t | signed 64-bit integer |
| i128 | s128 | __int128 | signed 128-bit integer |
| u8 | u8 | uint8_t | unsigned 8-bit integer |
| u16 | u16 | uint16_t |  unsigned 16-bit integer |
| u32 | u32 | uint32_t | unsigned 32-bit integer |
| u64 | u64 | uint64_t | unsigned 64-bit integer |
| u128 | u128 | unsigned __int128 | unsigned 128-bit integer |
| isize | ssize | intptr_t | signed pointer sized integer |
| usize | usize | uintptr_t | unsigned pointer sized integer |

**Comment by joachimschmidt557** [comment]
I guess zig follows conventions set by other programming languages here. As far as I know, Rust also uses `i64` for a signed 64-bit integers for example. It also makes sense coming from C as it has `int` and `unsigned int` rather than `signed int` and `unsigned int`.

Honestly, I personally find the current type names very intuitive and accessible.

**Comment by drfuchs** [comment]
Mathematicians have defined "integer" to mean all the whole numbers, positive and negative and zero. This predates all programming languages by centuries, if not millennia.
One might also make an argument that "unsigned integer" should really be "non-negative integer," but never mind.
-drf
    On Friday, September 25, 2020, 05:29:28 AM PDT, Joachim Schmidt <notifications@github.com> wrote:  
 
 


I guess zig follows conventions set by other programming languages here. As far as I know, Rust also uses i64 for a signed 64-bit integers for example. It also makes sense coming from C as it has int and unsigned int rather than signed int and unsigned int.

Honestly, I personally find the current type names very intuitive and accessible.

**Comment by alexnask** [comment]
I am closing this issue for now.  
Feel free to reopen it or make a new issue if you rephrase it as a proposal instead of a question.
