### ISSUE TITLE
Await broken on mips32be 

### ISSUE THREAD

**Issue by Matt8898** [ziglang/zig#6601]
Steps to reproduce:

clone `https://github.com/Matt8898/zig-async-mips`

run:
`qemu-system-mips -kernel zig-cache/zig-async -monitor stdio -cpu '24Kc'`

after building

then in the qemu monitor `x/x 0x81000000`, the result will be `81000000: 0x00000006`, while the expected behaviour  would be `81000000: 0x00000007`, equivalent code has been tested on the x86_64 freestanding target and the result was as expected.

This has been tested on 53dee08af99dd334b0d227afb5ce2a0f92c35a5d

**Comment by LemonBoy** [comment]
Sorry for the delay but I've just found some time to triage this bug.

The good news is that there's no Zig bug, it's your code that's partially wrong:

* `0x81000000` is the base load address for the kernel, the counter is overwriting the very first instruction of `_start`
* The stack pointer is set-up in a region where any write operation is silently rejected, hence the wonky counter value
* Since every read from the stack is always zero at some point you're trying to jump back to `0` with a `lw $ra, N($sp); jr $ra` and since there's no exception handler at `0x80000180` you start executing a loooong sequence of `nop`

Note that with the latest Zig version & LLVM 11 the counter doesn't ever get past `2`.

**Comment by N00byEdge** [comment]
Thank you @LemonBoy for spotting the stack issue.
I can confirm that with `li	sp, 0xa0001000` instead, the expected output is achieved.
```
(qemu) x/x 0x81000000
81000000: 0x00000007
```
