### ISSUE TITLE
Consider assigning a shorter symbol for the most used token ('const')

### ISSUE THREAD

**Issue by luauser32167** [ziglang/zig#6747]
The 'const' token is the most frequent but is the 2nd longest:

| token | occurrences in std |
|----------|----------------------------|
|const|24169|
|pub|14946|
|return|9006|
|self|7257|
|if|6273|
|fn|6216|
|try|5255|
|test|4845|
|var|4478|

The '$' symbol does not seem to have any use in Zig, so I think it can be used to denote 'const'.

```zig
const std = @import("std");

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("Hello, {}!\n", .{"world"});
}
```

Using '$' instead of 'const' the above hello world  program becomes:
```zig
$std = @import("std");

pub fn main() !void {
    $stdout = std.io.getStdOut().writer();
    try stdout.print("Hello, {}!\n", .{"world"});
}
```

'const' also occurs in types:
```zig
[]const u8 -- []$u8
```

In types when using '$', the space is no longer required.

Edit:
Replacing all the occurrences of 'const ' to '$' in any of the big files in std ('os.zig'. 'fs.zig', 'build.zig', etc.), does not seem to hinder the readability in my opinion.

Zig already uses another sigil ('@') for builtin functions, using '$' for 'const' doesn't seem that far-fetched.

**Comment by Vexu** [comment]
Changing `const` has already been rejected in #5076 and #5215.

**Comment by data-man** [comment]
> Using '$' instead of 'const'

Why `$`?
There is other cool symbols: ₠₡₢₣₤₥₦₧₨₩₪₫€₭₮₯₰₱₲₳₴₵₶₷₸₹₺₻₼₽₾₿

**Comment by jedisct1** [comment]
One of Zig's strengths is its readability, due to its intentionally limited use of sigils.

`const` is not that long, very common, self-explanatory, and we don't have completely different ways to declare mutable vs immutable variables.

Most text editors also support shortcuts and autocompletion. I'm pretty sure the Visual Studio extension for Zig can be easily tweaked to suggest `const` when the cursor is at the beginning of a new line and `co` is typed.

Efforts should rather be spent on improving these great development tools rather than changing the language itself.

**Comment by ifreund** [comment]
You could even configure your editor to auto replace `$` with `const` if you'd prefer to type that instead. I think `const` is undeniably more readable.

**Comment by windows-h8r** [comment]
@luauser32167
> In types when using '$', the space is no longer required.

In that case...
```zig
fn x(y: anytype) ![]?*const ?*const @TypeOf(y)
```
becomes
```zig
fn x(y: anytype) ![]?*$?*$@TypeOf(y)
```
Yuck.
