### ISSUE TITLE
WASI reactors

### ISSUE THREAD

**Issue by DagAgren** [ziglang/zig#6757]
I can't seem to find any information about this, so sorry if I am just missing something, but, does zig support building WASI "reactors"?

The concept of a reactor in WASI is a module that does not have a regular start function that runs and exits, but instead has a simpler _initialize() entry point, that just does whatever low-level initialisation the binary and WASI implementation needs (calling global constructors, setting up the preloaded directories), and then exits, leaving everything in place. The hosting environment then calls whatever function the module exports to actually do work.

Is this currently possible in zig, and if not, would it be possible to add support for it?

**Comment by zigazeljko** [comment]
You can manually export the `_initialize` function and use `build-lib` (instead of `build-exe`):

```zig
const std = @import("std");

export fn _initialize() void {
    std.debug.print("hello, world!\n", .{});
}
```

Other than that, there is no special support for this.

**Comment by DagAgren** [comment]
The issue, I guess, is that wasi-libc relies on initialisation that happens in either _start() or _initialize(), and things like fopen() will refuse to work without it. But I am not sure if there is an exposed way to trigger this initialisation outside of the default crt1.o and crt1-reactor.o.

**Comment by DagAgren** [comment]
Also, it seems this happens through __attribute((constructor))__ in wasi-libc. How is that handled in zig? Is it supported?

**Comment by kubkon** [comment]
https://github.com/ziglang/zig/pull/8837 unified the behavior of build commands for Wasm, where `build-lib` will by default produce a static archive that can be used for further linking with `wasm-ld`. If you want to generate a module using `build-lib` you should pass additional `-dynamic` flag to the invocation.

As far as a WASI reactor is concerned, I haven't put much thought into that yet, however, given that we now ship WASI libc, it would be good to first work out how to expose this functionality in C (i.e., with `zig cc`) since #8837 left it a TODO. For pure Zig, we have to be careful since Zig doesn't invoke any ctors. In fact, it is currently assumed the user's responsibility to call any relevant startup code that would otherwise involve dynamic memory allocation such as fetching the preopens, hence the actual startup amounts to calling `_main` in `start.zig`: https://github.com/ziglang/zig/blob/a9dd8d75431357a59238da3fd949aa1f11eead84/lib/std/start.zig#L166.

**Comment by mathetake** [comment]
@kubkon thanks for the response! I created a draft PR for supporting WASI reactor in `zig cc`: https://github.com/ziglang/zig/pull/8978 by leveraging the existing `-mexec-model` flag (https://reviews.llvm.org/D62922). Do you think this is the right way to do?
