### ISSUE TITLE
Improve comptime conditional evaluation

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#6768]
This bug is regarding the feature of Zig where it can discard whole code branches at comptime depending on some conditionals that can be known to always evaluate to **false**. But it seems like it does not always work.

Following are 2 test cases which should both compile without a compile error:
```zig
pub fn main() void {
    var runtime_true: bool = true;
    if (false and runtime_true) {
        @compileError("Shouldn't get here...");
    }
}
```
and
```zig
pub fn main() void {
    var runtime_true: bool = true;
    if (runtime_true and false) {
        @compileError("Shouldn't get here...");
    }
}
```
Unfortunately, only the first example compiles without the error, second example throws the `Shouldn't get here...` message, even though logically second example conditional should also evaluate to **false** and therefore discard the **if** branch as well at compile time.

**Comment by LemonBoy** [comment]
This is not trivial to implement with the current compiler architecture due to the heavy use of laziness (and limitations of the compiler architecture itself).

A expression like `runtime_true and false` is desugared as:
```
if (runtime_true)
    val = false;
else
    val = false;
```

As you can see it's branching on a runtime-known `runtime_true` and the compiler cannot constant-fold the `if` as it does if you swap the two operands.

(The compiler could detect that the two branches are exactly equal but the stage1 compiler is dumb as a brick)

We can't "peek" the second operand because the desugaring is (sadly) done when types/infos about the operands aren't available yet, forget about that solution too. Implementing the `or`/`and` ops with a `SrcBinOp` is also useless: even though you now have enough infos it's too late because by the time you're analyzing the operator the compiler has already "helpfully" analyzed the operands too.
To understand why that's a problem consider this common pattern: `@hasDecl(S, "foo") and S.foo()`. Analyzing `S.foo()` is bound to fail if the `hasDecl` check is not true, hence the need to desugar the boolean expressions.

If stage2 doesn't become a 1:1 copy of stage1 (trading C++ for an obscene memory usage) this improvement may land sooner or later.

Note that this simplification is only sound iff `runtime_true` has no side-effects, otherwise you'd be breaking the left-to-right evaluation contract.

**Comment by SpexGuy** [comment]
I would argue that the current behavior is correct.  The tricky thing with "it can be known that X" is that you may be looking at a set of clues or using assumptions that the compiler cannot.  Or the compiler may be looking at things that you hadn't thought of.  For example, in this code:
```zig
var x = false;
if (x) {
    @compileError("");
}
```
The compiler can technically prove that this if branch never executes, since no pointer is taken to x and it is not modified locally.  Attempts to get a pointer to x through other means (e.g. taking a pointer to a different stack variable and doing pointer math to it) are intentionally UB and can be ignored, so this could be ok.  But with this code:
```zig
extern fn foo(x: *const bool);

var x = false;
foo(&x);
if (x) {
    @compileError("");
}
```
It appears at first glance that the same idea holds because the parameter to `foo` is a pointer to const, but this isn't actually true.  Because the underlying memory for this pointer is a `var`, it is well-defined to use `@intToPtr` + `@ptrToInt` to cast this to a non-const pointer and modify it.  Since the compiler can't see the body of `foo`, it can't assume that this won't happen.

The semantics of comptime are intentionally simpler than the abilities of the optimizer.  This disparity is what makes it possible to reason about comptime vs runtime execution in a simple way, without studying the exact abilities of the optimizer.  Comptime evaluation rules need to be clear, predictable, and documented well.

The semantics of `and` under comptime are currently simple:
- if the left operand is comptime known, evaluate to comptime false if the left operand is false or the right operand if the left operand is true.

This mirrors the behavior of `and` at runtime:
- evaluate the left operand.  If it is false, evaluate to false.  Otherwise evaluate the right operand and use that value.

We could add a clause like:
- if the right operand is comptime false, generate code that evaluates the left operand and evaluate the expression to comptime false.

(this phrasing accounts for side effects)

But this rule would be a major distinction from the runtime behavior of `and`, so it's kind of weird.  I think introducing this sort of behavior would make comptime harder to reason about.

**Comment by zzyxyzz** [comment]
The code compiles fine if you make `runtime_true` const. In general, it is unreasonable to expect the compiler to figure out *anything* about vars, or worse, global vars. Although it may do so on a best-effort basis, of course. In your particular example, the compiler doesn't actually need to know anything about `runtime_true` to make the elision, so that could be reasonably special-cased. But I don't think it's possible to *guarantee* that control flow is precomputed and elided in almost any other case, even if it looks painfully obvious, like

```zig
var one = 1;
if (one < 0) {
    @compileError("No, that can't be!");
}
```

**Comment by zzyxyzz** [comment]
BTW, this also poses an interesting compatibility question: If the official Zig compiler becomes super-smart in the future, and can suppress lots of unreachable `@compileError`s, should it actually do so? If it does, then code that compiles fine on the official compiler might error out on a less sophisticated implementation, which would make the concept of a "compliant compiler" very fuzzy.

**Comment by zzyxyzz** [comment]
After thinking about this some more, I think there is a reasonably simple rule that would allow precomputing conditionals containing `var`s in a consistent manner:

* The compiler attempts to determine the values of all local variables, both mutable and constant, that are computable *without back branches*.
* In practice, this means that the evaluator starts from literals and explicitly `comptime` variables and evaluates any arithmetic and conditionals where possible, but does not enter loops and function calls of any kind (unless they are explicitly marked as `comptime`).
* No advanced analysis à la `llvm::DemandedBits` is performed. A value is either fully known or unknown, with no in-between.
* `false and x`, `x and false`, `true or x` and `x or true` evaluate to `false`/`true` even if `x` is unknown.
* If this process results in a provably unreachable branch, it is discarded.

Although I'm pretty sure that this would work, I don't know how hard it would be to implement. Consequently, I'm not at all sure that this would be a reasonable thing to put in the spec and demand of all compliant implementations. If this is too much, we can always fall back on a much more restricted rule: the condition must be either explicitly `comptime` or computable without touching any `var`s, loops and function calls.

Also, all of this would only be binding for the front-end. The optimizer can still do whatever it wants afterwards.

**Comment by topolarity** [comment]
> We could add a clause like:
> 
> * if the right operand is comptime false, generate code that evaluates the left operand and evaluate the expression to comptime false.
> 
> (this phrasing accounts for side effects)
> 
> But this rule would be a major distinction from the runtime behavior of `and`, so it's kind of weird. I think introducing this sort of behavior would make comptime harder to reason about.

I'm not sure I understand the challenge here.

It seems like this is already exactly how, e.g., multiplication behaves at comptime. For example, this compiles:
```zig
test {
    const y: u32 = 0;
    var x: u32 = 15;
    if (x * y != 0) {
        @compileError("This should never happen");
    }
}
```

Why can't we do the same for `(runtime value) and (comptime false)`?
