### ISSUE TITLE
zig run from stdin

### ISSUE THREAD

**Issue by JRaspass** [ziglang/zig#6780]
Apologies if this has been discussed before but I couldn't find any record.

I would like to be able to pipe zig code to the compiler and have it compile and execute it.

Under 0.6.0 the following works:
```
echo 'pub fn main() !void { try @import("std").io.getStdOut().outStream().print("Hello, world!\n", .{}); }' | ./zig run /dev/stdin
```
But both of these don't:
```
echo 'pub fn main() !void { try @import("std").io.getStdOut().outStream().print("Hello, world!\n", .{}); }' | ./zig run - --
Invalid argument: -
See `./zig --help` for detailed usage information
```
```
echo 'pub fn main() !void { try @import("std").io.getStdOut().outStream().print("Hello, world!\n", .{}); }' | ./zig run /proc/self/fd/0
./lib/zig/std/start.zig:238:35: error: root source file has no member called 'main'
    switch (@typeInfo(@TypeOf(root.main).ReturnType)) {
                                  ^
```

However I see that under the latest master (0.6.0+4b48fccad) the first form doesn't even work anymore:
```
echo 'pub fn main() !void { try @import("std").io.getStdOut().outStream().print("Hello, world!\n", .{}); }' | ./zig run /dev/stdin
error: unrecognized file extension of parameter '/dev/stdin'
```

Are there any plans to support this form of execution? Ideally without needing to pass either proc or dev as the environment I would like to run this under has neither mounted.

**Comment by andrewrk** [comment]
Out of complete and genuine curiosity, can you share more about this use case? (I'm inclined to support it already; I'm just really curious what you're doing with this.)

**Comment by JRaspass** [comment]
Sure, I run [code.golf](https://code.golf) and I recently added Zig to it. The design is such that I like to have the user's solution come via stdin and the challenge's arguments come via argv. I also like to avoid having the source on disk during execution so people can't cheat at the Quine challenge.

ATM My Zig wrapper looks like this but if it supported stdin to run I would need no such wrapper.

```sh
#!/bin/sh -e

chdir /tmp

cat - > code.zig

/usr/local/bin/zig build-exe --global-cache-dir . code.zig

rm code.zig

exec ./code "$@"
```

**Comment by andrewrk** [comment]
Neat! People have been chatting on IRC about having fun with code.golf, so thanks for supporting Zig :-)

One of the reasons to want a source file on disk is for debug info - it makes stack traces work for example. For your use case, however, it seems you would be comfortable passing `--strip`, disabling debug info for the compilation. I would recommend adding that for your case, in fact, since it will remove bloat and speed up compilation.

OK so I'll accept this and here are a couple addendums:
 * Add `-x` CLI parameter to match C compilers, and support `c`, `c++`, and `zig`. So you'll need to use `-x zig` when the type of source cannot be determined from the file extension.
 * `-` as an alias for stdin, approved. :heavy_check_mark: 

I see the merit in getting this done by 0.7.0, so that you don't have to mess with master branch builds for code.golf.

**Comment by JRaspass** [comment]
Hah snap, my Discord room has also been discussing your language quite heavily lately, thanks for making it!

Oh cool, I naively expected `--strip` to take longer thinking it would apply the debug info and then strip it out, but if not happy to apply said flag, any other flags you'd recommend for speeding up compiles? It's definitely one of the slower languages on Code Golf ATM.

Getting this in before the next stable would be a huge as while I'm happy to fetch master tarballs for now I would prefer to track stable releases going forward.

Thanks for being supportive of this idea :-)

**Comment by andrewrk** [comment]
Perhaps it should be renamed, but in zig `--strip` does less work for 2 reasons:
 * it omits adding debug info in the first place rather than a post-processing step
 * it sets `@import("builtin").strip_debug_symbols` to true which is a comptime value that debug info code uses to avoid adding, for example, stack tracing code that wouldn't work anyway without debug symbols

https://github.com/ziglang/zig/blob/194e29adfccbd5076a3523572c7e119d4bfa647d/lib/std/debug.zig#L105-L111

I think it should make a pretty big difference. As far as any other tips, let's see if we can get the [much faster self-hosted compiler](https://www.youtube.com/watch?v=R5FKgi9BYyU) shiping by 0.8.0.

**Comment by JRaspass** [comment]
Nice, `--strip` made a pretty large win - https://github.com/code-golf/code-golf/commit/bec5b91

```
Before
292 solutions (0 failing) in 04:30.29
292 solutions (0 failing) in 04:32.70
292 solutions (0 failing) in 04:30.97

After
292 solutions (0 failing) in 02:54.55
292 solutions (0 failing) in 02:56.53
292 solutions (0 failing) in 02:53.22
```

**Comment by daurnimator** [comment]
> Oh cool, I naively expected `--strip` to take longer thinking it would apply the debug info and then strip it out, but if not happy to apply said flag, any other flags you'd recommend for speeding up compiles?

It sucks to not have tracebacks when you e.g. hit an integer overflow. Could you not strip?

**Comment by andrewrk** [comment]
Ah, apologies for the suggestion - I didn't know that output was visible on the UI. In this case, zig programmers expect these helpful stack traces (as you can see) and I would suggest not passing `--strip`. It's also nice to have the .zig code be in an actual file instead of using stdin, because the debug info works better when there is a zig source file on disk the stack trace can use to print the source code. If this feature were implemented it and you switched to use it, the stack traces would not be able to print the source code line that failed. So this issue might actually be an anti-feature.

**Comment by JRaspass** [comment]
So I'm less fussed about keeping `--strip` especially if the compiler is going to get a lot faster in future but I need to do something about not having the source on disk.

ATM you can "cheat" at the quine hole by sourcing the code with `@embedFile("code.zig")`, I thought I had protected myself by removing the file before execution like so:

```sh
/usr/local/bin/zig build-exe --global-cache-dir . --strip code.zig

rm code.zig

exec ./code "$@"
```

But I now realise that the embedding must be happening at compile time. So I now see the best UX to be reverting `--strip` so the golfer gets stack traces, but no source code lines in the stack trace as the source will be fed via stdin as to prevent quine cheating.

**Comment by andrewrk** [comment]
See #6957 for an explanation of why I am reversing the decision here.
