### ISSUE TITLE
[Proposal] Dedicated repo for proposals

### ISSUE THREAD

**Issue by RUSshy** [ziglang/zig#6890]
Hi

I want to make more proposals, but i feel bad for having to polute the main git repo

Just like other languages, i think it is time to create a dedicated repo for proposals, so we can:

- Search for proposals, obviously
- Find if my BEST IDEA was already proposed or no
- Check status of language evolution
- Better place of discussion

**Comment by daurnimator** [comment]
> Search for proposals, obviously

use the proposal label. https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+label%3Aproposal

**Comment by RUSshy** [comment]
you miss the point, i don't think github issue si the right place to discuss about language evolution

**Comment by andrewrk** [comment]
At this point most non trivial proposals are going to get rejected. The language is almost done. I actually would like to discourage new proposals because I don't want people to put all this effort in and have their work rejected.

Also I'm the main person who has to deal with proposals and I prefer this flatter organization.

**Comment by RUSshy** [comment]
> The language is almost done

Hmm, I 'm curious, what areas left for the language? not plan to improve existing designs?

That is the kind of questions such place would be answer, need proper vision

Also i believe a future proof language is a language that knows when to reconsider certain features, improve them, remove them, introduce new syntax

Nobody knows what's tomorrow is made of, flexibility is key, discouraging proposals is not healthily, in my opinion
