### ISSUE TITLE
Improve release debugging

### ISSUE THREAD

**Issue by Rageoholic** [ziglang/zig#6924]
So if you compile in a release mode the compiler will naturally do it's best to inline whatever it can. And that's what you want. But right now if a function is inlined it becomes impossible to step through the inlined code. This makes it really hard to run a debugger on a release build which you do occasionally want. (note: this is from the win32 build. I don't know if the dwarf debug information is in a better space)

**Comment by andrewrk** [comment]
Everybody wants release debugging to be improved, but this issue is not actionable. I'm closing it for now, but if you edit the title & description into a more specific idea, including test cases, expected behavior, actual behavior, etc, to improve release debugging in some particular way, then I'll be happy to re-open it.
