### ISSUE TITLE
Changes to imported C headers don't trigger re-compilation

### ISSUE THREAD

**Issue by mkeeter** [ziglang/zig#7007]
Here's a simple `main.zig` which imports a C header then prints the size of a struct:
```
const std = @import("std");
const h = @cImport(@cInclude("test.h"));

pub fn main() void {
    std.debug.print("{}\n", .{@sizeOf(h.S)});
}
```

And `test.h`:
```
struct S {
    int a;
    int b;
};
```

Then `zig run -I. main.zig` prints `8`, as expected.

However, if you edit `test.h` to add another member, `zig run -I. main.zig` doesn't recompile, so it continues to print `8`, even though the struct's size has changed.

**Comment by andrewrk** [comment]
hmm I believe this is a recent regression.

**Comment by pfgithub** [comment]
This bug doesn't seem to be a recent regression and it has existed in zig versions as far back as `zig-linux-x86_64-0.5.0+83f6f730c`

**Comment by andrewrk** [comment]
Hmm this should be working in theory because we do add the depfile arguments to the clang command line when doing translate-c, and then we parse the dep file and add the resulting files to the cache manifest. So everything is set up for this case to work correctly - we need to debug what is going wrong.

**Comment by andrewrk** [comment]
OK I see the problem here. The .h file does successfully make it into the translate-c cache system, and if the `@cImport` was semantically analyzed again, it would properly detect the changes to the C header file. However, the C header does not go into the list of files associated with the entire compilation. So, because no .zig files were touched, zig does not realize that the `@cImport` is outdated. The solution is to include the files picked up from parsing the  .d into both the translate-c cache and the Compilation cache.
