### ISSUE TITLE
error: unable to create compilation: UnableToSpawnCCompiler when cross compile .S

### ISSUE THREAD

**Issue by zhaozg** [ziglang/zig#7012]
When I try to compile luajit for aarch64_linux_gnu on macos

```
zig cc -Dtarget=aarch64_linux_gnu  ./lj_vm.S
error: unable to create compilation: UnableToSpawnCCompiler
```

**Comment by alexnask** [comment]
@zhaozg This is a confusing error message, however it is not caused because of cross compilation.  
What happens is the following:
`-Dtarget` is not a flag for `zig cc` (or any of the `zig build-*` commands), the `-D` prefix is only valid in `zig build` flags defined by the build script.  
For some reason, `zig cc` does not detect the wrong flag (this is the actual bug) and therefore tries to compile the file for the native target.  
To do this, it must detect the system libc and it tries to do so and fails by spawning `cc` with some flags.

**Comment by zhaozg** [comment]
Thanks @alexnask , you are write, I write a fail CMakefiles.
