### ISSUE TITLE
Calling struct methods which take a pointer to this struct is inconsistent between dot and 'normal' syntax

### ISSUE THREAD

**Issue by ducrids** [ziglang/zig#7028]
In short, the code snipped below shows what I mean. I'm using latest Zig compiler btw.

```zig
const print = @import("std").debug.print;

const Box = struct {
    length : f64,
    width : f64,
    height : f64,
    
    fn volume(self : *const Box) f64 {
        return self.length * self.width * self.height;
    }
};

pub fn main() void {
    const box = Box {
        .length = 2.0,
        .width = 2.0,
        .height = 4.0
    };

    const pointer_to_box = &box;

    print("{}\n", .{Box.volume(&box)}); // 1.6e+01
    print("{}\n", .{Box.volume(pointer_to_box)}); // 1.6e+01
    // print("{}\n", .{Box.volume(box)}); // I think that if this isn't right...

    print("{}\n", .{&box.volume()}); // f64@7ffdf0035f50 -- ? 
    print("{}\n", .{(&box).volume()}); // 1.6e+01
    print("{}\n", .{pointer_to_box.volume()}); // 1.6e+01
    print("{}\n", .{box.volume()}); // this shouldn't be either. anyways, 1.6e+01
}

```

Has this been already addressed?

**Comment by rohlem** [comment]
Quick explanation of what's happening - you might already know, but just in case.

>`print("{}\n", .{&box.volume()}); // f64@7ffdf0035f50 -- ? `
What's happening here is that the address-of has lower precedence, so you're invoking `Box.volume(&box)` via `box.volume()` and taking the address of the result. What you're giving `print` is a *f64.
(Currently Zig extends the life time of temporaries until the end of that statement if you take their address... and sometimes even longer I think. I'm not sure if this is well-documented anywhere.)

> `box.volume()`
The special rule that allow this syntax allows both per-value arguments and single-item-pointers.
Note that all arguments are implicitly constant in Zig, so all modifying methods have to take `*T` as parameter, and would not qualify for method call synatx otherwise.

> `Box.volume(box)`
Zig doesn't automatically take the address of arguments in general.
(I don't remember whether method call syntax is the _only_ exception, but in general it's rather strict - even when converting arrays to slices (slices count as pointer types, whereas arrays represent the stored values.)

**Comment by ducrids** [comment]
Thank you for your answer!

>What's happening here is that the address-of has lower precedence, so you're invoking` Box.volume(&box)` via `box.volume()` and taking the address of the result. What you're giving print is a `*f64`.

I have sort of figured it out some time after posting this isssue, thanks for the explaination, though!

>Currently Zig extends the life time of temporaries until the end of that statement if you take their address... and sometimes even longer I think. I'm not sure if this is well-documented anywhere.

That's cool, hadn't known that.

>The special rule that allows this syntax allows both per-value arguments and single-item-pointers.
Note that all arguments are implicitly constant in Zig, so all modifying methods have to take `*T` as parameter, and would not qualify for method call synatx otherwise.

This explains a lot...

>So your suggestion would be to allow auto-addressof in functions namespaced in the type if it's the first argument?

...and thus, at the end of the day, I won't suggest any changes to the current state.
