### ISSUE TITLE
Ensure there's a way  to clear padding bytes

### ISSUE THREAD

**Issue by Rageoholic** [ziglang/zig#7206]
So let's say that I'm writing a kernel or something and I am planning on copying a struct from kernel space to user space. If I have previously used the memory backing that struct for anything secret and haven't cleared the bits, then I can potentially have bytes of secret hiding in the padding of my struct. This can lead to some security vulnerabilities. Therefore it seems we need some way of initializing a struct that *ensures* that a struct's padding is set to zero (although we can still have any bits the compiler decides to insert for checking)

**Comment by marler8997** [comment]
If you wanted to zero memory, there are functions you can call to do so.  What language feature are you proposing here?

**Comment by Rageoholic** [comment]
According to someone I talked to, memset on a struct was UB because of the security bytes that can be inserted into a struct. Therefore we need some way to clear the padding while leaving the security bytes intact.

**Comment by SpexGuy** [comment]
This is a valid concern, even in the absence of debug bits.  The following code doesn't work:
```zig
var ptr: *T = ...;
// zero memory
@memset(@ptrCast([*]u8, ptr), 0, @sizeOf(T));
ptr.* = .{
    // write whole struct
};
```

This looks like it should work, but the compiler may realize that writing the pointer this way sets padding to undefined, and therefore all bytes written by the memset are clobbered.  Because of that, it's allowed to "optimize" away the memset completely.  You could write each field individually after the memset, but then you lose the benefit of having a compile error if you add a field.  We need either a way to write a whole struct and guarantee that the padding is written, or to write a whole struct and guarantee that the padding retains its value.  The current approach of "it could be either" doesn't leave any way to handle this use case.

**Comment by Snektron** [comment]
Note that the standard library contains the function secureZero, which is supposed to unconditionally zero a piece of memory:
https://github.com/ziglang/zig/blob/ba967ae9a1eada3a08803470f557bafcfb69151e/lib/std/crypto/utils.zig#L43

**Comment by SpexGuy** [comment]
Good point, that works by making the pointer volatile so the compiler can't optimize away the memset.  That's pretty ugly though, especially because using a volatile pointer prevents fast zero optimizations like using SSE instructions.  Instead, this implementation always has to write each byte individually because it's volatile.

Maybe a builtin is the way to solve this, something like `@zeroPadding(T) T`.  Like other builtins, this infers T from its result type.  So you could do
```zig
var ptr: *T = ...;
ptr.* = @zeroPadding(.{
    // init fields
});
```

An alternate approach would be to provide a stricter guarantee for padding, something like "on struct initialization, padding bits must either preserve their value or be written with compiler-defined bits.  For extern or packed structs, padding bits must preserve their value or be written with zero.".  This rule would prevent the memset from being optimized away, or guarantee that all of the bits get clobbered and there's no secure information left.  But it also may prevent optimizations that detect write-after-write and remove the first one.  Maybe it makes sense to do this but only for extern/packed structs?

**Comment by cajw1** [comment]
> This is a valid concern, even in the absence of debug bits. The following code doesn't work:
> 
> ```zig
> var ptr: *T = ...;
> // zero memory
> @memset(@ptrCast([*]u8, ptr), 0, @sizeOf(T));
> ptr.* = .{
>     // write whole struct
> };
> ```
> 
> This looks like it should work, but the compiler may realize that writing the pointer this way sets padding to undefined...

I am surprised the compiler is allowed to treat it the same as:

```zig
@memset(@ptrCast([*]u8, ptr), undefined, @sizeOf(T));
```

This issue is related to @breakin's comment https://github.com/ziglang/zig/issues/7115#issuecomment-729648487

What about a new keyword `zerobits` ?

```zig
var ptr: *T = ...;
ptr.* = zerobits;
ptr.* = .{ ... write whole struct ... };
```

The reason I suggest the keyword is that I was thinking that - as an implementation detail at least - `anyfrozenbits `(should it be accepted) could be defined to mean `zerobits` for comptime instances (and maybe the compiler could then force the use `zerobits `instead of `anyfrozenbits` for comptime instances, should one wish to make this implementation detail explicit).

**Comment by andrewrk** [comment]
I don't think there is an issue here. The code in https://github.com/ziglang/zig/issues/7206#issuecomment-732354394 is not a realistic example. If you're going to re-write every field then have a userland struct type including the padding and set the padding explicitly to zero at the same time that you populate the other fields. Sending the user `undefined` memory is inherently insecure, even if you are not pointer casting, because if it's `undefined` then it is allowed to be any value, including copies of values from kernel memory, which could leak kernel secrets. IMO all your userland structs should have no implicit padding. You could even have some `comptime` code that makes a compile error if this restriction is invalidated. Also in your userland structs you can define the padding field with a default initialization of 0 so it's completely painless.

I'm going to close this but I will re-open it if provided some real zig OS code that demonstrates the problem and the workaround contains a footgun.
