### ISSUE TITLE
Accessing tagged union members should result in %Type, not Type

### ISSUE THREAD

**Issue by zesterer** [ziglang/zig#736]
Accessing tagged union members should result in an error-or type if the union's tag enum does not correspond to the member attempting to be accessed.

This maintains the honesty of Zig's type system and forces the programmer to consider edge cases that may cause undefined runtime behaviour.

This is in accordance with the following two Zen points:

- Edge cases matter.
- Compile errors are better than runtime crashes.

Optionally, adding a built-in function such as `@rawVariant(TaggedUnionType, MemberType)` may allow an unsafe way to override the default tag-checking behaviour in cases where performance is of critical importance. This override function's use should be strongly discouraged and its use should probably produce some sort of compiler warning (since virtually all uses of this function can and should be mitigated by more sensible type choices).

**Comment by tiehuis** [comment]
Here are some current methods of accessing/checking a tag explicitly before using it.

```
const debug = @import("std").debug;

const Foo = union(enum) {
    Integer: usize,
    Slice: []const u8,
};

pub fn main() void {
    const s = Foo { .Slice = "hello" };

    // Use an if then explicitly access
    if (s == Foo.Slice) {
        debug.warn("{}\n", s.Slice);
    }

    // Switch and capture the inner value
    switch (s) {
        Foo.Slice => |slice| {
            debug.warn("{}\n", slice);
        },
        else => unreachable,
    }

    // Allowed if using the proposed method (using if-error)
    //
    // if (Foo.Slice) |slice| {
    //     debug.warn("{}\n", slice);
    // } else |err| {}
}
```

I'm personally favoured towards the current status quo. I see the explicit union type to access an inner member more similar to something like an array access. The current if semantics on error unions means that it is still slightly unwieldy to get the value itself as well so I wouldn't count that as a benefit.

I've been writing some union(enum) heavy code lately and my only use-case of an explicit tag access is when the tag is guaranteed to be one I'm accessing. In all cases where it could be one of many, an if or switch has sufficed and is usually preferred since most of the time you want to deal with more than one variant anyway.

**Comment by zesterer** [comment]
If you're using a tagged union like an array, I'd suggest using another language feature or using my proposed unsafe syntax if you must.

By providing a way for programmers to subvert the strong typing system subtly and without any compiler error, Zig opens itself up to a lot of problems down the line. Runtime errors like this can be difficult to detect, difficult to notice in code, and extremely dangerous in practice. The temptation to skip a tag check is very high, especially for prototype code. It's also the sort of thing that will be easily missed when refactoring for production code. Not placing some kind of safety constraint around this feature is **bad** news.

**Comment by tiehuis** [comment]
Fair points. I'll switch my take on it. I've had another look and there are only a few places which are doing an explicit assertion on a particular tag. Replacing these with a builtin is not a burden. This is more in-line with the zig philosophy.

**Comment by thejoshwolfe** [comment]
This is a discussion of what kinds of exceptional (for lack of a better term) circumstances should result in first-class error values or result in assertion failures (crashes when safety is enabled). Union access is just one of many circumstances that are subject to this kind of discussion.

Consider integer addition. Overflow is always a possibility, and the author should be conscious of it. Does this mean that the addition operator should produce an errorable result? Perhaps, but that would be an awful lot of error checking. Instead, addition includes a runtime safety assertion for overflow, and semantically produces the (non-errorable) result directly.

Sometimes you do want an errorable result instead of an assertion. In this case, you should use a userland utility function. For integer addition, this is `@import("std").math.add`, which produces an errorable integer result, and can return `error.Overflow`. For union enums, it's not very convenient to implement such a utility function yet, but with the planned `@field()` builtin function, it should be easy.

There is a precedent in Zig where no particular named error is used by any language feature or builtin function (builtin functions start with `@`; not to be confused with standard library functions accessed through `@import("std")`). For example, `@addWithOverflow()` does not return an errorable value. There are no error declarations in `@import("builtin")`. (This is in contrast to languages like Java which define `NullPointerException` that can result from doing language-level things like `a = b.c;`.)

So we don't want `a = b.c;` in Zig to involve any magically named error, like `error.WrongTagValue` or something. Leave that error declaration to a userland utility function.

In my experience using tagged unions (such as [here](https://github.com/thejoshwolfe/legend-of-swarkland/blob/46b1916af06e9d7f6829cb6ff552049e5cd38f28/src/event.hpp#L418) in C++), I've always wanted an assert rather than a conditional branch. If I wanted a conditional branch on the tag value, I would check it with a `switch`.

**Comment by zesterer** [comment]
Perhaps, then, accessing members of a tagged union should not use the `a.b` syntax if adding error checking to this syntax is so refuted?

It seems to me that allowing the current behaviour to persist flies directly in the face of the language zen.

Besides: If one wishes to access a tagged union member without overhead, one only has to take a pointer to the member and access that member through that pointer. LLVM's optimiser should be smart enough to remove the extra layer of indirection upon compilation, meaning there's no particular code slowdown, but a substantial layer of safety has been added to the language. Alternatively, as I suggested previously, a built-in function such as `@rawVariant(union_instance, MemberTag)` would go some way to mitigating performance losses in software that _really_ requires it.

**Comment by andrewrk** [comment]
Consider that `?T` is essentially a tagged union: `union(enum) {Null, Payload: T}`
Likewise `anyerror!T` is: `union(enum) {Error: anyerror, Payload: T}`
To access the payload for `?T` you use `.?` which asserts non-null.
To access the payload for `anyerror!T` you use `catch unreachable` which asserts non-error.
To access these in a way that lets you check the tag, you use `if`, `while`, `catch`, or `orelse`.
Likewise to access tagged unions in a way that lets you check the tag, use `switch`.

We can have a standard library function that tries to get a specific payload based on tag name, or returns `error.UnionFieldNotActive`, but the language syntax certainly should not depend on an error.
