### ISSUE TITLE
Doc comment error in fixed_buffer_stream.zig

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#7423]
the doc comment for `FixedBufferStream.inStream` says:
```zig
        /// Deprecated: use `inStream`
```
shouldn't that be: 
```zig
        /// Deprecated: use `reader`
```

**Comment by andrewrk** [comment]
Please don't open issues for something as trivial as this, either send a PR or ask the question in one of the chat rooms.

If you want to participate in zig pre-1.0 you will have to (1) lower your expectations of quality, stability, and documentation, and (2) put more effort in yourself rather than putting it upon others who are already working at full capacity.

Otherwise, take a break for a year or two then come back.
