### ISSUE TITLE
Proposal: Implement slices in userland insead of the compiler

### ISSUE THREAD

**Issue by UgiNyaa** [ziglang/zig#7432]
Currently, there are two families of slices:
- slices with dynamic length
- slices with comptime known length

### slices with dynamic length
Slices with a truly dynamic (not comptime known) length can only be achieved by allocation. Allocation is defined in userland, not in the compiler. So it does not make sense to include slices as a native type, since there is no way to actually create a slice with dynamic length and without allocation.

### slices with comptime known length
Slices with comptime known length are essentially just normal arrays. Whether you have a slice like `[]u8` with length `N` (`N` is comptime known) or an array like `[N]u8`, it is the same thing.

### alternative use of `[]T` syntax for any type `T`
`[]T` should communicate the indent, that an array with variable but comptime known length is expected. It would take a similar position as `anyerror` or `anyframe`, where the type of a certain value has to have certain properties.

### goal of this proposal
The goal of this proposal is to make the compiler code base **simpler** and the syntax more **consistent**.

**Comment by MasterQ32** [comment]
I don't think it's a good idea to do this as it would increase the difference between comptime and runtime instead of decreasing it. Comptime known slice lengths don't hurt anywhere in the coding experience, but removing runtime slices will hurt a lot. It will also remove the possibility to use stuff like `std.mem.eql` both at runtime and comptime (or it would make usage harder)

Reducing the compiler complexity is a good goal, but not when increasing the language complexity

**Comment by UgiNyaa** [comment]
@MasterQ32 
I think the distinction between runtime and comptime known length of an array is important, because it determines if the user should or shouldn't allocate space for it.

However, I see that the distinction becomes meaningless and even counter productive when passing arrays or slices to functions as an argument, since the function doesn't care whether the array or slice was allocated or not.

In the case of `std.mem.eql`: It will not be impossible to use, nor will it be harder to use, but it will be harder to implement, since `std.mem.eql` will have to explicitly allow arrays of runtime and comptime known length and handle each case appropriately.

I understand that the tradeoff of increasing the implementation complexity of `std.mem.eql` and similar functions might not be worth taking.

**Comment by MasterQ32** [comment]
> I think the distinction between runtime and comptime known length of an array is important, because it determines if the user should or shouldn't allocate space for it.

Yes, i agree with that. That's why we have `[N]T` for `comptime` known length and `[]T` for runtime-known length. Even if the length is comptime-known in a `comptime` context, you still might need to change the length of a `[]T`, but you cannot change the length of a `[N]T`.

The properties are the same for `comptime` and runtime. The only question that differs is *where does the memory come from?*,  but you also need to back a `comptime` slice with `comptime`-allocated memory. `comptime` slices are not magically populated with memory

**Comment by SpexGuy** [comment]
The premise that slices require allocation is false.  Here is a perfectly valid use of slices without allocation:
```zig
pub fn printInteger(int: i32) void {
    // integer cannot exceed 11 bytes, including leading `-`
    var buffer: [11]u8 = undefined;
    // number of actual bytes used is runtime known
    const bytesWritten = std.fmt.bufPrint(&buffer, "{}", .{int}) catch unreachable;
    // this slice is not allocated but its length is runtime known
    const string = buffer[0..bytesWritten];
    puts(string);
}
```

**Comment by UgiNyaa** [comment]
@MasterQ32 
I think I get what you mean now. Essentially, thinking of arrays as something separate then slices doesn't make sense. Rather, It is healthier to think of arrays as slices of comptime known length. As you said, both arrays and slices have the same properties, so a distinction becomes meaningless. It is only, that for a slice, the length has to be stored in memory, but for an array there is no need. Therefore in memory, arrays and slices look different, so I was assuming they are different structures without quite thinking it through.

@SpexGuy
That example is quite insightful. I could not have imagined a usecase where slices without allocation would be useful.

I think there is no need for this issue to stay open. Thank you for the contribution and for clearing up my misunderstandings!

**Comment by MasterQ32** [comment]
You're welcome!
