### ISSUE TITLE
Overzealous undefined behaviour check at comptime

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#7635]
Trying to use `PackedIntArray` initialised to `undefined` at comptime results in errors such as:
```
./lib/std/packed_int_array.zig:127:13: error: use of undefined value here causes undefined behavior
            target &= mask;
            ^
./lib/std/packed_int_array.zig:100:20: note: called from here
            setBits(bytes, MaxIo, bit_index, int);
                   ^
./lib/std/packed_int_array.zig:222:26: note: called from here
            return Io.set(&self.bytes, index, 0, int);
                         ^
./lib/std/packed_int_array.zig:229:25: note: called from here
                self.set(i, int);
                        ^
```

I think this is a false positive of the undefined value tracking.

Possibly related: #7634

**Comment by LemonBoy** [comment]
> I think this is a false positive of the undefined value tracking.

Definitely not a false positive, if `target` is undefined and-ing it with some value _is_ undefined behavior.
Are you suggesting {un,bi}nary ops with `undefined` values to return `undefined` instead of warning the user?

**Comment by daurnimator** [comment]
> Definitely not a false positive, if `target` is undefined and-ing it with some value _is_ undefined behavior.
> Are you suggesting {un,bi}nary ops with `undefined` values to return `undefined` instead of warning the user?

and-ing undefined with something could end up clearing some the undefined bits: `@as(u8, undefined) & 0xfe` => you now (theoretically) have an undefined even integer: the high bits can be undefined, but the low bit is *not* set.

`PackedIntArray` seems to rely on this behaviour.

**Comment by LemonBoy** [comment]
Oh well, this is an enhancement proposal more than a bug report then, the compiler currently treats any value as fully defined or fully undefined.

**Comment by daurnimator** [comment]
> the compiler currently treats any value as fully defined or fully undefined.

It only seemed to be detected at comptime: at runtime it didn't seem to get detected?
I assumed this was a bug with comptime; but perhaps it is just undetected at runtime.

So either `PackedIntArray` needs some help, or we need to add support for partially undefined values to the compiler. 

One easy option might be treating partially undefined as defined; and back fill with `0xaa`?

**Comment by LemonBoy** [comment]
> It only seemed to be detected at comptime: at runtime it didn't seem to get detected?
I assumed this was a bug with comptime; but perhaps it is just undetected at runtime.

It's triggered at comptime because the compiler can read the pointer `target` comes from and see that, when `setBits` is called, the value is `undefined`.

> or we need to add support for partially undefined values to the compiler.

That's the best and technically more difficult way to solve this problem. Value range propagation and live bit tracking would be helpful here and in some other optimizations.

**Comment by andrewrk** [comment]
Clarifying the language spec here: Zig has the concept of undefined values which is different than undefined behavior. Here are the rules about how that works:

 * Branching on an undefined value is Illegal Behavior
 * Most kinds of illegal behavior are checkable, in which case when safety is enabled for the scope, the behavior is defined to panic.
 * When safety is disabled for the scope, or the specific kind of Illegal Behavior is not checkable, invoking Illegal Behavior invokes Undefined Behavior

Operations on undefined values:
 * Operations that can trigger Illegal Behavior for some values of operands, if one of the operands is undefined, that operations triggers Illegal Behavior. For example `a + b` triggers Illegal Behavior if an overflow occurs. So if either `a` or `b` is undefined, this operation triggers Illegal Behavior.
 * Operations that cannot trigger illegal behavior for any values of operands, if one of the operands is undefined, the result of the operation is undefined. For example, `a +% b` where either `a` or `b` is undefined, results in an undefined value.
 * If one of the operands is comptime known and the operation therefore becomes impossible to invoke Illegal Behavior for any values of the other operands, and any of the other operands are undefined, then the operation results in undefined, no Illegal Behavior is invoked. For example `x + 0` where `x` is undefined.
 * If one of the operands is comptime known and the operation therefore has a comptime-known result regardless of the values of the other operands, that operation results in the comptime known result.

So the example from this issue is indeed a compiler bug.

cc @SpexGuy

**Comment by LemonBoy** [comment]
Oh I see, a few bitwise ops (and, or, xor, not?) fall under this category I guess

> Operations that cannot trigger illegal behavior for any values of operands, if one of the operands is undefined, the result of the operation is undefined. For example, a +% b where either a or b is undefined, results in an undefined value.
