### ISSUE TITLE
 Complete out the debug AIR dumping code

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#7670]
`--verbose-ir` has some helpful output, but it's not complete yet:

https://github.com/ziglang/zig/blob/d8f3f14532c4b5d65377efaef015c3855137dccf/src/zir.zig#L1962-L1971

**Comment by xpyxel** [comment]
Looks like this was changed drastically since this issue was published, a few things need to be completed, mainly:

https://github.com/ziglang/zig/blob/master/src/zir.zig#L1767-L1774
https://github.com/ziglang/zig/blob/master/src/zir.zig#L1776-L1783
https://github.com/ziglang/zig/blob/master/src/zir.zig#L1795-L1811

**Comment by andrewrk** [comment]
This is done in master branch.
