### ISSUE TITLE
Assert compile error for unspecified array/slice format

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#7675]
I'm opening an issue based on my comment here: https://github.com/ziglang/zig/pull/6870#issuecomment-735450839

That PR was just merged which means that now the default format for printing slices/arrays will be integer values rather than raw values, i.e.:

```zig
const std = @import("std");
pub fn main() void {
    std.debug.warn("Hello, {}\n", .{"World"});
}
```

```bash
$ zig run hello.zig
Hello, [5:0]u8@7ff7cb1be3a0
```

The fix for this example is to specify `{s}` whenever you're printing a string.  The problem with this is now whenever a format string does not specify the correct format, the bug will not be caught until runtime and the string is inspected.  What makes this worse is that this kind of format string is commonly used for error messages, which often don't get tested or inspected until the error occurs, which many times is only seen rarely if at all.  There is now a disconnect between what code looks like, and the default way to format strings.

To remedy this, I propose that we require a format specifier for slices/arrays. On top of that, in order to support generic code I propose that we enable today's current behavior of `{}` with an explicit specifier.  Something like `{any}`.  The `{any}` specifier would mean "print this thing, I'm not picky about the exact format, just print it somehow".  The difference here is that instead having this "I'm not picky about the format" attitude by default with `{}`, the user has to opt-in to it.

Also note that with the PR that was just merged, alot of Zig code will now be broken due to missing format specifiers that were meant to be `{s}`.  Implementing this proposal means these bugs will be found at compile-time so they will be easy to find and fix.

Here's the list of array specifiers:
```
{s} - format as a list of Unicode characters characters and interpret array as a utf8 encoded string
{d} - format as a list of decimal values
{x} - format as a list of lowercase hex values
{X} - format as a list of uppercase hex values
```

**Comment by daurnimator** [comment]
As an alternative solution, what if there was a `String` type in zig that made it distinct from an array of u8?

**Comment by marler8997** [comment]
Yeah having distinct string type would be another way to solve this.

**Comment by rohlem** [comment]
Unless I'm missing something, even if we had a distinct `String` type, we still want `[]u8` (any kind of "normal" C string that people forgot to cast) to trigger an `assert` with the default `{}` format, right?
Because that seems the essence of this footgun, the fact that the "simplest"/"most obvious" solution gives undesirable output in rarely-tested code paths. Adding "a right way" via an optional `String` type alone doesn't quite solve this I think.

**Comment by marler8997** [comment]
@rohlem yes that's a good point.  Even if we added a distinct `String` type, code that uses arrays of `u8` would still exist.  My guess is that this would be common code meant to work with both strings and data.  All this code would still be subject to this problem even if a `String` type exists.

**Comment by kyle-github** [comment]
If you want to allow easy UX for printing formatted strings, I really only see four possibilities:

1. Do like C and have a `char` type (it would have to be a Unicode code point I think, so definitely not 8 bits).  Arrays of these would be easily inferred to be strings.   This is painful for interop with C.
2. Have a utf8 data type for a utf8 byte.   It is 8 bits, but when you pass an array of them, you can easily tell and use it as a utf8 string.  If it is malformed, you get nasal demons.   This works with C pretty well. 
3. Have a string type and drop down to a `[]u8` representation when passing to C.   This is really a separate string library.
4. Specify that the data should be processed as a string with `{s}` or something.   This is feasible.

Personally I like the second option.  If you know that your data is actually a utf8 string, it would be nice to let the system know that via types.  It works with sentinel-terminated arrays as well as counted arrays just fine.  You should be able to bit cast a byte between utf8 and u8, but they are not the same and should not be trivially interchangeable.

**Comment by marler8997** [comment]
> If you want to allow easy UX for printing formatted strings, I really only see four possibilities:

I wouldn't describe the goal here as "to allow easy UX for printing".  The only goal here to catch bugs at compile time instead of runtime.  One of the tenants I've learned over the years is:

    "interfaces should be easy to use correctly and hard to use incorrectly...and they matter"

    - Scott Meyers

I recommend watching this entire talk from Scott Meyers, but here's the timecode of the section where I pulled that quote from:
https://www.youtube.com/watch?v=3WBaY61c9sE&t=43m24s

We've made a change to our `fmt.zig` module where `{}` is now the "incorrect" way to format arguments in a common use case, which is when you intend to format raw strings.  Note that this change in default behavior isn't the problem.  The issue is that now the "easy way" to format arguments with `{}` produces bugs that are not detected until you run the program and inspect the resulting string.  I'm proposing that we modify our interface so this bug is detected at compile-time instead of runtime.  The way to make this detectable at compile-time, is to not allow an unspecified formats for these "ambiguous" types.  When we detect an "ambiguous" type being formatted with no specifier, its likely the developer has a bug and we can inform them at compile-time.  To demonstrate, by making this change to the interface, I've already identified handful of bugs in the compiler (see https://github.com/ziglang/zig/pull/7676).

**Comment by andrewrk** [comment]
Two things this proposal should clarify:
 * Example of intentionally printing arrays
 * Example of intentionally printing any type including arrays

**Comment by kyle-github** [comment]
HI, @marler8997  I am familiar with Meyers :smile_cat:   Perhaps too familiar!  I still have his first edition _Effective C++_ somewhere around here...

Note that that options 2 and 4 are not contradictory.   However, what 2 allows is any compile time introspection to determine that something is roughly a printable string without having an explicit string type.  Instead `utf8` becomes the explicit string _element_ type.

Option 2 would be a significant change to Zig, but it works exactly along Meyer's point.   Think of it this way:  If you are required to tell your code that a piece of data means something then you want the "interface" for that statement to be easy to use and hard to get wrong.   

A printf-style format specifier is out-of-band with the data itself.   Because it is out of band, you can change your type but forget to change your specifier.   Any time you have to tell code something about your data (metadata) that is not an inherent part of that data itself, you have a risk that the data and metadata diverge.   If your metadata is all in your type information, then you cannot lose it unless you transform your type.

I hope that makes it more clear what I was thinking with option 2.   It was _precisely_ to make it more difficult to make a mistake that I was thinking of leveraging Zig's excellent type handling and compile time features in order to make strings a little easier to use.   This is almost certainly the wrong place to work that out, however, as it is a rather invasive change at this point and this issue is about printing arrays.

**Comment by marler8997** [comment]
@kyle-github yes I can see the benefits of your proposed option 2.  However, adding a new `utf8` element type would come with many other effects that I'd have to ponder on.  The fact that Zig doesn't distinguish between `char` and `uint8_t` like C does makes things simpler.  I'm sure Zig could do a better job than C but I myself don't know whether it would be a net gain.  So far I haven't seen a big need for it other than for formatting, and I don't think that alone is reason enough to add this new type to the language.  I'll keep the potential feature in mind as I continue to work with this language.

P.S. The problems that arise from "out-of-band" data are worth looking into.  String interpolation is another solution that gets around it by making the data "in-band".  There is a library that allows a form of that, but its a bit verbose.

**Comment by andrewrk** [comment]
> On top of that, in order to support generic code I propose that we enable today's current behavior of `{}` with an explicit specifier. Something like `{D}` for "Default" would work. The `{D}` specifier would mean "print this thing, I'm not picky about the exact format, just print it somehow". There difference here is that instead having this "I'm not picky about the format" attitude by default with `{}`, the user has to opt-in to it.

OK we definitely need this but I think `{D}` is problematic for a couple reasons:
 * we already have `{d}` which means "decimal"
 * it's just not something you would guess without reading the docs. If you have never used zig and you see `print("x = {}\n", .{x})` your guess about what it does is probably right. But with `{D}` the reader would be left scratching their head.

**Comment by marler8997** [comment]
Keeping in mind that this `{D}` specifier would be uncommon and it would only be used to print `anytype` values, what about a verbose option like `{anytype}`?

**Comment by kyle-github** [comment]
I'd suggest `{?}` or `{*}` but those are already used sigils :frowning_face:

**Comment by matu3ba** [comment]
@kyle-github 
So the difference between option 2 and 3 is only, that option 2 is an explicit annotation for a "conversion to C" and option 3 is implicit ?

If this is expected to be heavily used in comptime, I would prefer `{any}` to keep it shorter.

**Comment by kyle-github** [comment]
@matu3ba Not really.   Option 2 is the idea that there is a utf8 string **element** type (which I confusingly called `utf8`, I'll use `utf8_byte` here).   It is not a character or code point or glyph.  It is 8 bits of information, but it is not a u8.   If any code sees an array or slice of that new type, it can assume that it is a printable string.  The point of that idea is that it would work in practice almost the same as slices or arrays of u8.   There still is not a string type per se.  

For option 3 (from @daurnimator above), there would be a string type.   Whether or not it was implemented internally as an array or slice of u8 or something else would be hidden away.  My concern here is that it is unrealistic to think that such a string implementation can be done outside of `std` because the compiler has to deal with it.

If the compiler returns `[]u8` for all constant strings, you would have the same problem as C++ with C strings and `std::string`.  Except without automatic coercion and all the other C++ hackery, it would not ergonomic at all and everyone would write all their APIs to use `[]u8`.  I was also thinking of the different types of string in Rust and how much I think that is a design smell in the language.  Strings are something that code deals with often, the language should make them at least not painful to deal with.

With option 2, the compiler will translate "Hello" into something with type `[5:0]utf8_byte`.  With option 3, it would be either `[5:0]u8` (so you do not know if this is some binary blob or a string) or some special Zig string type.

With option 2, you get type information that says, "here is an array of 5 elements with a zero terminator, and by the way the data is printable as utf8."   With the existing option of `[5:0]u8` you get, "here is an array of 5 elements with a zero terminator and the elements are unsigned integers of 1 byte each."   Nothing about the _interpretation_ or meaning of those elements.

I was trying to see if there was a middle ground between `[]u8` and a full-blown string type.   If the underlying type tells you that something is printable then you can have formatting guess right and you can have debuggers get this right too (assuming that the debug info contains enough type info).

Note that you could achieve the same effect of option 2 if there was a way to annotate types with additional information like `const utf8_byte = u8 { .is_printable = true }` then make your strings building on `utf8_byte` instead of `u8`.

This is all really far afield from the original point of the issue which was just to fix up the formatting type markers.

**Comment by marler8997** [comment]
@matu3ba I like `{any}`.  I'll steal that and modify my proposal/description to use that for now.
