### ISSUE TITLE
Automatically add includes for cimports

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#7771]
Currently if I have a folder that contains two files: `main.c` and `main.zig`, the following code inside `main.zig` does not work:
```zig
const c = @cImport(
    @cInclude("main.c"),
);
```
This is because our way of including C files is modeled after how C does it (which makes total sense). However, this is a bad user experience and frankly unsatisfying.

What I propose here is automatically adding includes for cimports - one include at the directory of cimporting zig file.

**Comment by SpexGuy** [comment]
We could do the C thing and have two:
```zig
@cInclude("foo.h"), // searches this directory first
@cInclude(<foo.h>), // searches only include directories
```
(but please don't actually do this)

---

In all seriousness though, the C compatibility features are there to match C.  Since C's behavior for an include with quotes is to search the current directory, and we use quotes (albeit for different reasons), I think we should do the same thing as C here and search the current directory before searching include directories.

**Comment by andrewrk** [comment]
@Sobeston I'm happy to re-open this if you clarify the proposal more. As it stands I don't really understand what it is suggesting. Can you include a full example with all files involved and the command line you expect to execute?

**Comment by SpexGuy** [comment]
Here's a complete example:
```c
// src/foo.c
#include "foo.h"
```
```c
// src/foo.h
#define FOO 1
```
```zig
// src/foo.zig
comptime {
  _ = @cImport({
    @cInclude("foo.h");
  });
}
```
The command `zig cc src/foo.c -c -o foo.o` succeeds, because `#include "foo.h"` searches in the directory containing the .c file first.  But the command `zig build-obj src/foo.zig -lc` fails, because `src` is not specified on the include path.  The proposal here is to change the search path of `@cInclude` to start with the directory containing the .zig file.

**Comment by andrewrk** [comment]
Thanks!

**Comment by andrewrk** [comment]
Solved by moving `@cImport` to the build system. #20630
