### ISSUE TITLE
Proposal: Relegate return values of `@offsetOf` and ilk to runtime, or post-comptime

### ISSUE THREAD

**Issue by EleanorNB** [ziglang/zig#7888]
Hand in hand with #7887. Preventing superfluous commitment.

Ideally, struct layout is determined after semantic. However, comptime precedes semantic analysis. Therefore, when the values of `@offsetOf` and co. are used at comptime (even in seemingly transparent places such as comparison with literals), layout must be determined before any analysis, and therefore any optimisation, can be done. The unoptimised result must then be preserved all the way through to runtime.

However, some brainstorming with @SpexGuy on Discord turned up exactly one use case where `@offsetOf` could be used and `@field`/`@fieldParentPtr` could not: iterating over a struct's fields at runtime, without unrolling a hot loop. This case does not *need* to know the offset at comptime; in fact it's actively harmful to the cause of not unrolling. So, there is no reason to require it to be computed then.

I propose that layout shall not be determined before semantic analysis. Instead, the return value of `@offsetOf` shall be treated as runtime during sema, and only written to the output once sema has completed. This is effectively #1639's post-comptime.

This may appear to add undue complexity, but in fact it removes an unsightly wart on compilation (unoptimised layout, *sometimes*), and there is even precedent in pointer resolution (which is done at link time, after sema).

**Comment by SpexGuy** [comment]
The compiler already does this - if you don't force the result of offsetof to be comptime known, it will be patched after optimization.  The one use case does exactly this - just storing the value in a runtime data structure without forcing it to be evaluated.  Using offsetof at all still prevents the compiler from removing unused fields, regardless of whether the result is runtime known, so what does this change actually save?  The only thing left is field reordering, and it's unclear that anything more than a basic reordering based on alignment will be worth the optimizer's time.  Offset should definitely still be comptime known for extern and packed structs, so it's kind of strange that offsetof would sometimes return a comptime value and sometimes return a runtime value.

This issue feels to me like an alternative to #7887, rather than an addition.  Both are alternate ways to attack the problem of struct optimization -- 7887 moves the optimized struct to be separate from the default struct, and this one attempts to fix the default struct.  Ultimately I think this one is not very effective, I don't think that this fixes a real problem.

**Comment by andrewrk** [comment]
Superseded by #8642. Offset-of and friends will remain comptime for well-defined memory layouts.
