### ISSUE TITLE
Compiler doesn't mark a function as async when using @asyncCall

### ISSUE THREAD

**Issue by zenith391** [ziglang/zig#7914]
Hello, I have encountered a bug where calling a normal function makes Zig panic with `thread 59560 panic: resumed an async function which already returned`.

For information, I used this code (simplified):
```zig
loader: ?fn(allocator: *Allocator, ptr: usize, stream: *AssetStream) callconv(if (std.io.is_async) .Async else .Unspecified) anyerror!usize = null, // field with a function pointer

if (std.io.is_async) {
    // ...
    self.objectPtr = try await loaderFrame;
} else {
    if (self.loader) |loader| {
        self.objectPtr = try loader(allocator, self.loaderData, &self.stream); // <-- panics with "resumed an async function which already returned"
    } else {
        // ...
    }
}
```

**Comment by zenith391** [comment]
Found the problem, I had an interface struct that contained an async function, it exposes a read() function (used by the called loader) that contains `@asyncCall()`, however still, for some unknown reason, the Zig compiler hasn't reported at all that the called loader was async due to that. For this reason I believe the fact that the compiler didn't report that problem is a bug and thus, i leave the issue opened.

**Comment by lithdew** [comment]
Could you provide a concise runnable test case and stack trace? There are a a lot of possible reasons for the error without full context.

Here's one possible reason: `read()` is async, but does not suspend `loader()` as the call to`@asyncCall()` in `read()` does not suspend its caller, but instead only instantiates a new async frame. `loader()` is async due to it's call to `read()` which, perhaps, may resume `loader()` via `loader()` passing an async frame of itself to `read()`, causing `loader()` to have already returned. The `try loader(...)` call then unwraps essentially down to `try await async loader(...)`, and you get your error as expected.

**Comment by zenith391** [comment]
Couldn't reproduce the bug.

**Comment by g-shon** [comment]
getting the same error: `thread 118800 panic: resumed an async function which already returned` when running the following code:

    const bcrypt = std.crypto.pwhash.bcrypt;
    var salt: [bcrypt.hash_length]u8 = undefined;
    std.crypto.random.bytes(&salt); //(issue here!!!!!)
