### ISSUE TITLE
translate-c creates extern enum(c_int) with values that don't fit in c_int

### ISSUE THREAD

**Issue by xackus** [ziglang/zig#8003]
```c
enum DXGI_FORMAT {
    DXGI_FORMAT_FORCE_UINT = 0xffffffff
};
```
```zig
// -target x86_64-windows-gnu
// error: integer value 4294967295 cannot be coerced to type 'c_int'
pub const enum_DXGI_FORMAT = extern enum(c_int) {
    _FORCE_UINT = 4294967295,
    _,
};

// -target x86_64-windows-msvc
pub const enum_DXGI_FORMAT = extern enum(c_int) {
    _FORCE_UINT = -1,
    _,
};
```
If I increase the value so that it doesn't fit in a `u32`:
```zig
// -target x86_64-windows-gnu
pub const enum_DXGI_FORMAT = extern enum(c_ulonglong) {
    _FORCE_UINT = 68719476735,
    _,
};

// -target x86_64-windows-msvc
pub const enum_DXGI_FORMAT = extern enum(c_int) {
    _FORCE_UINT = -1,
    _,
};
```
Looks like clang is bug-compatible with MSVC?
https://developercommunity.visualstudio.com/content/problem/490264/standard-violation-enum-underlying-type-cannot-rep.html

**Comment by xackus** [comment]
The problem is here:
https://github.com/ziglang/zig/blob/a5cb4ab95e80c4f75356b80251c3628811956b19/src/translate_c.zig#L906-L922
But if I change it to `if (int_type.ptr != null)`, some casts in `test-run-translated-c` fail.
If different compilers emit different types, perhaps another helper function is needed.

**Comment by Einh06** [comment]
I just hit this issue on macOS trying to use the `AudioToolbox` framework, specifically the `AudioQueue` API, using `zig version 0.7.1`. 
Here is a small code snippet that reproduce the issue:
```zig
// built with: 
//zig build-exe src/main.zig -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/ -framework AudioToolbox -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
const std = @import("std");
const atb = @cImport({
    @cInclude("AudioToolbox/AudioToolbox.h");
});

fn main() anyerror!void {
    const should_fail = atb.kLinearPCMFormatFlagsAreAllClear;
}
```
Trying to compile that generate `integer value 2147483648 cannot be coerced to type 'c_int'`.
It's pretty clear that the API author meant `0x80000000` (`FlagsAreAllClear`, but isn't 0).

I wonder if a fix to that issue should be to use the hex value of the constants, rather than its decimal representation. This should generate a valid value regardless if the API author meant to represent a hex value, bit field or a number constant.
