### ISSUE TITLE
Bind `try` keyword as higher precedence

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#8067]
There are a few cases where Zig doesn't match my intuition because `try` is too low of precendence:

```zig
if (try foo == bar) {}
if ((try foo) == bar) {} // I meant this
if (try (foo == bar)) {} // Zig uses this

const baz = try foo orelse return bar;
const baz = (try foo) orelse return bar; // I meant this
const baz = try (foo orelse return bar); // Zig uses this
```

I'm not quite clear on the rules as [precedence table](https://ziglang.org/documentation/master/#Precedence) does not include `try`.

**Comment by Mouvedia** [comment]
Can `foo $operator bar` throw?

**Comment by Vexu** [comment]
This has been previously rejected in #5436 and #2138.

**Comment by raulgrell** [comment]
For quick reference, Vexu is referring to the decision:

> andrewrk:
> We have an accepted proposal for this already, which is to require parentheses to disambiguate: #114

**Comment by batiati** [comment]
The main issue I see on status-quo `try` is the fact it has the opposite precedence of `catch`, which seems non-intuitive.

```zig
// tries the firstFunc
try firstFunc().secondFunc();

// catches the secondFunc
firstFunc().secondFunc() catch |err| {...}
```

I like `try` because it is very explicit and visible when reading code, but I would prefer to have a unwrap operator, acting just like `try`, but without margin for precedence ambiguity. I suppose the `.!` operator:

```zig
firstFunc().!.secondFunc().!;

//equivalent of
try (try firstFunc()).secondFunc();
```

It would be particularly useful when writing fluent APIs,

```zig
var ret = firstFunc().!.secondFunc().!andThen().!;
``` 

The possibility of catching together groups of errors would be nice too:

```zig

//something like that
var ret = (firstFunc().!.secondFunc().!.andThen().!) catch |err| {...};

//status-quo zig
var ret1 = firstFunc() catch |e1| { ... }
var ret2 = ret1.secondFunc() catch |e2| { ... }
var ret3 = ret2.andThen() catch |e3| { ... }

//this only catches the last function call
var ret = (
(try (try firstFunc()).secondFunc()).andThen()
) catch |err| { ... }

``` 

Cheers!

**Comment by raulgrell** [comment]
Also for reference, the `.!` used to be part of the language as the error unwrap operator just like the current `.?` operator for nulls. It was removed in favor of the more verbose `catch unreachable` as a way to disincentivize its use since although it's good to make ignoring errors ergonomic, it would be overused if it's trivial.

Making it act like try, returning the error for the current function, would go against having all control flow handled by keywords which is one of Zig's design principles.

The grouping issue makes it hard to know which function resulted in an error, which is one of the problems with exception handling in many other languages. When refactoring to allow handling each of the functions properly, setting appropriate defers and errdefers between calls, after all the shuffling around of catch blocks and intermediate variables you'd end up with something like status quo Zig anyway.

**Comment by batiati** [comment]
@raulgrell considering `maybe_null.?` is similar to `maybeError() catch unreachable`, I totally agree, it must be more verbose and not too easy to ignore errors.

I suggested `maybeError().!` can behave just like `try maybeError()` does, bubbling up the error, and therefore preserving Zig's current design, with the benefit of the obvious precedence of the `.!` operator (just like it is in Rust's `.?` operator)

For grouping errors, I imagine it could behave exactly the way it is for `fn`, but in a `block` scope:

```zig
fn maybeError() !void {
    try canFault1();
    try canFault2();
}

fn caller() void {
    // I don't care if it was from canFault1 or canFault2
    maybeError() catch |err| { .... }
}
// catching errors together in the same way, but without a function
fn proposal() void {
    {
       try canFault1();
       try canFault2();
    } catch |err| { ... }
}


```

**Comment by YohananDiamond** [comment]
I have a suggestion to introduce a new keyword operator, `andthen`, which could be used  as `<expr1> andthen [capture] <expr2>`.
```zig
// Let's suppose we have `funcN` as a function with signature `fn(i32) error{N}!i32`, and it returns `error.N`.
// Let that be true for funcA-funcZ.
fn funcN() error{N}!i32 {
    return error.N;
}

const result: error{A, B}!i32 = funcA() andthen |x| funcB(x);
std.testing.expect(result == error.A);

// for this one to work `andthen` should have a higher or the same precedence as `catch` (not sure).
const result: error{A, B, C}!i32 = funcA() andthen |x| funcB(x) andthen |x| funcC(x);
std.testing.expect(result == error.A);
```

With this addition, the code @batiati previously suggested could be rewritten as this:
```zig
// @batiati's old suggestion:
var ret = (firstFunc().!.secondFunc().!.andThen().!) catch |err| {...};

// my suggestion:
var ret = firstFunc() andthen |x| x.secondFunc() andthen |x| x.andThen() catch |err| { ... };
```

Not only that, but we can even extend the usage of `andthen` so it can be also used in optional types, although I don't know if they would be very useful here:
```zig
const value: ?i32 = null;
const result: ?i64 = value andthen |x| fallibleNumberOperation(x) andthen |x| x * 2;
std.testing.expect(result == null);
```

There's also https://github.com/ziglang/zig/issues/5610, though I think this suggestion of mine is better when working with function/method chaining:
```zig
// Attempt one with block-local error handling
blk: {
    // Since we can't shadow variable declarations, we'll have to create a variable for each attempt.
    const v = try :blk getValue();
    const v2 = try :blk v.doSomethingWithValue();
    break :blk v2.doYetAnotherThingWithValue(); // you could also accidentally pass `v` here if the method name is the same
}

// Attempt two with block-local error handling
blk: {
    break :blk (try (try :blk getValue()).doSomethingWithValue()).doYetAnotherThingWithValue();
}

// Using andthen to clean things up
// The two lines below are equivalent. Because of that, you can use the same |v| capture without causing shadowing issues.
getValue() andthen |v| v.doSomethingWithValue() andthen |v| v.doYetAnotherThingWithValue();
(getValue() andthen |v| v.doSomethingWithValue()) andthen |v| v.doYetAnotherThingWithValue();
```

**Comment by matu3ba** [comment]
> I'm not quite clear on the rules as [precedence table](https://ziglang.org/documentation/master/#Precedence) does not include `try`.

If the spec is not wrong, look here: https://github.com/ziglang/zig-spec/blob/4e4c1a9c27707996e39206830c842639e916307d/grammar/grammar.y#L283

cc @SpexGuy Is there some enforced order of the prefix keywords? The prefix keywords dont look like there must be an order ie that the first word must be a try (and subsequent words must not be a try).

**Comment by batiati** [comment]
I still thinking about it, and I realized that maybe it is not a precedence matter ...

Considering:

```zig
pub Something = struct {

	const Self = @This();
	
	fn maybeError(self: *Self) anyerror!*Self {
		//...
		return self;
	}

	fn noError(self: *Self) *Self {
		//...
		return self;
	}
}
```

Since we cannot do that:
```zig
var something = Something {};

//compiler error here, makes no sense to try "noError"
_ = try something.noError();
```

And we cannot do that either:
```zig
var something = Something {};

//compiler error here, no function "noError" found in an ErrorUnion
_ = something.maybeError().noError();
```

We naturally expect the compiler to try the only possible ErrorUnion:
```zig
var something = Something {};

//just one possible error, should be OK
_ = try something.maybeError().noError();

//just one possible error, should be OK too
_ = try something.noError().maybeError();


//compiler error, no function "maybeError" found in an ErrorUnion
_ = try something.maybeError().maybeError();

```

Extending this to the problem of fluent APIs, there is a way to introduce a syntax-sugar operator, still having all control flow handled by keywords.
Introducing the `.!` operator not as `try` replacement, but as an "error-propagation" operator, could it work like that:

```zig
var something = Something {};

//status quo, OK
_ = try something.maybeError();
_ = something.maybeError() catch |err| { ... }

//The error propagation .! operator should be allowed only in "try" or "catch" expressions

//Try the first and second calls
_ = try something.maybeError().!.maybeError();

//Catches the first and second calls
_ = something.maybeError().!.maybeError() catch |err| { ... };

//Wrong usage
_ = something.maybeError().!; //Wrong
_ = try something.maybeError().!; //Wrong
_ = something.maybeError().! catch |err| { ... }; //Wrong

```

**Comment by matu3ba** [comment]
>  Introducing the !. operator not as try replacement, but as an "error-propagation" operator, could it work like that:

That looks very easy to miss, because !. are hard to read. 
Piping commands together is also counter-intuitive for understand the control-flow of the program.

For shells one uses at least `command1 | command2`, if one uses best practices.

**Comment by YohananDiamond** [comment]
@matu3ba:

> Piping commands together is also counter-intuitive for understand the control-flow of the program.
> For shells one uses at least `command1 | command2`, if one uses best practices.

Could you elaborate on this please? I don't understand what would be counter-intuitive about it.

*Sorry for taking so much time to respond, I didn't understand if you mentioned my suggestion ^^'*

**Comment by nkoturovic** [comment]
**I would like to step back a little bit and make slight digression**

- To me chaining functions is very modern and **expressive** way of writing code, which makes it easier to write, read and understand programs.
- Many languages encourage and transition to this kind of patterns:
    -  `Rust`: (`Option<T>`, `Result<O,E>`, `Iterators`, `UFCS`, ...)
    -  `C++20` (`std::optional`, `std::expected<T,E>`, `Ranges`, ...),
    - `Haskell` (`Functions`, `>>=  Monads(Maybe<T>, Either<T,E>)`, ...)
    - `Nim` (`UFCS`, ...)
    -  `Bash` `Pipe operator`
 

**General idea**

So there are numerous places where this patterns could be applied to. It comes from functional realm, and it's ultimately way of **composing and evaluating functions** in  way that reduces boilerplate code.

In majority of listed use cases, Option, Errors, Containers, ... It ultimately unfolds to generalization called `Monads`.
I will not be another guy trying to explain `Monads` 😅, but it might be useful to tackle this problem from wider **Monadic perspective** (Just sayn 🤠).

### Narrowing scope (Error handling)
**How I imagine `Rust` did it**: 🦀 
- Okay so here are all of these normies that like `Exceptions` and `std::begin`, `std::end`
- Okay so here are all of these Functional fellows with their crazy revolutionary ideas.   
- Let's try to find solution in the middle that works best for us.

```rust
trait SafeOps: Sized {
    fn safe_div(self, other: Self) -> Result<Self, String>;
}

impl SafeOps for i32 {
    fn safe_div(self, other: Self) -> Result<Self, String> {
        if other == 0 { Err(String::from("Division by zero")) }
        else { Ok(self / other) }
    }
}

fn calc() -> Result<i32, String> {
    8.safe_div(2)?.safe_div(0)?.safe_div(1)
}

fn main() {
    match calc() {
        Err(msg) => println!("Err occured: {}", msg),
        Ok(result) => println!("Result is: {}", result)
    }
}
```

### My personal opinions (Not Zig expert)

**👍 I think I like:**
- **try** only in terms of visual pattern matching
- **?/! operator** like in **Rust** example with some kind of chaining (ex. UFCS, Pipe operator such as: ( `|`, `>>=`, `>>`, `|>`, ...) but it would be nicer to somehow use `.` like **Rust** is. But also maybe not overcomplicate it with UFCS feature.

**👎 I think i dont like:**
- **orelse**: I personally am not fan of introducing **orelse** operator. It's also common to introduce `member` function `.orElse` for `Result/Error` type for this simple task.
- **try operator**: Maybe try could also be method on `Result/Error` type too instead of being operator.

**🤝 Neutral about:**
- **.andThen()** member function like in this `c++` library: [Expected](https://github.com/TartanLlama/expected)  this would require us to pass function (not call them on the spot). 
- **(|>)** Function application operator (like in `Elm`), or proposed to `C++`[ pipeline rewrite operator  ](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2011r0.html) 
  
**🤔 Final opinion and further considerations:**

- I think there is thirst for **simplifying** some aspects of **error handling**, or at least slightly modifying `Result/Error` type API. 
- We should consider `Chain` or `Not to Chain`, and translate that to other language features - (Chain container transformations like (`container.filter(isPositive).map(sqrt)`), 
- Maybe or not chain normal functions, compose them etc ...
- How to achieve it, what we should and we should not do?

**Comment by alexrp** [comment]
For what it's worth, I come from the C# world where prefix keyword operators work as in this proposal, i.e. [this](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xArANwX4DMdhNAwjQN4UaQuh3oA2OgA46EgLLQYACgCU/QcI0A3CMhoIIAZwDWNALwyAdACV0ilWYB8lgGLIA9mCsBTA6gA2CIoALITKyizkGhrqUTRQAGY0ivgAnHqGJqbmIcoxscL0KYoARAg+CMXheQC+FNVAA) is valid.

So I expected to be able to write code like this:

```zig
        if (try reader.readInt(u16) != dos_signature)
            return error.InvalidDosSignature;
```

Only to then discover that I needed to put parentheses around the left-hand side of the `!=` operator. I think that's a little unfortunate. My background might be coloring my perspective here, but I have a hard time imagining anyone finding this bit of code (without parentheses) ambiguous.

**Comment by andrewrk** [comment]
https://github.com/ziglang/zig/issues/8067#issuecomment-786012195

:point_up:
