### ISSUE TITLE
Feature request: slicing with negative numbers like python. 

### ISSUE THREAD

**Issue by glyh** [ziglang/zig#8154]
It's frequent that when you have to access the tail elements of some slices. 

In zig, I first get the len of the array, and then access the calculated address, which is not convenient. 

Are there other approaches? If not, I think it would be handy if we add slices like python.

**Comment by mrakh** [comment]
Such a feature would require extra instructions to be emitted to check whether the index value is negative every time an array is indexed with a runtime-known signed integer, which brings with it a potential performance penalty, especially on architectures that have poor or no support for conditionally executed instructions. If you wish to emulate it, you can always write a function that does it for you.

**Comment by g-w1** [comment]
I do not think this feature is necessary, but @mrakh this wouldn't be the case either. The compiler would just turn arr[-1] into arr[arr.len - 1].

**Comment by mrakh** [comment]
> I do not think this feature is necessary, but @mrakh this wouldn't be the case either. The compiler would just turn arr[-1] into arr[arr.len - 1].

That is only possible because the index is comptime known.

**Comment by SpexGuy** [comment]
The current behavior is by design.  There is no way to distinguish in the language between `arr[-1]` and `arr[i]` where `i` is `comptime_int`.  Allowing this would mean that code where the index underflows and becomes negative compiles but creates a runtime bug, instead of being a compile error.  Similarly if we allow it with runtime integers, it changes checked UB into unchecked bugs (and added perf cost).

Because of this, the way to access tail elements in Zig is `arr[arr.len-1]`.  If this is inconvenient, you could use these functions to make it easier:
```zig
fn indexFromEnd(slice: anytype, from_end: usize) std.meta.Child(@TypeOf(slice)) {
    return slice[slice.len - from_end];
}

fn pyIndex(slice: anytype, index: isize) std.meta.Child(@TypeOf(slice)) {
    return if (index < 0) slice[slice.len +% @bitCast(usize, index)] else slice[index];
}

fn pySlice(slice: anytype, from: isize, to: isize) []std.meta.Child(@TypeOf(slice)) {
    const actual_from: usize = if (from < 0) slice.len +% @bitCast(usize, from) else from;
    const actual_to: usize = if (to < 0) slice.len +% @bitCast(usize, to) else to;
    return slice[actual_from..actual_to];
}
```

**Comment by daurnimator** [comment]
> The current behavior is by design. There is no way to distinguish in the language between `arr[-1]` and `arr[i]` where `i` is `comptime_int`.

Huh? why would you need to distinguish? Indexing becomes: `arr[if (i>=0) i else arr.len + i]`. 

>  Allowing this would mean that code where the index underflows and becomes negative compiles but creates a runtime bug, instead of being a compile error.

well yeah: if `arr.len` is only runtime known, but `i` is comptime known, then we may only get a runtime `index out of bounds` panic/UB. But that's no different to if the user wrote `if (i>=0) i else arr.len + i` themselves.

>  Similarly if we allow it with runtime integers, it changes checked UB into unchecked bugs (and added perf cost).

I still fail to see the issue: there would be the same out-of-bounds checks.
And there would be no perf cost for the usual case of `arr[i]` where `i` is unsigned.

**Comment by Tetralux** [comment]
> And there would be no perf cost for the usual case of arr[i] where i is unsigned.

Just for clarity: your thinking is that if the type of the index is unsigned, then it's as it is today - but if it's signed, then it does  
`arr[if(i>=0) i else arr.len + i]` ?

**Comment by daurnimator** [comment]
> Just for clarity: your thinking is that if the type of the index is unsigned, then it's as it is today - but if it's signed, then it does
> `arr[if(i>=0) i else arr.len + i]` ?

Yes. with the overflow check and bounds checking that would occur if written like that.

**Comment by SpexGuy** [comment]
> I still fail to see the issue

This is an example of the footgun:
```zig
var base: isize = ...;
var offsets: []const isize = ...;
for (offsets) |offset| {
    values[base + offset] = 0;
}
```
Here it is a bug for `base + offset` to be negative.  But with this proposed behavior, instead of getting a nice helpful panic, you overwrite the wrong index on the other end of the array and the program keeps running, only to maybe crash later because of the bug, or maybe just produce incorrect output.  To get the correct version, you need to intCast the result to `usize`  The easy way to write this code is no longer the maintainable way.  Therefore this sugar is not merited.

Additionally, this takes something which is known statically (whether an index is relative to the front or back of the array), and turns it into runtime state.  This is against the whole design of the language, which tries to bake as many invariants as it can into static state.

A proposal for a separate operator which indexes from the back of the array might make sense.  But I'm very confident that changing the default behavior of array indexing like this is not on the table.
