### ISSUE TITLE
zig fmt mis-formats arrays with const/volatile

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#8161]
This is invalid code, but:
```zig
const x = [0]const u8;
```
becomes
```zig
const x = [0constu8;
```

**Comment by ifreund** [comment]
We can make this fail to parse with a grammar change, so I think that would be the proper solution: https://github.com/ziglang/zig-spec/pull/28

**Comment by Vexu** [comment]
We explicitly decided to allow `*:0 u8` in the parser in #5146 so we should also allow qualifiers on arrays.

**Comment by ifreund** [comment]
The decision there seems motivated by wanting to provide a better error message, which is very possible in the parser by simply checking explicitly for pointer modifiers before parsing the array child type so that a context aware error message can be provided.  The question then becomes whether this is the right place to put this code or not, I'll defer to you and @andrewrk on that decision.

I think if this approach is the one we want to take, there are several other cases where the grammar could be relaxed and simplified by moving more of the burden to semantic analysis.

**Comment by andrewrk** [comment]
Indeed the decision is motivated by providing a better error message. If such a better error message is possible to implement in the parser, as you suggest, then I agree that is the best approach.

**Comment by ifreund** [comment]
Updated the PR, I think the new error message is as good as any we could provide during semantic analysis:
```
/tmp/foo.zig:1:14: error: pointer modifier 'const' not allowed on array child type
const x = [0]const u8;
             ~~~~~
```
