### ISSUE TITLE
Proposal: Remove function aliasing and user named namespaces

### ISSUE THREAD

**Issue by kruseborn** [ziglang/zig#8182]
**Namespaces**

This proposal is related to the topic of namespaces in C++ which Titus Winter talks about in this talk at **20:50**:
https://youtu.be/xu7q8dGvuwk

_"Can I tell what this function does when I am encountering it in code, and I am not familiar with that function"
"I don't care how it looks in the header, I care how it looks when you are reading it and you are unfamiliar with it"_

Let's say we have two files with the function `open_connection(...)`;
`tcp.zig`: `open_connection`
`udp.zig`: `open_connection`

The author of the files has the intention that the user will import these files with the namespace `tcp `and `udp`.
```
const tcp = @import("tcp.zig");
const udp = @import("udp.zig");
...
tcp.open_connection(...);
```

If this was the case, it would be easy to understand the context which `tcp.open_connection` is referring to. 
You can also do a full search for the name `tcp.open_connection` and you will find all occurrences in the project.

However, Zig gives you the possibility to choose a namespace name separately for each include. For example:
```
const t = @import("tcp.zig");
const u = @import("udp.zig");
...
t.open_connection(...);
```

Now when you are reading` t.open_connection(...);` you have less context of what the `open_connection `refers to, and you have to scroll up to see what `t` is referring to. You can no longer do a full project search to find all occurrences because each file may have a different namespace name for each include.

**Function aliasing**

The same problem occurs with function aliasing. Let's say instead of the function `open_connection`, you have a better and a unique name `open_tcp_connection`. Now the user will have better context when reading it and it is easier to search for. But then in Zig the user is allowed to do an alias for that function:

```
const open = @import("tcp.zig").open_tcp_connection;
...
open(...);
```

The same problem as with namespaces appears. No context and no ability to do a global search for the function.

In C, we do not have this problem because there is no such thing as a namespace. Instead, you can get function name collision.
In C++, it has namespaces, but it also has nested namespaces and the possibility to include the namespace in the current scope, which removes the context and you will have the same problem as in Zig.

**Proposal:**
1. Remove the ability to alias a function
2. Let the author of the file decide the namespace name, but do **not** allow nested namespaces, and do **not** allow to include the namespace in the current scope

**Comment by daurnimator** [comment]
>  You can no longer do a full project search to find all occurrences because each file may have a different namespace name for each include.

Runtime dispatch can occur too: there is no assurance that there isn't a pointer out there also pointing at a given function.

**Comment by kruseborn** [comment]
> > You can no longer do a full project search to find all occurrences because each file may have a different namespace name for each include.
> 
> Runtime dispatch can occur too: there is no assurance that there isn't a pointer out there also pointing at a given function.

Yes, that is a possibility, but my guess is that it will not be as common as aliasing a function or using different namespace names in different files.

**Comment by haxorgrill** [comment]
Good proposal. If we would define different names for a namespace in every single file, readability and searchability would suffer. The same goes for function aliasing. It would add unnecessary complexity and be especially damaging in large codebases such as the one I work in (a game engine).

**Comment by MasterQ32** [comment]
I can not see how that should work in a language that is as dynamic as zig.

What about anonymous functions? Anonymous namespaces? How should that work? Can you explain how this code example should be possible with this proposal:

```zig
fn foo() void {
    const sortSymbol = struct {
        fn lt(ctx: void, a: Symbol, b: Symbol) bool {
            return a.index < b.index;
        }
    }.lt;

    std.sort(my_list, {}, sortSymbol);
}
```

Another problem is see:
What is the inherent name of a namespace in zig? There is none, and we cannot use the file name as those might alias:
```zig
const network_a = @import("foo/network.zig");
const network_b = @import("bar/network.zig");
```

are both namespaces named `network`? What about my `network` package then? 

In my opinion, this issue introduces more aliasing problems than it solves. It's a huge benefit that we can name our scopes per file instead of "one global name" as this solves the problem of ambiguitiy very well.

All languages i know suffer from this problem. C# can import two DLLs into the same namespace. C/C++ is completly unusable when two libraries export the same symbol name or use the same include guard.

Zig solves this by moving the problem from global space (huge) to file space (very small) and i am convinced that the status quo is the right thing. Everything has drawbacks, but the problem outlined here can be solved by tooling whereas symbol conflicts cannot be solved by that.

**Comment by kruseborn** [comment]
My proposal was mostly to start a discussion about the topic. I agree that C++'s way of solving it by adding all namespaces to the global scope is not a good solution.
And being able to solve symbol conflicts with file scope is very good. However, looking for a function name is a very common operation, and it would be nice to find a solution where tooling will not be the only way to solve it. 

Something that could help with this is to only use file scope when you have a conflict. The normal case would be to write
`@import("foo/network.zig");` Then the author of the file will not expect a namespace. There are already zig libraries that assume what the namespace name will be. 
For example https://github.com/Snektron/vulkan-zig, has removed all vk prefix from the vulkan functions because it expects the namespace to be vk.

**Comment by MasterQ32** [comment]
> For example https://github.com/Snektron/vulkan-zig, has removed all vk prefix from the vulkan functions because it expects the namespace to be vk.

I don't think it's a very strong argument. I assume @Snektron removed the prefix because it's unnecessary. That prefix is a hack around that said global namespace of C and is not necessary at all in zig. If i now use `vulkan.createInstance` or `vk.createInstance` is my decision. Forcing me to type a unnecessy `vk` is worse, especially on readability as it conveys no information

> And being able to solve symbol conflicts with file scope is very good. However, looking for a function name is a very common operation, and it would be nice to find a solution where tooling will not be the only way to solve it.

I have used this already quite extensively to improve APIs. Consider this: `opengl.Shader.glCreateShader` vs. `opengl.Shader.create`. They are the *same* function, but i don't want to encode redundant information in function names that are provided by scope. But i don't think it's common that people randomly rename functions for improved convenience

**Comment by kruseborn** [comment]
But the problem is that you don't know what the scope is going to be. If you are expecting a specific scoped name, you may remove important information. If someone is writing, and probably will do, the context is lost. 
```
const create = @import("opengl").Shader.create;
...
create(...);
```
It's the same as in C++. You are expecting someone to use the namespace, but then someone does: `using namespace ...;` And you end up with _C++ best practices_ to tell developers to not use a specific feature, a feature that should not be there in the first place.

**Comment by MasterQ32** [comment]
> But the problem is that you don't know what the scope is going to be. If you are expecting a specific scoped name, you may remove important information. If someone is writing, and probably will do, the context is lost.
> 
> ```
> const create = @import("opengl").Shader.create;
> ...
> create(...);
> ```
> 
> It's the same as in C++. You are expecting someone to use the namespace, but then someone does: `using namespace ...;` And you end up with _C++ best practices_ to tell developers to not use a specific feature, a feature that should not be there in the first place.

I'm totally okay with that. Zig is there to liberate the user from working around certain things and if it makes the code better if a global function `create` exists, i'm totally fine with that. Luckily, nearly nobody uses `usingnamespace` in zig except for some *explicit* module merging.

I see the status quo as a strength of zig, not as a weakness. It allows me to write the code i intent, not the workaround to express what i intent

**Comment by SpexGuy** [comment]
Huh, I was just thinking about something like this yesterday.  I don't think it's the language's job to prevent you from renaming modules/functions, but I do think it would be nice to have something that encourages using the original name for things.

**Comment by Snektron** [comment]
> For example https://github.com/Snektron/vulkan-zig, has removed all vk prefix from the vulkan functions because it expects the namespace to be vk.

My primary reason for removing the namespace is so that there is only one namespace - the Zig one - instead of both a Zig and a C namespace. The other option would have been to keep the C namespace and require the user to perform `usingnamespace @import("vk.zig");` to deduplicate that namespace. In this scenario, and in the proposed change, it would be very hard to keep track of in which file a certain function is defined (with the status quo, one can simply look up where the namespace is assigned). This is my main concern with this proposal.

My other concern is related to nested namespaces. I think there are plenty of situations where that is required, and this proposal would either force me to write overly long namespaces or merge them all into one top-level namespace. Furthermore, i think that requiring absolute everywhere (i'm not sure if this proposal entails that) is quite inconsistent: If i'm writing code in some namespace X, then its against the common scoping rules that i would need to address X again when referencing some entity in that same namespace, even if its in a sub- or super namespace.

For myself, i consider `const thing = @import("thing.zig");` clear enough to make up what namespace refers to what, even if `thing` is not the "intended namespace" for such a module.

**Comment by kruseborn** [comment]
> Huh, I was just thinking about something like this yesterday. I don't think it's the language's job to prevent you from renaming modules/functions, but I do think it would be nice to have something that encourages using the original name for things.

Maybe a Zig linter would be a good fit for that. Most people are lazy when they code and I see it as a common pattern that people will use short alias for long functions, not thinking about the consequences(readability/context in the future)

> For myself, i consider const thing = @import("thing.zig"); clear enough to make up what namespace refers to what, even if thing is not the "intended namespace" for such a module.

I agree, but if each file has a different namespace, searching for it will be harder, but maybe as discussed above, it can be solved with tooling. The other topic of nested namespaces is not bad per se, but in C++ it's common to include nested namespaces in the scope, and later when you read the function, you have no context.
