### ISSUE TITLE
[Proposal] Introduce optional types as a valid switch argument

### ISSUE THREAD

**Issue by batiati** [ziglang/zig#8186]
### Proposal

Introduce optional types as a valid `switch` argument.

```zig

// arg is an optional type, and null means "follow the parent orientation" for example
fn setOrientation(arg: ?Orientation) void {

      // allow switch over arg without unwrapping it
      switch (arg) {
          .Horizontal => ...
          .Vertical => ...
          // An exhaustive switch must handle all values plus the null option
          null => ...
      }
}

// arg is an optional type and null must be handled together with other values
fn checkPermissions(arg: ?Clearance) void {

      switch (arg) {
          .Allowed => ...
         // handle null and non-null values in the same block
          .Revoked, null => ... 
      }
}

// works with any type allowed in switch statements
fn setValue(arg: ?u32) void {

      switch (arg) {
          0 => ...
          1 => ...
          // Else can handle null values in non-exhaustives types
          else => ...
      }
}
```

### Motivation

As `null` can be a meaningful value, makes sense to handle its value in the same `switch` statement.
It improves the code readability and avoids related logic to be split across different control flows.

```zig
// same example in Zig status quo
fn setOrientation(arg: ?Orientation) void {

      if (arg) |non_null| {
            switch (non_null) {
                .Horizontal => ...
                .Vertical => ...
            }
      } else {
          // handles null here
      }
```

### Workarround

For enums, define a `None` option instead of `?` to representing the `null` value

**Comment by marler8997** [comment]
To be more fair, I think the following 2 would be the equivalent:

```zig
    // CURRENT SYNTAX:
    if (arg) |a| switch (a) {
        .Horizontal => ...
        .Vertical => ...
    } else {
        ...
    }

    // NEW SYNTAX:
    switch (a) {
        .Horizontal => ...
        .Vertical => ...
        null => ...
    }
```

One thing I didn't see explained was whan happens with optional exhaustive enums?  Does else handle both null and unspecified values in that case?

Also what about a double optional `??T`?  Would the `else` case handle both `null` and `null null`? Or maybe a double optional wouldn't be supported?

The other issue is this adds support for 2 different ways of accomplishing the same thing.  We'll have the current syntax and now another syntax.  Unless we come up with some way to remove the old syntax?  But I don't think that will work since not all optional values can be used inside a switch.  Or maybe an idea is we don't allow "switchable" values to use the `if (opt) |val| ...` syntax?

**Comment by Vexu** [comment]
Rejected in #1545.
