### ISSUE TITLE
std.debug.panic should respect root.panic

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#8214]
Right now the panic dependency graph is as follows:
![image](https://user-images.githubusercontent.com/219422/110859470-159dfe80-8281-11eb-8529-c9236810d110.png)

`std.debug.panic()` _**ignores**_ the overridden root panic handler and always calls `os.abort()`

### Thoughts on a fix:
1. Point `std.debug.panic` to `builtin.panic`
    - can we update `panic()` args to match format string?
    - or is there a nice workaround to convert the arguments?
2. Make panicExtra less of a footgun
    - either change the body so it only dumps the data (e.g. reusable in a custom panic handler)
    - or update the function name to indicate it's going to os.abort

**Comment by rgreenblatt** [comment]
I posted an idea related to this on discord.  Here is my (slightly updated) post:

> One annoyance (at least for me) right now is that approach to overriding panic and stack trace printing isn't very straighforward, particularly for freestanding.
> 
> You can override `panic` easily, but in order to get an implementation of `panicExtra` on freestanding you need:
>  - `openSelfDebugInfo`. 
>  - `isatty`
>  - `stderr` (which implies file descriptors, at least fake ones to just support `stderr`)
>  - probably some other stuff I am missing
> 
> There is an implementation of `format` for the builtin `StackTrace` type which can't be overriden directly, and you need all of the same implementations from panicExtra (other than `stderr`) to use it (they both end up calling `std.debug.writeStackTrace`).
> 
> `GeneralPurposeAllocator` (which is _supppppper_ nice btw) uses the format implemention of `StackTrace`, so using that allocater requires all of the previously mentioned implementations.
> The functions in `std.testing` use `std.debug.panic`, so they also require the same (when doing integeration/runtime testing).
> 
> 
> My purposed simplification would be something like the following:
>  - `panicExtra` should use a writer returned by `getDebugWriter` (name in flux) which can be overriden.
>  - you can override a mapping from addresses to symbols (name/impl in flux)
>  - you can override printLineFromFileAnyOs
> 
> With these changes, all that you would have to implement to get access to `testing`, `GeneralPurposeAllocator`, and `panicExtra` would be `getDebugWriter`, the mapping from address to symbols, `printLineFromFileAnyOs`,  and `os.abort`

I am drafting this right now. 

It seems to me like there are multiple different types of things you might want to override with `panic`:
 - the writer (handled by above idea)
 - symbols (handled by above idea)
 - how file lines are printed (handled by above idea)
 - how actual termination is done (`os.abort` can be overriden, but this is gross for non-freestanding. Maybe `debugTerminate` should be called which calls `os.abort()` by default and can be overriden)
 - how lines from files are printed in the stack traces
 - other details about how printing is done

I thought a bit about a data dumping approach. One minor issue is that most of the stack trace dumping functions iterate over the stack trace, so collecting it would be a bit grosser and require memory allocation which isn't actually neccessary (this might result in a higher likelyhood of additional failures if the panic is due to OOM). It would be possible to use an iterator passing approach, but zig doesn't have a nice paradigm for this. I will link my PR when it is up.

**Comment by rgreenblatt** [comment]
I believe https://github.com/ziglang/zig/pull/8228 resolves this issue. As far as the approach used see here https://github.com/ziglang/zig/pull/8228#issuecomment-803049027.

**Comment by nektro** [comment]
I think this transition would be helped a lot if the custom panic handler signature was changed to the same signature as `panicExtra`.
