### ISSUE TITLE
Writing to a file in comptime

### ISSUE THREAD

**Issue by tatumizer** [ziglang/zig#8272]
I'm trying to generate some glue code for integration with dart via FFI. However, so far my attempts were unsuccessful. I cant' even write to stdout in comptime. Any hint would be appreciated.

**Comment by LemonBoy** [comment]
No I/O is allowed at comptime.

This is a bug tracker, feel free to direct your questions [to one of the many community hubs](https://github.com/ziglang/zig/wiki/Community).

**Comment by g-w1** [comment]
A solution to this would be to generate your bindings at runtime in the `build.zig` and then you can use them in your application.

**Comment by tatumizer** [comment]
Can I somehow pass the string I generate in comptime, to runtime? I use reflection over my zig program to generate bindings written in dart language. Please tell me how to pass the string to runtime - and I will go away!

**Comment by SpexGuy** [comment]
You cannot generate code from a comptime known string, you must write a file and recompile it.  Another method would be to create a main function which generates bindings for an imported package, and link it with your package to produce the bindings generated and write a .zig file.  Have zig build run that program, and then link the result with your package to produce the final library.

Closing this issue since it's not a compiler problem.  Please visit a [community location](https://github.com/ziglang/zig/wiki/Community) like the IRC or Discord for questions like these.
