### ISSUE TITLE
zld: ability to link against shared libraries

### ISSUE THREAD

**Issue by zacwood9** [ziglang/zig#8317]
Trying to setup a SDL project with Zig using macOS 11.2.3. I have SDL installed via Homebrew and a Zig 0.8 master install manually added to my PATH.

When running with `zig build run`, it fails with the error:
```
dyld: lazy symbol binding failed: Symbol not found: _SDL_Init
  Referenced from: /Users/zac/Developer/ZigTest/zig-cache/bin/ZigTest
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _SDL_Init
  Referenced from: /Users/zac/Developer/ZigTest/zig-cache/bin/ZigTest
  Expected in: /usr/lib/libSystem.B.dylib
```

It's worth noting `/usr/lib/libSystem.B.dylib` doesn't even exist.
Another interesting note: `zig build` runs, but does not produce an executable.

I'm including SDL in my program this way:
```zig
const c = @cImport({
    @cInclude("SDL.h");
});
```

My build.zig:

```zig
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    // Standard target options allows the person running `zig build` to choose
    // what target to build for. Here we do not override the defaults, which
    // means any target is allowed, and the default is native. Other options
    // for restricting supported target set are available.
    const target = b.standardTargetOptions(.{});

    // Standard release options allow the person running `zig build` to select
    // between Debug, ReleaseSafe, ReleaseFast, and ReleaseSmall.
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("ZigTest", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);

    exe.addIncludeDir("/usr/local/include/SDL2");
    exe.addLibPath("/usr/local/lib");
    exe.linkSystemLibrary("SDL2");
    exe.linkLibC();

    exe.install();

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}
```

**Comment by dominikbraun** [comment]
Funny because I got pretty much the same setup and faced the same issue today. For me, `curl` does not work:

```zig
// build.zig
// ...

// Manually add the include directory and library path.
exe.addIncludeDir("/usr/local/opt/curl/include");
exe.addLibPath("/usr/local/opt/curl/lib");

// ...
```

Despite specifying the include directory and library path, Zig seems to look for the files in the wrong directory.

```
dyld: lazy symbol binding failed: Symbol not found: _curl_global_init
  Referenced from: /Users/dominik/projects/aligator/todo/zig-cache/bin/todo
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _curl_global_init
  Referenced from: /Users/dominik/projects/aligator/todo/zig-cache/bin/todo
  Expected in: /usr/lib/libSystem.B.dylib
```

I'm on MacOS 11.2.3.

**Comment by holmesmr** [comment]
For the record, it's at least expected that libSystem.dylib is not found as of 11.0 - macOS has removed its system libraries from the filesystem and only looks them up from an immutable linker cache. The main issue here seems to be that the linker is looking up symbols for SDL/Curl in libSystem.dylib - my guess is this is related to recent changes in #8282 as I was able to build and run a zig project linked against SDL on macOS 11.2.3 from a build earlier last week.

**Comment by holmesmr** [comment]
Specifically, the PR and current master commit contains a noted deficiency that linking shared libraries does not currently work on macOS: https://github.com/ziglang/zig/blob/dce612ac2be5aa8a1aa0ee8dd670d7e875624216/test/standalone.zig#L12-L15

**Comment by kubkon** [comment]
Hi @zacwood9! Thanks for submitting an issue. As @holmesmr rightly pointed out, this is due to deficiencies in our in-house linker, and linking shared libraries is on the roadmap of course, but frankly, I just didn't have time to look into it yet (hopefully in a few weeks though!). In the meantime, if you're on the macOS, you can force the system linker, ld64, by setting `ZIG_SYSTEM_LINKER_HACK` variable, e.g.,

```
ZIG_SYSTEM_LINKER_HACK=1 zig build
```

**Comment by slimsag** [comment]
Just wanted to say if it'd be possible to hint at this in an error message whenever external link flags are present:

> In the meantime, if you're on the macOS, you can force the system linker, ld64, by setting ZIG_SYSTEM_LINKER_HACK variable

That would be a HUGE quality of life improvement for new folks trying out HEAD, I wasted ~4h digging into the linker code to try and figure out why something like `exe.linkSystemLibrary("WTF");` didn't make its way to the linker with `--verbose-link` before stumbling across this issue and realizing I was using the new zld 😄

**Comment by kubkon** [comment]
Just an FYI that some (largely preliminary) support for linking against dylibs with `zig ld` landed in #8806. I'm not sure if it's enough for your use case, but it's worth a try. If things are still not working, do please submit a stack trace and the error message!

**Comment by moosichu** [comment]
Hi I don't know how hopeful this is (and I would be happy to share more info) - but I'm using master zig (with zig build) to try and compile & build a C++ project for my macOS device. I'm trying to link against SLD2 & moltenVK - but without the system linker hack I get these issues:

```
warning(zld): unknown filetype for a library: 'VulkanSDK/macOS/macOS/lib/libvulkan.dylib'
warning(zld): unknown filetype for a library: 'VulkanSDK/macOS/macOS/lib/libMoltenVK.dylib'
error(object): common symbol _mach_base_info in /usr/local/Cellar/sdl2/2.0.14_1/lib/libSDL2.a(SDL_systimer.o)
error: UnhandledSymbolType
```

I'm more than happy to provide more info & otherwise assist with debugging this issue (even learning and getting hands-on, but this is well outside of my wheelhouse) - unfortunately my project isn't on GitHub (yet), but I would be happy to share what could be useful from it.

**Comment by kubkon** [comment]
> Hi I don't know how hopeful this is (and I would be happy to share more info) - but I'm using master zig (with zig build) to try and compile & build a C++ project for my macOS device. I'm trying to link against SLD2 & moltenVK - but without the system linker hack I get these issues:
> 
> ```
> warning(zld): unknown filetype for a library: 'VulkanSDK/macOS/macOS/lib/libvulkan.dylib'
> warning(zld): unknown filetype for a library: 'VulkanSDK/macOS/macOS/lib/libMoltenVK.dylib'
> error(object): common symbol _mach_base_info in /usr/local/Cellar/sdl2/2.0.14_1/lib/libSDL2.a(SDL_systimer.o)
> error: UnhandledSymbolType
> ```
> 
> I'm more than happy to provide more info & otherwise assist with debugging this issue (even learning and getting hands-on, but this is well outside of my wheelhouse) - unfortunately my project isn't on GitHub (yet), but I would be happy to share what could be useful from it.

Hi @moosichu, thanks for the report! Is `libvulkan.dylib` and `libMoltenVK.dylib` available somewhere for me to download by any chance? I'd need to inspect the header and load commands within the libraries to work out why `zld` is reporting an unknown filetype. Also, did you try running using the latest zig master?

As far as the error goes however, `zld` doesn't yet know how to handle common symbols. I've now filed a tracking issue for this: https://github.com/ziglang/zig/issues/8945

**Comment by moosichu** [comment]
HI @kubkon thank you for for swift response! Yes, so the dynamic libraries are available here: https://vulkan.lunarg.com/sdk/home#mac Cheers, that's good to know about the tracking issue for common symbols as well. I did check on latest master as of a couple of days ago (when I first posted the issue and a bit after that as well).

**Comment by moosichu** [comment]
@kubkon thank you so much for the quick/swift response oncovering  on all of the issues. I think this is the only remaining error that I get now!
```
warning(zld): unknown filetype for a library: 'libraries/VulkanSDK/macOS/macOS/lib/libvulkan.dylib'
warning(zld): unknown filetype for a library: 'libraries/VulkanSDK/macOS/macOS/lib/libMoltenVK.dylib'
```

If it helps (just to make cross-compilation & dependency mangement easier for myself), I've put together a little repo that has my binary dependencies including the vulkan libs for macOS as well.

https://github.com/moosichu/game-bootstrap

**Comment by moosichu** [comment]
So I've been looking at this function:
```zig
pub fn isDylib(file: fs.File) !bool {
    const header = try file.reader().readStruct(macho.mach_header_64);
    try file.seekTo(0);
    return header.filetype == macho.MH_DYLIB;
}
```

So for both libMoltenVK & libVulkan, the value of filetype.header is 50331648 which maps to 0x3000000 - so something doesn't seem quite correctly formed with these. Having a dig now because it's an interesting problem.

**Comment by kubkon** [comment]
I wonder, have I forgot to rewind the file pointer somewhere and this returns garbage?

**Comment by kubkon** [comment]
Anyhow, just an FYI that I'll be redoing this logic when adding tbd parser to zld.

**Comment by moosichu** [comment]
I've done some further research - and the issue is that these aren't mach-o files, they are universal binaries. 

Having opened them up in a hex-editor they start with the magic number `0xCAFEBABE `, so I think that is the issue. So there's two problems:
- No code seems to currently check that the magic number for the macho-o files is a valid value (& report an appropriate error if so).
- Additionally, the magic number for a universal binary could also be specifically checked-against so that lack of support for them could be properly reported if so. (or support for them could be added).

I could look into helping with this if there isn't already a set plan in place (and it wouldn't interfere with the other work you are doing such as the redoing of this logic).

https://github.com/aidansteele/osx-abi-macho-file-format-reference#universal-binaries-and-32-bit64-bit-powerpc-binaries

**Comment by moosichu** [comment]
I had a quick look at what it might take to support fat arch files - and there does seem to be baked in assumption that there will be one lib per-file (eg. `Dylib.IsDylib` seeking back 0 after completion) - and there's potentially multiple ways to structure a solution. I could probably hack something together (that isn't production ready but a proof-of-concept that is quick 'n dirty) and create a pull-request for that if that would help. Just let me know!

**Comment by kubkon** [comment]
Sounds good @moosichu, feel free to have a stab at this if you want! I'm sure we'll be able to work out a production-ready PR and I'll be more than happy to help with any rebasing if the tbd parser arrives first.

**Comment by moosichu** [comment]
Cheers! OK, I will put something quick & dirty together first that just short-cuts to getting my project correctly compiling & linking with the vulkan libs using zld. I will create a pull request with that proof-of-concept & list the different options for making it something robust so you can see what it looks like and give direction on which options you think would fit best into the zig compiler. 

Just as a heads-up, I might be slow with my turnaround times (just because I have bad experiences burning myself out) - so will be careful to structure things in small bytes & I will make it clear that I'm open to people jumping in and continuing with the PR if I'm being slow.

**Comment by moosichu** [comment]
One thing I'm curious about is that I currently am focused on the case of building _for_ a single arch but being able to link against universal dynamic libraries. Are there any plans to support building universal binaries themselves?

**Comment by kubkon** [comment]
> One thing I'm curious about is that I currently am focused on the case of building _for_ a single arch but being able to link against universal dynamic libraries. Are there any plans to support building universal binaries themselves?

There are, but we're not quite there yet ;-)

**Comment by kubkon** [comment]
Closing as `zig ld` is now able to link against shared library in multiple forms: `.dylib`, `.dylib` (FAT, thanks to @moosichu), `.tbd`.
