### ISSUE TITLE
[std] Comptime and std.testing

### ISSUE THREAD

**Issue by masters3d** [ziglang/zig#8367]
Hi, 

Is a failing test  expected to throw a compiler error when used with comptime? Is  comptime meant to be used with std.testing? I am brand new to zig. 

<img width="857" alt="image" src="https://user-images.githubusercontent.com/6539412/112710749-c65eed00-8e80-11eb-9b86-5ce65b33587e.png">

zig 0.7.0+9af53f8e0
macos bigsur 11.2.3 (20D91)

hello_world.zig
```zig 
 pub fn hello() []const u8 {
    return "Something Else";
}
```

test_hello_world.zig
```zig 
const std = @import("std");
const testing = std.testing;

const hello_world = @import("hello_world.zig");

test "say hi" {
    const expected = "Hello, world!";
    const actual = comptime hello_world.hello();
    comptime testing.expectEqualStrings(expected, actual);
}

```

**Comment by jedisct1** [comment]
Hi,

Yes! `std.testing` can be used at comptime, and quite a few tests in the standard library do, in order to verify that the tested function can actually work at comptime.

And if there is an error, compilation fails because... well... the test is run at comptime.

The stack trace may be a little bit off compared to the same test not run at comptime, though.

**Comment by masters3d** [comment]
Ah okay. “Unable to evaluate constant expression “ was throwing me off. There are other cases where comptime won’t work if there is a @panic in the test harness. 

I naive expectation was that the test would just fail.
