### ISSUE TITLE
Mutating "methods" can't be called on zero sized struct.

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#838]
```
const S = struct {
    fn doC(s: &const S) void {}
    fn do(s: &S) void {}
};

test "" {
    var s = S{};
    S.doC(&s); // works!
    s.doC();   // works!
    S.do(&s);  // works!
    s.do();    // error: expected type '&S', found 'S'
}

```

**Comment by Sahnvour** [comment]
The branch between empty and non empty structs happens at https://github.com/zig-lang/zig/blob/master/src/ir.cpp#L12178 where an empty struct "handle" is not considered a pointer since 7bc0145b802002c38a409dd9fe0b297c8af82391.
We end up with `first_arg` being `S` instead of `&S`.

At this point I'm not sure what the correct fix would be.
