### ISSUE TITLE
LHS of shift must be a fixed-width integer type

### ISSUE THREAD

**Issue by hubiierik** [ziglang/zig#8395]
Hi,

I am encountering an unexpected compile error regarding the left-shift operator '<<'.

The code below shows a situation where I would expect that a literal integer would be automatically coerced into suitable fixed-width integer type.
Instead, I get a compilation error.

zig 0.8.0-dev.1482+6787f163e

Regards,
Erik

```
// Unexpected failure. Expected LHS literal int to automatically be coerced into fixed-width integer type.
fn foo () u64 {
    var p: u6 = 1; // 'var 'is required for use case of interest
    return 1 << p; // error: LHS of shift must be a fixed-width integer type, or RHS must be compile-time known
}
```

```
// Works with workaround.
fn bar () u64 {
    var p: u6 = 1; // 'var' is required for use case of interest
    const one: u64 = 1; // LSH workaround explicitly using fixed-width integer type
    return one << p; // Works
}
```

```
// Complete use case.
fn tTop (t: u64) u64 {
    var top: u64 = 0;
    var p: u6 = 0;

    while (top < t + 1) {
        p += 1;
        top += 1 << p;  // error: LHS of shift must be a fixed-width integer type, or RHS must be compile-time known
    }

    return top;
}
```

**Comment by SpexGuy** [comment]
The behavior you are expecting is described in proposal #6903.  The current workaround is to use `@as` so you don't need to introduce a local variable.  For example, `return @as(u64, 1) << p`.

**Comment by hubiierik** [comment]
@SpexGuy Thank you for the alternative workaround.

**Comment by lemaitre** [comment]
Is there any reason that bit shifts are not defined on comptime int?
As far as I'm aware, comtime int are 2-adic integers, and we can easily define shifts on those.

**Comment by tecanec** [comment]
> Is there any reason that bit shifts are not defined on comptime int?
> As far as I'm aware, comtime int are 2-adic integers, and we can easily define shifts on those.

I haven't heavily investigated the compiler, so I can't give you a definitive answer, but I think that it's because of some ambiguity regarding the returned type. Zig is very strict regarding types, even more so than other "strongly typed" languages, and any ambiguity or uncertainty regarding types, no matter how minor, is a compile error. Bit-shifting an integer of a fixed-width type would return an integer of the same type, but you can't use variable-width integers at runtime. Bitshifting a variable-width integer by a runtime integer is thus impossible.

The `return @as(u64, 1) << p` workaround assigns a fixed-width type to the left operand, which extends to the return type, thereby solving the issue. However, I don't think that the compiler is intelligent enough to confirm the viability of `return @as(u64, 1 << p)` (which is the implication of your first example) or `return @truncate(u64, 1 << p)` (which would otherwise equate to `return @as(u64, 1) << p`).

**Comment by lemaitre** [comment]
Oups, I did not see that `p` was not comptime. Then it makes sense. We could probably argue that `1` could be automatically casted to the same type as `p` in order to make the shift, but I'm not sure it makes sense for a shift.

If you are interested in a comptime `p`, I have written a small explanation thereafter (before realizing the true nature of `p`).

<details>
<summary>Explanation of 2-adic numbers</summary>

> 2-adic numbers are represented by an infinite sequence of binary digits with no decimal point. For instance, 6 is `...[0]110`, -3 is `...[1]00`, where `...[x]` means the pattern `x` is repeated up to infinity. In theory, 2-adic numbers can represent any numbers, not just integers. But if we impose the repeating pattern to be either `0` or `1`, then, it can only represent integers, but it can represent all of them.
> 
> In particular, positive integers end with `...[0]` and negative integers with `...[1]`. Moreover, negative are actually encoded like 2-complement. In other word, if the number is within range, the truncation of the bit sequence to 32 bits give the representation of that number as a signed 32-bit integer.
> 
> With that in mind, we can safely define shifts on comptime ints: `1 << 3` is `...[0]1 << 3 = ...[0]1000` and `-3 >> 1` is `...[1]00 >> 1 = ...[1]0`.
</details>
