### ISSUE TITLE
Proposal: raw string literals or regex literal syntax

### ISSUE THREAD

**Issue by akvadrako** [ziglang/zig#8540]
Regular expressions are common enough it shouldn't be painful to write them in source code. Regex parsers make ample use of backslashes, but in zig strings backslashes need to be escaped. So to create a simple regex like `^\w[\w\s\\]+\n` one must write:
```zig
Regex.compile(alloc, '^\\w[\\w\\s\\\\]+\n')
```

Javascript has a regex literal syntax and python has a raw string syntax which makes this less painful:
```js
/^\w[\w\s\\]+\n/.exec(...)
```
```python
re.compile(r'^\w[\w\s\\]+\n')
```

Would either of these or something similar be suitable for zig?

**Comment by ifreund** [comment]
I'd typically use a [multiline string literal](https://ziglang.org/documentation/master/#Multiline-String-Literals) for this:
```zig
Regex.compile(
    alloc,
    \\^\w[\w\s\\]+\n
)
```

**Comment by akvadrako** [comment]
The multiline syntax would be okay for occasional usage, but if you had say a dozen patterns it would be pretty unwieldy.

I wonder why this issue was closed? I'm just curious, since I'm not familiar with the process.

**Comment by g-w1** [comment]
> The multiline syntax would be okay for occasional usage, but if you had say a dozen patterns it would be pretty unwieldy.

Can you give an example of how it would be unwieldy?

**Comment by akvadrako** [comment]
Sure. Take this example from a markdown parser in python:

```python
PUNCTUATION = r'''\\!"#$%&'()*+,./:;<=>?@\[\]^`{}|_~-'''
ESCAPE = r'\\[' + PUNCTUATION + ']'
HTML_TAGNAME = r'[A-Za-z][A-Za-z0-9-]*'
HTML_ATTRIBUTES = (
    r'(?:\s+[A-Za-z_:][A-Za-z0-9_.:-]*'
    r'(?:\s*=\s*(?:[^ "\'=<>`]+|\'[^\']*?\'|"[^\"]*?"))?)*'
)
ESCAPE_CHAR = r'\\([' + PUNCTUATION + r'])'
LINK_TEXT = r'(?:\[[^\[\]]*\]|\\[\[\]]?|`[^`]*`|[^\[\]\\])*?'
LINK_LABEL = r'(?:[^\\\[\]]|' + ESCAPE + r'){0,1000}'
```

In zig each line becomes three lines. Roughly:
```zig

PUNCTUATION = 
  \\\\!"#$%&'()*+,./:;<=>?@\[\]^`{}|_~-
;
ESCAPE = 
  \\\\[
  ++ PUNCTUATION ++
  \\]
;
HTML_TAGNAME = 
  \\[A-Za-z][A-Za-z0-9-]*
;
HTML_ATTRIBUTES = .{
  \\(?:\s+[A-Za-z_:][A-Za-z0-9_.:-]*
  ,
  \\(?:\s*=\s*(?:[^ "\'=<>`]+|\'[^\']*?\'|"[^\"]*?"))?)*
};
ESCAPE_CHAR = 
  \\\\([
  ++ PUNCTUATION ++
  \\])
;
LINK_TEXT = 
  \\(?:\[[^\[\]]*\]|\\[\[\]]?|`[^`]*`|[^\[\]\\])*?
;
LINK_LABEL = 
  \\(?:[^\\\[\]]|
  ++ ESCAPE ++
  \\){0,1000}
;
```

Mostly it looks okay, though the comma and semicolon lines aren't great. And a longer list would be:

```zig
var patterns = .{
  \\\\!"#$%&'()*+,./:;<=>?@\[\]^`{}|_~-
  ,
  \\\\[
  ++ PUNCTUATION ++
  \\]
  ,
  \\[A-Za-z][A-Za-z0-9-]*
  ,
  \\(?:\s+[A-Za-z_:][A-Za-z0-9_.:-]*
  ,
  \\(?:\s*=\s*(?:[^ "\'=<>`]+|\'[^\']*?\'|"[^\"]*?"))?)*
  ,
  \\\\([
  ++ PUNCTUATION ++
  \\])
  ,
  \\(?:\[[^\[\]]*\]|\\[\[\]]?|`[^`]*`|[^\[\]\\])*?
  ,
  \\(?:[^\\\[\]]|'
  ++ ESCAPE ++
  \\){0,1000}
};
```

The zig way does have some advantages; the extra space aids readability.

**Comment by truemedian** [comment]
Zig doesn't have language level support for regular expressions, so why should there be a special kind of string for them?

I guess what this is less suited towards regular expressions and you just want some way to use a string with absolutely no escape sequences, is that more accurate?

**Comment by slimsag** [comment]
I would phrase the problem here as: Zig lacks a _single line_ raw string literal.

I think it's [multi-line string literals](https://ziglang.org/documentation/master/#Multiline-String-Literals) are okay, and one nice aspect about them compared to e.g. Go raw string literals is that the raw string can be indented to match your code level (this is one thing that sucks about Go raw string literals, if you indent the contents to match the code then the string contains that indention)

But needing to write a single line incantation as:

```zig
Regex.compile(
    alloc,
    \\^\w[\w\s\\]+\n
)
```

Definitely seems like a "trick" and a bit more annoying than if Zig had e.g. Go raw string literal syntax:

```
Regex.compile(alloc, `^\w[\w\s\\]+\n`)
```

**Comment by truemedian** [comment]
Its just my opinion, but I think the former actually looks fine, another kind of string literal is just more mental load when it can be accomplished with such a small change.

**Comment by jdknezek** [comment]
FWIW current multiline string literals are also prohibitively cumbersome for large blocks of content (e.g. SQL) without tooling support.

In many languages there's *some* string literal form I could use to `CTRL+V` a block of SQL from a query window into some code, but with Zig's current multiline strings I would then have to prefix the lines by careful application of a regex search/replace, or an editor incantation that I have never otherwise needed.

**Comment by matu3ba** [comment]
> prohibitively cumbersome for large blocks of content (e.g. SQL) without tooling support.

Does your editor not support block selection and block prefixing? Even [eclipse supports it](https://stackoverflow.com/q/9460945).

**Comment by akvadrako** [comment]
> I guess what this is less suited towards regular expressions and you just want some way to use a string with absolutely no escape sequences, is that more accurate?

Regex is my use case, but something applicable to other formats which use many backslashes would be more generally useful. I can't recall any though.

**Comment by akvadrako** [comment]
Maybe another option besides a new string syntax is a new string type. Strings with invalid escape sequences become something like:
```zig
var s: [:0,extraescapes]u8 = '\.';
```
Bad escapes don't need to be syntax errors since they are not ambiguous. But using them where they are not expected could still be an error.

**Comment by matu3ba** [comment]
> Maybe another option besides a new string syntax is a new string type.

zig aims to have a simple syntax, so this wont get accepted.

You could add/suggest a simple function into std for testing escape sequence at comptime and runtime. You could then make a abbreviation for the name.

Something like
```zig
// really not sure where it would fit, so I make up a file here
const unesc = std.mem.myescapefunction;
var s:[:0]u8 = unesc(
\\yourstring part 1
\\yourstring part 2
);
```

This would have no difference in LOC to the standard multiline string and you can check at comp-time or runtime your string.

**Comment by akvadrako** [comment]
@matu3ba That doesn't do anything along the lines of this proposal. As you say it has the same LOC as the multiline strings.

**Comment by jdknezek** [comment]
> > prohibitively cumbersome for large blocks of content (e.g. SQL) without tooling support.
> 
> Does your editor not support block selection and block prefixing? Even [eclipse supports it](https://stackoverflow.com/q/9460945).

I realize that there may be some way to accomplish this in every editor. I was lamenting that the answer to, "how do I write this kind of code in Zig" is, "use another tool to do it". This and multiline comments are two pain points to editing Zig in e.g. `nano` due to environment constraints.

These are two cases (along with indentation/newlines, though I know those are side-effects of `zig fmt`'s youth) where I feel the Zig developer ergonomics have regressed compared to other modern languages.

**Comment by markfirmware** [comment]
For complex expressions it might be just as well to use parser combinators and skip the traditional markup with backwards slashes.

**Comment by matu3ba** [comment]
> I realize that there may be a way to accomplish this in many editors. I was lamenting that the answer to, "how do I write this kind of code in Zig" is, "use another tool to do it". This doesn't feel zen to me. This and multiline comments are two pain points to editing Zig in e.g. nano due to environment constraints.

I read

* Favor reading code over writing code.
* Only one obvious way to do things.

and prefixing multiline strings makes them very obvious (even without syntax highlighting).
Otherwise you rely on syntax highlighting from your editor, so it is a tradeoff.

* Avoid local maximums.

might be interpreted as such. Why this does not really apply I mentioned above.
Could you elaborate what you mean?

**Comment by jdknezek** [comment]
> and prefixing multiline strings makes them very obvious (even without syntax highlighting).
> Otherwise you rely on syntax highlighting from your editor, so it is a tradeoff.

That's fair, it is a tradeoff indeed.

In my mind I had followed a logical progression from "no hidden control flow" to "readable at a glance" to "editable with minimal external requirements", but that final step may just be my own assumption.

It is still my opinion that quoted string literals and multiline comments have value, as evidenced by their presence in most other modern languages, but I've made my point above. Thanks for the civil discourse :)

**Comment by lerno** [comment]
Since I vocally complained about Zig multi-line syntax elsewhere, let me propose the following formats:

`"""..."""` string with normal behaviour, except `"` does not usually need to be escaped.

Multi-line with escapes
```c
foo = """
  some \u1234
    text
 here
 """;
 // current Zig:
foo =
  \\ some \u1234
  \\   text
  \\here
  ;
 ```
 Will trim right hand spaces and will trim the left side to the starting left side. It will also remove trailing \n
 
 Verbatim string:
 `'''...'''` string with no escape codes.

 Verbatim multi-string:
```c
foo = '''
  some \u1234
    text
 here
 ''';
 // current Zig:
foo =
  \\  some \\u1234
  \\    text
  \\ here
  \\
  ;
```
Only first \n is stripped.
 
Using this, a string like `^\w[\w\s\\]+\n` is simply written as `'''^\w[\w\s\\]+\n'''`
