### ISSUE TITLE
zig build-exe requires a Windows SDK even when using -Dtarget=native-native-gnu

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#8543]
On a windows machine that does not have visual studio, trying to compile the following C file will fail.

```c
#include <windows.h>
int CALLBACK WinMain(HINSTANCE,HINSTANCE,LPSTR,int)
{
    return 0;
}
```

```batch
> zig build-exe main.c -lc -Dtarget=native-native-gnu
error: unable to create compilation: WindowsSdkNotFound
```

The `-Dtarget=native-native-gnu` is supposed to allow this to work without the Windows SDK.  Note that this does work if it's done with a `zig build` and a `build.zig` file.

```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();
    const exe = b.addExecutable("main", "main.c");
    exe.setTarget(target);
    exe.setBuildMode(mode);
    exe.linkLibC();
    exe.install();
}
```

This command works:
```batch
> zig build -Dtarget=native-native-gnu
```

**Comment by bibo38** [comment]
Looks to me like you've just used the wrong flag. While `-Dtarget=` is correct in the build.zig case, in the build-exe case the correct flag is `-target ` (while `-D` sets a macro, which is why the flag didn't fail to parse). While my Windows test gave me some error about a missing C Runtime with your command, `zig build-exe -lc -target native-native-gnu main.c` compiled without a problem.

**Comment by marler8997** [comment]
Shoot you are right @bibo38.  I'm surprised @andrewrk didn't catch that?  The command-line parameters for the various zig commands could probably use some improvement to make them more consistent.  Closing this issue.
