### ISSUE TITLE
Compilation silently fails when executable output file already exists and is locked for reading.

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#859]
The executable is not touched and other files (`zig-cache/` and `.pdb` in my case) are updated.

The compilation process returns 127 but does not output any message.

**Comment by suirad** [comment]
Could a workaround for this be that the compiler has a windows specific check to be sure that the file is able to be written? Because if for whatever reason you are left with a lingering process during development, it will prevent the out binary from being modified when recompiled. That would be inconsistent with Linux in that you can modify the binaries of an active process.

**Comment by suirad** [comment]
@andrewrk can you add a help wanted tag?

**Comment by andrewrk** [comment]
=> #3825
