### ISSUE TITLE
Proposal: have testing.expectEqual use the `eql` method if defined

### ISSUE THREAD

**Issue by LemonBoy** [ziglang/zig#8625]
It is common wisdom to define an `eql` predicate whenever the equality between two objects needs some extra logic to be determined.
Let's make `testing.expectEqual` use `eql` to compare objects for equality if available.

Opening a ticket to gauge interest.

**Downsides**

The `eql` name is officially blessed as `format` already is (perhaps we want to rename it into `equal` ?).

**Implementation**

```diff
diff --git a/lib/std/testing.zig b/lib/std/testing.zig
index ac1aa3bf6..9ea02dc01 100644
--- a/lib/std/testing.zig
+++ b/lib/std/testing.zig
@@ -45,6 +45,13 @@ pub fn expectError(expected_error: anyerror, actual_error_union: anytype) void {
 /// then aborts.
 /// `actual` is casted to the type of `expected`.
 pub fn expectEqual(expected: anytype, actual: @TypeOf(expected)) void {
+    if (comptime std.meta.trait.hasFn("eql")(@TypeOf(expected))) {
+        if (!expected.eql(actual)) {
+            std.debug.panic("expected {}, found {}", .{ expected, actual });
+        }
+        return;
+    }
+
     switch (@typeInfo(@TypeOf(actual))) {
         .NoReturn,
         .BoundFn,
```

**Comment by jayschwa** [comment]
> The `eql` name is officially blessed as `format` already is (perhaps we want to rename it into `equal` ?).

What does "officially blessed" mean? I think the overall proposal is a good idea, plus a rename too. "eq", "eql", and "equal" can all be found in the standard library. Personally, I think `if (foo.equals(bar))` reads the best for a method name.

**Comment by LemonBoy** [comment]
> What does "officially blessed" mean?

That we reserve the name `eql` (or `equal` or whatever) for equality predicates and we expect the prototype to be `fn (T,T) bool` with several properties (symmetric and transitive at minimum).

**Comment by tauoverpi** [comment]
Would it be worth to have this for `meta.eql` too? Same could apply to a `meta.lessThan` and similar.

**Comment by jedisct1** [comment]
> Would it be worth to have this for `meta.eql` too? Same could 

> apply to a `meta.lessThan` and similar.

Having this for `meta.eql` could indeed be very useful.

**Comment by andrewrk** [comment]
I veto this proposal. Reasoning:

The purpose of `expectEqual` is to print diagnostics about why two things are not equal. Here are the doc comments:

> This function is intended to be used only in tests. When the two values are not
> equal, prints diagnostics to stderr to show exactly how they are not equal,
> then returns an error indicating a failed test.
> `actual` is coerced to the type of `expected`.

As an example, if slices are provided, the diagnostics ideally will print the two slices side by side so the programmer can visualize why they are not equal.

Calling the `eql` function on objects would not be able to show any diagnostics about *why* the objects are not equal, since that concept would be inside a black box. It would be equivalent to `testing.expect(a.eql(b))` which we already have available.

On top of this, I'm already a little concerned with the `format` function as it is used today. It has a few code smells associated with it - a topic for another day. But I think it is wise for Zig to keep the amount of magic methods and things like this to a minimum. I don't think we should define this equality standard and try to use it everywhere.

My suggested alternative is to implement an application-specific `testingExpectEqual` method on your objects, and have it do the diagnostic printing. Or, have a separate testing namespace for your application. One of these two things:

```zig
try myapp.testing.expectEqual(a, b);
try a.testingExpectEqual(b);
```

Both of these approaches are just as convenient to write, offer a better debugging experience, and require no magic names or comptime reflection.
