### ISSUE TITLE
Function returning union causes unnecessary "depends on itself"

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#8677]
```zig
const Foo = union { f: fn () Foo };
test {
    const foo: Foo = undefined;
}
```
Produces the error:
```
./test.zig:1:13: error: union 'Foo' depends on itself
const Foo = union { f: fn () Foo };
            ^
```
Only seems to happen with unions, not structs, and only with return values, not arguments.

**Comment by yurapyon** [comment]
I found what seems to be related
```zig
pub fn Generic(comptime T: type) type {
    return struct {
        data: T,
    };
}

pub const Union = union {
    func: fn (S) void,
};

pub const S = struct {
    generic: Generic([]Union),
};

pub fn main() !void {
    const u: Union = undefined;
}
```

error:
```
./src/main.zig:7:19: error: union 'Union' depends on itself
pub const Union = union {
                  ^
./src/main.zig:12:22: note: referenced here
    generic: Generic([]Union),
                     ^
./src/main.zig:12:21: note: referenced here
    generic: Generic([]Union),
                    ^
./src/main.zig:8:5: note: while checking this field
    func: fn (S) void,
    ^
./src/main.zig:16:22: note: referenced here
    const u: Union = undefined;
```
You can change the line ```generic: Generic([]Union)``` to a pointer or just the Union itself and the error isn't produced. Seems to be only with arrays and slices. Also the fact the type is being generated by a function seems to matter, as changing the line to ```generic: []Union``` doesn't produce the error.

**Comment by acarrico** [comment]
Would anyone like to propose a nice idiom for hiding this sort of recursion from Zig (with casting I assume), while we wait for all the "depends on itself" bugs to get resolved? What is the least invasive way to make the @silversquirl example go through with current Zig?

```
const Foo = union { f: fn () Foo };
test {
    const foo: Foo = undefined;
}
```

**Comment by mlugg** [comment]
This issue was made when stage1 was still the main compiler. stage2 separates function pointer types from function body types, so the equivalent of the original code is this:
```zig
const Foo = union { f: *const fn () Foo };
test {
    const foo: Foo = undefined;
}
```
That code works fine today.
In fact, storing the function body itself in `Foo` (making it a comptime-only type) also compiles okay. Trying to construct a value of that type gives a weird error (shown below), but the type itself is fine.
```
const Foo = union { f: fn () Foo };

fn mkFoo() Foo {
    return .{ .f = mkFoo };
}

test {
    _ = mkFoo();
}
```
```
main.zig:4:20: error: expected type 'fn() main.Foo', found 'fn() main.Foo'
    return .{ .f = mkFoo };
                   ^~~~~
main.zig:4:20: note: generic function cannot cast into a non-generic function
main.zig:8:14: note: called from here
    _ = mkFoo();
        ~~~~~^~
```
...but a function pointer should be fine in pretty much any case anyway, and that works fine to construct.

**Comment by acarrico** [comment]
@mlugg Ah! I'm working with stage3 on a different machine, and the example works great. Even this one which exercises the union:

```
const Foo = union {
    a: u8,
    f: *const fn () Foo
};

fn example() Foo {
    return Foo{ .a = 8 };
}

test {
    const foo: Foo = undefined;
    _ = foo;
    const foo2 = Foo{.f=example};
    try expect ((foo2.f)().a == 8);
}
```
Thank you!

**Comment by acarrico** [comment]
@mlugg

> In fact, storing the function body itself in `Foo` (making it a comptime-only type) also compiles okay.

Interesting. What would that even mean?

**Comment by mlugg** [comment]
Function bodies are a comptime-only type. Comptime values are boxed, and a function body will be basically represented as a pointer anyway. The type exists basically because it has a distinct meaning at runtime (in terms of what a symbol represents - exporting a function and exporting a function pointer are very different things!) but storing a function body in an aggregate isn't really useful in any case I can think of.

**Comment by Vexu** [comment]
Fixed in self-hosted, tested in `test/behavior/union.zig:test "no dependency loop when function pointer in union returns the union" {`.
