### ISSUE TITLE
netbsd has a maximum limit of files open with O_EXLOCK

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#9162]
- tested on NetBSD 9.2 amd64
- orthogonal to `proc.curproc.rlimit.descriptors.soft` or `setrlimit(RLIMIT_NOFILE, ...)`
- files opened `O_CREAT | O_EXLOCK` is seemingly hard-limited to 1024
- error is `ENOMEM`
- unknown if there is a system tunable without rebuilding kernel
 
motivation for issue:

`zig build-exe hello.zig -target x86_64-linux-musl -lc` fails building musl `.c` sources at around 1,000 file mark

and failure is:

https://github.com/ziglang/zig/blob/e006281d79a31e10bdbc07b3e33427d719ec01df/lib/std/os.zig#L1258

**Comment by alarixbsd** [comment]
You don't need to rebuild the kernel.

There are a few tunables, `ulimit -n` (inherited from the parent process, usually the shell, defaults to 1024), and `sysctl kern.maxfiles` (can be changed by root, defaults to [scaling with system RAM](https://github.com/NetBSD/src/commit/7ce9f83e751d35fed49b4b236d8dd468abbe1dad), older releases have a lower default, I think a few thousand).

- https://man.netbsd.org/ulimit.3
- https://man.netbsd.org/sysctl.7

**Comment by alarixbsd** [comment]
After further testing: yeah, you're right, this is independent of any kind of "open files" limit, kernel-wide or per-process. It also seems filesystem independent - I get the same results with a reproducer on ZFS and TMPFS.

While I'm unsure if this is a bug, or intentional to prevent exhaustion of system resources (a compiler isn't a web server - thousands of open file descriptors isn't quite normal), I've made a post on tech-kern@ to see if anyone can give an autopsy of the problem.

http://mail-index.netbsd.org/tech-kern/2021/06/19/msg027486.html

**Comment by mikdusan** [comment]
Ah here's the limit; so there are no knobs:

https://github.com/NetBSD/src/blob/28264188da79f4c05fb6cbbec3ce34639ba4f51e/sys/kern/vfs_lockf.c#L116-L126

and it's:
- per uid (shared across processes)
- root uid is unlimited

**Comment by mikdusan** [comment]
> While I'm unsure if this is a bug

definitely not a netbsd bug and imo we need to do something better on the zig side.

**Comment by mikdusan** [comment]
- this issue no longer manifests on netbsd 9.3 and 10.0 (beta)
- the workaround for netbsd 9.2 is to run-as-root to overcome the limit; there are no system knobs to change it for users
