### ISSUE TITLE
Windows: `zig.exe: error: not ranlib, ar, lib or dlltool`

### ISSUE THREAD

**Issue by vitreo12** [ziglang/zig#9225]
Hello! 

I have downloaded the zig compiler from the website hoping I could use it to replace my C build tools on Windows. When I run `.\zig.exe ar`, however, I receive the following error: `zig.exe: error: not ranlib, ar, lib or dlltool`. 

This happens for both versions 0.9.0-dev and 0.8.0.

**Comment by jmc-88** [comment]
As also noted on [zigforum.org](https://zigforum.org/t/cannot-run-zig-ar-on-windows/585/9?u=jmc), this issue is reproducible on a Linux host via WINE.

**Comment by andrewrk** [comment]
This is a contributor friendly task if anyone wants to take it on - probably something as simple as looking at argv[0] instead of argv[1] to find the name of the tool. Or maybe the llvm code called Windows API GetCommandLine() and needs to be told to skip the first one.

**Comment by SpexGuy** [comment]
It looks like the culprit is InitLLVM.  On windows, the constructor calls `GetCommandLine()` and does custom parsing, in order to handle nonstandard argument character encodings.  InitLLVM also sets up signal handlers for crashes, which we probably want to keep?

Options to fix it are:
1. Modify LLVM (probably not worth it)
2. Make a copy of argv and pass that to InitLLVM
3. Duplicate the signal handler and destructor logic and remove the instantiation of InitLLVM

Between 2 and 3, I'm not sure what the better approach is.

**Comment by SpexGuy** [comment]
`InitLLVM` is also used by `ZigClang_main`, which is probably causing other compilation problems on Windows.

**Comment by andrewrk** [comment]
>  InitLLVM also sets up signal handlers for crashes, which we probably want to keep?

Nah. Ideally, for debug builds we allow zig's own signal handler mechanism to function, and for release modes, it just crashes when it crashes without trying to be helpful.

Small patches to zig_llvm-ar.cpp are ok; we can carry those in our tree. Keep in mind the end-game here is to implement `zig ar` in pure zig and delete the llvm integration.
