### ISSUE TITLE
meta.trait.hasUniqueRepresentation handles integer types incorrectly

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [ziglang/zig#9333]
```Zig
comptime { std.debug.assert(@sizeOf(@Vector(3, i16)) == 6); }
```
fails with Zig 0.8.0. I don't know if this is intended behavior, but it seems to me that the padding should not be counted towards the size. `mem.asBytes`, for example, results in a slice containing undefined data, and an AutoHashMap with `@Vector(3, i16)` keys is silently broken.

**Comment by AssortedFantasy** [comment]
Vectors are SIMD things. They don't really do what you might believe they do. Peeking under the covers they seem to get padded to the nearest power of two size upwards.

`sizeof(@Vector(15,i16)) == 64`
`sizeof(@Vector(16,i16)) == 64`
`sizeof(@Vector(17,i17)) == 128`

This *sorta* makes sense when you consider how the SIMD registers on your computer actually work. But it also kinda doesn't.

`sizeof(@Vector(513,i16)) == 2048`

I mean nobody has a AVX1024 register lying around so the padding there is kinda wasteful. Frankly a lot of the way `Vectors` in Zig work is kinda random and weird.
 
Anyway I think you probably mean to use arrays. `[3]i16`.

They are what should be used 99% of the time.

**Comment by SpexGuy** [comment]
> it seems to me that the padding should not be counted towards the size

`@sizeOf` returns the amount of space needed in an array or struct to contain a type.  Since it is also the array stride, it must include padding.  Additionally, again because it's the array stride, size must always be aligned to the type's alignment.  Vectors tend to have larger alignment than other types, due to the requirements surrounding vector instructions on some ISAs.

> an `AutoHashMap` with `@Vector(3, i16)` keys is silently broken

This is true, but the problem is that `std.meta.trait.hasUniqueRepresentation` doesn't handle vector types correctly.

**Comment by InterplanetaryEngineer** [comment]
Thank you for the clarification!
