### ISSUE TITLE
"Unable to infer variable type" of integer literal

### ISSUE THREAD

**Issue by jarble** [ziglang/zig#9452]
The Zig compiler is unable to infer the type of the variable `b` that is declared here:
```
var b = 1;
const std = @import("std"); pub fn main() void { std.debug.print("Hello, {}!", .{b}); }
```

```
An error occurred:
/tmp/playground733872304/play.zig:1:1: error: unable to infer variable type
var b = 1;
^
/tmp/playground733872304/play.zig:2:82: note: referenced here
const std = @import("std"); pub fn main() void { std.debug.print("Hello, {}!", .{b}); 
                                                                                 ^
```
But the type is inferred when I declare it as a constant instead of a variable:
```
//this program compiles successfully
const b = 1;
const std = @import("std"); pub fn main() void { std.debug.print("Hello, {}!", .{b}); }
```

A similar error happens when I assign one integer variable to another:

```
var b:i32 = 1;
var c:i32 = b;
const std = @import("std"); pub fn main() void { std.debug.print("Hello, {}!", .{c}); }
```

```
An error occurred:
/tmp/playground674368768/play.zig:2:13: error: cannot store runtime value in compile time variable
var c:i32 = b;
            ^
/tmp/playground674368768/play.zig:3:82: note: referenced here
const std = @import("std"); pub fn main() void { std.debug.print("Hello, {}!", .{c}); 
                                                                                 ^
```
Is this a compiler bug?

**Comment by jarble** [comment]
I see the problem now: this program works when I declare the variables in a local scope.
```
const std = @import("std");
pub fn main() void{
var b:i32 = 1;
var c:i32 = b;
std.debug.print("Hello, {}!", .{c});
}
```

**Comment by Vexu** [comment]
The reason your first example doesn't work is that integer literals in Zig have type `comptime_int` which can only be used at comptime. Inside functions the error is already more helpful:
```
./a.zig:4:5: error: variable of type 'comptime_int' must be const or comptime
    var b = 1;
    ^
./a.zig:4:5: note: to modify this variable at runtime, it must be given an explicit fixed-size number type
    var b = 1;
    ^
```


Your third example doesn't work since the initialization values of container level variables must be comptime known as mentioned in the docs here https://ziglang.org/documentation/master/#toc-Container-Level-Variables.

These errors will get more helpful as the self hosted compiler matures but in the meanwhile reading the documentation and asking questions in the [communities](https://github.com/ziglang/zig/wiki/Community) should help.
