### ISSUE TITLE
zig cc exe OFFSETOF macro crash

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [ziglang/zig#9528]
zig 0.9

This code just crashes if compiled with `zig cc -g`

```
#include <stddef.h>
typedef struct foo
{
    int a;
}foo;

#define OFFSETOF(TYPE, ELEMENT) ((size_t)&(((TYPE *)0)->ELEMENT))

int main(int argc, char** argv)
{
    int offset = OFFSETOF(foo, a);
    (void) offset;
    
    return 0;
}
```

the crash happens on the OFFSETOF line:
Unhandled exception at 0x00007FF6955A100F in a.exe: 0xC000001D: Illegal Instruction.

The problem manifested in a dll compiled with zig cc in a slightly different way, but the crash is exactly the same so I suppose the root cause of the problem is the same:

![image](https://user-images.githubusercontent.com/70660839/128425365-25f73fc7-da45-4216-8e80-88114241c547.png)

I tried to isolate the problem and arrived at the small program that I posted above, hope it helps.

**Comment by floooh** [comment]
My guess is that the OFFSETOF() macro is undefind behaviour because of the null-pointer dereference. Compilers often inject an 'ud2' instruction when they detect UB. ```zig cc``` activities various sanitizers (see the command line that's dumped with ```zig cc -v```), and maybe one of those sanitizers detects the nullptr dereference as UB and injects the illegal instruction.

FWIW, when replacing the custom OFFSETOF() macro with the standard ```offsetof()``` it works fine (offsetof() resolves to __builtin_offsetof() in clang, and it also works in GCC and MSVC, so IMHO it's no longer necessary to use a custom macro).

Also see this wikipedia snippet about potential undefined behavior (https://en.wikipedia.org/wiki/Offsetof):

"While this implementation works correctly in many compilers, it has generated some debate if this is undefined behavior according to the C standard,[2] since it appears to involve a dereference of a null pointer"

**Comment by leonardo-ourmachinery** [comment]
The actual problem was misaligned memory, I'm so sorry for opening the issue. (At least I learned that the OFFSETOF macro is UB :) )
The fact is that I didn't know (And I still don't) how to make the sanitizer print meaningful errors at runtime instead of just making the program crash, and so I just had to guess... but that's another story.

Thank you for the support and sorry for the useless issue.

Leonardo

**Comment by Vexu** [comment]
> The fact is that I didn't know (And I still don't) how to make the sanitizer print meaningful errors at runtime instead of just making the program crash, and so I just had to guess... but that's another story.

That is an issue with Zig that is tracked in #5163.

Also no need to apologize for opening an issue but I do recommend asking in one of the [communities](https://github.com/ziglang/zig/wiki/Community) if you're unsure whether something is a bug.
