### ISSUE TITLE
translate-c: enum types and values differ in signedness

### ISSUE THREAD

**Issue by 17dec** [ziglang/zig#9582]
Stumbled upon this one while using LMDB.

```c
typedef enum MDB_cursor_op {
    MDB_FIRST,
    MDB_FIRST_DUP,
    MDB_GET_BOTH,
// ...
} MDB_cursor_op;
// ...
int  mdb_cursor_get(MDB_cursor *cursor, MDB_val *key, MDB_val *data, MDB_cursor_op op);
```

Is translated into:

```zig
pub const MDB_FIRST: c_int = 0;
pub const MDB_FIRST_DUP: c_int = 1;
pub const MDB_GET_BOTH: c_int = 2;
// ...
pub const enum_MDB_cursor_op = c_uint;
pub const MDB_cursor_op = enum_MDB_cursor_op;
// ...
pub extern fn mdb_cursor_get(cursor: ?*MDB_cursor, key: [*c]MDB_val, data: [*c]MDB_val, op: MDB_cursor_op) c_int;
```

The enum type is a `c_uint` whereas the enum values are given a `c_int`, with the result that passing an enum constant to `mdb_cursor_get()` throws a compile error. Nothing an `@intCast` can't fix, but it does make using the API somewhat less convenient. Would it make sense to declare the enum type as `c_int` as well?

**Comment by ehaas** [comment]
Is the problem with using an enum constant directly, or with using a variable like `var my_val = MDB_FIRST`? I would expect a direct usage to coerce to unsigned since it's comptime known to be within range.

Unfortunately C can treat enum constants (`MDB_FIRST`, `MDB_FIRST_DUP`) differently than enum types (`MDB_cursor_op`). It's a consequence of C enums being weakly typed and non-exhaustive - to make the translated C technically correct requires sacrificing some ergonomics.

Consider the following C program:
```C
typedef enum my_enum {
    MY_VALUE,
} my_enum;

my_enum foo(my_enum x, my_enum y) {
    return x * y;
}
int bar(int x, int y) {
    return x * y;
}
int main(void) {
    foo(60000, 60000); // perfectly fine if my_enum is unsigned
    bar(60000, 60000); // undefined behavior
    return 0;
}
```
If you compile with `clang -ftrapv` you'll see that the call to `bar` triggers an abort but the call to `foo` does not. If Zig translated `my_enum` as `c_int` then `foo` would have incorrect undefined behavior for some inputs.

**Comment by 17dec** [comment]
> I would expect a direct usage to coerce to unsigned since it's comptime known to be within range.

Yup, you're exactly right. The following indeed works fine:

```zig
const c = @cImport(@cInclude("lmdb.h"));
pub fn main() void {
    _ = c.mdb_cursor_get(null, null, null, c.MDB_FIRST);
}
```

And this throws an error:

```zig
const c = @cImport(@cInclude("lmdb.h"));
pub fn main() void {
    var op = c.MDB_FIRST;
    _ = c.mdb_cursor_get(null, null, null, op);
}
```

```
./t.zig:4:44: error: expected type 'c_uint', found 'c_int'
    _ = c.mdb_cursor_get(null, null, null, op);
                                           ^
./t.zig:4:44: note: unsigned 32-bit int cannot represent all possible signed 32-bit values
    _ = c.mdb_cursor_get(null, null, null, op);
                                           ^
```

Specifying a type in the form of `var op: c_uint = c.MDB_FIRST;` also works as expected and is ergonomic enough.

C keeps having weird corner cases everywhere. Thanks for the clarification.
