### ISSUE TITLE
ChildProcess.exec can't handle std.fs.cwd() as .cwd_dir

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#9688]
Only tested on Linux, not sure if other platforms have similar issues.

Test code:

```zig
const std = @import("std");

test "exec fs.cwd()" {
    const allocator = std.testing.allocator;
    const cwd = std.fs.cwd();
    const reopened = try std.fs.cwd().openDir(".", .{});
    std.debug.print("cwd(): {}\nreopened: {}\n", .{ cwd, reopened });

    const result = try std.ChildProcess.exec(.{
        .allocator = allocator,
        .argv = &[_][]const u8{"echo"},
        .cwd_dir = cwd,
    });
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);

    std.debug.print("stdout:\n{s}\n", .{result.stdout});
    std.debug.print("stderr:\n{s}\n", .{result.stderr});

    switch (result.term) {
        .Exited => try std.testing.expectEqual(@as(u8, 0), result.term.Exited),
        else => {
            std.debug.print("{}\n", .{result.term});
            return error.UnexpectedExit;
        },
    }
}
```

This will fail with the output:

```
cwd(): Dir{ .fd = -100 }
reopened: Dir{ .fd = 3 }
stdout:

stderr:
thread 41649 panic: reached unreachable code
/home/ryan/Programming/zig/zig/build/lib/zig/std/os.zig:2448:22: 0x21579e in std.os.fchdir (test)
            EBADF => unreachable,
                     ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/child_process.zig:614:26: 0x20e791 in std.child_process.ChildProcess.spawnPosix (test)
                os.fchdir(cwd.fd) catch |err| forkChildErrReport(err_pipe[1], err);
                         ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/child_process.zig:134:35: 0x20cd08 in std.child_process.ChildProcess.spawn (test)
            return self.spawnPosix();
                                  ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/child_process.zig:356:24: 0x209bee in std.child_process.ChildProcess.exec (test)
        try child.spawn();
                       ^
/home/ryan/Programming/zig/tmp/exec-cwd.zig:9:45: 0x208d47 in test "exec fs.cwd()" (test)
    const result = try std.ChildProcess.exec(.{
                                            ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/special/test_runner.zig:76:28: 0x240842 in std.special.main (test)
        } else test_fn.func();
                           ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/start.zig:505:22: 0x237e7c in std.start.callMain (test)
            root.main();
                     ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/start.zig:457:12: 0x2103de in std.start.callMainWithArgs (test)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/start.zig:371:17: 0x20a606 in std.start.posixCallMainAndExit (test)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/start.zig:284:5: 0x20a412 in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^

Term{ .Signal = 6 }
Test [2/1] test "exec fs.cwd()"... FAIL (UnexpectedExit)
```

If instead `reopened` is passed as the `.cwd_dir` field, then it works fine. 

This is due to `fs.cwd()` returning an `fd` of `AT_FDCWD`:

https://github.com/ziglang/zig/blob/eb5e4ac495356dd0dae680ca316e18b848c9efa3/lib/std/fs.zig#L2130-L2138

which it seems like `fchdir` can't handle. Since presumably `fchdir` is unecessary when `fd` is `AT_FDCWD`, though, it seems like adding a conditional somewhere to skip the `fchdir` would fix it. Where exactly that conditional should go (in `ChildProcess.spawnPosix`? in `os.fchdir` itself?), and/or which other functions might be affected by something similar I'm unsure about.

**Comment by Ersikan** [comment]
I think the current behavior is strange and inconsistent with the semantics of other languages for getting the current directory. 

`AT_FDCWD` is a special value used by specific system calls instead of a directory file descriptor to specify that the operation must be executed relative to the current directory. It is not a file descriptor, and in fact is defined to be `-100` in [`fcntl.h`](https://github.com/torvalds/linux/blob/master/include/uapi/linux/fcntl.h#L95), which is not a valid file descriptor.

For example, this zig program also fails because the directory is not a real file descriptor: 
```zig
const std = @import("std");

pub fn main() !void {
    const cwd = std.fs.cwd();
    const stat = try cwd.stat();
    std.debug.print("{}", .{stat.kind});
}
```
Output:
```
thread 56245 panic: reached unreachable code
/home/aelerinya/Documents/zig/local/lib/zig/std/os.zig:3717:18: 0x225709 in std.os.fstat (read_cwd)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/aelerinya/Documents/zig/local/lib/zig/std/fs/file.zig:323:32: 0x20d29d in std.fs.file.File.stat (read_cwd)
        const st = try os.fstat(self.handle);
                               ^
/home/aelerinya/Documents/zig/local/lib/zig/std/fs.zig:2179:25: 0x230eb4 in std.fs.Dir.stat (read_cwd)
        return file.stat();
                        ^
/home/aelerinya/Documents/zig/zig/tmp/read_cwd.zig:5:30: 0x229e6e in main (read_cwd)
    const stat = try cwd.stat();
                             ^
/home/aelerinya/Documents/zig/local/lib/zig/std/start.zig:535:37: 0x2227ca in std.start.callMain (read_cwd)
            const result = root.main() catch |err| {
                                    ^
/home/aelerinya/Documents/zig/local/lib/zig/std/start.zig:477:12: 0x2063ee in std.start.callMainWithArgs (read_cwd)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/aelerinya/Documents/zig/local/lib/zig/std/start.zig:391:17: 0x205476 in std.start.posixCallMainAndExit (read_cwd)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/home/aelerinya/Documents/zig/local/lib/zig/std/start.zig:304:5: 0x205282 in std.start._start (read_cwd)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
[1]    56245 abort (core dumped)  ./stat_cwd
```

Storing `AT_FDCWD` instead of a real file descriptor to the directory only work if it will only be used with the `openat` or related system calls.
Moreover, this always resolved to the current working directory, not the one at the point where `std.fs.cwd()` was called, which I think is a real foot gun, considering that other languages return a handle which always point to the same directory, no matter how much you change the current directory afterwards.

I would suggest replacing the `Dir{ .fd = os.AT.FDCWD }` by a real call to openat which will open the current directory.

Another solution would be for `std.fs.cwd()` to return a special object, on which only the system calls which recognize this pseudo file descriptor could be called.

**Comment by matu3ba** [comment]
You can set `cwd_dir` to null, which is also the default to inherit the `cwd()` from the parent process.
Windows is more lax with file permissions, so it provides a usable file descriptor.
Linux is less lax, so it provides merely a Kernel stub for the default permissions which also ensures that certain things dont fail.

Zig cant fix the defaults of Kernels, unless we plan to let the user pay for some performance or memory loss.

> this would make the function fail sometime and therefore be a breaking change.

This would also break comp time-availability and add not-existing error conditions.

> pseudo file descriptor are available

This sounds like a hack for single case. Probably the better option is to add some documentation when to use which argument.

**Comment by matu3ba** [comment]
> Since presumably fchdir is unecessary when fd is AT_FDCWD, though, it seems like adding a conditional somewhere to skip the fchdir would fix it. 

Unfortunately no. Think of paths `../subdir`, `subdir/..`. Checking this for every case is expensive, because you need to track the complete possible traversal or do path normalization.
Assume for now, that we do in libstd path function comptime path normalization (how much compilation time cost?):
How do we check runtime appended paths, which have the form `pathconcat("..", subdir)` ?

> Where exactly that conditional should go (in ChildProcess.spawnPosix? in os.fchdir itself?), and/or which other functions might be affected by something similar I'm unsure about.

With aforementioned example, this is unfeasible to solve in general as it boils down to the halting problem.
Unless we do comptime-path normalization, for I would expect very limited usefulness.

`EBADF => unreachable,` could be properly documented though to indicate this possible cause.

**Comment by squeek502** [comment]
@matu3ba could you clarify where those path strings could come into play? `std.os.fchdir` only takes an `fd_t` (so no possible path string), and `std.ChildProcess.cwd_dir` is a `?fs.Dir` so no possible path string there either.

**Comment by tau-dev** [comment]
> I think the current behavior is strange and inconsistent with the semantics of other languages for getting the current directory.

I agree. I would never have expected a `Dir` value to change meaning by an `os.chdir()`. The `fs.cwd()` signature does not indicate in any way that it returns an unusual value.

**Comment by tau-dev** [comment]
> I think the current behavior is strange and inconsistent with the semantics of other languages for getting the current directory.

I agree. I would never have expected a `Dir` value to change meaning after an `os.chdir()`. The `fs.cwd()` signature does not indicate in any way that it returns an unusual value.

What is the use of `fs.cwd()` at comptime? `os.AT.FDCWD` can be accessed either way.

**Comment by nektro** [comment]
> What is the use of `fs.cwd()` at comptime?

unusable
