### ISSUE TITLE
Trouble understanding `parser.cpp`

### ISSUE THREAD

**Issue by jasonluaved** [ziglang/zig#9692]
This isn't an issue, nor a bug. I've been reading through the Zig Parser implementation (esp `parser.cpp`), and I'm trying to understand the logic behind the following. The syntax of the comments are new to me (new to compiler development), so was a bit lost there. 

In https://github.com/ziglang/zig/blob/master/src/stage1/parser.cpp#L1242,
![image](https://user-images.githubusercontent.com/84307150/132238145-9d157e2b-d73f-478e-ab67-64423ce489a4.png)
where the implementation for `ast_parse_bin_op_expr` is:
![image](https://user-images.githubusercontent.com/84307150/132238266-e6afbec7-924f-46cb-bf64-3c3907718e17.png)
... what is the idea behind `op_parse` and `child_parse`?

Also in first image, for Comparison expr, why you are using `ast_parse_compare_op` are `op_parse` and `ast_parse_bitwise_expr` as `child_parse`? Aren't comparison expr like: `a == b`?

Please help, @andrewrk, and rest of Zig team. 

Thank you!

**Comment by g-w1** [comment]
Since a lot of expressions are binops, it does not make sense to duplicate this logic for every one, so op_parse and child_parse are function pointers that allow functions to pass other functions to ast_parse_bin_op_expr that can actually parse specific things, while ast_parse_bin_op_expr is generic, and calls those function pointers. 
For the second point, as we can see in the grammar
https://github.com/ziglang/zig-spec/blob/d28bba9244136b5e276dc99fe6016bc40ce107f2/grammar/grammar.y#L71
, a compare expr is a bitwise expr then an optional (compare op and a bitwise expr), the whole operator precedence parsing works like this. A BitwiseExpr is not only a bitwise, but any expr that has a lower precedence than a CompareExpr. 
I hope this clears it up.
In the future, you may get better answers asking in a zig community listed here: https://github.com/ziglang/zig/wiki/Community

**Comment by jasonluaved** [comment]
Thank you for the clarification, but could you kindly provide examples? I don't understand what CompareExpr and BitwiseExpr are in code. Maybe a Zig code example will help

**Comment by jasonluaved** [comment]
Okay, so I'll try to explain my question a bit better: 
For example in the function [`ast_parse_bit_shift_expr()`](https://github.com/ziglang/zig/blob/master/src/stage1/parser.cpp#L1251), the comment for this is
```c
// BitShiftExpr <- AdditionExpr (BitShiftOp AdditionExpr)*
```
which calls
```c
    return ast_parse_bin_op_expr(pc, BinOpChainInf, ast_parse_bit_shift_op, ast_parse_addition_expr);
```

I understand the idea behind `ast_parse_bin_op_expr` being generic, but I find the grammar confusing.

For example, doesn't a bitshift expr imply something like the following?
```zig
a << 2; 
```

Why is an `AdditionExpr` followed by another `AdditionExpr`? I don't understand the logic
This is the code for the `parse_addition_expr`:
```cpp
// AdditionExpr <- MultiplyExpr (AdditionOp MultiplyExpr)*
static AstNode *ast_parse_addition_expr(ParseContext *pc) {
    return ast_parse_bin_op_expr(pc, BinOpChainInf, ast_parse_addition_op, ast_parse_multiply_expr);
}
```
that for `ast_parse_multiply_expr`:
```cpp
// MultiplyExpr <- PrefixExpr (MultiplyOp PrefixExpr)*
static AstNode *ast_parse_multiply_expr(ParseContext *pc) {
    return ast_parse_bin_op_expr(pc, BinOpChainInf, ast_parse_multiply_op, ast_parse_prefix_expr);
}
```
and `ast_parse_prefix_expr` is:
```cpp
// PrefixExpr <- PrefixOp* PrimaryExpr
static AstNode *ast_parse_prefix_expr(ParseContext *pc) {
    return ast_parse_prefix_op_expr(
        pc,
        ast_parse_prefix_op,
        ast_parse_primary_expr
    );
}
```
Please explain the logic behind this (and maybe provide some examples to illustrate this?). 

Thank you in advance!

**Comment by Vexu** [comment]
`ast_parse_compare_expr` is being passed because the children of bit shift operations are comaprision operations.

I recommend you go read about [PEG grammars](en.wikipedia.org/wiki/Parsing_expression_grammar) and [ASTs](https://en.m.wikipedia.org/wiki/Abstract_syntax_tree).

Also note that github is not the right place for questions like this and you should instead go to one of the [communities](https://github.com/ziglang/zig/wiki/Community) and that the cpp compiler is in the progress of being replaced by the self-hosted compiler whose parser can be found in `lib/std/zig/parse.zig`.
