### ISSUE TITLE
riscv64-freestanding: C and Zig object files default to soft-float ABI

### ISSUE THREAD

**Issue by sagehane** [ziglang/zig#9760]
### Issue:
`zig build-obj -target riscv64-freestanding` seems to default to `soft-float ABI` for C and Zig files.
Assembly files seem to target `double-float` as expected.

### Expected behavior:
It should probably default to `double-float`, like what every other platform seems to, at least with `-mcpu baseline_rv64+d` or more.

### How to reproduce:
Sample `main.zig` file:
```zig
const std = @import("std");

pub fn main() anyerror!void {
    std.log.info("All your codebase are belong to us.", .{});
}
```
The ABI of the file is different when targeting `freestanding` or `linux`:
```
$ zig build-obj -target riscv64-freestanding main.zig && file main.o
main.o: ELF 64-bit LSB relocatable, UCB RISC-V, RVC, soft-float ABI, version 1 (SYSV), with debug_info, not stripped

$ zig build-obj -target riscv64-linux main.zig && file main.o
main.o: ELF 64-bit LSB relocatable, UCB RISC-V, RVC, double-float ABI, version 1 (SYSV), with debug_info, not stripped
```

### Notes:
I came across this issue while reading https://matrix89.github.io/writes/writes/experiments-in-riscv/ and got the urge to make a `build.zig` file to compile the project as I was too lazy to get the GCC cross compiler.

Since the assembly file targets `double-float` and the C file targets `soft-float`, I got the following error:
```
ld.lld: error: /home/plumeus/zig_projects/riscv_test/zig-cache/o/cc21692bae9a5e68729e9557aedcbb22/start.o: cannot link object files with different floating-point ABI
error: LLDReportedFailure
```
Examining the cause led me to open this issue.

### Possibly related issues:
#4863
#5558

**Comment by leapofazzam123** [comment]
Got this issue as well when trying to build my zig riscv64 kernel

**Comment by akovaski** [comment]
Still new to Zig and RISC-V, but I dug in a bit into the problem here. I can create at least a proof-of-concept fix.

### Problem
The main issue here appears to be the different way Zig call clang/llvm for Zig, assembly, and C (and Cpp, m, h). See `src/Compilation.zig` for assembly and C. Add `--verbose-cc` to your build-obj command to see what clang commands Zig calls.  See `src/codegen/llvm.zig` for Zig.
* For Zig code, feature flags for the RISC-V extensions are passed (based on mcpu), but the abi defaults to ilp32/lp64 (or ilp32d/lp64d for linux targets).
* For assembly code, Zig creates an `-march` parameter (derived from the cpu features). Clang recognizes the arch and automatically selects an appropriate psABI (abi/`-mabi` argument in clang, MCTargetOptions.ABIName in llvm, which I don't know if it is really independent from the abi/EnvironmentType in the target triplet).
* For C code, Zig does not pass `-march`. It does however pass the cpu features with individual target-feature arguments. This is apparently not enough to get clang to upgrade the default psABI.

### Solution
There are a couple improvements I think could be done here:
1. Generate `-march` for compiling C code.
    * Alternatively, remove `-march` from the assembly compilation, add the feature flags, and specify the psABI for both.
2. Make the default abi for non-linux `.zig` files to be none/float/double based on arch.
    * I think letting LLVM handle the default would be best, if possible.
    * Though it looks like `src/codegen/llvm.zig` doesn't pass `march`, so the default might have to be specified by Zig.
3.  Does clang keep psABI/`-mabi` and the triplet abi separate because it makes sense or is it just to match gcc arguments? If psABI should indeed be separate from the target triplet abi, then we can add a way to specify the psABI via the command line and build.zig.
    * We'd want this to propagate to assembly, C (and Cpp, m, h), and Zig source file builds.
    * For specifying it on the command line, it could be passed via `-mabi`, added as a feature flag, or something else
    * For specifying it in build.zig, it could correspondly be passed though a new member of the CrossTarget struct, as a feature flag, or something else

### Additional References:
  * [RISC-V ELF psABI doc](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/)
  * [RISC-V Toolchain Conventions](https://github.com/riscv-non-isa/riscv-toolchain-conventions)
  * [RISC-V ISA Manual](https://github.com/riscv/riscv-isa-manual) (Specifically "1.2 RISC-V Software Execution Environments and Harts")

**Comment by akovaski** [comment]
I have made a draft pull request #10006 with a change so that the psAbi is also selected by architecture+extensions for C and Zig files now. I think this is enough for most use cases.

I'm still not sure on the distinction between the target-triplet abi and mabi/psAbi. If anybody could point to a reference where the interaction between the two is clearly laid out, I would appreciate it.

**Comment by akovaski** [comment]
Found a similar issue while running `zig build-exe` with multiple files (`.s + .c`, `.s + .zig`, `.c + .zig`) with Zig's release modes (ReleaseSafe, ReleaseFast, ReleaseSmall). Turns out that that clang and LLVM don't pass/store the mabi flag when doing LTO. https://reviews.llvm.org/D71387

`.s + .c` and `.s + .zig`: the linker will give an error:
```
$ zig build-exe -mabi=lp64f -target riscv64-freestanding entry.s kernel.zig -T linker.ld -mcmodel=medium -OReleaseSmall
ld.lld: error: lto.tmp: cannot link object files with different floating-point ABI
error: LLDReportedFailure
```

`.c + .zig`: builds a binary with mabi flag set to ilp32/lp64, even if the user passes mabi!
```
$ zig build-exe -mabi=lp64f -target riscv64-freestanding kernel.zig print.c -T linker.ld -mcmodel=medium -OReleaseSmall
$ readelf -h kernel | grep Flags
  Flags:                             0x0
```


So C and Zig files once again default back down to ilp32/lp64. Thankfully the workaround for the Zig user is simple: turn off LTO if they want to avoid the LTO behavior described above:
```
exe.setBuildMode(.ReleaseSmall);
exe.want_lto = false;
```
or pass `-fno-lto` to zig build-exe

btw, this is also a problem for those that want to compile with LTO with clang:
```
$ clang-13 -mabi=lp64d -target riscv64-unknown-unknown-unknown -march=rv64ifdc -c entry.s kernel.c -flto -mno-relax -mcmodel=medany
$ file *.o
entry.o:  ELF 64-bit LSB relocatable, UCB RISC-V, version 1 (SYSV), not stripped
kernel.o: LLVM IR bitcode
$ ld.lld-13 entry.o kernel.o -T linker.ld
ld.lld-13: error: lto.tmp: cannot link object files with different floating-point ABI
```
```
$ clang-13 -mabi=lp64 -target riscv64-unknown-unknown-unknown -march=rv64ifdc -c entry.s kernel.c -flto -mno-relax -mcmodel=medany
$ file *.o
entry.o:  ELF 64-bit LSB relocatable, UCB RISC-V, version 1 (SYSV), not stripped
kernel.o: LLVM IR bitcode
$ ld.lld-13 entry.o kernel.o -T linker.ld
$ readelf -h a.out | grep Flag
  Flags:                             0x1, RVC, soft-float ABI
```

**Comment by andrewrk** [comment]
Important question: is it ever possible to mix and match the "ABI" portion of the triple with this "machine ABI" concept? Or does, for example, `riscv64-linux-gnueabihf` always imply `lp64d`?

What I'm getting at is, perhaps instead of adding a new concept, we should add some more ABIs to the Target ABI since we already have the concept of a Target ABI?

Otherwise we are in for a naming situation because "target ABI" would be ambiguous between 2 completely unrelated things.

**Comment by akovaski** [comment]
I don't have the in-depth knowledge to truly answer if the triplet-abi should be merged with the target-abi. Though, I'd like to share my thoughts anyways.

# Conclusion
This is a meandering post, so I'm including the conclusion up at the top.

While I am not completely familiar with the rational behind the `-mabi` flag, I think it would be practical to have the target-abi available for selection for freestanding targets. For Linux, I think riscv64-linux-gnu and riscv64-linux-musl (both using mabi=lp64d) are sufficient for the majority of cases. riscv{32,64}-linux-gnueabihf should be undefined. I have an explicit list of target triplets below.

# Background
According to a [Sifive blog post](https://www.sifive.com/blog/all-aboard-part-1-compiler-args), the `-march`, `-mabi`, and `-mtune` arguments are exposed to ensure the RISC-V compiler command-line interface is easy to extend in the future. `-mabi` controls the [C] calling convention and the [C] layout of data in memory.

I think clang and gcc both have those flags due to collaboration with RISC-V people.

When you compile an ELF object, the `mabi` is stored in the object, and lld.ld will refuse to link an lp64 object and an lp64d object together.

# Linux
At least [Debian has a baseline](https://wiki.debian.org/RISC-V#Hardware_baseline_and_ABI_choice) of march=RV64GC (G = IMAFD) and mabi=lp64. (And Debian has theoretical support for 32-bit.)

# Thinking about gnueabihf
But, then, let's think about gnueabihf. What is this even? From what I can gather, gnueabihf is an ARM-specific ABI for 32-bit ABI for [ARM v7 and up](https://wiki.debian.org/ArmPorts). In ARM's [latest compiler releases](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads) for Aarch32 they have a bare-metal compiler which uses the eabi ABI, and they have a Linux compiler which uses the gnueabihf ABI.

So, for consistency, I think riscv64-linux-gnueabihf should be undefined. From the [above-mentioned Debian page](https://wiki.debian.org/RISC-V#Pre-built_toolchains), it seems they use `gnu` as the triplet-abi gcc-riscv64-linux-gnu.
And [musl](https://musl.cc/) has riscv{32,64}-linux-musl.

# Wait, how could programs with different taget-abi use libc on Linux?
I think perhaps somebody wanting to use a different target-abi on Linux would not be able to use the system's dynamic libc. Or you'd have to have a libc for each supported target-abi. Statically linking using musl seems reasonable.

Here are some tests:
## gnu
```
$ riscv64-linux-gnu-gcc hello_world.c -mabi=lp64
In file included from /usr/riscv64-linux-gnu/include/features.h:485,
                 from /usr/riscv64-linux-gnu/include/bits/libc-header-start.h:33,
                 from /usr/riscv64-linux-gnu/include/stdio.h:27,
                 from hello_world.c:1:
/usr/riscv64-linux-gnu/include/gnu/stubs.h:8:11: fatal error: gnu/stubs-lp64.h: No such file or directory
    8 | # include <gnu/stubs-lp64.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.

$ riscv64-linux-gnu-gcc simple.c -mabi=lp64
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: /tmp/ccfkBqKf.o: can't link soft-float modules with double-float modules
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: failed to merge target specific data of file /tmp/ccfkBqKf.o
collect2: error: ld returned 1 exit status

$ riscv64-linux-gnu-gcc simple.c -mabi=lp64 -nostdlib
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: warning: cannot find entry symbol _start; defaulting to 000000000000029a
```

## musl
```
$ riscv64-linux-musl-gcc hello_world.c -mabi=lp64
/opt/riscv64-linux-musl-cross/bin/../lib/gcc/riscv64-linux-musl/11.2.1/../../../../riscv64-linux-musl/bin/ld: /tmp/cclCilbo.o: can't link soft-float modules with double-float modules
/opt/riscv64-linux-musl-cross/bin/../lib/gcc/riscv64-linux-musl/11.2.1/../../../../riscv64-linux-musl/bin/ld: failed to merge target specific data of file /tmp/cclCilbo.o
collect2: error: ld returned 1 exit status

$ riscv64-linux-musl-gcc simple.c -mabi=lp64
/opt/riscv64-linux-musl-cross/bin/../lib/gcc/riscv64-linux-musl/11.2.1/../../../../riscv64-linux-musl/bin/ld: /tmp/ccEKjDdh.o: can't link soft-float modules with double-float modules
/opt/riscv64-linux-musl-cross/bin/../lib/gcc/riscv64-linux-musl/11.2.1/../../../../riscv64-linux-musl/bin/ld: failed to merge target specific data of file /tmp/ccEKjDdh.o
collect2: error: ld returned 1 exit status

$ riscv64-linux-musl-gcc simple.c -mabi=lp64 -nostdlib
/opt/riscv64-linux-musl-cross/bin/../lib/gcc/riscv64-linux-musl/11.2.1/../../../../riscv64-linux-musl/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000000252
```

So I guess it turns out musl doesn't fare much better. Though I do still think musl is better positioned here to use different target-abi on Linux.


# Creating more ABIs
So, I still don't think I fully understand why the RISC-V folk want to have a `-mabi` flag... maybe reducing the absolute number of gcc cross-compilers is part of it? But if I were to merge the target-abi and the triplet-abi, I think the following triplets would be a fairly complete set (until they make more ABIs):
## For Freestanding:
* riscv32-freestanding-ilp32e
* riscv32-freestanding-ilp32
* riscv32-freestanding-ilp32f
* riscv32-freestanding-ilp32d
* riscv64-freestanding-lp64
* riscv64-freestanding-lp64f
* riscv64-freestanding-lp64d

## For Linux
* riscv32-linux-gnu (ilp32d)
* riscv32-linux-musl (ilp32d)
* riscv64-linux-gnu (lp64d)
* riscv64-linux-musl (lp64d)

## Probably unnecessary, but if you wanted to support the different target-abi on Linux (possibly using a delimiter instead of squishing together)
* riscv64-linux-gnulp64
* riscv64-linux-gnulp64f
* riscv64-linux-gnulp64d
* gnuilp32 already existing here is interesting. This seems to be for Aarch64, and LLVM has gnuilp32 as an ABI. On the other hand, [gcc seems to allow the user to pass ilp32 or lp64 via the `-mabi` flag for Aarch64](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html).

# Automatic target-abi selection based on `-march`
Theoretically, somebody would want to use a lp64 binary library for their Linux program, or maybe when vectors are fleshed out somebody would want to use a vector-ABI for their Linux program. But we saw above that gcc currently doesn't even work with a different `-mabi` until you turn off the stdlib, even with musl. For Linux, sticking to ilp32d/lp64d makes sense.

For bare-metal, people might be slightly more sensitive, but I think choosing lp64 vs lp64d based on architecture is fine for most.

**Comment by alexrp** [comment]
Given the age of this issue, can you please open a new issue with repro steps?
