### ISSUE TITLE
Add a small string optimization to Buf (C++ compiler code)

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#986]
This could be done by adding a small buffer optimization to all ZigLists (or through a template bool flag) or by creating a new representation for buffers instead of simply relying on ZigList.  

This optimization could reduce compile times by quite a bit by avoiding lots of allocations (since most buffers used in compiler code will probably fit in the small string representation).

**Comment by BraedonWooding** [comment]
While I'm skeptical about it reducing compile times by "quite a bit", it could be worth a try to see the impact of the effect.

**Comment by BraedonWooding** [comment]
Am very interested in the results 😄.  In the end any positive effect is an effect, I'm excited!

**Comment by Hejsil** [comment]
I might look into some profile of the Zig compiler. This might give us an idea of how much this will affect out compile times. Also, maybe we want this optimization in `std`? :)

**Comment by alexnask** [comment]
My attempt is [here](https://github.com/zig-lang/zig/compare/master...alexnask:sbo?expand=1) but I've hit some bugs that I will have to correct at some other point.  

(This implementation should be able to hold 23 byte buffers inline, including the null terminator) 
 Once I get it up and running I'll post some stats on the number of allocations saved and the compile time benefits.

**Comment by andrewrk** [comment]
I actually tried this exact optimization before, and found that it did not change the performance of zig one way or another. I tried having ZigList preallocate various different amounts to avoid calling malloc, and ultimately it didn't change the performance at all. So I removed the complication.

That said I just now implemented SegmentedList (linked above) which supports preallocated elements. I think it will be the best data structure for most of the lists in the self hosted compiler, especially because it is so friendly to arena allocators, and it removes the footgun of referencing list items before an append. With SegmentedList, a pointer to an element lasts as long as the element is still in the list.

**Comment by Validark** [comment]
Hello from 2021. I just wanted to drop this video here as a reference for some strategies used by fbstring, which notably allows for 24 byte small strings (including the null terminator). It's also just an interesting video in general for anyone who doesn't know about this optimization.

https://youtu.be/kPR8h4-qZdk?t=387
