### ISSUE TITLE
std.math: change the naming style for constants

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#9888]
Currently, we have:

**log2e** for log2(e)
**ln2** for ln(2)
**two_sqrtpi** for 2/sqrt(pi)

I suggest addition of underscores for clarity.
The new names would be:
**log2_e**
**ln_2**
**two_div_sqrt_pi**

With this it will be possible to add constants like:
**log10_2**
**log2_10**

Question: Why **f64_max** and **inf_f64**? Is there a reason why f64 was first and last?

**Comment by InKryption** [comment]
To give my own interpretation, while I can't speak to the actual motivations behind the naming of `f64_max` and `inf_f64`, I imagine it is because `f64_max` is describing "f64's maximum value", and `inf_f64` is describing "the value infinity in f64 representation". 

Side note: this may be a bit out there, but it could also be beneficial to add aliases using the `@""` syntax, where the constants are named as `@"log2(e)"`, `@"ln(2)"`, and `@"2/sqrt(pi)"`. Not sure if something like that belongs in the standard library, but I guess this is a good place as any to put it on the table.

**Comment by binarygcd** [comment]
Can you please clarify the reason for the downvote? I'm willing to close this if you have a strong argument.
