### ISSUE TITLE
Proposal: Private Fields

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#9909]
## Introduction

Currently, function and variable declarations are private by default and are made externally visible with the `pub` modifier. However, data fields are always public and there is no way to restrict their visibility. Apparently, field access control was never really working in Zig (#569) and was officially removed in #2059. Which is somewhat surprising, since no other modern language I can think of (Java, C++, C#, D, Rust, Go, ...) fails to provide this feature.

The lack of private data makes it impossible to do proper encapsulation / implementation hiding, which is widely considered to be a basic software engineering technique. In particular:
* Types can hide some of their methods and constants, but always expose their internal structure. This leaves them open to accidental (or bad-practical) corruption. The compiler will not complain if the `.capacity` of an `ArrayList` is overwritten.
* Documentation value is lost. Whether or not a field is intended for direct access can only be communicated through code comments.
* Auditing code becomes more difficult, because there are more opportunities to violate constraints and invariants.
* Implementing opaque handles is nearly impossible without additional builtins: #9859, [#1595 (comment)](https://github.com/ziglang/zig/issues/1595#issuecomment-425590705).

## Possible objections

No official reason was given in #2059, but two possible objections to private fields come to mind:

1. Visibility control is more useful for decls than for fields, because invisible decls become completely inaccessible, while fields can always be messed with through pointers.
2. This will lead to over-encapsulation and getter-setter boilerplate ([#2974 (comment)](https://github.com/ziglang/zig/issues/2974#issuecomment-515948745)). Sometimes it's just better to reach in and do things directly.

Concerning 1, I'd say that protection does not have to be perfect to be useful. Preventing accidental and semi-deliberate messing is valuable by itself, not to mention the documentation value.

2 may be a real concern, or maybe not. The same argument can be made about private decls, but a proposal to override the visibility of methods at the call site (#8779) was recently met with a resounding rejection -- even though there are certainly cases where it is both reasonable and safe to call private methods. In addition, Zig is increasingly making legal but potentially buggy patterns into hard errors, somtimes controversially (e.g. unused variables). The lack of basic implementation hiding is not consistent with this safety-first attitude, IMHO.

## Syntax

The simplest option is to adopt the same default as with decls: file-level private by default and externally visible with `pub`. If this clashes with data-oriented style, the opposite default can be chosen, but that wold require the introduction of a `private` keyword. Yet another possibility is to make field visibility struct-level, e.g. with `opaque struct {...}`.

I don't really have a strong opinion here.

## Open questions

* Is there a case for field-level access control in unions?

---

Update 1: As a side benefit, it may be possible to remove the `opaque {}` type from the language, since it is rarely used and can be simulated with `struct { private ptr: usize }`.

Update 2: I wouldn't mind adding an escape hatch like `@privateField(object, "name")` for cases where you need to use a particular library, but find the API too locked-down. Some discussion of this is [here](https://github.com/ziglang/zig/issues/9909#issuecomment-937723462).

**Comment by vijfhoek** [comment]
I feel the argument you make in the objections ("In addition, Zig is increasingly making legal but potentially buggy patterns into hard errors, somtimes controversially (e.g. unused variables).") is a very good one. This is also something that I feel Zig has evolved in since #2059.

Maybe worth moving that argument up to the introduction, to pay it more attention?

**Comment by Guigui220D** [comment]
I have been using naming conventions for my private fields, like `_capacity: usize` in order to discourage usage, but I feel like having pub for fields would be better.

**Comment by sina-devel** [comment]
If the `private` keyword is added, it's not syntactically compatible (functions, etc are private by default and exported by the `pub` keyword)

**Comment by zzyxyzz** [comment]
Thank you for the detailed explanation!

I can't say I agree with it, but it's certainly good to know where things stand.

**Comment by daveb68** [comment]
I had never heard of Zig until today.  Someone mentioned neovim possibly considering it as a language.  After reading this post I hope that never happens.   

It appears that many don't fully grasp the value/importance of hiding implementation.   That value is not so significant in small code bases.  However, the larger and more involved a code base is, the more critical facilities such as data hiding, readonly member variables, ... are.   This is especially true in a statically typed compiled language.   Different coding choices, patterns, and practices impacted by the language's capabilities have a substantial impact on how efficiently one can read and reason about code that is known to compile.  Enough bad choices and one can't reason about the code cost effectively at all.  Some bring TDD to the rescue writing many tests that a well designed language would have made completely unnecessary.  This is also not efficient.   Knowing the scope within which a variable or object member can be read or written and that scope being as small as possible leads to the shortest time  necessary to reason about the code, components, and sets of components.  That leads to the most efficient developers.  The scope being 100% of the source code is the opposite of efficient.   Unless a developer does not read and reason about their code as components (i.e. relies 100% on TDD as they can't understand the code as component pieces), I don't know how this is not seen as a significant issue unless the size of the code bases they work on (or the language is meant to be used with) is relatively small.
Rockstar level development tools only help if the code is fully compiling and they have access to 100% of the code using the module under development. Either that or variable naming conventions which makes the names unique across the code base such that a good text searching tool can find how it is being used.

I do hope you reconsider on this point.  Or at least that the neovim developers take a closer look before they consider Zig.

**Comment by likern** [comment]
@andrewrk I understand your reasoning and agree with it. On the other hand, it's not clear is it safe (is this intended / allowed) to access struct fields directly, as they can be unprotected.

A would propose to have private/public fields, so they can't be accessed **accidentally**.
But not hiding private fields from accessing completely. If you **really need you can**.
This is how it'd don in TypeScript with `object!.field` syntax, which means "Hey, I know what I'm doing!".

```zig
const obj = struct {
  const Self = @This();
  // private by default or have # syntax as modern JavaScript proposal
  #length: usize,
  pub fn length(self: *Self) {
    return self.#length;
  }
}

// Know what I'm doing!
const a = obj {};
const len = a.!length;
// or like this
const len = a.#length;
```

**Comment by zzyxyzz** [comment]
@likern
I agree that adding an escape hatch is the proper answer to the concern that interfaces will become too locked-down and uncomposable. This solution was already suggested in this thread, though (in the form of `@privateField(a, "length")`). Using a built-in for this has multiple advantages, such as not requiring new syntax and being easier to search for. The additional verbosity may also be seen as a benefit, since overriding visibility is not to be used casually.

**Comment by andrewrk** [comment]
As a reminder this issue is closed

**Comment by zzyxyzz** [comment]
I know this issue is closed, but just in case it is ever reconsidered, I'd like to post this reply to Andrew's comments. This has been eating at me for a while, so here goes:

> There are many properties that can be "leaked" into the public interface of an API. For example: size/alignment of a struct, performance characteristics of a given function implementation, whether a function can be executed at comptime, existence/non-existence of declarations, and more. It is up to the documentation of a given package to specify what exactly the major version is protecting - that is - what exactly counts as "breaking" and what does not. Whether a given field is part of the public API or not is one more item in this list.

Yes. But lets not throw the baby out with the bathwater. Just because there will always be things (some of them quite esoteric) that cannot be formally expressed in the interface, that should not necessarily prevent us from picking the low-hanging fruit. Field access control is a simple and well-established technique, not unlike the distinction between `var` and `const`. Implying that it is about as useful (and complex) as, e.g., a compiler-checked formal specification of the performance characteristics of a function is incorrect, IMO.

> The idea of private fields and getter/setter methods was popularized by Java, but it is an anti-pattern.

I would not say that getter-setters are *per se* an anti-pattern. Their excessive use in some languages certainly is, but when there is a legitimate need for an encapsulated interface, they're just the thing. And it's not like Java is the only language with private fields. Almost all popular languages have them. I did not have the impression that Rust, for example, was suffering from a getter-setter epidemic.

> My recommendation is to name fields carefully and leave them as part of the public API, carefully documenting what they do.

This will work well sometimes, and sometimes it won't. I'm pretty sure that many library authors would prefer to hide some parts of the implementation, rather than carefully arranging things such that there is nothing to hide.

> In this case the field name unprotected_counter properly communicates the danger of using the field without using any abstraction. However it being public also allows proper abstractions to be built, if the ones provided are not enough.

I note that the building of additional abstractions is just as likely to be prevented by low-level *methods* being private. Does this mean we should remove visibility controls etirely and rely on careful naming and documentation for methods and other decls as well? Besides, anticipated disagreements between library authors and users about what should or shouldn't be hidden can also be resolved with an explicit override (e.g. `@privateField()`).

> Then if the API user held the mutex for some other reason, getCounter() would actually deadlock (or rely on a silly hack such as recursive mutexes).

So the fields should be public *in this particular case*. It does not follow that struct fields in general should *always* be public. Plenty of valid examples can be presented on both sides of the argument.

> The bottom line here is that private fields is an addition to the language, making it more complicated and requiring the language to answer a bunch of questions that otherwise would not exist.

Arguably, adding private fields would *simplify* the language, at least from the user perspective, since it makes the language more consistent and more in line with patterns familiar from other languages.

---

In my view Andrew makes a good case for why open interfaces should be preferred in general. He does not make a convincing case for why they should be forced to always be open. Projects differ. Requirements differ. Sometimes what you need is an open library, at other times it's a piece of high-assurance code that is audited forwards and backwards. Neither is right or wrong, they're just different, and I see little reason to pick one over the other when we can easily support both.

**Comment by egtann** [comment]
I am a beginner at Zig, but I come from a background in many other languages. Perhaps my experience is wholly irrelevant to Zig, but I wanted to share my perspective as it seems a bit different from @andrewrk.

I’ve noticed private fields have 3 major benefits in my codebases and libraries, leading to improvements for library authors, consumers, and the ecosystem as a whole:

1. Private fields enable library authors to communicate intent in APIs for how things should be used.
2. Private fields add enormous clarity to readers/users of the API. In many cases in Go, I know exactly how something can and should be used, and I can’t misuse it. For instance, sync.Mutex had Lock and Unlock. The internals are hidden away. If I need a deeper access I can of course fork it, copy/paste/modify it, write my own or use a different library. But most times, if a library is well-designed for your use-case, its API provides the right abstraction.
3. When combined with semver-based tooling and community buy-in, you get backwards compatibility guarantees that are not reasonably possible otherwise. I have been able to reliably upgrade and use libraries. I’ve encountered just 1 broken package version in 8 years (which go.mod allows me to blacklist) across a 300k LOC codebase with several dozen dependencies. This is unlike any experience I’ve had in any other language in my career (including Java, Objective C, JavaScript/Typescript, Ruby, Python). Go’s ecosystem stability is a wonderful feature of the language.

I do not believe we will have Go’s level of stability in the Zig ecosystem without giving library authors a standard way to say, “this is what I promise will remain stable.”

Zig already has default private behavior with pub methods and exports, so pub fields seem like such a natural inclusion from a beginner Zig-user’s POV.

**Comment by svew** [comment]
I think it's worth saying, to rebutt the reasoning about docs as a suitable solution for private fields, that **docs are always the WORST way of communicating code contracts to other developers**, the best being language features which enforce certain behavior (types, mutability modifiers, access modifiers, etc.), the second best being widely recognized conventions.

Java has the "private" field language feature, Python has an underscore prefix code convention. Both of these are extremely valuable for communicating the intended use of a struct or library. It's valuable not just to the developer who may or may not (probably not) be fully reading the docs of the library they're using, but also to any code reviewers to show that a library is being used in an unintended way. It's not hard to imagine a new developer modifying the "capacity" field of a struct because intellisense suggested it first over "setCapacity" (which does additional, necessary work), and it getting missed during code reviews since there's no indication at all that this is a misuse of the class unless you comb over the library's documentation.

Not introducing ANY concept of "You probably don't want to call/write this function/field" is a huge mistake. If Zig wants to strive for being a maintainable language used by a team of more than a half dozen developers, then it **MUST** introduce either a language feature or code convention to communicate what is meant to be public API and what is not. It doesn't matter if it's Java-style private fields, or a Python-style naming convention, or something inbetween, any of these are adequate for communicating an unusual use of a library during development and code reviews. Docs, and expecting only developers of a certain rigor will use your language, are simply not an acceptable substitute for this kind of important & easily communicable information.

**Comment by Jarred-Sumner** [comment]
Private fields would've made this memory leak harder to happen:

<img width="372" alt="image" src="https://github.com/user-attachments/assets/38fdd26d-a35b-42a6-9f51-a74d70b5276e">

**Comment by LearnLoop365** [comment]
Private fields can also help them reduce some validation code for some invalid modification cases...

**Comment by chenzhekl** [comment]
I still think a private field is a good idea, at least building some conventions like prefixing the field with an underscore helps a lot. I understand people want to keep Zig concise and small, but it is very hard nowadays to tell what constitute the public API of a type by skimming through the code.

**Comment by jfalcon** [comment]
> I still think a private field is a good idea, at least building some conventions like prefixing the field with an underscore helps a lot. I understand people want to keep Zig concise and small, but it is very hard nowadays to tell what constitute the public API of a type by skimming through the code.

While it totally makes sense not to over-complicate the language, and just to play devil's advocate here. :)

If take the assumption that self-documenting code is a good thing, then I think it's safe to assume that if the intent is to be C evolved then it's ok to introduce a couple new concepts. Not need to go all C++/Rust on it and ruin the vibe though when we be jamming.

So, if keeping is simple is the way, then perhaps we can make the secondary option "official" where we rely on naming conventions. Like with an underscore decorating a "private" member, as we did with JavaScript to fake it before it got that abstraction. It would be akin to the "official" style guides and solve the self-documenting concept while also not adding new abstractions if someone really does wanna shoot themselves in the foot by messing with it.

**Comment by yousefak007** [comment]
Hi devs,

Without official support for private fields and methods, we can adopt a naming convention to indicate that certain fields and methods should be treated as private. By prefixing field and method names with an underscore `_`, we can signal to developers that these elements are not intended for direct access. This approach is similar to the convention used in Dart.

```zig
const obj = struct {

    const Self = @This();

    _length: usize, // private field

    fn length(self: *Self) usize {
        return self._calc();
    }

    fn _calc(self: *Self) usize { // private method
        return self._length;
    }
};

```

In this example, both `_length` and `_calc` are intended to be treated as private.

By adopting this naming convention, we can achieve a level of encapsulation and communicate the intended usage of fields and methods, even without official language support for private elements.

**Comment by amarz45** [comment]
The way I like to get around the lack of private struct fields is to define a `private` inner struct. Here is a very simple example:

```zig
pub const Data = struct {
    private: Private = .{},

    const Private = struct {
        length: usize = 0,
    };

    pub fn get_length(data: Data) usize {
        return data.private.length;
    }
};
```

Of course, I wouldn’t create a getter like this in actual code, this is just a simple example. I like doing it this way because it’s self-documenting code. It also separates all the public fields from the private fields. Users of the struct can also do `data.private.length`, so they won’t be completely prevented from accessing private fields, but it will be clear that they are. I think this workaround is fine, because I want the majority of struct fields to be public from my experience.

**Comment by batiati** [comment]
Having no visibility modifiers in a struct’s fields, just like C, enforces that in runtime memory can be accessed regardless of compiler restrictions. However, there are cases where hiding certain fields is desirable.

In previous versions of Zig, if I recall correctly, using a field of a private type (like this inner private struct trick) made it inaccessible from outside, resulting in a compiler error similar to what happens when attempting to use a private function.

For what it's worth, in TigerBeetle, we address this (using another trick from C) by defining an "opaque" array of bytes in the public type and casting the pointer to a private type with properly defined fields. All enforced by `comptime` checks to verify field offsets.

https://github.com/tigerbeetle/tigerbeetle/blob/e55e3263d9606d50e6912341ce6c6a28718f9a5a/src/clients/c/tb_client/packet.zig#L20-L61
