### ISSUE TITLE
change the init-exe example to avoid confusion with ReleaseFast and std.log.info

### ISSUE THREAD

**Issue by M0n7y5** [ziglang/zig#9945]
### Zig Version

0.9.0-dev.1352+6d6cf5984

### Steps to Reproduce

just init simple zig project and build it with -Drelease-fast=true or -Drelease-small=true

```zig
const std = @import("std");

pub fn main() anyerror!void {
    std.log.info("All your codebase are belong to us.", .{});
}
```

### Expected Behavior

Produced binary should print `All your codebase are belong to us.`

### Actual Behavior

It doesn't print anything. Instead it just exits immediately.

**Comment by leecannon** [comment]
This is due to the default log level of release modes being higher than info:
https://github.com/ziglang/zig/blob/e851d89113a57064c38ed85722edc7f686d0c11a/lib/std/log.zig#L117-L122

To override this in the main file add `pub const log_level = std.log.LogLevel.info`

However it does make sense to still treat this as an issue as it would make sense to note this in a comment in the file generated by init-exe. As this is definitely unexpected.

**Comment by M0n7y5** [comment]
So this is intended behavior? Also i was trying to inspect generated binary using IDA , but for some reason generated PDB files is crashing IDA once its loaded.

**Comment by g-w1** [comment]
It was decided to log because this is better scaffolding for larger projects.

**Comment by Prince213** [comment]
If the intent is to remind users to use std.log, then it should be stated in the docs, not in a simple example program that is expected to do something simple.
